### ISSUE TITLE
Filter by transaction type in history

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1012]
UI Version: 0.8.2

Description:

The user should be able to filter the transactions types (wallet/staking/governance) on the transaction page.

**Comment by faboweb** [comment]
blocked on #355

**Comment by jolesbi** [comment]
i will include a design proposal to help with this!

**Comment by jbibla** [comment]
we can filter by tabs - as shown here: https://zpl.io/bLDW6gQ
