### ISSUE TITLE
how should we determine the order of validators

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1031]
there are many ways we can determine the order of the validator set list in voyager. we should decided on the methodology sooner rather than later.

- random 
- pseudo random
- random but consistent for each user
- ?

**Comment by gamarin2** [comment]
Here is my take on this. I would display validators in random order, but organize validators in 3 categories. This means that validators would be displayed randomly inside each category. However, validators in category 1 would always show above validators in category 2.

1. First category: Validators I have bonded stake to.
2. Second category: Validators with %vote >0 (i.e. currently validating)
3. Third category: Validator candidates with %vote = 0.

One possible idea would be to factor in the %vote, in inverse relationship. The more stake you have, the higher the chance you'd be displayed lower in your category. This might increase decentralisation.

**Comment by faboweb** [comment]
I would vote against randomness as I assume it will be confusing for the user to look for a validator once and after a refresh of the page / restart of Voyager. I would vote for pseudo randomness.

**Comment by jolesbi** [comment]
@gamarin2 
> First category: Validators I have bonded stake to.

is this accomplished by the new "my stake" section or do you think we should show this list again on the main validators list?

> Second category & Third Category

makes a lot of sense to me

> One possible idea would be to factor in the %vote, in inverse relationship

i like you're thinking here - but we will be offering filters for users. does this still make sense when with one click a user can sort by whatever they please?

@faboweb 
> pseudo randomness that stays consistent for each user.

yeah, i think this is a cool idea. so every validator list on voyager will be randomized - but the order will persist for that user and list. what happens when the validator set changes?

**Comment by gamarin2** [comment]
> is this accomplished by the new "my stake" section or do you think we should show this list again on the main validators list?

I don't see a way to increase your bonds on the "My Stake" section, so yes. And I'm not sure we should have an "Increase Bond" button on the "My Stake" section since it would incentivise concentrating bonds. 

> i like you're thinking here - but we will be offering filters for users. does this still make sense when with one click a user can sort by whatever they please?

I do. This is just the default when first clicking. After that users can filter however they want. But we'll get a non-negligible amount of users not filtering, and that's why it matter imo.

**Comment by faboweb** [comment]
Should we then even split in validators and candidates? This already concentrates bond on validators.

**Comment by jbibla** [comment]
@gamarin2 
> I don't see a way to increase your bonds on the "My Stake" section, so yes. And I'm not sure we should have an "Increase Bond" button on the "My Stake" section since it would incentivise concentrating bonds.

good feedback. have you seen this? https://sketch.cloud/s/xKnxA/all/voyager-wireframes/validator-profile

maybe it's not obvious enough - but we're thinking that clicking on a validator will take you to this page where delegation buttons will be.

> Should we then even split in validators and candidates? This already concentrates bond on validators.

i think having one list would be fine - but i think we should indicate the difference between validators and candidates in addition to just the % of vote stat.

**Comment by gamarin2** [comment]
> good feedback. have you seen this? https://sketch.cloud/s/xKnxA/all/voyager-wireframes/validator-profile

No, will check it out.

> maybe it's not obvious enough - but we're thinking that clicking on a validator will take you to this page where delegation buttons will be.

True, I had not realized that we moved away from the sliders. That's not trivial. Here is my current thinking:

I think the "My stake" page is fine as is (except for the comments I already made). However, on the Validator List, I think it would be valuable to add checkboxes at the far right of each validator. After you've checked some validators, you could click on a "Delegate" button. Then a popup window shows up, and you're presented with multiple slides. One for each validator you've checked. This process would act as a "Quick delegation mechanism".

Now you also have a way to bond/unbond from the validator page. IMO the best/most user-friendly to do it is to have a slider that is very visible on the validator page (top right would be ideal). 
The slider would go from left to right. If I have bonded stake to this validator, the slider would be moved to the right. Dragging the slider to the left would unbond, while dragging to the right would increase my bonds to this validator.

All in all there would be two ways to bond. One quick way to bond to multiple validators from the Validator List. And one way to bond/unbond from a single validator from the validator page.

> i think having one list would be fine - but i think we should indicate the difference between validators and candidates in addition to just the % of vote stat.

I second that.

**Comment by gamarin2** [comment]
> i like your ideas - but they feel like advanced features / workflows. as such, i don't think they are appropriate for our MVP.

Fair enough! It's true that it might be good to "force" the user to see the validator profile before delegating. 

Please consider the other ideas too :p
