### ISSUE TITLE
Validator OwnerAddr and Pubkey not showing

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1099]
UI Version: 0.9.3

Description:

**Explorer**: 

<img width="861" alt="screen shot 2018-08-08 at 3 17 34 pm" src="https://user-images.githubusercontent.com/31522760/43839418-54a2b244-9b1e-11e8-9ad5-2986815e1870.png">

**Voyager**: 

<img width="961" alt="screen shot 2018-08-08 at 3 17 47 pm" src="https://user-images.githubusercontent.com/31522760/43839443-64e24a84-9b1e-11e8-9c81-6c860ed5b103.png">

**Comment by jbibla** [comment]
nice catch @fedekunze 

super duper design updates coming soon: https://sketch.cloud/s/xKnxA/all/voyager-wireframes/validator-profile
