### ISSUE TITLE
Pick full node on UI

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1312]
As a follow up for https://github.com/cosmos/voyager/issues/1291 we might allow the user to pick a node they trust.

Scope:
- component: ability to enter an IP of a trusted node
- logic: ability to connect to a full node based on an IP set in the view

**Comment by jbibla** [comment]
a better ux might be to let the user pick from a list of full nodes including monikers and IPs. 

but i'm not sure we need to do any of this before launch.

**Comment by faboweb** [comment]
agreed

**Comment by jbibla** [comment]
> this will probably often be used by people how know the IP of their trusted node

even if you know the IP of the node, having a list would be nice / could help with verification etc...

**Comment by faboweb** [comment]
Maybe make it a config setting.

**Comment by jbibla** [comment]
> Maybe make it a config setting.

what do you mean?

**Comment by faboweb** [comment]
Make it configurable in the config.toml.

**Comment by jbibla** [comment]
isn't it already with `COSMOS_NODE`? i thought the point of this was to let users (not developers) pick a node...?

**Comment by faboweb** [comment]
> Make it configurable in the config.toml.

This was an outcome of a discussion in the team meeting. We want to be able to define the set of trusted full nodes when shipping Voyager. A regular user will not use `COSMOS_NODE` as you pointed out. As we discussed that validators may ship a branded Voyager, validators may want to put in their preferred full node in the configuration easily.
