### ISSUE TITLE
Refactor unit tests

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1337]
We want to redesign how the unit tests are written so they are uniform.

Scope:
- [x] written design proposal
- [ ] implementation of the proposal throughout all tests

**Comment by faboweb** [comment]
Open:
- Components
- [ ] AnchorCopy
- [ ] Page404
- [ ] ShortBech32
- [ ] TmBalance
- [ ] TmBtnCopy
~~- [ ] TmBtnReceive~~ (remove)
- [ ] TmLiCopy
- [ ] TmModalHelp
~~- [ ] TmModalReceive~~ (remove)
- [ ] TmModalSearch
- [ ] TmOnboarding
- [ ] TmSessionAccountDelete
- [ ] ToolBar
- [ ] LiProposal
- [ ] ModalDeposit
- [ ] ModalPropose
- [ ] ModalVote
- [ ] PageGovernance
- [ ] PageProposal
- [ ] TableProposals
- [ ] TabParameters (governance)
- [ ] TabProposals
- [ ] DelegationModal
- [ ] LiValidator
- [ ] PageStaking
- [ ] PageValidator
- [ ] PanelSort
- [ ] TableValidators
- [ ] TabMyDelegations
- [ ] TabPrameters (staking)
- [ ] TabValidators
- [ ] UndelegationModal
- [ ] LiCoin
- [ ] PageTransactions

- Modules
~~- [ ] filters~~ (should be removed)
- [ ] keybase
- [ ] onboarding
- [ ] pool
- [ ] validators

**Comment by fedekunze** [comment]
also please update the unit test code style doc while doing this

**Comment by faboweb** [comment]
Leet ticket :)

**Comment by jbibla** [comment]
lol @sabau we're still waiting for you
