### ISSUE TITLE
Add support for staking queries 

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1349]
Description:

Create search or advanced filter to query for specific parameters on the staking endpoints (once supported)

Ref: https://github.com/cosmos/cosmos-sdk/issues/2202

**Comment by faboweb** [comment]
Why would we need these additional querys?

**Comment by fedekunze** [comment]
@faboweb For instance to display only `jailed`, only `unjailed` or both validators. Same with validator `status`. Also to the state of the validator at a certain block height.

**Comment by faboweb** [comment]
Status queries can be evaluated offline, as we already loaded the data. I am not sure we need an extra endpoint for the sake of possibility. ;)

Regarding validator at certain block height: Can you think of a user story that would need this?

**Comment by fedekunze** [comment]
> Status queries can be evaluated offline, as we already loaded the data. I am not sure we need an extra endpoint for the sake of possibility. ;)

In the case of Voyager that's true, but still need to filter them

**Comment by fedekunze** [comment]
@faboweb 

"As a delegator I want to keep track the validator's voting power and self stake over time by being able to query for a specific block height"

"As a delegator I want to be able to identify important events that define validator performance over time such as slashing and jailing so that I can compare them with the validator's self stake, voting power and commission"

**Comment by faboweb** [comment]
So this really is about the block height? I see a benefit there when we do over time charts for validators. 👍 

I don't see a benefit for the other filters. I fear that they would only result in additional requests that would return data we already have.
