### ISSUE TITLE
Tab Validators doesn't redirect from PageValidator

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1351]
**Description:**

When I want to go back to the see the list of validators from `PageValidator`, the Validators tab doesn't work. I have to go back and with the arrow (to the My stake tab) and click the Validators tab.

**Expected behaviour:**

Clicking the Validators tab should redirect you to see the validator list

**Comment by NodeGuy** [comment]
Do you mean you're seeing a Validators tab on PageValidator?  If so then please try again with the latest develop because there shouldn't be one.

**Comment by faboweb** [comment]
Why are there no tabs on PageValidator? The design suggest there should be: https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5b8556a1cc45e20883c50006

**Comment by NodeGuy** [comment]
This may be an artifact of my conversation with @jbibla in which I convinced him to remove the tabs from `TmBalance`.  In order to be consistent with the design we should reimplement PageValidator as a nested route.  I created a new issue for it: https://github.com/cosmos/voyager/issues/1358
