### ISSUE TITLE
rename and clean up staking vuex modules

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1381]
it's not immediately obvious what these different modules are for or how they relate. i would propose renaming them and ensuring that the separation is necessary. this refactor should also include removing the concept of `candidates` from the code.

```
staking.js
validators.js
keybase.js // needs refactor
```

**Comment by faboweb** [comment]
as far as I know:
delegates -> all validators, would rename to validators
delegation -> staking related information, would rename to staking
validators -> current validator set, could be merged with delegates

**Comment by fedekunze** [comment]
the `candidates.js` module is very time inefficient. There're lots of duplicated/unnecessary `for` loops. Moving this to high priority as it's making the fee distribution vuex module more complex to implement
