### ISSUE TITLE
Create categories pie chart for Txs page

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1422]
Despcription: 

Here's a design I took from N26 (the picture is from their mobile app but we should try). 

It'd be nice to have a pie chart to display the different amounts spend by each of the tx categories. Clicking on a category would show you the list of txs with that category in a certain period (eg 1 month).

Note: the å means atoms (I used it only for this example instead of typing the whole denomination)

cc: @jbibla @nylira @khayeni 

![img_0846](https://user-images.githubusercontent.com/31522760/46570050-d2782c80-c95e-11e8-8a94-ab1ffb549f54.jpeg)

**Comment by jbibla** [comment]
great idea. maybe we need a `transaction history 2` label 😄

**Comment by faboweb** [comment]
I don't want to create more noise, then we already have (about half a year of work at least). I would even propose to close this proposal and reopen it, when there we actually start thinking about a transaction revamp.

**Comment by fedekunze** [comment]
reopening since we are discussing transaction2 features and todos and I'd like to discuss this eventually. Maybe it's not interesting for a user with say 3 txs, but if you have over 100 this would be useful
