### ISSUE TITLE
WalletPage and Send redesign proposal

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1424]
Description:

The wallet page needs a little love to be at the same level as the new designs made by @jbibla. Here's an attached design of my improvement idea:

![wallet voyager page](https://user-images.githubusercontent.com/31522760/46576339-83b2ad00-c9c7-11e8-87ec-49753a0d5fc4.png)

Balances should display each coin balance and clicking on one of them should redirect to the transactions page with a filter to show all transactions using that coin.

The Send page to make transfers should have the same designs as the Delegation/Undelegation modals. 

Happy to hear your thoughts on the subject

**Comment by NodeGuy** [comment]
It looks beautiful but we have no time for it until we're feature complete.  I'm labelling this `wallet2`.
