### ISSUE TITLE
Improve naming of tests

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1465]
All unit tests should be wrapped in a `describe` stating the file the test is handling.

Example: `onDelegation › submitDelegation › redelegation › unit › error`  is missing `PageValidator`. I would have assumed this handles the module `delegation`.

**Comment by NodeGuy** [comment]
Huh, so Jest doesn't report the name of the file automatically?  That's disappointing.

**Comment by faboweb** [comment]
Well it does:

![image](https://user-images.githubusercontent.com/5869273/47077047-615b3380-d200-11e8-8f31-8a91f3c180c6.png)

But I think it is more readable if the tests itself already tell you what you are seeing. This is especially usefully if a lot of tests fail.
