### ISSUE TITLE
Write more contract tests for the remaining Gaia Lite endpoints we use.

### ISSUE THREAD

**Issue by NodeGuy** [luniehq/lunie#1520]
We have [contract tests](https://github.com/cosmos/voyager/blob/03067df8325c49d19fffe9e7e35521f09c534369/test/unit/specs/lcdClient.spec.js#L208-L274) for the `keys` endpoints.  Write contract tests for all of the remaining endpoints used by Voyager.

**Comment by faboweb** [comment]
@NodeGuy did you eval just the split part of this issue or do you think this is really that easy?

**Comment by NodeGuy** [comment]
I evaluated the size of splitting the issue.
