### ISSUE TITLE
add "minimize and persist" feature for action modals

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1631]
would be great to add the option to minimize the action modals while keeping the data in place - allowing users to navigate around the app with actions in a "draft" state.

<img width="537" alt="screen shot 2018-11-22 at 12 05 52 pm" src="https://user-images.githubusercontent.com/6021933/48916117-06e07300-ee4f-11e8-96d8-96a196ccf941.png">
<img width="342" alt="screen shot 2018-11-22 at 12 05 58 pm" src="https://user-images.githubusercontent.com/6021933/48916118-06e07300-ee4f-11e8-8ec5-350d76d799cb.png">

**Comment by fedekunze** [comment]
this is soo cool

**Comment by faboweb** [comment]
The feedback regarding the modal is more negative. We should think about a redesign and test it with colleagues and users.

**Comment by jbibla** [comment]
> The feedback regarding the modal is more negative.

i still think this is a strong interaction model - but i think we need to improve the design to address the negative feedback.

**Comment by faboweb** [comment]
But let's not fall in love too much with our children. ;)

**Comment by jbibla** [comment]
i appreciate what you're saying fabo - but i don't think we've sufficiently tested this. a couple have seemed confused about why it's "not centred" ... has anyone provided feedback about the interaction or the flow? this would be valuable to know.

**Comment by faboweb** [comment]
I know you have read the same feedback as me. We can continue to improve and test this. Just saying, that if people are confused by the concept in its current form, maybe it is not the best interaction model.

**Comment by jbibla** [comment]
this is the feedback from billy:

> weird alignment on the page, the box that popped up is right and bottom aligned, the "no governance proposals" is still there. maybe it's cause i'm on a big screen or maybe this is a modal but it didn't pop up right...

> another bad modal, its bottom aligned and not totally right aligned but def not centred

also, please notice the difference between the design and the implementation (sizing, spacing, font-sizing - also positioning on page in designs vs. actual)...

<img width="511" alt="screen shot 2018-12-13 at 3 56 16 pm" src="https://user-images.githubusercontent.com/6021933/49967037-bc9f5e80-feef-11e8-9c74-f4d13fae4fde.png">

![screen shot 2018-12-13 at 3 56 48 pm](https://user-images.githubusercontent.com/6021933/49967115-ec4e6680-feef-11e8-85e2-f37b65e111c4.png)

**Comment by fedekunze** [comment]
Who’s assigned on this issue?

**Comment by jbibla** [comment]
no we're not - but i'm working on improving the forms a lot.
