### ISSUE TITLE
Handle slow network speeds

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1645]
Description:

We should have add message on the connection bar that the network is slow. 

Ideas:

- https://stackoverflow.com/questions/38137422/show-alert-message-if-the-internet-connection-speed-is-slow-in-android
- https://ux.stackexchange.com/questions/110156/what-would-be-a-user-friendly-message-when-the-user-has-a-slow-internet-connecti

**Comment by jbibla** [comment]
love this idea!

**Comment by jbibla** [comment]
@sabau aside from reducing the bundle (is this idea / project being tracked somewhere?) are there are other easy ways to improve this for us?

try switching to 3G in chrome - the website won't even load 😨
