### ISSUE TITLE
TabValidatorDelegations on PageValidator

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1656]
Description:

> As a validator I'd like to see all the delegations I've received

We can implement a tab within PageValidator with a table showing all delegations

**Comment by jbibla** [comment]
uhhhh i think we are specifically not building this app for validators. has something changed? can you provide some context for this feature?

**Comment by faboweb** [comment]
I agree with Jordan. But this also is tagged as low priority staking 2. We can see if we want this when we tackle that milestone.

**Comment by faboweb** [comment]
Closing in favor of #1015
