### ISSUE TITLE
Design new session sign in flow

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1695]
We need to design the sign in flow for using ledger (without gaia). We then need to get feedback from users for this new design.

Inspiration: Balance.io, MyCrypto

**Comment by faboweb** [comment]
Proposal:
Step by step strategy. The user can choose to either "explore" (not logging in) or "sign in" (if advanced). 
If the user is an explorer and triggers and interaction, he gets a message about needing to sign in and an option to checkout and tutorial about what it means to sign in and sign a transaction.

**Comment by jbibla** [comment]
> The user can choose to either "explore" (not logging in) or "sign in" (if advanced).

i would go one step further and default users to "explore" with a sign in + sign up button for users who wish to do so.

**Comment by fedekunze** [comment]
See #1823

**Comment by jbibla** [comment]
is this ticket covered by the following open tickets or do we need a visuals for this?

#1823
#2121 
#1982

**Comment by fedekunze** [comment]
I think we can close this

**Comment by jbibla** [comment]
i will share some designs very shortly. just finishing up.

**Comment by jbibla** [comment]
https://zpl.io/br8Pg0L

**Comment by faboweb** [comment]
Can we add the sign in with ledger option:
https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5c7d64c5fd01aebc6067941a?did=5c7d74c179fda9bda45cee0c&cmid=5c7d75712e478f51ff637070

And what about creating accounts on testnets?

**Comment by jbibla** [comment]
i can work on the designs / updates this week.

**Comment by jbibla** [comment]
lots of work happening in this area. this ticket is not helpful anymore.
