### ISSUE TITLE
Look up different address' txs on the Transaction history page

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1719]
Description:

Follow up on #1718: 

I think we can also add an input field on the Transactions page to display the transactions from/to the address that the user wants to see.

cc: @cwgoes

**Comment by jbibla** [comment]
there should be a search bar on the tx history page but we should discuss the state of "account specific" features when the user is not logged in.

**Comment by faboweb** [comment]
Relates to #1718
