### ISSUE TITLE
Proposal:  Allow Keybase Teams as Validator Identity

### ISSUE THREAD

**Issue by sunnya97** [luniehq/lunie#1722]
Currently, as part of the identity field for a validator, one can include a keybase key.  However, it would be nice if one could include a _Keybase Team_ as the identity of a validator.

For example, Sikka (validator run by myself and @ValarDragon) exists on Keybase as a team:  https://keybase.io/team/sikka

But this means it does not have Public Key associated with it, but it does have an avatar that we would like to be displayed next to the Validator on Voyager.

Would this be possible?

**Comment by fedekunze** [comment]
++

**Comment by jbibla** [comment]
nice idea @sunnya97!
