### ISSUE TITLE
Input and button order when using tab navigation

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#1724]
Description:

 If you try to navigate using tabs, the order not always reflect the rendered boxes, we should keep them aligned.

ModalsProposal i.e. is mostly OK, but amount comes after the readonly denom

**Comment by jbibla** [comment]
not sure what you mean @sabau can you share a screenshot?

**Comment by faboweb** [comment]
@jbibla "tab navigation" is hard to show in a screenshot. It means pressing the "->"/"tab" key on your keyboard.

**Comment by jbibla** [comment]
ohhhhhhhh thank you i misunderstood
