### ISSUE TITLE
Implement multi step action modals

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1735]
We get some bad feedback about the action modal. It seems to not be well designed for the expectation of customers. Let's come up with 2 proposals on how the action modal should look like and collect feedback from our colleagues.

**Comment by jbibla** [comment]
also, can you share some of the feedback?

**Comment by fedekunze** [comment]
I propose to use the same steps as Ledger Live: 

1. Transaction details (`generate_only`)
2. Connect Ledger and Sign the transaction with the hardware (`sign`)
3. Verification (`broadcast`)
4. Confirmation of the transaction and link to Transaction History or Transaction Page (from the sketches we made)

<img width="486" alt="screen shot 2019-01-14 at 11 06 37 am" src="https://user-images.githubusercontent.com/31522760/51118740-dcc48500-17ef-11e9-984b-fb6be0557403.png">

**Comment by fedekunze** [comment]
If the user uses the account password on step 1 we can skip steps 2 and 3

**Comment by faboweb** [comment]
I would do signing with password also step 2

**Comment by faboweb** [comment]
Wait for https://github.com/cosmos/voyager/pull/1807

**Comment by jbibla** [comment]
#1807 will help make improvements mentioned here easier to implement!

**Comment by fedekunze** [comment]
also we should add a `Back` button on step `2.` to change the tx details before signing with Ledger or password

**Comment by faboweb** [comment]
Bring back the back button he said 🤣

**Comment by jbibla** [comment]
i think this is blocking on #1338

**Comment by faboweb** [comment]
> i think this is blocking on #1338

Can't we already have a design for the signing approach without final implementation?

**Comment by jbibla** [comment]
> Can't we already have a design for the signing approach without final implementation?

my mistake. yes, you are correct. 

i will do this!

**Comment by jbibla** [comment]
ok ya'll!

here are some design proposals. these designs will result in smaller action modals #1897 and add support for numerous signing methods #1823.

https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/dashboard?seid=5c51aeea881152354d6f7101

**Comment by migueog** [comment]
@jbibla Are the designs that you provided above ready to be implemented? If so, could you please invite me to that Zeplin project?

**Comment by jbibla** [comment]
@migueog done! 

there are a lot of improvements mentioned in this thread. please only worry about the following items. I would recommend making a separate PR for each of them as 2, 3, and 4 are fairly substantial.

1. show step count and center modal header
<img width="214" alt="Screen Shot 2019-05-06 at 11 22 38 AM" src="https://user-images.githubusercontent.com/6021933/57235667-64c5d900-6ff1-11e9-857d-fc9faddd4a70.png">

2. display small tx-li for each modal (send, delegation, vote etc)
<img width="618" alt="Screen Shot 2019-05-06 at 11 22 47 AM" src="https://user-images.githubusercontent.com/6021933/57235666-64c5d900-6ff1-11e9-9c02-5adbe02fd28b.png">

3. improved ledger steps UI
<img width="549" alt="Screen Shot 2019-05-06 at 11 23 12 AM" src="https://user-images.githubusercontent.com/6021933/57235664-64c5d900-6ff1-11e9-97cc-f750c9cefa92.png">

4. new proposal modal (without full screen icon or link)
<img width="626" alt="Screen Shot 2019-05-06 at 11 25 47 AM" src="https://user-images.githubusercontent.com/6021933/57235813-bb331780-6ff1-11e9-838f-b1576f669832.png">

**Comment by faboweb** [comment]
For 2) we want to use the actual transaction list component (probably) `LiAnyTransaction`

**Comment by migueog** [comment]
@jbibla Thanks for the invite and outlining the work for this issue! I'll let you know if I run into any troubles.

**Comment by jbibla** [comment]
> For 2) we want to use the actual transaction list component (probably) LiAnyTransaction

yep! thank you @faboweb

**Comment by migueog** [comment]
@jbibla Following your advice with regards to creating a PR for each item in this issue, I was thinking of create a branch for this issue. I would then create a branch for each item in this issue. That way I can create separate PRs for each item and each PR would then be merged into this issues' branch. 

Let me know if approach makes sense to you.

**Comment by jbibla** [comment]
usually we have a branch per issue. when the branch is ready to be merged you can make a PR to develop. feel free to make as many PRs and issues as you'd like. the smaller they are, the easier they are to review and get merged!

**Comment by migueog** [comment]
@jbibla Just checking to see if this is the sort of behaviour you're expecting to see

![stepModalGif](https://user-images.githubusercontent.com/2801551/57558024-2fe7b800-734a-11e9-933b-f2da6acda34e.gif)

**Comment by faboweb** [comment]
Looks good

**Comment by jbibla** [comment]
yep! very much so!
