### ISSUE TITLE
Show worth of vote when voting

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1740]
Description:

Currently the behaviour on the SDK is that if you are a delegator who wants to vote, your vote only counts on the total tally if you have a delegation to a validator. 

Consider the following flow:

1) Not yet bonded delegator casts a vote on proposal 1 
2) Tally of proposal 1 is still the same
3) delegator submits a delegation to validator 
4) Tally of proposal 1 is updated and increased by the delegation amount

This means that on this case, before (or after) the delegator cast a vote , we need to show a message that the vote won't count unless it delegates to a validator before the voting period finishes. 

cc: @faboweb @sabau @jbibla  @jackzampolin 

**Scope**:

if user doesn't have any delegation:

- [ ] Disable Submit button on VoteModal
- [ ] Add message to delegate first

else

- [ ] add a message on VoteModal about how much the vote is worth

**Comment by jackzampolin** [comment]
Agree completely! Great improvement.

**Comment by jbibla** [comment]
do we have to let users vote if they haven't delegated yet?

**Comment by fedekunze** [comment]
> do we have to let users vote if they haven't delegated yet?

I think that's a great question but I think it's more suitable for the SDK team

**Comment by jbibla** [comment]
my gut says we should just tell users they need to delegate before voting - as opposed to letting them vote and telling them their vote won't count until they do another action. we also have to account for changing the way we show their "uncounted vote" which i'd prefer to avoid. 

sometimes, UIs will not directly mimic the SDK.

**Comment by fedekunze** [comment]
> my gut says we should just tell users they need to delegate before voting - as opposed to letting them vote and telling them their vote won't count until they do another action. 

I totally agree

**Comment by faboweb** [comment]
But we also need to teach the user that their vote changes according to bonding/unbonding

**Comment by fedekunze** [comment]
> But we also need to teach the user that their vote changes according to bonding/unbonding

Sounds something we should add to the Voyager tutorial/walkthrough. Thoughts ?

**Comment by faboweb** [comment]
> Sounds something we should add to the Voyager tutorial/walkthrough.

I would do that on top. I always assume the user is not doing the tutorial ;)

**Comment by fedekunze** [comment]
@jbibla updated title

**Comment by fedekunze** [comment]
Do we want to disable the Vote Button on the `PageProposal` or the submit button on the VoteModal ?

**Comment by faboweb** [comment]
I think we shouldn't disable the button but display a message about the worth of this vote. This should educate the user.

**Comment by jbibla** [comment]
> later they undelegate some votes

did you mean undelegate some stake / atoms?

> I still think we shouldn't disable the button but display a message

my preference would be to disable the button on the modal - but include a message on `PageProposal` and on `ModalPropose`  ...

**Comment by faboweb** [comment]
> disable the button on the modal - but include a message on PageProposal and on ModalPropose

ok cool

**Comment by fedekunze** [comment]
> my preference would be to disable the button on the modal - but include a message on `PageProposal` and on `ModalPropose`

@jbibla you mean `VoteModal` instead of `ModalPropose`?

**Comment by jbibla** [comment]
ugh, yes. #awaketooearly

although, can you make a proposal if you're not delegated to anyone?

**Comment by fedekunze** [comment]
So from the comments above, the scope should be:

- if user doesn't have any delegation
   - Disable Submit button on `VoteModal` 
   - if user is signed in, add a message (which one?) on `PageProposal`  (and `VoteModal`?)
- else 
   - add a message on `PageProposal` (and `VoteModal`?) about how much her vote is worth ? (shouldn't this go on the gov tutorial #1786 @faboweb ?)

**Comment by faboweb** [comment]
I would do both. People are not eager to read tutorials from my experience.

**Comment by faboweb** [comment]
From other ticket:
votes depend on staked atoms
votes change if your staked atoms change
votes only count at the end of the voting period
