### ISSUE TITLE
Customize local network

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#1752]
Description:

While working on adding more nodes to the local network command I had an idea to propose: we can decide to have a second parameter to choose how many of them have to become validators:

```
start --nodes=5 --validators=3
```

On the other hand every node should be a validator if not specified explicitely

```
# launching 
start --nodes=3
# is equivalent to
start --validators=3
```

And a third parameter to add N extra accounts to your local network, where their wallet could be empty or with some default values to keep the CLI at a bearable level of complexity
```
start --accounts=3
```

**Comment by faboweb** [comment]
Sounds interesting :)

**Comment by jbibla** [comment]
yep, cool idea!

**Comment by jbibla** [comment]
no longer relevant
