### ISSUE TITLE
multiple validator local-testnet takes too long to start

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1760]
Bug:

`yarn start local-testnet 5` takes too much time because it can't find the address and funds to submit the self-delegation:

This is one of the error outputs, this happens multiple times on each validator (at least 4 times each):

```
ERROR: No account with address cosmos1th5l4qfvxu2f6crzqkkn6z7er27vsmhayw9jl4 was found in the state.
Are you sure there has been a transaction involving it?

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/Users/federico/Projects/voyager/builds/Gaia/darwin_amd64/gaiacli query account cosmos1th5l4qfvxu2f6crzqkkn6z7er27vsmhayw9jl4 --home /Users/federico/Projects/voyager/builds/testnets/local-testnet/cli_home_5 --output "json" --trust-node',
  stdout: '',
  stderr:
   'ERROR: No account with address cosmos1th5l4qfvxu2f6crzqkkn6z7er27vsmhayw9jl4 was found in the state.\nAre you sure there has been a transaction involving it?\n' }
Waiting for funds to delegate
...
```

Full log:
[log.txt](https://github.com/cosmos/voyager/files/2695453/build_61576_step_102_container_0.txt)

**Comment by faboweb** [comment]
It waits for the funds to be there. The error is expected and should be suppressed.

**Comment by jbibla** [comment]
> The error is expected and should be suppressed.

uhhhh can't this be done in a way that doesn't cause errors?

**Comment by faboweb** [comment]
it polls the balance until it is present. just the console error in this case should be suppressed and only one final error if something goes bad should appear imo.

**Comment by faboweb** [comment]
on 2nd thought: stargate should not return errors on empty accounts (if that's what happens).
