### ISSUE TITLE
SDK parameters strategy

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1764]
**Description**:

We probably have to rethink were to put all the parameters from each of the SDK modules since new ones are being added to the existing ones (`stake/gov/auth/slashing/distribution`).

 Do we want to display them all ? In separate tabs ? all in the same tab ? where ? my guess is maybe within `Governance` since we'll have the parameter change proposals in the future.

**Comment by jbibla** [comment]
we should display parameters that are relevant for delegators (our users) in the params tab for staking / gov ... why does this need to change?

**Comment by fedekunze** [comment]
Because there are other parameters as well that can be changed by delegators

**Comment by faboweb** [comment]
they can all go into the same parameters view. if they are special we can mark them somehow.
