### ISSUE TITLE
let's use scoped styles

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1767]
right now, our `<style>` section is missing the `scoped` keyword. i believe we should be using this feature to ensure clean and well-structured css. as such, i'd like to go through our styles and apply the scoped keyword to see what happens (and then fix the resulting issues).

**Comment by faboweb** [comment]
Love it. Would be interesting to investigate if there is something like root level scoping: applying styles only on the template of that component, not on children. this would clean up a lot of css selectors.

**Comment by jbibla** [comment]
i believe [scoped styles](https://vue-loader.vuejs.org/guide/scoped-css.html#scoped-css) (`<style scoped>`) are applied only to the component template by default (not the children). 

but you can specify if you want them to effect the children: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors.

**Comment by faboweb** [comment]
Sold 💃

**Comment by jbibla** [comment]
we've added scoped to many places. we can close this and we will use scoped going forward.
