### ISSUE TITLE
Filter transactions by coin denom

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1772]
**Description**:

It'd be cool to filter only txs from a specific denom on the `Transaction` History page. My idea is that you go to the page `Wallet` and when you click on the `LiCoin` element (not the `Send` btn) you get redirected to the `Transaction` page with the filter activated. 

Imo there should also be a button (`x`) to remove the filter (eg: `Localcoin x`), and the balance header should be updated to only show the `Localcoin` balance (to enable further features like #1773)

Note: balances with 0 amount should also display the past tx history (depends on #1586)

<img width="1296" alt="screen shot 2018-12-22 at 12 11 17 pm" src="https://user-images.githubusercontent.com/31522760/50375840-dd983b80-05e2-11e9-8566-a02962a7f539.png">

<img width="1288" alt="screen shot 2018-12-22 at 12 12 11 pm" src="https://user-images.githubusercontent.com/31522760/50375859-3536a700-05e3-11e9-9b44-aa575628b0c5.png">

**Comment by jbibla** [comment]
great ideas. we'll play with some designs for this in 2019!
