### ISSUE TITLE
update single coin balance on scrolling

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1773]
Description:

Follow up on #1771 and #1772. I'd be nice that to update the balance on the header when you scroll down on your past txs on the `Transaction` page, when the single coin view/filter is displayed. 

In example of the image bellow your balance will increase as you're scrolling: 

<img width="342" alt="screen shot 2018-12-22 at 12 02 51 pm" src="https://user-images.githubusercontent.com/31522760/50375929-21d80b80-05e4-11e9-98f3-47afb0449ab5.png">

**Comment by jbibla** [comment]
i don't get it.
