### ISSUE TITLE
Add tutorial for governance

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1786]
The voting for proposals with your staked tokens is confusing for users. We need to add an explanation here. A small tutorial for now should be fine.

Infos:
- votes depend on staked atoms
- votes change if your staked atoms change
- votes only count at the end of the voting period

**Comment by fedekunze** [comment]
> votes change if your staked atoms change

we should also clarify that the votes tally changes but not the option you submitted

> votes only count at the end of the voting period

i.e the option you submitted is only final after the voting period ends

**Comment by fedekunze** [comment]
no tutorial anymore

**Comment by faboweb** [comment]
> no tutorial anymore

I think we still need this for our users.
