### ISSUE TITLE
Define cookie policy 🍪

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1797]
Description:

We need to define this on Voyager web for GDPR compliance

**Comment by faboweb** [comment]
We can use @nylira approach.

**Comment by jbibla** [comment]
i will share some design ideas.

**Comment by jbibla** [comment]
i'd like to hear from our lawyers on this before i design anything. is that ok?

**Comment by faboweb** [comment]
That could still take some time ^^ We can use something standard in the meantime.

**Comment by jbibla** [comment]
i don't really want to emulate the cookie popup just because everyone else is doing it - if we are not sure what is actually required. plus, we won't really even be certain we're covering our bases in terms of event and error tracking.

**Comment by faboweb** [comment]
Note:
I think we should have error tracking for people who don't sign in. For those a popup and following a set cookie about the preferences would be nice.

**Comment by jbibla** [comment]
here is a nice example from https://safe.gnosis.io/

![screen shot 2019-03-05 at 3 57 50 pm](https://user-images.githubusercontent.com/6021933/53837025-8bb74e80-3f5f-11e9-8d40-4953add93db0.png)

**Comment by faboweb** [comment]
I like it, let's do it.
