### ISSUE TITLE
Voyager Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1798]
Description:

I think we should add this to Voyager. Most of the wallets in the market have them for legal reasons and we should too

cc: @jessysaurusrex

**Comment by jessysaurusrex** [comment]
Just discussed this with @zmanian, and we will be doing some comparative research into ToS for Ledger Live and a few similar applications this week. From there, we should be able to get a good idea for what we need to include and how those agreements should be structured, and then move forward with legal to figure out our next steps.

**Comment by jbibla** [comment]
done!
