### ISSUE TITLE
Improve Ledger connection steps

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1823]
Description:

Imo the steps to connect ledger thought the Hardware session are not intuitive as you have to click the icon to proceed to the next step and to log in. Ideally we should have something like what Ledger live has, with multi step and automatic detection of the device and if you're connected to the Cosmos app:

<img width="566" alt="screen shot 2019-01-14 at 10 48 41 am" src="https://user-images.githubusercontent.com/31522760/51116577-46da2b80-17ea-11e9-98fc-0f27a0d2799f.png">

The steps should be the same but the 3rd one which should say Open the Ledger Cosmos app.

**Comment by fedekunze** [comment]
Here's the image of the top
![connectdevice](https://user-images.githubusercontent.com/31522760/51116696-9fa9c400-17ea-11e9-9f82-fbefd6aa82dc.png)

**Comment by jbibla** [comment]
100% agree!

**Comment by jbibla** [comment]
reminder to collect ledger hardware and firmware version information.

**Comment by fedekunze** [comment]
> reminder to collect ledger hardware and firmware version information.

yes, we probably need to use the ledger library for that (not the Cosmos one). cc: @jleni

**Comment by jleni** [comment]
Do you need the cosmos js library to be extended with this functionality?

**Comment by jbibla** [comment]
i think that would be ideal - the use case i can think of would be for more detailed error messages.

**Comment by jbibla** [comment]
soon, it will not be necessary to "sign in" - signing will be only for transactions.

![screen shot 2019-03-04 at 9 11 49 am](https://user-images.githubusercontent.com/6021933/53738600-a6090380-3e5d-11e9-9f63-512b82c56123.png)

**Comment by jbibla** [comment]
this is still worth doing. our current ledger flow is not so great.

**Comment by jbibla** [comment]
this improvement would be really nice @mariopino ;)

**Comment by mariopino** [comment]
> this improvement would be really nice @mariopino ;)

Another ledger user that thinks it would be great!

**Comment by jbibla** [comment]
let's make sure we generalize this component to work for the extension as well!
