### ISSUE TITLE
Refactor send module

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1828]
In `send.js` we use a mechanism where every request waits until a previous promise is resolved. But this reads very poorly. This should be refactored.

**Comment by faboweb** [comment]
"at once" == "during one block" which is about 5s so this is possible.

**Comment by jbibla** [comment]
can you share what you think the solution might be / an idea for how to solve / improve this?

**Comment by faboweb** [comment]
Sketch:
- queue tx
- on queue start sending txs from queue
- if queuing and already started sending, don't start
- after done sending, send next
- when no next stop

**Comment by faboweb** [comment]
Also consider: Moving number to string conversion to send module. But numbers could be bigger then int...
