### ISSUE TITLE
Optimistic updates for transaction page

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1849]
from #1118: 
```
instead of blocking the user from proceeding with more submissions / transactions ...

- clear form for new tx's
- show loading icon in sidebar next to transactions link
- include the loading tx in tx history instantly with loading icon and adjust language accordingly
- if it fails, replace loading icons with error icons and replace loading language with error language
- on failure, show button to retry transaction
```

designs for this more optimistic approach can be seen here: https://zpl.io/bLDW6gQ

_Originally posted by @jbibla in https://github.com/cosmos/voyager/issues/1092#issuecomment-418142498_

**Comment by jbibla** [comment]
_Originally posted by @sabau in https://github.com/cosmos/voyager/issues/1284#issuecomment-448300448_

we can do in simpler way:
 - not everything needs to have this unfconfirmed state
 - isolated states

Alternative approach:
- Just update the state as if succeeded
- then query for the next block

**Comment by jbibla** [comment]
i'd like to include another improvement here:

- [ ] after submitting a tx, if we display the success notification, let's include a link to the transaction on the transaction page (equivalent to the "view message" link displayed below)
- [ ] let's move the notification to the bottom left - this will fit better with the action modals

- the undo button would be a nice thing to have one day but is not as important as the two previous points and the work @sabau has mentioned above.

<img width="394" alt="screen shot 2019-01-17 at 10 25 41 am" src="https://user-images.githubusercontent.com/6021933/51329277-2d7fec00-1a43-11e9-93af-66e77e619482.png">

reminder: errors shouldn't be displayed in notifications anymore. just success messages.

**Comment by fedekunze** [comment]
related #2295
