### ISSUE TITLE
Refactor user accounts

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1862]
Good question, account + accounts is a bit misleading, It seems accounts comes from the genesis, where instead account is the one you are authenticated with, is that right?

Do we really need to have all the accounts loaded? I don't know how much/fast this list will grow so initially won't be a problem probably

_Originally posted by @sabau in https://github.com/cosmos/voyager/pull/1814_

**Comment by faboweb** [comment]
> I think accounts are all accounts in the keystore, so just yours.

And `account` is the current logged in account I think. But feels like a refactor to me.
