### ISSUE TITLE
Define Export method we want to use

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#1868]
Description:
- We are using different export/import methods in different modules, we should use ES6 when possible
- Avoid side effect: every js file that have the export keyword shuold never call a function at root level of the file, or the function will be called even if you just imported a function from it (now the only example I have in my mind is main.js where we export main but we also call it)
- We should export the minimum set of functions we want to really make available to the outside world

- suggestions and discussion is really welcome, this was one of the ticket I wanted to discuss in person when also Jordan will be here

**Comment by faboweb** [comment]
how do you handle unit testing of functions if you don't export them?

**Comment by faboweb** [comment]
We should use es6 `export` and enforce it with eslint.

**Comment by sabau** [comment]
to test functions we need to export all of them
