### ISSUE TITLE
Transaction filters

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#1870]
- Add filtering
- pre-populate filter with URL query parameters if they match with the filters in the current page
- query at least by `hash`, `block` and `address` 
  - substring or exact match for hash and address? 

(optional) in a different PR we may want to:
- accept array both from URL (; separated values) and from filters to filter from a set of elements
- block is the only outlier that may require range instead

Subticket of: #1744

**Comment by sabau** [comment]
I wasn't 100% to add also this to the current Sprint, what do you think @faboweb

**Comment by faboweb** [comment]
Removed it as we have already a lot on our plate.
