### ISSUE TITLE
Proposal description max length should match the max length set in the SDK

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1871]
it would be nice if this matched the size from the SDK. but we can adjust later.

_Originally posted by @jbibla in https://github.com/cosmos/voyager/pull/1807/review_comment/create_

**Comment by faboweb** [comment]
Chris mentioned that there is only an implicit max length.

**Comment by jbibla** [comment]
> implicit max length.

what does that mean?

**Comment by faboweb** [comment]
https://github.com/cosmos/voyager/pull/1807#discussion_r250216470

There is only a max length per transaction in total.

**Comment by jbibla** [comment]
what is it? let's ensure that the description field is as large as can be to fit within this limit.

**Comment by faboweb** [comment]
@cwgoes what is the max size of tx?

The max length of a description is the max size of the tx minus the length of the title minus the length of the fees string etc. etc.
Hard to calc. We can add a max length that is defensive.

**Comment by cwgoes** [comment]
I am not sure the SDK will directly enforce a maximum size (Tendermint does, but it is quite high) - rather, the maximum size will be set implicitly by a gas limit and gas charged proportional to size.

We can very easily add a separate maximum length just for validator descriptions, and that probably makes sense from the UX perspective too.

https://github.com/cosmos/cosmos-sdk/issues/3420

**Comment by faboweb** [comment]
Thx @cwgoes for creating the issue.

**Comment by faboweb** [comment]
Maybe subtract a heuristic of the size of the rest of the transaction from the max transaction size. @ebuchman what is the max transaction size?

**Comment by sabau** [comment]
Just as reminder @jbibla made a nice expeiment:
- 10000 throwed error
- 5000 worked

**Comment by fedekunze** [comment]
new length limits are:
```
MaxDescriptionLength = 5000
MaxTitleLength = 140
```
