### ISSUE TITLE
make validators an Object instead of array

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1882]
we should make `delegates.delegates` an object: `{address: validatorObject}`

_Originally posted by @fedekunze in https://github.com/cosmos/voyager/pull/1860_

**Comment by faboweb** [comment]
We are doing this for most of the look up lists as it is easier to read querying for one element in this way:

Array (list):
```
list.find(item => item.key === keyIAmLookingFor)
```

Object (dictionary):
```
dictionary[keyIAmLookingFor]
```

**Comment by faboweb** [comment]
See also #1708
