### ISSUE TITLE
Create amount input component

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#1885]
In a lot of ActionModals we will check for the correct amount. @fedekunze recommended we refactor this component out and create a component for it.

We also introduced a "Max" button to maximize the input to the available amount. This should be included in this component.

AC:
- We have an input component that takes a max amount as a property
- The component checks if the amount entered is less or equal to the max amount
- The component allows to switch on a "Max" Button which would display on the right side of the input
- Hitting the "Max" button, the input would be set to the max amount defined by the property
- The component allows for easy binding to a value in a parent form

**Comment by jbibla** [comment]
this is done #2956
