### ISSUE TITLE
clean up URLs for web

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1886]
- [x] `/staking/staking-parameters`--> `/staking/parameters`
- [ ] `/staking/my-delegations`--> `/staking`
- [ ] `/governance/proposals` --> `/proposals`
- [ ] `/governance/staking-parameters`--> `/governance/parameters`
- [ ] `/network` --> `/explore`

- [x] URL doesn't always stay in sync with current route - probably solved by #1313 - may be an issue for other edge cases

**Comment by fedekunze** [comment]
I'm doing this together in #2338
