### ISSUE TITLE
clean up li components

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1930]
- add motion to status icons
- most of these are actually table rows (change name)
- standardize and reuse styles
- delete some of the redundant li components

**Comment by faboweb** [comment]
> * most of these are actually table rows (change name)

I think we should keep them names as list items, because they appear as list items even though they are styled in a different way under the hood.

> * add motion to status icons

what do you have in mind?

**Comment by jbibla** [comment]
> what do you have in mind?

right now they are static colored dots. i think for the green dots it would be better to use an icon of some kind and have it pulse or spin to show "alive-ness"

**Comment by faboweb** [comment]
https://media.giphy.com/media/YEL7FJP6ed008/giphy.gif
