### ISSUE TITLE
Warn if user is trying to delegate to a jailed validator

### ISSUE THREAD

**Issue by jackzampolin** [luniehq/lunie#1932]
Feature request:

If a delegator is trying to delegate to validator that is jailed, we should warn the user.

**Comment by jbibla** [comment]
nice idea.

**Comment by jackzampolin** [comment]
@jbibla thank you! I think it needs to get spec-ed out a bit better.

**Comment by jbibla** [comment]
what do you mean exactly? on our end, we can just add a warning for our users. delegating to a jailed validator isn't necessarily bad .. assuming they unjail themselves soon? is it?

**Comment by jackzampolin** [comment]
@jbibla We used to not allow this in code, but there is no in protocol reason to not allow delegation to a jailed validator. I think the usecase would be to delegate to a validator who is going to be unjailed soon. 

We should however notify the users if they are trying to do this to make sure its what they want.

**Comment by jbibla** [comment]
thanks for the clarification. we'll do this!

**Comment by jbibla** [comment]
this is still worth implementing.
