### ISSUE TITLE
Cache user address for querying accounts

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1953]
Description:

we should cache the `user.address` to query the account balance, delegations, transactions, etc as stated in #1638 

Note that it's different from the `wallet.address` as the first can change for different address look up (See #1719), while the 2 is the ledger/ keystore address for signing txs

**Comment by faboweb** [comment]
> Note that it's different from the `wallet.address` as the first can change for different address look up (See #1719), while the 2 is the ledger/ keystore address for signing txs

we need to redesign transaction lookup. `wallet.address` will probably not be used when we implement this.

**Comment by fedekunze** [comment]
we use it to send txs (eg: from `ledger.pubKey()` get the account address and set it to `wallet.address`)

**Comment by faboweb** [comment]
`wallet.address` should probably not be used for sending either but `user.address` as a single source of truth for the session a user is logged in with.
