### ISSUE TITLE
Show address on Ledger

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1962]
Description:

need to update the ledger cosmos app

Ref: [ledger.showAddress()](https://github.com/ZondaX/ledger-cosmos-js/blob/master/src/ledger-app.js#L281)

**Comment by jbibla** [comment]
why should we do this?

**Comment by jleni** [comment]
Do you need the address to be returned too? 
This means that you will need to send the HRP (bech32 human readable part) in the request. Is that acceptable? At the moment, you can retrieve the pubkey and ask the device to show the address in teh screen.

**Comment by fedekunze** [comment]
moved to #2181

**Comment by fedekunze** [comment]
@jbibla reopening this as this feature allows you to show the address you have on the Ledger
