### ISSUE TITLE
Internal error: already subscribed

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#1970]
![screen shot 2019-02-13 at 5 38 23 pm](https://user-images.githubusercontent.com/6021933/52727793-46ce7680-2fb6-11e9-9d94-b395abdb16b3.png)

**Comment by jbibla** [comment]
in `wallet.js`: 

```
 queries.forEach(query => {
        node.rpc.subscribe(
          {
            query
          },
          onTx
        )
      })
```

**Comment by faboweb** [comment]
It's not really a bug. The subscription is already there when you "sign out" and then "sign in" again. I propose we handle this when we get rid of tendermint-js and handle our websocket connection ourself. (#1858)

**Comment by jbibla** [comment]
we shouldn't resubscribe ... but your proposal sounds fine. maybe in the very short term we can just remove the pesky notifications!

**Comment by faboweb** [comment]
> is this causing notifys?

no it just shows a console.error

**Comment by jbibla** [comment]
@faboweb is this still an issue? i haven't seen in a while.

**Comment by faboweb** [comment]
I think so, you need to sign in > sign out > sign in so it subscribes twice.

**Comment by faboweb** [comment]
Does this raise a notification?
