### ISSUE TITLE
Show warning if trying to use Ledger in Safari or Firefox

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#1995]
Description:

Safari throws an error if you click on the icon to connect ledger on mobile: [https://voyager-staging.interblock.io](https://voyager-staging.interblock.io)

![unadjustednonraw_mini_2cb2](https://user-images.githubusercontent.com/31522760/52941274-af2ba800-3368-11e9-9714-552b6baa1156.jpg)

**Comment by faboweb** [comment]
Do we even have ledger on mobile browsers?

**Comment by jbibla** [comment]
let's hide the ledger option on mobile until we support ledger x

**Comment by fedekunze** [comment]
> Do we even have ledger on mobile browsers?

The Nano X

> let's hide the ledger option on mobile until we support ledger x

Let's not hide it but show a message to use a desktop browser

**Comment by faboweb** [comment]
> Let's not hide it but show a message to use a desktop browser

👍 

> The Nano X

I haven't even seen one yet ^^

**Comment by jbibla** [comment]
- session modal should say you can only sign in on desktop 😭 
- until we are able to "sign in" without a ledger / password

**Comment by faboweb** [comment]
If only "ledger" is available. If in insecure mode I think people can sign in.

**Comment by faboweb** [comment]
This is happening also on desktop Safari

**Comment by faboweb** [comment]
Apparently Firefox on Mac also doesn't work.

**Comment by migueog** [comment]
@faboweb When I try to reproduce this error using Firefox and Safari, the sign in process doesn't conclude. Is this the error that you're running into?
