### ISSUE TITLE
JS Reserved words

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#2014]
Description:
Currently we are using some js reserved words as variable names around the project, we should avoid doing that as it may cause unexpected behaviours.
`module`, `from`, `default`, `class`, ...
All those should be contextualised and we may want to add an eslint rule to avoid falling into this problem again

**Comment by faboweb** [comment]
do we use any of those apart from `from` out of context?

**Comment by faboweb** [comment]
let's enable the eslint rule for this
