### ISSUE TITLE
Gracefully killing local nodes

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#2041]
**Describe the bug**
Currently when you kill  a running local node it happens they keep running, I would like to have them all die when I press `crtl-c` or just close the terminal

**To Reproduce**
1. `yarn start`
2. `ctrl-c`
3. `yarn start`
4. Ports already busy by previous ran

**Expected behavior**
Every run should kill all his processes when stopped, so anyone can expect to be able to stop and rerun without killing them indipendently

**Comment by faboweb** [comment]
Still an issue:
1. yarn start
2. close terminal
3. yarn start somewhere else
