### ISSUE TITLE
Do not load data while users are not looking at Lunie

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2084]
Stop websocket connections and http calls while user is not looking at page / tab is not active

**Comment by faboweb** [comment]
Decided to check for connection
We should use exponential back off

**Comment by faboweb** [comment]
After a couple of minutes show a reconnect modal

**Comment by jbibla** [comment]
> show a reconnect modal

not sure if we need a modal for this. our "you're not connected" in app components should display everywhere - tm connected can switch from "reloading" to a "retry" link.

**Comment by jbibla** [comment]
hey @faboweb can you clarify this for benji?

> Decided to check for connection
> We should use exponential back off

**Comment by faboweb** [comment]
Exponential back off:
Increase each interval to recheck for connection. I don't know but this is necessary and anyway could be done in a second step.
