### ISSUE TITLE
Statuses/Errors structure for specific objects accessed direclty

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#2099]
I think I will never see the error, we had a little discussion with @faboweb about this, I'll open an issue where we can develop

Here the loaded status is shared across `getProposals` and `getProposal`, when you access a proposal that `proposalId` is going to the `proposals` dictionary, but loading, loaded and error are promiscuous, same happen for transactions etc.. 

We were thinking of changing the priority in TmPage so error rule, and error in this case should not come from `proposals.error` but from either:
- `proposals.statuses[proposalId]` if we want a structure with `{loading, loaded, error}`
- `proposals.errors[proposalId]` if we want to store just errors

All this apply only to proposals that got accessed directly from URL, the others won't mind, they are already in the store thanks to `getProposals` and adding a bunch of `true false null` for every proposal scanned is not really useful I think, so we should expect those flags to be also undefined in case of succesfully fetched proposals

This shuold be generic so we can replace the word `proposal` with transaction etc..

_Originally posted by @sabau in https://github.com/cosmos/voyager/pull/2066/review_comment/create_

**Comment by jbibla** [comment]
yes, you are correct. right now, users will not see this error. we need to use the error properties per module and per item to trigger the proper in-app-error components (instead of notify). same applies for loading.

i would consider this fairly high priority, as this has a huge impact on user experience and usability.

**Comment by jbibla** [comment]
relates to #2121

**Comment by faboweb** [comment]
We also need a global error:
as there might be an issue with "loading all txs" and "loading one tx"

**Comment by fedekunze** [comment]
My opinion is that an item with an error or on loading state shouldn't prevent you form accessing others. 

This discussion from which option should we use needs to be done per module, for some might not be important to have all the individual `statuses`

**Comment by faboweb** [comment]
> This discussion from which option should we use needs to be done per module

I would rather have a standard so thinking about modules is easier and accessing them from the components is easier.

**Comment by jbibla** [comment]
> This shuold be generic so we can replace the word proposal with transaction etc..

`items`

**Comment by faboweb** [comment]
Maybe we don't need the states if we use a modern connection library like GraphQL
