### ISSUE TITLE
Loading, Disconnected, Blank, and Error states are not behaving as expected.

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2121]
## Wallet
- [x] placeholder for when user has no balances
- [x] component for when user is not signed in
- [ ] loading state for when balances are loading
- [ ] error state for when there is an error getting balances

## Transactions
- [ ] placeholder for when user has no transactions
- [x] component for when user is not signed in
- [x] loading state for when transactions are loading
- [ ] error state for when there is an error getting transactions

## Staking
- [x] placeholder for when user has no delegations
- [x] component for when user is not signed in 
- [ ] loading state for when delegations are loading
- [ ] error state for when there is an error getting delegations

### Validators
- [ ] loading state for when validators are loading
- [ ] error state for when there is an error getting validators

### Validator
- [ ] loading state for when validator is loading
- [ ] error state for when there is an error getting validator

## Governance
- [ ] placeholder for when there are no proposals
- [ ] loading state for when proposals are loading
- [ ] error state for when there is an error getting validators

### Proposal
- [ ] loading state for when proposal is loading
- [ ] error state for when there is an error getting proposal

## Network
- [ ] loading state for when blocks are loading
- [ ] error state for when there is an error getting blocks

### Block
- [ ] loading state for when block is loading
- [ ] error state for when there is an error getting block

**Comment by faboweb** [comment]
I started on this.
