### ISSUE TITLE
Improve error messages for malformed decimal numbers

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2123]
**Describe the bug**

If the user types in a bad decimal number like `1..2.3` there currently is no way to validate these numbers. JS triggers an input event but doesn't sent back the actual string but sends an empty string. This way Vuelidate will always trigger the `required` check.

Proposal: Remove Vuelidate and use native form validation.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
we can still use Vuelidate and create a custom function to validate decimals

**Comment by jbibla** [comment]
@fedekunze is correct! 

are there other reasons you want to remove vuelidate?

**Comment by faboweb** [comment]
please one of you try it yourself

**Comment by faboweb** [comment]
Note: Don't invest too much

**Comment by fedekunze** [comment]
Spent an almost an hour in this, it's not possible to overwrite the `required` error by defining a custom `isValidNumber` function on vuelidate
