### ISSUE TITLE
rename initializeWallet dispatch

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2127]
let's rename `initializeWallet` to `initializeAccount` or `initializeSession` then

_Originally posted by @faboweb in https://github.com/cosmos/voyager/pull/2049_

**Comment by jbibla** [comment]
which one will we choose?

**Comment by faboweb** [comment]
Probably have a meta action `initializeSession` which is called on sign in. `initializeWallet` could then call `initializeWallet`.
