### ISSUE TITLE
Bring back Create Proposal button

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2157]
**Is your feature request related to a problem? Please describe.**

We removed the button as the the UI was inconsistent.

**Describe the solution you'd like**

Buttons should always be visible. The modals then show a message regarding the user needs to sign in. So the "create proposal" button should be visible on the PageProposals even if the user is not signed in.

**Describe alternatives you've considered**

--

**Additional context**

**Comment by jbibla** [comment]
our convention is to not hide buttons but show the correct messaging. 

- button should always be visible and clickable
- create proposal modal should prompt user to sign in
