### ISSUE TITLE
Redirect to 404 on not found validator

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2164]
**Describe the bug**

When I go to a validator route that doesn't exist the app stays empty

**To Reproduce**

go to `https://localhost:9080/#/staking/validators/cosmosvaloper1lknsahxsn9yfxr7q400y6xyezxpqq4c90xrn8d`

**Expected behavior**

The app redirects to `/404`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by thebkr7** [comment]
Resolved but due to issue #2683 if the user triggers a refresh when on the validator specific page it 404's. I will wait to make a PR until I've fixed that issue for a better UX.
