### ISSUE TITLE
Sign in with password not displayed after account creation

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2168]
**Describe the bug**

Sign in with password not displayed after importing seed

**To Reproduce**

1. `yarn start:new`
2. Import seed
3. Log out
4. Click Sign in

Doesn't display Sign in with password option
After refreshing it is solved
 
**Expected behavior**

Show sign in with password after importing seed

**Screenshots**

cc: @jbibla

**Comment by jbibla** [comment]
@faboweb fixed this
