### ISSUE TITLE
Message port closes before response is received

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2171]
**Describe the bug**

When you submit a transaction from the action modal, there is a console error.

**To Reproduce**
- Click "Delegate"
- Include amount and password
- Hit enter on the submit button

`Unchecked runtime.lastError: The message port closed before a response was received.`

**Expected behavior**

Transactions should succeed or fail without console errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 
 - Browser: Chrome
 - Version: 72.0.3626.119 & 72.0.3626.121

**Additional context**

Seems to be fairly consistent. May apply to all action modal actions.

**Comment by faboweb** [comment]
I can't reproduce this (on local and production). Is this still happening?

**Comment by jbibla** [comment]
yep, unfortunately.

**Comment by fedekunze** [comment]
Yes all the time

**Comment by sabau** [comment]
Can you post a screencast? I can't reproduce, maybe our timings are different

**Comment by faboweb** [comment]
Assuming this doesn't happen anymore
