### ISSUE TITLE
Shorten block hash a la short-bech32

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2173]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently, we display the full block hash on PageBlock. It would be nicer to apply the same principles to the block hash as we do to bech32 addresses. We should shorten the hash and display the full hash in a tooltip.

**Describe alternatives you've considered**

We could leave it as is, but this would be an easy improvement.

**Additional context**

**Comment by fedekunze** [comment]
please consider #1741
