### ISSUE TITLE
disable sending txs to yourself 

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2178]
**Is your feature request related to a problem? Please describe.**

Not required for testing anymore.

**Describe the solution you'd like**

Show error on Send modal

**Comment by jbibla** [comment]
was this a feature for testing? i don't see any reason to stop users from doing this if they want to. maybe a warning message if the addresses match - but this seems fine to me.

**Comment by fedekunze** [comment]
I’m fine with showing a warning message
