### ISSUE TITLE
HD wallet support

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2181]
Now that `v1.1.1 `of the ledger app is released, it supports getting multiple addresses from the Ledger. 

**Is your feature request related to a problem? Please describe.**

Users with Ledger will want to use several accounts for sending and receiving transactions. 

Use cases:
1. One address for each coin (eg: atoms, photons)
2. One address to transact exclusively with a specific chain
3. One address to transact only with another specific address
4. One address for receiving all delegation rewards from all the addresses
5. One address to delegate for each delegation to distinct validators

**Describe the solution you'd like**

- "Generate" a new address for each new receiving transaction
    - Click a button to generate a new address from a new path
- Display addresses from the HD wallet and select them to sign txs
     - Select an account on the Action modal **before** rendering the child transaction modal (i.e step 1: select account, step 2: fill tx form, step 3: sign)
- Display transactions for all accounts "generated"
    - (nice-to-have) Filter transactions by addresses available on the HD wallet
- Display balances for all accounts "generated"
- Set withdraw rewards address to one of the generated HD addresses (see case 4)

Not sure what's the process for querying other stuff:
- should we only show total delegation amount from the first generated address, the last one, sum of all ?
- same with other staking, governace and distribution actions.

**Describe alternatives you've considered**

- Iterate over the HD path index or account to generate a new address/pubkey
- Store the account and index number for signing with ledger (see format below)
- Restore `wallet.address` (?) (default address and HD path for sending txs, can be updated on preferences)

Format for `session.address` should be the following, : 
```
{
address: { 
    account: <int32>,
    index: <int32>
  }
}
```

**Additional context**

The `HD path` used has the following format:  `[44, 118, account, 0, index]`
Each `(account, index)` combination gives you a new address and pubkey. 

For instance, in the example below, you get the address and pubKey from account = 5 and index = 3  
```
hdPath = [44, 118, 5, 0, 3];
address = await app.showAddress("cosmos", path)
```

then you can use the path from that address to sign txs

```
await app.sign(hdPath, tx)
```

**Comment by jbibla** [comment]
amazing summary @fedekunze and a bunch of great ideas here.
