### ISSUE TITLE
Flickering error in Modals Deposit and Proposal

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2190]
**Describe the bug**

For some milliseconds an error appears on the modal deposit

**To Reproduce**

- create proposal with less then needed deposit
- click on the proposal before the next block

**Expected behavior**

no error shows

**Additional context**

https://github.com/cosmos/voyager/pull/2167#pullrequestreview-211204495

**Comment by fedekunze** [comment]
I can't reproduce this anymore. Can you check too ?

**Comment by faboweb** [comment]
Reproduced on develop

**Comment by fedekunze** [comment]
also occurs on ModalProposal

**Comment by jbibla** [comment]
this might be an issue with the simulation request.

`initialDeposit: {}` might need to become `amount: {}`
