### ISSUE TITLE
Optimistic Updates: Voting

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2191]
**Is your feature request related to a problem? Please describe.**

If I vote, the voting on PageProposal and PageGovernance doesn't change until the next block.

**Describe the solution you'd like**

I would like to immediately see my voting changing the results to be sure my action had results.

**Describe alternatives you've considered**

Leaving it as is as it will be updated after a couple of seconds.
Maybe we could just flag the proposal as "updating" and don't do an optimistic update.

**Additional context**

**Comment by fedekunze** [comment]
yeah... we'd have to calculate how much the vote is worth depending on the user's delegations

**Comment by jbibla** [comment]
we've worked on implementing optimistic updates across the board - let's not stop here!

**Comment by faboweb** [comment]
I almost finished this already, but wanted the other stuff to get merged already.

**Comment by jbibla** [comment]
status here @faboweb ?
