### ISSUE TITLE
stop using notify for success and error messages

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2218]
**Is your feature request related to a problem? Please describe.**

Notify is very disruptive. We have discussed removing it for most use cases. 

**Describe the solution you'd like**

Stop using notify. Show success and error messages in app instead.

**Describe alternatives you've considered**

We could keep it and be annoyed for eternity. 

**Additional context**

**Comment by fedekunze** [comment]
success message should be a check displayed on the action modal imo

**Comment by jbibla** [comment]
as well, we need to use the sidebar to show loading on the tx page. we can put a check there for a bit too.

**Comment by faboweb** [comment]
> success message should be a check displayed on the action modal imo

remember also #1631 which could include a spinner + success indicator

**Comment by jbibla** [comment]
> remember also #1631 which could include a spinner + success indicator

do you mean, we could add a spinner and success indicator _in_ the action modals? this is a nice idea - don't see it mentioned on #1631

**Comment by sabau** [comment]
![notification](https://user-images.githubusercontent.com/1656471/54933526-1961da80-4f1d-11e9-8bb2-91e783845a6c.jpeg)
