### ISSUE TITLE
add tooltips to balance header

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2220]
**Is your feature request related to a problem? Please describe.**

Based on user feedback originally documented in #1812 we may want to consider adding tooltips to the balance header because "Total" and "Available" may not be as self-explanatory as originally thought.

**Describe the solution you'd like**

Add tooltips to important details on the balance header.

**Describe alternatives you've considered**

Alternatively, we could hide "Available" until there is a difference between Total and Available which may help to indicate to the user what it _actually is_.

**Additional context**

_originally from https://github.com/cosmos/voyager/issues/1812_:

> I don't know what total / available mean, and there are no tooltips - I guess "total" includes any stake I might have delegated (and thus locked up) at the moment?

**Comment by faboweb** [comment]
Please formulate a good issue
