### ISSUE TITLE
Display amount of rewards obtained from reward withdrawal

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2222]
**Is your feature request related to a problem? Please describe.**

Currently we don't show on the transactions how many tokens you gained when you withdraw rewards.  

**Describe the solution you'd like**

Show the rewards obtained with the withdraw transaction.

**Describe alternatives you've considered**

Query balance before and after withdrawal and get the difference (short term)
Get the reward coins obtained through Gaia-lite (post-lunch release)

**Additional context**

<img width="1416" alt="Screen Shot 2019-03-05 at 10 31 10 AM" src="https://user-images.githubusercontent.com/31522760/54052424-ab12dd80-41e4-11e9-9dee-ab3048bc1ab2.png">

cc: @jackzampolin @alexanderbez

**Comment by alexanderbez** [comment]
This would be super simple once we implement an event-based log system in the sdk (e.g. `ctx.Event("delegation_rewards", coins)`. I'm not sure there is a super clean solution in the short-term.

**Comment by jbibla** [comment]
> post-lunch

🍔

**Comment by fedekunze** [comment]
> This would be super simple once we implement an event-based log system in the sdk (e.g. ctx.Event("delegation_rewards", coins). I'm not sure there is a super clean solution in the short-term.

I think that's too much overhead, we just need to either 

- add an `amount` field to the request withdraw message, or 
- return the amount withdrawn by adding it to the response message

**Comment by faboweb** [comment]
Should this issue move into the SDK?

**Comment by alexanderbez** [comment]
> return the amount withdrawn by adding it to the response message

Seems like the easiest approach. Sure @faboweb.

**Comment by faboweb** [comment]
This is now possible as the tags on a withdraw tx include the withdraw amount.

**Comment by faboweb** [comment]
Still relevant

**Comment by jbibla** [comment]
would be nice to do this still. probably very simple.

**Comment by alexanderbez** [comment]
This is now emitted in the txs event logs.

**Comment by jbibla** [comment]
> Wait till the next major upgrade

@alexanderbez do you mean cosmoshub-3?

**Comment by alexanderbez** [comment]
Yup!

**Comment by jbibla** [comment]
we can implement on gaia-13k6

**Comment by jbibla** [comment]
yes, please. let's do this already!

**Comment by jackzampolin** [comment]
This should not be doable fwiw

**Comment by jbibla** [comment]
yep! definitely, thanks @jackzampolin. 

@Bitcoinera @mariopino is this covered with the new tx abstraction work?

**Comment by Bitcoinera** [comment]
> @Bitcoinera @mariopino is this covered with the new tx abstraction work?

Yes, it is. But in multidenom networks we only display the staking denom.

**Comment by jbibla** [comment]
> in multidenom networks we only display the staking denom.

ok for now!

**Comment by Bitcoinera** [comment]
> ok for now!

Cool. This is how it is looking now:

<img width="530px" src="https://user-images.githubusercontent.com/40721795/75165874-5503b680-5723-11ea-9d98-3800d05a95cd.png">

**Comment by mariopino** [comment]
Related: https://github.com/luniehq/lunie-api/issues/369
