### ISSUE TITLE
Vesting account and coins support

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2228]
**Is your feature request related to a problem? Please describe.**

I'd like to know if any of my coins are vesting (locked) and the time they vest so I can choose those vesting coins over the regular ones to delegate.

**Describe the solution you'd like**

- Clearly separate vesting coins from regular coins on the wallet balance
- Choose either vesting (`original_vesting`) or regular coins (`coins`) for staking (delegation, redelegation) and governance.
- If (re)delegate using my vesting coins, I want to see that the delegation was made with them and not with regular coins
- Show a message on Send action modal that the `original_vesting` coins are locked and I can't transfer them until `end_time` date
- (optional) show a time progress bar for when coins become vested (unlocked) on the Wallet Page

**Describe alternatives you've considered**

- create a separate state for vesting balances (`original_vesting`)
- add a dropdown on action modals to choose which coin to use: regular or vesting (`original_vesting`)

**[BaseVestingAccount](https://github.com/cosmos/cosmos-sdk/blob/4b765b6ab4dfac38a896b66478b3b14b40d0c731/x/auth/account.go#L178-L191
)**

A vesting account has the following additional fields:

```
type BaseVestingAccount struct {
	*BaseAccount

	OriginalVesting  sdk.Coins `json:"original_vesting"`  // coins in account upon initialization
	DelegatedFree    sdk.Coins `json:"delegated_free"`    // coins that are vested and delegated
	DelegatedVesting sdk.Coins `json:"delegated_vesting"` // coins that vesting and delegated

	EndTime int64 `json:"end_time"` // when the coins become unlocked
}
```

**[ContinuousVestingAccount](https://github.com/cosmos/cosmos-sdk/blob/4b765b6ab4dfac38a896b66478b3b14b40d0c731/x/auth/account.go#L347-L353)** 

Same as the `BaseVestingAccount`, but it additionally has a **start_time** for `when the coins start to vest`:

```
type ContinuousVestingAccount struct {
	*BaseVestingAccount

	StartTime int64 `json:"start_time"` // when the coins start to vest
}
```

AC:
- [x] display vesting accounts tokens
- [ ] display vesting account information

**Comment by fedekunze** [comment]
`low priority` label description:  `has been discussed, will be addressed later`. This hasn't been discussed yet, so removing the label until then

**Comment by faboweb** [comment]
also make default account a vesting account
