### ISSUE TITLE
Pressing enter on action modals should submit forms

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2234]
**Describe the bug**

Pressing enter on action modals should submit the form. Currently, it does not.

**To Reproduce**

- go to wallet page
- open send modal
- fill in empty form fields
- press `Enter`
- form is not submitted

**Expected behavior**

I would expect the form to be submitted.

**Additional context**

I believe this would be more semantic and accessible HTML.

**Comment by fedekunze** [comment]
technically not a bug tho

**Comment by jbibla** [comment]
if you press enter and expect the form to behave how html forms are supposed to behave, then i think it's a 🐞

**Comment by fedekunze** [comment]
https://stackoverflow.com/questions/42951967/handling-enter-key-in-vue-js

**Comment by fedekunze** [comment]
I tried to fix this for 2 hours, no result. Seems like either the click-outside or some of the template components closes the modal once you press `Enter`
