### ISSUE TITLE
Optimistic updates: Withdraw rewards

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2235]
**Is your feature request related to a problem? Please describe.**

As a user
I want to see the remaining withdrawable rewards to update immediately after claiming them
So I feel comfortable that my action worked.

**Describe the solution you'd like**

Update the claimable rewards immediately

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
is there some way we can use the action modals to help make this happen by default instead of having to manually implement this for every tx type?

**Comment by fedekunze** [comment]
all success txs should also trigger get balance and query txs (besides the individual action)

**Comment by faboweb** [comment]
But that would not be optimistic and only get called after each block. So in the worst case there is 5s delay for the update. We still need to update the state after a tx is sent.
