### ISSUE TITLE
Block requests if page not visible

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2243]
**Is your feature request related to a problem? Please describe.**

Cosmos Wallet is requesting a lot in the background. This is consuming data and power. Users would probably prefer to not have this.

**Describe the solution you'd like**

We can use https://davidwalsh.name/page-visibility in `api.js`.
This would not submit any request if the page is not active.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
this is a great idea. additionally, there may be a few places where we are making requests that are not necessary or are redundant.
