### ISSUE TITLE
Add memo to transactions via UI

### ISSUE THREAD

**Issue by ten-eugeniy** [luniehq/lunie#2265]
There isn't any way to set custom memo message to transaction sent via Voyager.
Can we have an option to include it when sending coins?
Would be nice to see the memos in the Transactions listing view.

**Comment by fedekunze** [comment]
this is a great feature imo too 👍 let me share this with the team

**Comment by jbibla** [comment]
definitely. thanks @ten-eugeniy!

**Comment by ten-eugeniy** [comment]
are there any estimation to when we will have the feature? if we will

**Comment by jbibla** [comment]
can you help us unserstand the use case a little bit more? what you are hoping to use the memo field for?

**Comment by ten-eugeniy** [comment]
sure, @jbibla 
I'm trying to use it to identify the source of incoming transaction, particularly user identifier of the system we develop. We are trying to avoid using HD wallets to make it simpler for us

**Comment by jbibla** [comment]
i'm not sure i understand exactly. you'd like to learn how to implement this feature in your own UI or you want to be able to track the memo field in your UI based on what users input from Voyager?

maybe this link is helpful? https://github.com/cosmos/voyager/blob/a7fdb4e547b9c0b9fb05056362aa7f95d0262e5a/app/src/renderer/vuex/modules/send.js#L102

we set a memo by default already.

**Comment by ten-eugeniy** [comment]
I'd like to be able to track users input. Of course, users should be able to put whatever they want into memo field.

**Comment by ten-eugeniy** [comment]
so, are there any plan/estimations? will the feature be available? the answer to this question is extremely important for us.

**Comment by fedekunze** [comment]
@ten-eugeniy Sure, I can add it this week
