### ISSUE TITLE
New proposal alert notifications

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2275]
**Is your feature request related to a problem? Please describe.**

Hard to keep track when a new proposal was generated without checking explorers.

**Describe the solution you'd like**

> @cwgoes: I would love a governance proposal notification bot, so I can stop checking whether there have been any yet

> @jaekwon: we should make a general purpose alert module that can handle various kinds of events notifications...
w/ twilio integration.

**Comment by faboweb** [comment]
We could make a web notification listening on Tendermint events. Could be costly though. Alternative would be a service that sends pushes.

**Comment by jbibla** [comment]
this is a huge new feature and i would not consider it part of governance-2 - it would be applied to all modules.

**Comment by faboweb** [comment]
> this is a huge new feature and i would not consider it part of governance-2 - it would be applied to all modules.

agreed

**Comment by cwgoes** [comment]
I would still :heart: this feature.

Ideally the notifications could be asynchronous (sent even if I don't log in to Lunie, over email, push or the like).

**Comment by jbibla** [comment]
me too. go away stale-bot.

**Comment by faboweb** [comment]
still valid

**Comment by jbibla** [comment]
we are actively working on this now
