### ISSUE TITLE
Handle syncing

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2286]
**Describe the bug**

If the full node is syncing we do some requests which fail.

**To Reproduce**

Run a full node and sync with main-net.

**Expected behavior**

No errors notifications.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
I get this error too: https://forum.cosmos.network/t/cant-sign-in-with-ledger-nano-s/1740/5

**Comment by jbibla** [comment]
easiest solution: full screen message if node is syncing.

**Comment by faboweb** [comment]
Disable requests + trigger reconnect handling on full sync

**Comment by jbibla** [comment]
no longer relevant.
