### ISSUE TITLE
Cancel tx

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2292]
**Is your feature request related to a problem? Please describe.**

If you close the action modal while viewing the ledger for confirmation, it can be unclear as to what is happening.

**Describe the solution you'd like**

Give the user the option to cancel a tx in the action modal and do this action automatically if the action modal closes. 

**Describe alternatives you've considered**

Not sure what would happen if the user signed a tx on their ledger while the action modal was closed... @fedekunze any idea?

**Additional context**

**Comment by fedekunze** [comment]
ledger timeouts if there's no response, so that case is handled

**Comment by fedekunze** [comment]
> Give the user the option to cancel a tx

Agree here

**Comment by fedekunze** [comment]
Idk if it's still there, but we should remove the close on click outside interaction

**Comment by jbibla** [comment]
> we should remove the close on click outside interaction

good thinking. i think we need to think about this in the context of #1631. but this might make sense.

**Comment by faboweb** [comment]
So this only targets signing with ledger?

**Comment by jbibla** [comment]
this should be possible from the action modal for any type of tx.

@jleni is it possible to cancel / reject a transaction programatically from the UI?

**Comment by jbibla** [comment]
this applies to the extension approval screen as well. consider adding alerts if the user tries to close the action modal. 

@colw let's discuss together.
