### ISSUE TITLE
Display ledger's firmware version

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2298]
**Is your feature request related to a problem? Please describe.**

Getting the firmware version could help to identify unsupported Cosmos app versions.
Ref: [Unable to sign tx with ledger](https://forum.cosmos.network/t/unable-to-sign-delegation-transaction-with-ledger-nano-s-cosmos-app/1677)

**Describe the solution you'd like**

Get and display connected ledger's firmware version. Eg from Ledger live

<img width="740" alt="Screen Shot 2019-01-14 at 10 58 19 AM" src="https://user-images.githubusercontent.com/31522760/54474758-1feba600-47e9-11e9-918e-fda74ba08904.png">

**Describe alternatives you've considered**

TODO: look into Ledger docs

**Additional context**

**Comment by jbibla** [comment]
nice idea. 

we should be able to check:

1. if the ledger is plugged in
2. what state it's in (open, closed, screensaver) 
3. if the cosmos app is installed
4. what version the ledger firmware is
5. what version of the cosmos app they have installed
