### ISSUE TITLE
Display Cosmos ledger app version

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2299]
**Is your feature request related to a problem? Please describe.**

Could help identify unsupported versions.
Coupled with #2298 

**Describe the solution you'd like**

Display cosmos app version when connected to ledger.
Not sure where to put it on the UI, maybe on Wallet Page ?

**Describe alternatives you've considered**

Version is already retrieved from Ledger, just need to show it on UI. cc: @jbibla 

**Additional context**

**Comment by jbibla** [comment]
> Version is already retrieved from Ledger, just need to show it on UI.

cool. will do.
