### ISSUE TITLE
Performance issues with the validator table

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2306]
**Describe the bug**

- the validator table requires an unreasonable number of requests (473)
- the validator table requires too much data (17.8mb) 
- the page loads slowly and the browser frequently struggles to render this part of the app (7.16s)

**To Reproduce**

- open the network tab
- visit the validator page
- witness the resource hog

**Expected behavior**

- i would expect this page to load quickly and effortlessly, that as much of the data as possible was cached correctly, and that we would only make the necessary requests

**Notes**
- it seems to me that reducing the number of requests, taking care of enriching the validator objects in the vuex module instead of in the TableValidator component would be good first steps to resolving this issue.
- `signing_info` is getting called ALOT
- it doesn't seem like cacheing is working very well

**Screenshots**

![Screen Shot 2019-03-16 at 4 50 51 PM](https://user-images.githubusercontent.com/6021933/54492617-90a0ca00-489e-11e9-856c-cd6fd1b9c943.png)

**Comment by fedekunze** [comment]
yeah we really need https://github.com/cosmos/voyager/issues/1381 too

**Comment by faboweb** [comment]
Check if this is still the case.

**Comment by jbibla** [comment]
yep. this has been dramatically improved.

400 requests (for the whole app on a hard reload - still very high)
2.8MB (still very high IMO)
9.0s (to completion)

- i suspect batching the API requests will help.
- we're calling `https://stargate.cosmos.network/staking/validators` 3 times
- we're calling `https://stargate.cosmos.network/validatorsets/latest` 2 times
- perhaps we can lazy load / lazy request the signing_info and keybase calls for only what is visible (+10 or something)
- should we bundle all the npm.js files?
- i think we're still requesting the validator avatars from keybase's s3 every reload

**Comment by jbibla** [comment]
this is being addressed by a number of ongoing changes.
