### ISSUE TITLE
Web Version of the Cosmos Wallet doesn't handle redelegation of redelegated tokens

### ISSUE THREAD

**Issue by mnugumanova** [luniehq/lunie#2325]
**Describe the bug**
There is a limitation in cosmos where tokens could be re-delegated only once. 
If a user decides to do a redelegation again, he or she needs to go through unbonding process

**To Reproduce**
1. Delegate 1 muon to Validator A
2. Redelegate 1 muon from validator A to validator B
3. Attempt to redelegate 1 muon from validator B to someone else

**Expected behavior**
There should be either a warning, prompting me to go through unbonding process and/or this should be reflected in a limit of tokens available to transfer

**Screenshots**
Unchecked runtime.lastError: The message port closed before a response was received.
index.js:3801 POST http://localhost:8080/txs 500 (Internal Server Error)
<img width="747" alt="Screen Shot 2019-03-20 at 10 10 23 PM" src="https://user-images.githubusercontent.com/8264666/54734494-15b90700-4b5d-11e9-8078-f5f727dba28c.png">

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser: Chrome
 - Version: 72

**Comment by faboweb** [comment]
Thank you for opening this issue. I like the suggestions. We probably should do both:
- showing a warning that there is an active redelegation
- showing a limited amount of tokens to redelegate

**Comment by jbibla** [comment]
if this is still an issue, let's fix it.
