### ISSUE TITLE
Add space between two addresses

### ISSUE THREAD

**Issue by mnugumanova** [luniehq/lunie#2326]
Transaction screen could benefit from proper formatting of the "From and To" addresses

Expected:
From jack to Staking Fund

Actual
From jacktoStaking Fund

<img width="660" alt="Screen Shot 2019-03-20 at 10 15 03 PM" src="https://user-images.githubusercontent.com/8264666/54734590-e1921600-4b5d-11e9-99ce-8f7ddf7db530.png">

**Comment by faboweb** [comment]
Thx! Will fix

**Comment by faboweb** [comment]
Fixed
