### ISSUE TITLE
submit proposal creates 2 proposals and overwrites proposal number 1

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2346]
**Describe the bug**

submit proposal creates 2 proposals and overwrites proposal 1

**To Reproduce**

Submit a proposal
Proposal gets created twice

if a new proposal is created, proposal 1 gets overwritten.

**Expected behavior**

only create 1 proposal, not overwrite

**Screenshots**

<img width="1411" alt="Screen Shot 2019-03-25 at 12 12 01 PM" src="https://user-images.githubusercontent.com/31522760/54915456-73e84000-4ef7-11e9-9f14-2131990576b6.png">

<img width="1411" alt="Screen Shot 2019-03-25 at 12 12 28 PM" src="https://user-images.githubusercontent.com/31522760/54915466-79458a80-4ef7-11e9-8b19-5538c53f1057.png">

**Additional context**

**Comment by fedekunze** [comment]
uhh apparently the response I get from `GET gov/proposals` doesn't contain proposal 1,  I'm pretty sure this is an optimistic update bug

**Comment by fedekunze** [comment]
either that or the limit query parameter from the sdk is failing

**Comment by jbibla** [comment]
@fedekunze still an issue?

**Comment by fedekunze** [comment]
Probably was bc of the pruning strategy on the local testnet. I don’t think it applies anymore
