### ISSUE TITLE
Collect coverage while running jest 

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2347]
**Is your feature request related to a problem? Please describe.**

Can't see code coverage while running unit tests with Jest

**Describe the solution you'd like**

Add configuration to print coverage on run

**Describe alternatives you've considered**

Add the following configurations to Jest 

- https://jestjs.io/docs/en/configuration.html#collectcoverage-boolean
- https://jestjs.io/docs/en/configuration.html#collectcoveragefrom-array

**Additional context**

**Comment by mnugumanova** [comment]
I would like to help with this issue. Let me know if that's ok

**Comment by fedekunze** [comment]
Thanks ! Feel free to open a PR

**Comment by jbibla** [comment]
@mnugumanova absolutely, please do!
