### ISSUE TITLE
Scrolling in Firefox on Mac on PageValidator is broken

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2353]
**Describe the bug**

Apparently the scrolling is broken there according to one user.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
confirmed

**Comment by jbibla** [comment]
note: re-write sidebar and header css to get scrolling _for free_
