### ISSUE TITLE
CirlceCI won't recognize failure while building Gaia

### ISSUE THREAD

**Issue by sabau** [luniehq/lunie#2364]
**Describe the bug**
Clearly is failing
```
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/download/v1.15.0/golangci-lint-1.15.0-checksums.txt
install: cannot change permissions of ‘/go/bin’: Operation not permitted
scripts/Makefile:51: recipe for target '/go/bin/golangci-lint' failed
make: *** [/go/bin/golangci-lint] Error 1
```
But the build is green, we are ignoring the exit code of that command.
https://circleci.com/gh/cosmos/lunie/24088?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Expected behavior**
The build job should fail

**Comment by sabau** [comment]
Seems to be related to an issue currently on the SDK https://allinbits.slack.com/archives/GBB5RM200/p1553527801025700

**Comment by sabau** [comment]
This needs some work on makefile side, @greg-szabo  I will try to apply your lesson :)

**Comment by faboweb** [comment]
@mircea-c pinging for pushing all the old versions to Docker hub

**Comment by mircea-c** [comment]
@faboweb I'm a bit out of the loop I think. Are you talking about old versions of the SDK docker image?

**Comment by faboweb** [comment]
@sabau can explain

**Comment by jbibla** [comment]
we don't build gaia anymore so i think this can be closed.
