### ISSUE TITLE
Emphasize delegation and rename "Network"

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2368]
**Is your feature request related to a problem? Please describe.**

I think Lunie should focus on and highlight delegation as its current primary feature and strongest use case, followed by governance. As well, the "Network" link should be renamed to "Explorer" because this is what people will expect and understand. 

**Describe the solution you'd like**

I'd like to propose the following change to the sidebar layout:
```
Staking
Governance
Explorer
--
Wallet
Transactions
```
Additionally, the app should default to `staking/my-delegations`, not the explorer (for _ALL_ users). This will encourage sign ups and provide the right emphasis on staking.

**Additional context**

Landing on any link that is not the first link is awkward.

**Comment by fedekunze** [comment]
++

**Comment by fedekunze** [comment]
> Landing on any link that is not the first link is awkward.

@jbibla Shouldn't it be then

```
Explorer
Staking
Governance
--
Wallet
Transactions
```

**Comment by jbibla** [comment]
yes i see what you're saying but i'm proposing that all users land on _My Delegations_ by default. of course this means most people will see the sign in card first. but we will improve this over time.
