### ISSUE TITLE
Validator list rendering is janky

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2371]
**Describe the bug**

When clicking on the validator tab the rendering is very slow.

**To Reproduce**

On mainnet:
Click on mydelegations
Click on validators

**Expected behavior**

Instant rendering

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
addressed by numerous changes
