### ISSUE TITLE
CSV export of wallet transactions

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie#2372]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have a CSV export function of the wallet transactions, that can be used for accounting purposes.

Ideally it should be user selectable which types transactions are included in the output (reward withdrawals, transfers, delegations).

**Comment by faboweb** [comment]
Nice idea

**Comment by fedekunze** [comment]
I also thought once something like this idea could be a "premium" feature of the wallet

**Comment by mdyring** [comment]
Premium as in paid-for?

**Comment by fedekunze** [comment]
Not necessarily (TBD), but we’re looking for revenue models other than the standards in the wallet industry (eg paying fees per tx)

**Comment by jbibla** [comment]
really cool feature idea. @mdyring thanks for sharing. we're playing with a few ideas internally - but have no plans to implement a premium or paid feature set at this time. 

if you're interested, maybe we can set up some time to hear your feedback and other feature ideas you may have.

**Comment by mdyring** [comment]
Please leave open, I think this is a useful feature.

**Comment by jbibla** [comment]
me too. we'll add it to our roadmap.

**Comment by faboweb** [comment]
still valid

**Comment by jbibla** [comment]
we can re-open in Q1
