### ISSUE TITLE
Disable withdrawal when user doesn't have any delegations 

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2378]
**Describe the bug**

Attempting to do a withdrawal without delegations renders the following error on the modal:

`Withdrawal failed: JSON Missing msgs.`

**To Reproduce**

1. Sign in with an account with no delegations
2. Click withdraw and try to submit the transaction

**Expected behavior**

Show a message that user needs to delegate to be able to withdraw.

**Comment by jbibla** [comment]
how can a user do a withdrawal of zero? doesn't that mean we're not validating the form?

**Comment by fedekunze** [comment]
there's no "form" we only display the total rewards as the message doesn't contain any amount field

**Comment by jbibla** [comment]
ah ok. so we should just show a message on the action modal when rewards = 0

**Comment by fedekunze** [comment]
When delegations.length = 0

**Comment by jbibla** [comment]
ohhhhhhh. yeah. but also when rewards = 0 i guess.

**Comment by fedekunze** [comment]
You get rewards on every block so I wouldn’t bother handling that case

**Comment by jbibla** [comment]
ah, i see what you're saying. i suppose we agree on what the outcome should be. i'll leave the implementation to you!
