### ISSUE TITLE
User Feedback from gautier

### ISSUE THREAD

**Issue by gamarin2** [luniehq/lunie#2411]
UI Version: v1.0.0-beta.35

Just some feedback after using testnet.lunie.io

**Top Bar**
- See entire address cosmos1s37e4mnsxgsmflgrkawvqjqfu33fmzw9pupsvz. You only see a cut version of it. I also think it should be bigger, this is important info. 
- Total Stake / Available Stake / Pending Rewards can take more space horizontally.

**Account Creation**
- Should ask people to retype their seed phrase when creating an account. 

**Send**
- Denom not clear when sending. You have denom above address above amount in the "Send" box. It's confusing not to see the denom next to the amount but two rows above.
- I think we should drop the cosmos icon and make it ATOM instead. It's confusing.
- Bug when trying to send entire balance. Lunie tells you tx succeeded when it actually does not. 
- On ledger confirmation denom is stake, should be ustake (my ledger tells me the fee amount is 1812 stake!)

**Governance**
- Should not be possible to vote without bonded stake. It is right now. 
- x/100%? Why not x%
- Lacks a visual bar to see the vote distribution.

**Comment by faboweb** [comment]
> Account Creation

Maybe we don't even show the seeds. These are burner accounts and shouldn't be used anywhere. The seeds shouldn't be restored anywhere.

> On ledger confirmation denom is stake, should be ustake (my ledger tells me the fee amount is 1812 stake!)

Big bug! Luckily only on the testnet. :D

> Should not be possible to vote without bonded stake. It is right now.

You can vote without bonded stake. Once you bond your voting power will change. But we should probably show a warning.

**Comment by jbibla** [comment]
thank you for the feedback @gamarin2 ! agree with many of your points!

---

> Maybe we don't even show the seeds. These are burner accounts and shouldn't be used anywhere. The seeds shouldn't be restored anywhere.

this is a good idea.

**Comment by jbibla** [comment]
i believe all of these points have been addressed. thanks @gamarin2!
