### ISSUE TITLE
Show proposal's proposer

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2420]
**Is your feature request related to a problem? Please describe.**

Currently the proposal page doesn't display the proposer address or moniker

**Describe the solution you'd like**

show address or moniker (if validator) of the proposer

**Describe alternatives you've considered**

use [`GET gov/proposals/{id}/proposer`](https://cosmos.network/rpc/#/ICS22/get_gov_proposals__proposalId__proposer) endpoint to get the proposer and display it on the proposal page

cc: @jbibla

**Comment by jbibla** [comment]
@thebkr7 let's make sure this is included

**Comment by faboweb** [comment]
still valid

**Comment by jbibla** [comment]
let's do it! 

@mariopino might be a nice one for you

**Comment by mariopino** [comment]
Actually implemented in feature/api-gateway branch.
