### ISSUE TITLE
Show IPFS proposals in Lunie

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2426]
**Is your feature request related to a problem? Please describe.**

Users upload proposals mostly to IPFS. It would be nice to show the content directly in Lunie. Maybe let users even upload to IPFS via Lunie.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
this is still relevant. 

probably blocked by this: #2907
