### ISSUE TITLE
Optimistic updates should include fees

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2428]
**Is your feature request related to a problem? Please describe.**

Currently the optimistic updates don't include fees. This causes the balance to update twice.

**Describe the solution you'd like**

The calculated fees should be also added to the optimistic updates. Even if the fees differ in the end, this might not even be visible by the user when the difference is small.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
is this still the case? 

this feels more like a bug than a ux-improvement?
