### ISSUE TITLE
Sending on testnet broken

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2435]
**Describe the bug**

When I try to send coins on the testnet I am stuck on the fees step.
Also the total doesn't show my coins.

![image](https://user-images.githubusercontent.com/5869273/55669986-91fe5a80-587e-11e9-99a7-667be6bd957f.png)

(apparently the denoms are bad)

**To Reproduce**

Send 1 stake on the testnet to any address.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

@fedekunze

**Comment by fedekunze** [comment]
Would it be easier to change the testnet tokens to uatoms ?

**Comment by jbibla** [comment]
@fedekunze what is the difference between gas and fees (estimated)?

**Comment by faboweb** [comment]
> Would it be easier to change the testnet tokens to uatoms ?

That would mean redploying the testnet

**Comment by fedekunze** [comment]
> what is the difference between gas and fees (estimated)?

you mean `gas` or `gas_prices` ?

> That would mean redeploying the testnet

yeah... but I guess it's the easy solution to avoid this. Ethereum's testnets also have ether as their token
