### ISSUE TITLE
Display rewards in Atoms

### ISSUE THREAD

**Issue by mnugumanova** [luniehq/lunie#2445]
It is odd to see delegations in Atoms and reward in uatoms.
Consider displaying reward and delegations in the same metrics.

<img width="925" alt="Screen Shot 2019-04-08 at 3 16 44 PM" src="https://user-images.githubusercontent.com/8264666/55760765-e980ff80-5a11-11e9-943a-117b18a4d136.png">

**Comment by jbibla** [comment]
ah! thank you!

the rewards are actually being displayed as ATOMs, this is just an incorrect label. 

i will fix this today.
