### ISSUE TITLE
Don't let user sign tx if not enough funds

### ISSUE THREAD

**Issue by mnugumanova** [luniehq/lunie#2446]
1. User Account has 0.02 atoms
2. user tries to delegate 0.01 atom. Network fee is 0.02. Total amount in tx 0.03
3. Click "Next"

There could be an easy client-side check that I don't have enough funds.
Instead, the user is asked for a password and the app shows "Incorrect password error" after submit.
Very misleading.
![2019-04-08 15 36 48](https://user-images.githubusercontent.com/8264666/55761600-b855fe80-5a14-11e9-9426-474f497a4ae6.gif)

**Comment by jbibla** [comment]
thanks for reporting this.

did you "sign in with address" or "sign in with ledger"?

**Comment by mnugumanova** [comment]
sign in with address

**Comment by jbibla** [comment]
thanks. we pushed a fix yesterday so you shouldn't see "password" anymore. you can only sign txs with your ledger.

but we will add some validation to the form. thank you!
