### ISSUE TITLE
adding fees in txs with ledger causes "insufficient funds" error message

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2454]
**Describe the bug**

normal delegation flow, with fees included causes insufficient funds error to be displayed even when user does not have insufficient funds.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

_Thanks @keppel_

**Comment by fedekunze** [comment]
This is because the max amount allowed to enter on the form input is calculated without the fees. 

Idk how would it be posible to fix this without changing the UX on transactions

**Comment by faboweb** [comment]
Is this still an issue?
