### ISSUE TITLE
custom network fee input (experimental) is in uatoms, should be in ATOMs

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2455]
**Describe the bug**

It appears that fees are displayed in uatoms.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
It’s only the tag I think

**Comment by jbibla** [comment]
what do you mean?

**Comment by faboweb** [comment]
Fixed
