### ISSUE TITLE
validator not showing up on validator list (01node)

### ISSUE THREAD

**Issue by clawmvp** [luniehq/lunie#2461]
it seems that my validator (01node) is not showing up on validators list, also not showing on lcd  staking/validators
ex: http://185.36.252.148:1317/staking/validators

my validator: https://stargazer.certus.one/validators/B4E1085F1C9EBB0EA994452CB1B8124BA89BED1A

however if i query: gaiacli query tendermint-validator-set --chain-id=cosmoshub-1 | grep cosmosvalconspub1zcjduepqlzmd0spn9m0m3eq9zp93d4w6e5tugamv44yqjzyacelnvra634fqnfec0r
  Pubkey:           cosmosvalconspub1zcjduepqlzmd0spn9m0m3eq9zp93d4w6e5tugamv44yqjzyacelnvra634fqnfec0r

it does show up, also it does show up on all explorers..any hints?

**Comment by jbibla** [comment]
hmmm. not sure about this. 

@fedekunze any ideas?

**Comment by faboweb** [comment]
`/staking/validators` may only deliver all validating validators (currently 100).

**Comment by clawmvp** [comment]
what do u mean? i am active.
https://stargazer.certus.one/validators/B4E1085F1C9EBB0EA994452CB1B8124BA89BED1A

**Comment by fedekunze** [comment]
yeah, sadly it returns the top 100 validators. The fix will be included on `0.35`. Ref  https://github.com/cosmos/cosmos-sdk/issues/4099

**Comment by faboweb** [comment]
When will `0.35` come? And if this is not for a couple of days, can this be hotfixed instead?

**Comment by fedekunze** [comment]
The next upcoming release is 0.34. Although 0.35 is way underway already. How about if we move this discussion to the SDK ?

**Comment by jbibla** [comment]
for the record: the umbrella team is reporting the same issue.

you guys both appear on https://hubble.figment.network/chains/cosmoshub-1

![Screen Shot 2019-04-18 at 6 03 42 PM](https://user-images.githubusercontent.com/6021933/56394353-11881400-6205-11e9-8441-305f52797af8.png)

**Comment by jinghiskwon** [comment]
It's so weird that our names are addresses on Hubble lol.

**Comment by clawmvp** [comment]
Have u guys updated lunie? My validator still not listed.

**Comment by jbibla** [comment]
this appears to be effecting account balances as well. should we use a separate endpoint for balance calculations??

@faboweb

**Comment by jbibla** [comment]
@clawmvp we haven't resolved this issue yet but we are actively working on it.

**Comment by jinghiskwon** [comment]
Did you guys update to latest point release for your infrastructure? I think Umbrella shows up in all the other explorers correctly now that people have updated their full mode.
