### ISSUE TITLE
Reduce amount of subscriptions

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2472]
We have about 8 subscriptions to tendermint events but Tendermint is limiting now to 5.

Either:
- Increase subscription limit
- Only listen to new block event and parse txs in response

**Comment by faboweb** [comment]
In SDK 0.36 there will be one tag for the `sender` so we can reduce all our listeners to one.

**Comment by jbibla** [comment]
cool! didn't we also increase the number of subscriptions permitted on our node?

**Comment by faboweb** [comment]
We did so this is not an issue anymore.

**Comment by jbibla** [comment]
> In SDK 0.36 there will be one tag for the sender so we can reduce all our listeners to one.

but we should still do this?

**Comment by faboweb** [comment]
yeah, it reduced the amount of open connections to the server and should be cleaner + more future proof.
