### ISSUE TITLE
Total ATOM balance wrong

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2473]
A user reported that the total atom balance (especially bonded atoms) on Lunie and Hubble are different.

**Comment by colw** [comment]
Can this be closed now?

**Comment by jbibla** [comment]
yeah i think this was resolved with the _only getting 100 validator_ bug.

**Comment by faboweb** [comment]
Figment shows different a different total if you sum up the values:
Address: cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv
https://hubble.figment.network/cosmos/chains/cosmoshub-2/accounts/cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv

**Comment by jbibla** [comment]
yikes. yeah, rewards and balance seem to be matching. let's find out who's total is correct!

**Comment by faboweb** [comment]
ok after the server fix this looks good now
