### ISSUE TITLE
Idea to improve receiving address UX

### ISSUE THREAD

**Issue by thiloo** [luniehq/lunie#2474]
I tried to send a friend some atom, the person is a very average crypto user, with ledger and a few different coins. It took him literally an hour to find his cosmos address on lumie, the user experience is pretty poor for somebody not exposed to wallets regularly. 

Would be neat if the address could be displayed in full with an explanation next to it, to make it more user friendly. Instead of hiding it below the total atoms owned. 

![image](https://user-images.githubusercontent.com/21267961/56559871-72cd3000-65d5-11e9-9b51-dec047582c2c.png)

**Comment by zamson** [comment]
I just sent a feedback ticket about this. I totally agree.

**Comment by jbibla** [comment]
thank you @thiloo and @zamson! 

this is very valuable feedback for us. thank you! i will work to address this.

**Comment by jbibla** [comment]
i believe this has been resolved in the newest version of lunie.
