### ISSUE TITLE
Cannot stake ATOMS

### ISSUE THREAD

**Issue by pimato** [luniehq/lunie#2475]
**Describe the bug**
I am getting an error `Delegating failed: Request failed with status code 500.` as soon as I am trying to delegate some ATOMs to a validator with my Ledger Nano S.

**To Reproduce**
1. go to https://lunie.io
2. click on Sign in
3. click on `Sign with Ledger Nano S`
4. Click on `Sign in`
5. Click on the Staking button on the left navigation bar
6. Pick a validator you want to delegate with
7. Click on the delegate button
8. Set the Amount you want to delegate
9. See error

**Expected behavior**
a signing process with the goal that I send out my delegation transaction.

**Screenshots**
<img width="626" alt="Screenshot 2019-04-23 at 16 07 54" src="https://user-images.githubusercontent.com/5337809/56587516-f9880a00-65e1-11e9-95f8-a91dfd8f5e4b.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Browser: Brave 
 - Version: Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

**Comment by jbibla** [comment]
Thank you @pimato. We are looking into this now.

**Comment by faboweb** [comment]
This seems to be an SDK bug: https://github.com/cosmos/cosmos-sdk/issues/4172
We are investigating

**Comment by faboweb** [comment]
This will be fixed in the SDK release 0.34.2. It will be released this week. I am pushing for earlier. :)
