### ISSUE TITLE
Cannot undelegate full amount

### ISSUE THREAD

**Issue by pimato** [luniehq/lunie#2486]
**Describe the bug**
The undelegate window is showing me a delegation balance of "119.70000000002645". If I want to undelegate the exact amount I am getting an "Undelegating failed: Request failed with status code 400.".

**To Reproduce**
1. Go to lunie.io
2. Click on Sign in 
3. Pick Ledger Sign in
4. Navigate to Staking in the left Navigationbar
5. Pick a validator you are already delegating
6. Click on undelegate
7. Copy the full amount of the displayed "delegated amount" into the inputfield
8. See Error "Undelegating failed: Request failed with status code 400"

**Expected behavior**
The interface should let me undelegate the full amount which is displayed to me.

**Screenshots**
<img width="627" alt="Screenshot 2019-04-25 at 10 11 43" src="https://user-images.githubusercontent.com/5337809/56720414-1556f180-6743-11e9-90e2-c20d07db860c.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Browser: Brave 
 - Version: Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

**Comment by jbibla** [comment]
@pimato i believe this issue has been resolved. can you confirm if this is still an issue for you?
