### ISSUE TITLE
Show delegation, undelegation, and redelegation warning messages

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2504]
**Is your feature request related to a problem? Please describe.**

As a user it would be good to understand, that I can't use the undelegating tokens for 21 days. The user could loose revenue by that action.
If the user wants to redelegate instead, he needs to do another action that is not clear (set different delegation source). This needs a better UX.

**Describe the solution you'd like**

Add an undelegation warning
Improve redelegation UX (maybe move into own button)

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
so, after a long discussion with the cosmos hub team - here is my understanding about redelegation:

- you can redelegate up to 7 times with the same parties (your address, source validator, destination validator)
- voting power and rewards / distribution change instantly upon redelegation — but the original delegations are subject to the unbonding period. if the original validator is slashed, your redelegations will also be slashed (unless after the 21 day period)
- you cannot redelegate redelegations until after the unbonding period is over. (A -> B is permitted, B -> C is not (until after unbonding period)

@cwgoes @alexanderbez does that check out? missing anything critical?

---

we are going to add some information about this to lunie soon.

_Originally posted by @jbibla in https://github.com/luniehq/lunie/issues/2557#issuecomment-491278603_

**Comment by jbibla** [comment]
we still need to add a message for delegation and redelegation IMO

**Comment by jbibla** [comment]
new learning: rewards are instantly auto-withdrawn for redelegations and undelegations.

**Comment by cwgoes** [comment]
> new learning: rewards are instantly auto-withdrawn for redelegations and undelegations.

Isn't it magical? /sarcasm

I expect that's confusing - unfortunately, it's necessitated by the "F1" lazy fee calculation logic.

**Comment by jbibla** [comment]
@cwgoes even though they are instantly withdrawn, are delegators still subject to penalties for 21 days if the original validator is penalized for some reason?

**Comment by cwgoes** [comment]
> @cwgoes even though they are instantly withdrawn, are delegators still subject to penalties for 21 days if the original validator is penalized for some reason?

Yes, though the rewards are not bonded so not subject to any penalties (but the delegation amount is).

**Comment by jbibla** [comment]
@colw let's make sure these messages are in place for all staking transactions in the action modal.

**Comment by jbibla** [comment]
can someone confirm that these messages are in place for all staking transactions in the action modal?

@colw @mariopino
