### ISSUE TITLE
Optimistic undelegation update is wrong

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2505]
**Describe the bug**

The update adds to the total amount instead of staying the same (as the total doesn't change).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
is it wrong or is it just including rewards? :trollface:
