### ISSUE TITLE
Can't open links on validator pages

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2506]
**Describe the bug**

"Under validators website url does not link externally or with target _blank" (from Appzi)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
why’d you close this? many of the websites are not formatted correctly and we should do our best to make them clickable i think.

**Comment by faboweb** [comment]
Oh ok. I tried several and all worked.

**Comment by jbibla** [comment]
sometimes they don't include `http://`

https://lunie.io/#/staking/validators/cosmosvaloper1ey69r37gfxvxg62sh4r0ktpuc46pzjrm873ae8
