### ISSUE TITLE
show "waiting for Tx to be included in block" as step in action modal transaction flow

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2512]
**Is your feature request related to a problem? Please describe.**

Currently when you send a tx, on the signing step it will wait and show "Waiting for Ledger" until the tx is included. We should show another step "Waiting for Tx to be included". Where we show a message "Your transaction has been send.  Waiting for the transaction to be included in a block.".
If the transaction times out, add a description: "Your transaction wasn't included in a block until now. It still could be included later."
Bonus: Show the amounts of blocks the user has already waited.
Maybe increase the waiting time for txs as well. It already timed out for me (for 0 fees)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
perhaps we can include this as part of "improving ledger steps ux/ui" more generally
<img width="549" alt="Screen Shot 2019-05-06 at 11 23 12 AM" src="https://user-images.githubusercontent.com/6021933/57235664-64c5d900-6ff1-11e9-97cc-f750c9cefa92.png">

**Comment by faboweb** [comment]
This is independent from Ledger and will also be the case for other signing methods.

**Comment by jbibla** [comment]
good point. would be nice to have a UI component like i shared above for the different kinds of signing options.

**Comment by faboweb** [comment]
> good point. would be nice to have a UI component like i shared above for the different kinds of signing options.

still out of scope for this issue :D
