### ISSUE TITLE
Logo path, project name, typo needs updating

### ISSUE THREAD

**Issue by gin** [luniehq/lunie#2515]
**Describe the bug**
1. Logo path in README.md
2. Project name in CONTRIBUTE.md
3. Typo in TmWelcomeSession (text "loose" should be "lose", and is only visible on testnet.lunie.io)

**To Reproduce**
(For 3.)
1. Go to testnet.lunie.io
2. Click on "Sign In" button

**Expected behavior**

Expect "You could loose all your money." to be "You could lose all your money."

**Comment by gin** [comment]
TBA:
Pull Request

**Comment by jbibla** [comment]
thank you so much @gin
