### ISSUE TITLE
My Delegation page shows wrong status

### ISSUE THREAD

**Issue by dlguddus** [luniehq/lunie#2529]
**Describe the bug**
B-Harvest delegated 100 Atom to ATOMI validator but does not show any delegation amount on "my delegation" page.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38277329/57119991-2d64eb80-6da9-11e9-9852-e0d78dff4f08.png)
![image](https://user-images.githubusercontent.com/38277329/57120000-39e94400-6da9-11e9-9ec7-0f59cdc5bd61.png)

**Comment by faboweb** [comment]
Hi! Is this still an issue?
