### ISSUE TITLE
Warn user if wallet will be have low balance before submitting tx

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie#2530]
It would probably be useful (in all wallets, not just Lunie) to warn people if they would have less than X Atoms left following a tx (delegating or transferring). They should obviously be warned before signing :-)

A reoccurring theme seems to be that people send or delegate all their atoms, and are then "stuck" without anything to pay for gas.

**Comment by faboweb** [comment]
This is a fantastic idea!

**Comment by mdyring** [comment]
Adding some activity to prevent the issuing from getting closed. ;-)

**Comment by jbibla** [comment]
thanks @mdyring. i agree. this is useful ticket. we will add this notification to Lunie for folks!

**Comment by jbibla** [comment]
@colw it would be sufficient to include a simple message / notification in the action modal that recommends that users keep 0.25 atoms in their wallet to pay for future fees.

**Comment by jbibla** [comment]
@mariopino let's make sure if a user tries to input max-amount that we show the message (even if they don't use the max button)

**Comment by mariopino** [comment]
> @mariopino let's make sure if a user tries to input max-amount that we show the message (even if they don't use the max button)

@jbibla It's fixed in PR https://github.com/luniehq/lunie/pull/2974

What would be the threshold to display the warning to the user?

**Comment by jbibla** [comment]
good question. i think just the max. what do you think?

**Comment by mariopino** [comment]
That threshold may be the minimum fee that is acceptable to the current network so if user try to make a transfer with an amount > (free balance - min_fee) we can warn it.

In the warning message we can include a link to "Left a minimum amount for fees" action that subtract that fee to the max.

**Comment by jbibla** [comment]
i think that's a good solution. but i fear we are overcomplicating things. my preference would be to just let the user remove some from the max for fees.

@faboweb what do you feel?

**Comment by faboweb** [comment]
Sounds good to me. I would just use a constant for minimum fees for now (how about 0.05tokens?).

> In the warning message we can include a link to "Left a minimum amount for fees" action that subtract that fee to the max.

Sounds interesting. This way we not only warn the user but also help him act on the warning. Would this clutter the UI though?

**Comment by mariopino** [comment]
In the future we would probably need a different value for each network. I.e: In Polkadot an account with less that 100 milliDOTs (= 0.1 DOT) can be considered as inactive. It's called the existential deposit and is the minimum required balance for an account to be kept in the state,  although it may end up being 0.01 DOT instead of 0.1 DOT.

**Comment by faboweb** [comment]
Good insight! Maybe we can add these values to the backend?

**Comment by jbibla** [comment]
> Like your idea of have a minimun_fee field in network table in the backend to be able to define it per network.

yeah, this would be nice.

---

if a user presses a "max" button the button should behave as expected (by using the max).

**Comment by mariopino** [comment]
Actually done in latest develop, so I think we can close this.

![image](https://user-images.githubusercontent.com/9256178/67415230-ea9c0780-f5c4-11e9-840c-9bc92812137e.png)

In the future, with the new backend ready, we can develop a more complex warning which takes into account the minimum network fee.

**Comment by jbibla** [comment]
right! no worries - this is great.
