### ISSUE TITLE
Show warning if stargate is not connected

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2533]
**Is your feature request related to a problem? Please describe.**

We should show a warning if the user can't query data via the stargate. Like when we update the stargate.

**Describe the solution you'd like**

We base connection state only on tendermint. We should also base the connection state on the stargate. If the stargate is not available, we should also not do any requests.

**Describe alternatives you've considered**

Show a full page warning to prevent the user from using the UI while the stargate is offline.

**Additional context**

**Comment by jbibla** [comment]
don't we do this already @faboweb ?

**Comment by jbibla** [comment]
i believe this is done!
