### ISSUE TITLE
Can't sign out on mobile

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2538]
**Describe the bug**

On mobile the sign out button is not accessable.

**To Reproduce**

Log in to Lunie on your phone. Try to switch accounts.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
let's add the sign out link to the app menu on mobile

**Comment by colw** [comment]
Would you prefer to place the same icon or add another menu item?

**Comment by jbibla** [comment]
same icon with the word "sign out" before it could be nice.
