### ISSUE TITLE
Sentry sourcemaps not available

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2541]
**Describe the bug**

On Sentry the sourcemaps are not resolved.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
we removed sentry
