### ISSUE TITLE
Footer not present on about etc. pages

### ISSUE THREAD

**Issue by colw** [luniehq/lunie#2544]
**Describe the bug**

The footer bar is not visible when viewing the About, Terms of Service, Privacy, or Security pages.

**To Reproduce**
1. Open https://lunie.io
2. Scroll to bottom and see footer bar with above mentioned links.
3. Open https://lunie.io/#/about
3. See there is no footer bar visible

**Expected behavior**
Footer bar should be visible on all pages.

**Screenshots**
Current about page:
![lunie io_](https://user-images.githubusercontent.com/360865/57238084-e2590b80-7028-11e9-9bbc-f3da07d58680.png)

Desired footer:
![lunie io_ (2)](https://user-images.githubusercontent.com/360865/57238070-da00d080-7028-11e9-859d-cc2e3e9f24e1.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser:All
 - Version:All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser:All
 - Version:All

**Comment by jbibla** [comment]
good catch!
