### ISSUE TITLE
Refactor Session.js so that it has less than 250 lines to satisfy CodeClimate

### ISSUE THREAD

**Issue by migueog** [luniehq/lunie#2553]
**Describe the bug**

After adding some code to Session.js and pushing a commit to an open PR, Code climate throws an error that says 

`File session.js has 255 lines of code (exceeds 250 allowed). Consider refactoring`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

https://codeclimate.com/github/luniehq/lunie/pull/2537

**Comment by faboweb** [comment]
Hahahahh it's not a bug it'S a feature. That means we need to refactor that file.

**Comment by migueog** [comment]
@faboweb Ooo good to know! Why does this happen in the first place? Just to prevent files from getting too large?

**Comment by jbibla** [comment]
yep!

**Comment by migueog** [comment]
![Alt Text](https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif)

Thanks guys! I'll rename this issue to refactor session.js to prevent this error from occurring in the future.
