### ISSUE TITLE
network pages displays NaN for tx count while loading

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2556]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Should be done together with #2510
