### ISSUE TITLE
Can't undelegate more than available balance field

### ISSUE THREAD

**Issue by the-artilleryman** [luniehq/lunie#2557]
**Issue**

When attempting to undelegate, the undelegate box states:

**"Total must be between 0 and _N_"**, where _N_ is the 'Available Atom', and not the total delegated to the validator.

**Reproduce**

1. Navigate to your chosen validator, with whom you have a delegated balance.
2. Select 'Undelegate'
3. Box will state how much is delegated - e.g. "Currently Delegated: 100 Atoms"
4. Type e.g. '50' and click Next.
5. Box will return:

**Subtotal** 50.000000 ATOM
**Network Fee** 0.002742 ATOM
**Total** 50.002742 ATOM
Total must be between 0 and 5 (or whatever your available balance is)

... You can't progress beyond this point as the 'Next' button is faded out.

**System**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.131

**Reported on reddit by user hotc0**
https://www.reddit.com/r/cosmosnetwork/comments/bm6mlm/lunie_wallet_undelegate_total_must_be_between_0/

**Comment by faboweb** [comment]
Thank you for reporting this. We will fix this asap.

**Comment by Devnant** [comment]
I also can't redelegate (delegate from another validator) allocating more than my available balance. Is it true we have to wait for 21 days to redelegate after doing it once?

**Comment by faboweb** [comment]
> I also can't redelegate (delegate from another validator) allocating more than my available balance. Is it true we have to wait for 21 days to redelegate after doing it once?

Yes sadly that's the case. This might change in the future.

**Comment by the-artilleryman** [comment]
> Yes sadly that's the case. This might change in the future.

Off topic, but could you clarify please:

At the **protocol level**, we can only re-delegate freely one time?

Example: I delegate available funds to Validator A, then re-delegate those funds 3 days later to Validator B.
After that, those funds can't be re-delegated _again_ until 21 days have passed.

Is this correct? And this is protocol level, and not a Lunie limitation?

If so, then there are a lot of guides that are missing this information, and giving the impression that re-delegation is optional at any time.

**Comment by jbibla** [comment]
@the-artilleryman i am seeking clarification on the rules around redelegation and will share here when I  have clear answers to your questions. we will also include messaging about this in lunie soon so the rules are easy to understand.

but generally, lunie is not restricting any kind of behaviour - any restrictions that do exist are in the protocol.

**Comment by the-artilleryman** [comment]
@jbibla I found it documented at https://cosmos.network/docs/cosmos-hub/delegator-guide-cli.html

> After a redelegation, no other redelegation can be made from the account for the next 3 weeks

That may be useful.

Please note that this issue #2557 is also present when attempting to **redelegate** with Lunie. Selecting '**Delegate**' on a new validator, then choosing '**From: [current validator]**' > enter amount > '**Next**' will result in the same issue described above. I assume the fix will be similar.

Cheers.

**Comment by jbibla** [comment]
so, after a long discussion with the cosmos hub team - here is my understanding:

- you can redelegate up to 7 times with the same parties (your address, source validator, destination validator)
- voting power and rewards / distribution happen instantly but the original delegations are subject to the unbonding period. so if the original validator is slashed, your redelegations will also be slashed (unless after the 21 day period)
- you cannot redelegate redelegations until after the unbonding period is over. (A -> B is permitted, B -> C is not (until after unbonding period)

@cwgoes @alexanderbez does that check out?
---

we are going to add some information about this to lunie soon.

**Comment by alexanderbez** [comment]
Look's correct to me. Here is the original issue on transitive redelegations: https://github.com/cosmos/cosmos-sdk/issues/3288.

**Comment by the-artilleryman** [comment]
@jbibla That's great, thank you!

Explaining within Lunie will definitely help to disseminate that information.
