### ISSUE TITLE
Lunie crashes if google analytics can't be loaded

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2558]
**Describe the bug**

If windows.ga doesn't exist Lunie crashes. We need to wrap the calls in `scripts/google-analytics.js` with try catch.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment]
#2545

**Comment by jbibla** [comment]
let's close it then!
