### ISSUE TITLE
Footer moves with scroll

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2572]
**Describe the bug**

The footer hides at the bottom of the scrollable context.

**To Reproduce**

**Expected behavior**

It is clear that there is a footer. It should probably be at the fixed bottom?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
this is intended and is fine by me.
