### ISSUE TITLE
turn on strict mode

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2583]
https://vuex.vuejs.org/guide/strict.html

**Comment by jbibla** [comment]
worth doing? @colw @faboweb ?

**Comment by jbibla** [comment]
worth doing? @colw @faboweb ?

**Comment by colw** [comment]
Tried this. before. Once we remove the websocket it will be easier. Keep open

**Comment by jbibla** [comment]
is this doable now that we don't use the RPC directly?

**Comment by colw** [comment]
We still use the RPC for transactions, but it might be much easier to look at now. Keep open.

**Comment by faboweb** [comment]
My opinion: This is a "good programming style" safety feature we so far never needed. I wouldn't spend time on it. If we have a problem with this once, we can implement it. I vote to close.
