### ISSUE TITLE
Do Lunie has support MultiSig?

### ISSUE THREAD

**Issue by SorawitSiri** [luniehq/lunie#2600]
The Cosmos SDK has support MultiSig via gaiacli.
But, I'm not sure which Lunie support feature of MultiSig.
```
gaiacli tx sign \
  unsignedTx.json \
  --multisig=<multisig_address> \
  --from=p1 \
  --output-document=p1signature.json 
```

**Comment by jbibla** [comment]
Currently, we don't support multisig. Is this something you'd be interested in? For personal or business use?

**Comment by SorawitSiri** [comment]
I will use in business with my project.

**Comment by jbibla** [comment]
good to know! we will consider adding this to our roadmap!
