### ISSUE TITLE
Transaction list items overflow on mobile

### ISSUE THREAD

**Issue by migueog** [luniehq/lunie#2602]
**Describe the bug**

On mobile views, the transaction list items overflow off the screen. See gif for visual explanation

![Mobile view Delegations](https://user-images.githubusercontent.com/2801551/57884155-06210c00-77f6-11e9-9627-f64b53e26086.gif)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
resolved on #2850
