### ISSUE TITLE
add ledger referral link

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2616]
- on about page
- on session screen - "Don't have a ledger yet? Buy one here."

https://shop.ledger.com/?r=3dd204ef7508

<img width="610" alt="Screen Shot 2019-05-17 at 2 11 53 PM" src="https://user-images.githubusercontent.com/6021933/57947756-c289d900-78ad-11e9-99b8-9544865e731b.png">
<img width="767" alt="Screen Shot 2019-05-17 at 2 11 44 PM" src="https://user-images.githubusercontent.com/6021933/57947761-c4ec3300-78ad-11e9-8227-aec81d00dc83.png">

**Comment by faboweb** [comment]
#ledger
