### ISSUE TITLE
Cannot use Lunie to execute transactions with ledger

### ISSUE THREAD

**Issue by js-fb** [luniehq/lunie#2632]
**Describe the bug**
Basically Lunie.io is totally broken for ledger. Cannot execute transactions whatsoever using Ledger. If you try to execute a transaction, fails with CORS header violation:
```
Access to fetch at 'https://stargate.lunie.io/txs' from origin 'https://lunie.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
If you install Chrome extension to allow CORS bypass (https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=en) it then fails with 400 to stargate.lunie.io.

**To Reproduce**
Login with ledger at lunie.io and try to execute a transaction. I was doing delegation.

**Expected behavior**
Able to execute a transaction. Lunie useless with this bug.

**Comment by faboweb** [comment]
Fixed via #2633. Let me know if the issue persists.
