### ISSUE TITLE
Ledger Nano S is not able to process big transactions (i.e. many withdrawels)

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2637]
**Describe the bug**

Ledger Nano S is not able to process big transactions. When I delegate to a bunch of validators and try to withdraw from all of them at once (default) the Ledger reports an error, that it received too many "tokens" which stands for too big of a transaction to fit into the memory of the Ledger.

**To Reproduce**

Delegate to many validators.
Withdraw

**Expected behavior**

I am able to withdraw rewards. An easy fix is to add a withdraw button to each validators page. We probably need to come up with a better solution later.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
i think the withdrawal modal should use the dropdown component we use on the delegation modal to force users to select which validator they'd like to withdraw from - as opposed to defaulting to all of them.

**Comment by faboweb** [comment]
Hmmm, that would be very inconvenient for users with many delegations

**Comment by jbibla** [comment]
ok nice idea.

**Comment by colw** [comment]
@faboweb Yes, I believe this would solve the problem. We just make sure the message to the user is correct, and I don't believe they would be confused. We can provide more detail in an appropriate place, if it doesn't all fit in the initial message.
