### ISSUE TITLE
Unable to withdraw rewards/redelegate 

### ISSUE THREAD

**Issue by cjete001** [luniehq/lunie#2640]
**Describe the bug**
Went through the entire process to withdraw rewards including signing with ledger and nothing happened. Got the success message at the top of the page.

**To Reproduce**
1. Click to withdraw rewards 
2. Click next to view feed
3. Click next to sign with ledger
4. Sign with ledger 

**Expected behavior**
Withdraw rewards and increase available atom

**screnshot**
N/A

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Additional context**
Additionally tried to redelegate from one validator to another and went through the entire process including signing with ledger. Got the success message at the top of the page. And nada. Nothing shows in transactions tab as well.

**Comment by mikedeshazer** [comment]
Same issue.

**Comment by cjete001** [comment]
This item is closed, but it is still an issue for me.

**Comment by faboweb** [comment]
Do you still get success messages?

**Comment by cjete001** [comment]
Yes

**Comment by faboweb** [comment]
Can you send me your address to `fabian@lunie.io` so I can check what's going on?

**Comment by cjete001** [comment]
Everything is working correctly now, thank you for your assistance.
