### ISSUE TITLE
Withdraw tx can't go through as out of gas

### ISSUE THREAD

**Issue by kwunyeung** [luniehq/lunie#2641]
**Describe the bug**

I was trying to withdraw rewards with Ledger. The tx was signed and broadcasted but eventually it wasn't processed successfully as out of gas.

**To Reproduce**

Withdraw with Ledger and see if the tx is success or failed.

**Expected behavior**

Required gas should be enough for the withdraw tx

**Desktop (please complete the following information):**
 - OS:  macOS Mojave
 - Browser:  Brave
 - Version:  0.64.76

**Additional context**

The failed tx is
https://cosmos.bigdipper.live/transactions/4525AF9EB64BBE656F40E2F11EE3C361FC1662A9090664A44BEDC358784713E9

**Comment by faboweb** [comment]
Thank you for writing us about this issue. This is fixed in #2642 and will be shipped today.

**Comment by pimato** [comment]
@faboweb worked like a charm, thanks for the quick fixes! Great work!
