### ISSUE TITLE
Out of gas error when delegating

### ISSUE THREAD

**Issue by BassBauman** [luniehq/lunie#2648]
**Describe the bug**

When delegating using Lunie, UI says transactions are successful when they are actually failing due to insufficient gas. 

**To Reproduce**

Go to Lunie.io
Click to delegate
Complete delegation

**Expected behavior**

Successful delegation

**Desktop (please complete the following information):**
 - OS:  Chrome OS
 - Browser:  Chrome
 - Version:  74

**Additional context**

Block explorer says: "Warning! out of gas in location: ReadPerByte; gasWanted: X, gasUsed: >X"

**Comment by jbibla** [comment]
thanks for reporting! 

we pushed some fixes for this error last week - @BassBauman are you still experiencing this?

**Comment by BassBauman** [comment]
No longer experiencing any problems here. Thank you @jbibla!
