### ISSUE TITLE
add "max" button to amount fields

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2670]
**Is your feature request related to a problem? Please describe.**

Often, users want to do make a tx with all the atoms. since there are 6 decimal places, this can be tedious to type out.

**Describe the solution you'd like**

It is common in these situations to include a `max` button, which will automagically add the total amount left to the amount field for the user.

**Additional context**

Something to consider is the relationship with #2674.

**Comment by jbibla** [comment]
simple UI feature. would be nice to have!

**Comment by mariopino** [comment]
Set Max button is working on branch mario/2670-add-max-amount.

Currently set the entire available balance, so want to discuss about best way to subtract the fee from the available balance. If we click on the button, in the step 2 the fee is 0.000000 ATOM, is this a validation error?

It would be cool to include a fee slider to let user set the fee they want. We can include it in step 1 to let us calculate max = (available balance - fee).

**Comment by jbibla** [comment]
> Set Max button is working on branch mario/2670-add-max-amount.

awesome! if you make a draft PR we can see the link to the build and test out the feature 😉  


> If we click on the button, in the step 2 the fee is 0.000000 ATOM, is this a validation error?

no this is actually correct. if the user has no ATOMs left to pay fees we let them submit a tx without fees. 

can you add a warning to this section that explains this? i will help with the language.

> discuss about best way to subtract the fee from the available balance.

good thought here. a fee slider could work. i don't know what the best approach is. 

we could...
1. allow the user to set the true max with the max button on step 1
2. have a fee selector on step 1 (either a slider or three button/options)

alternatively...

1. allow the user to set the true max with the max button on step 1
2. show a warning that they are not leaving any for fees which may be required
3. turn the button into a "subtract fees" button

@faboweb what do you think?

---

this is related to https://github.com/luniehq/lunie/issues/2530

**Comment by faboweb** [comment]
We decided against a fee selector in favor of less mental overhead for the user.
We could run the simulation already on step 1 to know the fees there to calculate the max. Never the less we need to show a warning that the max already has subtracted fees.
But I vote for `show a warning that they are not leaving any for fees which may be required`. It is the least complex. And this way we don't block the user in their intended behavior but educate him about the consequences.

**Comment by jbibla** [comment]
so what you're proposing is:

1. when the user clicks `max` we run the fee simulation and subtract this from the max?
2. show a message explaining this is what happened and why

are you opposed to the following proposal?

1. allow the user to set the true max with the max button on step 1
2. show a warning that they are not leaving any for fees which may be required
3. turn the button into a "subtract fees" button

**Comment by faboweb** [comment]
Why do you want to make it more complex? Do we want to force the user to pay for fees?

**Comment by jbibla** [comment]
my intention is to make it as simple as possible while also letting the user know what's happening. 

i am in favour of the simplest solution - which i guess at this points is having a max button that doesn't know anything about fees and a message (#2530) that says "hey, you should probably leave some left over for fees". 

that would be simplest and easiest IMO.
