### ISSUE TITLE
add row numbers to validator list

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2671]
**Is your feature request related to a problem? Please describe.**

Users expect to see row numbers associated with each validator to help contextualize the validator set.  Most validator lists include a row number on the left side to help people understand the rankings.

- Is this the 8th most powerful validator or the 12th?
- How many validators are there in total?
- Which validator is the 100th?

**Describe the solution you'd like**

Let's add a column on the left hand side of the validator table (or li-validator) and include a row number. This should work on the main validator table but also on the my delegations tab too.

**Describe alternatives you've considered**

I don't think there are alternatives aside from _not_ displaying the numbers which is unsatisfactory.

**Comment by faboweb** [comment]
Could you give some context here?

**Comment by faboweb** [comment]
Your sure this is a good idea? Isn't that a tool to foster centralization?

**Comment by jbibla** [comment]
yes I am sure. no I don't think so. 

we need to be more clever than hide numbers / restrict filtering if we want to foster decentralization. obscuring or hiding information is not a good approach.

the numbers shouldn't be "attached" to a validator by ranking / voting power - but should act like row numbers. so if you sort by anything (or search) you should be able to see the row number (like a spreadsheet).

**Comment by faboweb** [comment]
What would you base the row number on?

**Comment by jbibla** [comment]
... the number of the row in the table.

the first row (no matter what filter is active) should display a 1 on the left

like an excel sheet

**Comment by faboweb** [comment]
But the position of a validator could change on two page loads. Did you consider that?

**Comment by jbibla** [comment]
> But the position of a validator could change on two page loads.

yeah, i think that's fine. it's not a validator number, it's a row number.

for example: how do you answer the following questions?

- which validator is number 101? 
- which is the 10th most powerful validator?
- how many validators are there?

**Comment by faboweb** [comment]
> which validator is number 101?

I can't because I don't know on which scale I evaluate the rank.

> which is the 10th most powerful validator?

I can do that by sorting by voting power and counting down.

> how many validators are there?

If this is interesting we should add this is an aggregate value. The value exists in the network tab.

**Comment by faboweb** [comment]
If the row number is just the rank according to voting power, I think that could be fine. It then could be combined with the voting power column.

**Comment by jbibla** [comment]
> I can't because I don't know on which scale I evaluate the rank.

when sorted by voting power, it will be the one with the number 101

> I can do that by sorting by voting power and counting down.

sure, but i'm saying we should help the users out by adding the numbers so you don't have to count

**Comment by faboweb** [comment]
We aligned on making the rank the voting power and adding the rank to the voting power column

**Comment by jbibla** [comment]
this is still relevant. our rows need numbers.
