### ISSUE TITLE
Unable to claim rewards if amount of validators is more than 5

### ISSUE THREAD

**Issue by xhipster** [luniehq/lunie#2672]
**Describe the bug**
I can claim rewards only from 5 delegates:

https://www.mintscan.io/txs/e426fbdbc9572568dde62154f5aa0d4691dc846261f8d07d7c0e8daf8d859f71

The next try claims rewards from the same delegates leaving some ATOMs unclaimed:
https://www.mintscan.io/txs/0449e3ccb4b0e0c76b2bf599a7a469dddfa461bcf1874fb1b40c62d40238f56d
https://www.mintscan.io/txs/f3273727c8e1bf678f6e51ecb9d9ffca323b1e26907b36e1360e32575a9c96dc

**To Reproduce**
Delegate to more than 5 delegates. Try to claim rewards.

**Expected behavior**

I expect that all my rewards can be claimable using one transaction independent on the number of validators I delegate.

**Screenshots**
<img width="1245" alt="Screenshot 2019-06-01 at 17 20 57" src="https://user-images.githubusercontent.com/410789/58750369-d29ade80-8491-11e9-880e-0b7918c1a59f.png">

**Desktop (please complete the following information):**
 - OS: fresh OSX
 - Browser: Chrome
 - Version: 74.0.3729.13

**Comment by faboweb** [comment]
The problem is, that you can't sign an unlimited amount of txs at the same time with the Ledger Nano S.
When you withdraw, you should withdraw always from the 5 validators with the most rewards. Additionally you can withdraw from a single validator from the validators profile page.
We will check if our logic to sort the validators is broken. Thanks for inquiring.

**Comment by xhipster** [comment]
> Additionally you can withdraw from a single validator from the validators profile page

It is good that exists workaround, thanks

**Comment by jbibla** [comment]
this issue has been resolved.

**Comment by JVsGithub** [comment]
unable to claim reward with windows 10

**Comment by jbibla** [comment]
Unfortunately, it's out of our hands. As soon as the Ledger team pushes a fix we'll update it the library to work with Lunie.

@btchip @jleni 

for reference: https://github.com/cosmos/ledger-cosmos/issues/157
