### ISSUE TITLE
Remove "(Sent via Lunie)" in memo field when clicked

### ISSUE THREAD

**Issue by chtmorris** [luniehq/lunie#2673]
I'm frustrated when I click on the memo field to paste a memo ID and I then have to first delete "(Sent via Lunie)"

(Sent via Lunie) could still be there as a suggestion, but when the field is clicked this text should disappear.

The reality is that no one is looking to include a memo that says (Sent via Lunie). I appreciate that this is marketing, but at the moment it is negatively impacting user experience.

**Comment by jbibla** [comment]
Sorry to hear this has been frustrating - I like your proposed solution and agree this would provide a better user experience.

Can I ask, what are you using the memo field for?

**Comment by chtmorris** [comment]
E.g. sending ATOMs to Binance requires a memo ID.

**Comment by jbibla** [comment]
this is done!
