### ISSUE TITLE
Max fees to available amount

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2674]
**Is your feature request related to a problem? Please describe.**

In the case the user has not enough liquid atoms to pay for fees, he currently can't perform a tx. 

**Describe the solution you'd like**

Max the fees to the available left over liquid atoms.

**Describe alternatives you've considered**

Allow for custom fees selection.

**Additional context**

**Comment by jbibla** [comment]
this is only for situations where the user doesn't have enough atoms to pay fees, right?

do we also have an open issue somewhere about warning the user if they are going to 0 atoms that they will need to retain some for fees?

**Comment by faboweb** [comment]
> this is only for situations where the user doesn't have enough atoms to pay fees, right?

jep

> do we also have an open issue somewhere about warning the user if they are going to 0 atoms that they will need to retain some for fees?

jep :)

**Comment by faboweb** [comment]
https://github.com/luniehq/lunie/issues/2530
