### ISSUE TITLE
Sign in with validator address produces error

### ISSUE THREAD

**Issue by colw** [luniehq/lunie#2677]
**Describe the bug**
Displays Javascript error message when loading Validators tab.

**To Reproduce**
1. Go to https://lunie.io/#/staking/validators
2. Look for Javascript error in notification area
3. Notice also error in dev tools network tab

**Expected behavior**
- Not possible to sign in with validator address
- No JS error shown

**Screenshots**
<img width="845" alt="Screenshot 2019-06-04 at 00 05 16" src="https://user-images.githubusercontent.com/360865/58837649-759f5400-865c-11e9-8e2b-5448e8276676.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 74.0

Bug only witnessed in above config, though may exhibit in some other way on other platforms.

**Additional context**

**Comment by faboweb** [comment]
Someone signed in with a wrong address. This is a validator address. We need to validate the signin: #2649
