### ISSUE TITLE
Releases are not published to GitHub

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2680]
**Describe the bug**

We are missing releases on GitHub

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
👍

**Comment by faboweb** [comment]
Still an issue

**Comment by jbibla** [comment]
@iambeone can you please take a look at this?

**Comment by iambeone** [comment]
Ok)

**Comment by faboweb** [comment]
We are tagging releases. But we want to create a release on GitHub with the changes of that release. We are using the Simsala tooling to handle changelogs and releases. I propose adding a function/option to Simsala to also add releases to GitHub. Simsala is here: https://GitHub.com/faboweb/simsala
