### ISSUE TITLE
Filtering Governance Proposals does not work accurately

### ISSUE THREAD

**Issue by thebkr7** [luniehq/lunie#2693]
**Describe the bug**
The filter options at the top of the list of proposals under the Governance tab do not work as expected.

**To Reproduce**
Go to: https://lunie.io/#/governance/proposals
Try selecting one of the filters
Now try selecting another. It does not work.

**Expected behavior**
For the filters to work.

**Comment by thebkr7** [comment]
Code is done and working but I'm blocked on the tests. Will discuss in standup Friday.

**Comment by jbibla** [comment]
we removed filters from the list (for now) in #2850
