### ISSUE TITLE
Multiple Networks

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#27]
As a user
I want to be able to select a blockchain-network
So I am able switch between production- and test-networks.

AC:
- [ ] The user is able to select a network and persist that decision

Note:
- What is the use case?

**Comment by faboweb** [comment]
Duplicate of #5

**Comment by faboweb** [comment]
For developers to use the test-net

**Comment by jolesbi** [comment]
ideally, i think this would be part of the welcome screen flow. but i believe the decision was to leave this until after launch.

**Comment by jbibla** [comment]
> Nov 27, 2017
> i believe the decision was to leave this until after launch.

wow. and so it is.

i think this is very important to consider as mainnet comes online. we should provide the option to switch from voyager testnet to mainnet and vice versa. 

they should be running the same version of Gaia anyways, so hopefully this won't be too painful?

@faboweb

**Comment by faboweb** [comment]
👍  I think this is not that hard as we have dynamic backends already in place. If you come up with a design for it, I think we can make this happen.

**Comment by jbibla** [comment]
https://media.giphy.com/media/5GoVLqeAOo6PK/200.gif
