### ISSUE TITLE
Cannot sign in via ledger nano X on windows 8.1

### ISSUE THREAD

**Issue by Onefox** [luniehq/lunie#2731]
**Describe the bug**
When using ledger nano x with cosmos app version 1.5.3 windows 8.1 and chrome 75.0.3770 I am unable to login.
The following error message is show: 
`Unknown Status Code: undefined`

**To Reproduce**
1. Start ledger nano X 
2. Open the cosmos app
3. Go to lunie.io and try to sign in.
4. See error `Unknown Status Code: undefined`

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome 75.0.3770

The same ledger nano X is working with lunie.io under a macOS 10.14.5

**Comment by faboweb** [comment]
Thanks for filing the issue. I check this out today.

**Comment by jbibla** [comment]
@faboweb any update?
