### ISSUE TITLE
Display multi message transactions

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2742]
**Is your feature request related to a problem? Please describe.**

Transactions with multiple messages get split and displayed as individual txs in Lunies transaction overview. This floods the transaction overview in the case of the multiple withdraw messages a user does every time he withdraws.

**Describe the solution you'd like**

Bundle the messages together. Showing all of them only on an interaction.

**Describe alternatives you've considered**

Only do this for withdraw transactions.

**Additional context**

**Comment by jbibla** [comment]
> Transactions with multiple messages get split and displayed as individual txs in Lunies transaction overview. 

exactly! 

@thebkr7 we were talking a bit about this yesterday.

**Comment by thebkr7** [comment]
We are not pursuing this option correct?

**Comment by faboweb** [comment]
> Transactions with multiple messages get split and displayed as individual txs in Lunies transaction overview.

It's not really accessible :(

**Comment by jbibla** [comment]
> We are not pursuing this option correct?

nope, don't worry about it now - just sharing for your info

**Comment by jbibla** [comment]
this is _almost_ a bug. i really don't like that we're misleading users here. let's resolve this.

**Comment by faboweb** [comment]
still valid

**Comment by jbibla** [comment]
@faboweb does anyone have an address i can use to see this tx type? i can do this issue.
