### ISSUE TITLE
Auto Opt-in remote error tracking

### ISSUE THREAD

**Issue by thebkr7** [luniehq/lunie#2744]
When a user is importing or signing up for Lunie they are asked: "I'd like to opt-in for remote error tracking to help improve Voyager." I think this should be checked automatically and have the option to uncheck and opt-out.

**Additional context**

**Comment by faboweb** [comment]
I think there are legal issues with opt-out error tracking

**Comment by jbibla** [comment]
what benji is suggesting is not "opt-out", the user still has to "opt-in" we would just pre-click the checkbox for them.

**Comment by faboweb** [comment]
Legally that's the same as an opt-out.

**Comment by jbibla** [comment]
we removed sentry
