### ISSUE TITLE
Clicking validators address from the transaction screen doesn't work

### ISSUE THREAD

**Issue by thebkr7** [luniehq/lunie#2749]
**Describe the bug**
Clicking validators address from the transaction screen doesn't work.

**To Reproduce**
Click into Transactions
Click the address of the validator that you deligated to
It cannot find that validator
*Screenshots**
a. doesn't work, but b. copies the address.
![image](https://user-images.githubusercontent.com/11528441/59938395-d97a9880-9422-11e9-82d2-505e87a1e190.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Those should also be converted to a moniker.

**Comment by colw** [comment]
What circumstances do these not appear as a Moniker? They do for me.

**Comment by thebkr7** [comment]
Delegation/Undelegation's

**Comment by jbibla** [comment]
yeah, these were working for me in production 🤔

**Comment by thebkr7** [comment]
I should have updated the issue. The problem I identified ended up being only my end with mine showing old transactions from previous testnets (how I do not know, potentially cached). But they still needed to be shortened for the extension.

**Comment by jbibla** [comment]
ah ok! yeah, probably cached.
