### ISSUE TITLE
Cannot sign in with ledger nano in win10 may 2019 update + chrome

### ISSUE THREAD

**Issue by williamchong007** [luniehq/lunie#2754]
**Describe the bug**
I am using ledger nano S to sign in on windows 10 may 2019 update (version 1903 build 18362.175). After clicking sign in with ledger, `Windows Security` popup (the new native FIDO U2F from Microsoft i suppose) keep on popup up and automatically closing itself for a while. 
After the popup flashing stops and I accepted login on ledger, I got stuck with an error screen in the windows security popup. Closing the window and retrying sign in yields either another error popup or getting stuck with `Take action on your security key` , while ledger is stuck in `Returning Address...`

**To Reproduce**
1. Go to lunie and try sign in with ledger. Click the signin button with ledger connected and cosmo app open.
2. Get a lot of "Windows security" popup on and off flashing the screen. Wait until it stop and a prompt appears on ledger.
3. Click accept button on ledger.
4. See an error screen in the Windows Security popup. Ledger stuck in `Returning Address`.

**Expected behavior**
Only 1 popup of Windows security asking me to press button should appear, I should be about to login after I press accept on ledger.

**Screenshots**
After the "Windows Security" popup flashing decided to stop
![1](https://user-images.githubusercontent.com/6198816/59967601-f7e5ae80-955e-11e9-8572-9d13cbfe8f1b.PNG)
After pressing accept on ledger:
![image](https://user-images.githubusercontent.com/6198816/59967522-af79c100-955d-11e9-89bb-253bd6db3e70.png)
Result:
![3](https://user-images.githubusercontent.com/6198816/59967602-f9af7200-955e-11e9-9fc0-0c0f33b52517.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10  (version 1903 build 18362.175)
 - Browser: Chrome 
 - Version: 75.0.3770.100

**Comment by faboweb** [comment]
There sadly is an issue with Ledger on the newer Windows version. I recommend using a secondary machine running Linux or OSX or an older Windows. Ledger told us, that a real fix will only be available later this year.
We are working on alternative signing mechanisms as I write here!

**Comment by btchip** [comment]
We're reviewing this issue with @jleni - it should be fixable with the current implementation before migrating to WebUSB later.

**Comment by jleni** [comment]
Linked to this PR
https://github.com/LedgerHQ/ledger-app-cosmos/pull/8

**Comment by jotaP73** [comment]
Absolutely the same problem. I have tried lots of solutions without sucess.

Did you find a solution?

**Comment by williamchong** [comment]
> Absolutely the same problem. I have tried lots of solutions without sucess.
> 
> Did you find a solution?

It worked for me after a new cosmos app veriosn was released on ledger an year ago. Not sure if the latest cosmos app and windows would cause similar issue now though.

**Comment by astro1983** [comment]
Anybody know the solution for this issue? I have windows blocking me asking to sign in

**Comment by faboweb** [comment]
Which Lunie version are you using? Or are you running this repo on your own?
