### ISSUE TITLE
Validators List Filter Bug

### ISSUE THREAD

**Issue by thebkr7** [luniehq/lunie#2770]
**Describe the bug**
In the validators list the "Voting Power" filter does not filter.

![image](https://user-images.githubusercontent.com/11528441/60032344-55b7ea80-9674-11e9-86a0-21b7881d2a3d.png)

**Comment by faboweb** [comment]
Push

**Comment by faboweb** [comment]
Apparently this only happens to developers

**Comment by jbibla** [comment]
i would still fix it - but just mark it as low priority
