### ISSUE TITLE
Unable to withdraw rewards

### ISSUE THREAD

**Issue by reinierkors** [luniehq/lunie#2773]
**Describe the bug**
I can't seem to withdraw any rewards, I've waited 21 days. Am I missing something? I am staking 1 validator.

**To Reproduce**
1. Login with Ledger Nano S
2. Go to staking
3. Click withdraw
4. Click next
5. Get error.. 

**Expected behavior**
Expecting to be able to withdraw rewards.

**Screenshots**
![ss](https://i.imgur.com/7cxqk3j.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 75.0.3770.100

**Comment by faboweb** [comment]
Hey! Thanks for reaching out! The reason is, that you don't own enough coins to pay for fees. I pushed a PR today #2775 which will solve the issue by limiting fees to you balance.

**Comment by jbibla** [comment]
it's odd that we're showing a validation error on this screen...

**Comment by faboweb** [comment]
Yeah that comes from the gas price input

**Comment by reinierkors** [comment]
Thanks for the quick support.
