### ISSUE TITLE
Refactor Sesssion Modal Common Controls

### ISSUE THREAD

**Issue by colw** [luniehq/lunie#2774]
Each `TMSessionXYZ.vue` component has common functionality:

- Title
- Close
- Go back

This should be factored out into a common component `TmSessionFrame.vue` to avoid repeating ourselves.

At least these to start with:

- TmSessionWelcome
- TmSessionSignUp
- TmSessionExisting
- TmSessionExplore
- TmSessionHardware
- TmSessionExtension

**Comment by jbibla** [comment]
yep!

**Comment by faboweb** [comment]
Agreed

**Comment by faboweb** [comment]
This is done right?
