### ISSUE TITLE
Add Gallery view for validators

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2789]
**Is your feature request related to a problem? Please describe.**

The current table/list view is useful if you want to quickly look at the values for each validator. Nevertheless, if you are familiar with the validators or simply want to have a cleaner overview of the validators it'd be better to have a Gallery view (like in squares). 

**Describe the solution you'd like**

Implement gallery view for validators

**Describe alternatives you've considered**

One approach could be displaying an enlarged image of the validator with its moniker and short-address

**Additional context**

PS: @jbibla I'm still waiting for the txs amounts on the right side xD

**Comment by jbibla** [comment]
https://lunie.io/#/careers

**Comment by fedekunze** [comment]
Lol

**Comment by jbibla** [comment]
things are being redesigned. this isn't an "issue".

thanks for the ideas fede 👍 

https://lunie.io/#/careers
