### ISSUE TITLE
Have all external links fetched from a single config file

### ISSUE THREAD

**Issue by thebkr7** [luniehq/lunie#2808]
**Is your feature request related to a problem? Please describe.**
Not related to a bug but rather a suggestion.

**Describe the solution you'd like**

Have all external links fetched from a single config file. Such as the chrome extension and ledger nano links. This would allow for changing the links addresses quickly and without worrying about missing one.

**Comment by jbibla** [comment]
great idea. still relevant. @colw we're doing this for some links already, right?

**Comment by colw** [comment]
> great idea. still relevant. @colw we're doing this for some links already, right?

Yes. We can absolutely, and should do this.

**Comment by jbibla** [comment]
is this done now on the api-gateway branch @colw ?

**Comment by colw** [comment]
No, but I believe the issue refers to simply putting them in a config local to this repo. It would be relatively straight forward to implement. A good first issue.

**Comment by jbibla** [comment]
ah! yes yes got it. thanks.

**Comment by colw** [comment]
This is a "nice to have", but as far as I'm aware it's not fixing an ongoing problem.

For the record I imagine it could be a simple module loaded into the store, and fetched where appropriate.

**Comment by jbibla** [comment]
true. will close for now.
