### ISSUE TITLE
show block proposer

### ISSUE THREAD

**Issue by fedekunze** [luniehq/lunie#2841]
**Is your feature request related to a problem? Please describe.**

The proposer of a block is missing on the block page.

**Describe the solution you'd like**

Display the validator proposer of the block on the blocks page.

**Describe alternatives you've considered**

add another row to the block page with the following info of the proposer: 

round image + moniker (with ValAddress on a tooltip)

**Comment by faboweb** [comment]
https://lunie.io/#/careers

**Comment by jbibla** [comment]
nice idea @fedekunze!

**Comment by jbibla** [comment]
@thebkr7 this should be data on our backend

**Comment by faboweb** [comment]
Still valid

**Comment by faboweb** [comment]
#3072
