### ISSUE TITLE
proposals aren't loading when refreshed

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2849]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment]
Resolved
