### ISSUE TITLE
Add warning field to backend

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2858]
**Is your feature request related to a problem? Please describe.**

We want to inform users quick, if the backend shows bad behavior. We currently need to update Lunie to do so.

**Describe the solution you'd like**

Add a field to our backend (Hasura) where we can set a warning message. Lunie queries this field and displays the warning bar.

**Describe alternatives you've considered**

Only use Twitter for warnings. Update Lunie manually with the warnings.

**Additional context**

**Comment by jbibla** [comment]
maybe this belongs in the hasura repo?

**Comment by faboweb** [comment]
Use existing component: https://github.com/luniehq/lunie/blob/develop/src/components/common/MaintenanceBar.vue

- Create table in Hasura `maintenance` with one column `message`
- Query `message` via apollo and display the bar with the message if exists.

Optional:
Create second column `type` and style the bar according to it
