### ISSUE TITLE
simplify validator loading

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2892]
**Is your feature request related to a problem? Please describe.**

- upon load, lunie will quickly display generated avatars for all validators and then switch to the keybase images if they are available

**Describe the solution you'd like**

- a better solution would be to show a loading image or simpler placeholder (empty box) before displaying generated avatars for validators that will eventually have an available keybase image

**Comment by faboweb** [comment]
Should we rather show `loading` (or display placeholder list items) until all the data is loaded? Names could also be overwritten by the Apollo query.

**Comment by jbibla** [comment]
sure that makes sense. we should only be loading 10 or 20 to start. it seems right now that the data is available before the keybase images. i don't care about the particulars so much but we should aim for a graceful and intelligent loading experience.
