### ISSUE TITLE
Remove caching code

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2895]
**Is your feature request related to a problem? Please describe.**

The caching is not used anymore after the mobile improvements. Let's remove the according code.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
can you add a bit more detail about which folders / files you're referring to?

**Comment by faboweb** [comment]
Mostly code in `src/vuex/store.js`

**Comment by faboweb** [comment]
Still valid.

**Comment by mariopino** [comment]
I need a bit of orientation to do this task. Please can you point the relevant code?

**Comment by faboweb** [comment]
> Mostly code in src/vuex/store.js

Anything related to persisting the state in local storage
