### ISSUE TITLE
improve tx data and event tracking

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2897]
**Is your feature request related to a problem? Please describe.**

-  we need to have a better understanding of lunie's impact on the ecosystem and how users are actually using lunie

**Describe the solution you'd like**

- events should include amounts
- add events for missing key actions (creating addresses, others?)
- events can be cleaned up / reorganized?
- add lunie memo for all txs (not in the action modal, but just programatically)

**Comment by faboweb** [comment]
Could you list the missing actions?

> events can be cleaned up / reorganized?
do you have an idea how to do that? what is currently not working for you?

**Comment by jbibla** [comment]
> Could you list the missing actions?

- creating addresses
- recovering addresses
- sign in session type (ledger, extension, mobile)

> events can be cleaned up / reorganized?

- i believe all the action modal events are tracked "on submit". might be better to track on success and on failure as opposed to having separate counts for all submits and all successes / failures.

**Comment by jbibla** [comment]
this would be worth doing

**Comment by jbibla** [comment]
ok yes i'll do this.
