### ISSUE TITLE
uptime improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2898]
**Is your feature request related to a problem? Please describe.**

- it's not clear how we're calculating uptime
- li-validator and page-validator uptime values are different

(from conversation with Chainflow validator)

**Describe the solution you'd like**

- let's do 30 days instead of 10,000 blocks because this is standard SLA timeframe
- li-validator / page-validator data should be consistent

**Comment by faboweb** [comment]
> let's do 30 days instead of 10,000 blocks because this is standard SLA timeframe

The problem would be, that we need to store the blocks missed in that timeframe. We already get the blocks missed among the last 10k blocks.

> li-validator / page-validator data should be consistent

I strongly agree.

**Comment by jbibla** [comment]
> We already get the blocks missed among the last 10k blocks

10000 blocks is approx 1 day (i think). this is not a good uptime indicator.

> The problem would be, that we need to store the blocks missed in that timeframe. 

what's the problem with storing the blocks missed in 30 days?

**Comment by faboweb** [comment]
when we process the whole chain, this gets easier as we can store this in the db. currently we rely on the onchain data. let's defer this until we have the per block crawler.

**Comment by jbibla** [comment]
uptime is not being displayed as a percentage at the moment...

**Comment by faboweb** [comment]
> uptime is not being displayed as a percentage at the moment...

next time I would be happy if you create a bug issue (so this doesn't get mixed with the improvement ideas) or quickly fix this.
