### ISSUE TITLE
network switch functionality

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2904]
In Lunie we need a network switcher and following it, the functioniality to query data for the selected network.
To avoid incompatibility between different SDK versions we want to limit data shown to the defined data schema in our backend.
The dataschema has a feature schema. These are the features we are already support for that network. Lunie should now show a message `Lunie has no support for this feature yet` on pages that are flagged with false. Lunie should also show `Lunie has no support for this feature yet` in the ActionModal for disabled interactions.

**Comment by jbibla** [comment]
should we move this to https://github.com/luniehq/lunie-backend ?
