### ISSUE TITLE
Serve fonts directly - Not seeing "buttons" only chevron_right etc.

### ISSUE THREAD

**Issue by azulmarino** [luniehq/lunie#2918]
macOS Catalina 
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

Seems like a fonts change was made , now the graphics aren't displayed.

BTW why was the font changed .. the UI was perfect as Peng designed it.

**Comment by faboweb** [comment]
Can you send a screenshot of the failing graphics? I am also on OSX and they display fine.

> BTW why was the font changed .. the UI was perfect as Peng designed it.

We aim to improve the UI to make it simpler and more accessible.

**Comment by azulmarino** [comment]
<img width="1440" alt="Screenshot 2019-08-28 at 15 42 14" src="https://user-images.githubusercontent.com/17141152/63861093-8258ed00-c9aa-11e9-8976-154cce9546a7.png">

**Comment by azulmarino** [comment]
There's an old adage , if it ain't broke don't fix it.
You worsened the look of the UI 
I understand changing some text , but graphically looks worse.

OFC this is just my opinion which is subjective and hopefully constructive criticism.

**Comment by faboweb** [comment]
What are you missing from the new UI? How is it graphically worse than before? Happy to incorporate the feedback in the next iteration.

**Comment by azulmarino** [comment]
<img width="1440" alt="Screenshot 2019-08-28 at 15 47 15" src="https://user-images.githubusercontent.com/17141152/63861394-2347a800-c9ab-11e9-9a79-1bf6f9765965.png">

**Comment by azulmarino** [comment]
> What are you missing from the new UI? How is it graphically worse than before? Happy to incorporate the feedback in the next iteration.

Seems font has changed ... or is it related to the problem I see ?

**Comment by faboweb** [comment]
Can you try a hard refresh? `Cmd+Shift+R`

**Comment by faboweb** [comment]
> Seems font has changed ... or is it related to the problem I see ?

This is a related problem.

It currently looks like this:

![image](https://user-images.githubusercontent.com/5869273/63861566-6e61bb00-c9ab-11e9-9e53-acd669ee246a.png)

**Comment by azulmarino** [comment]
Same problem , I have restarted a number of times.
Let me try to clear the cache.

**Comment by faboweb** [comment]
Does it work in incognito mode?

**Comment by azulmarino** [comment]
yes, Incognito mode is fine

**Comment by faboweb** [comment]
Then it is some kind of caching issue. Could you maybe try going to the developer console `cmd+shift+i` then to `Application` > `Clear storage` > click `Clear site data`.

**Comment by azulmarino** [comment]
Same problem

**Comment by faboweb** [comment]
Do you maybe block traffic from google? The fonts are loaded via `fonts.googleapis.com`

**Comment by azulmarino** [comment]
Failed to load resource: net::ERR_UNSAFE_REDIRECT
app.413bfb32.js:1 Expecting stargate at: https://lcd.nylira.net
app.413bfb32.js:1 init rpc with https://rpc.lunie.io:26657
flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://mnfifefkajgofkcjkemidiaecocnkjeh/contentscript.js:12 TezBox API is ready!
app.413bfb32.js:1 Service worker has been registered.
mem5YaGs126MiZpBA-UNirkOUuhpKKSTjw.woff2:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by azulmarino** [comment]
Looks to be the case . google analytics blocked

**Comment by faboweb** [comment]
Ok we try to load the fonts directly. 👍 Thank you.

**Comment by azulmarino** [comment]
thanks

**Comment by azulmarino** [comment]
Is this your plugin ? : PepperFlashPlayer.plugin

**Comment by azulmarino** [comment]
Surely there is enough space to show validator commission as it was before ? 
Why the change ?

**Comment by azulmarino** [comment]
https://blog.cosmos.network/lunie-is-live-196de97b6697

**Comment by azulmarino** [comment]
Why get rid of proposal number ?

**Comment by jbibla** [comment]
> Surely there is enough space to show validator commission as it was before ? Why the change ?

hey @azulmarino. thanks for all your feedback! we really appreciate it! 

commission can still be seen on the validator profile, but we wanted to make browsing the validator list (especially on mobile) a bit simpler. our thinking is that commission is one relevant data point in calculating approximate rewards but not really the whole story. which is why we added approx rewards % instead. 

what do you think about this new metric?



> Why get rid of proposal number ?

The proposals are by default in the order they were proposed in. you can see the proposal ID on the proposal itself if you click into it and in the URL.

do you think we should display the proposal number on the proposals list? if so, how come?

**Comment by faboweb** [comment]
Didn't focus on this, as it works. This would still be could to do for mobile and offline working.

**Comment by jbibla** [comment]
i would include the font file locally as per these instructions:

https://google.github.io/material-design-icons/#icon-font-for-the-web
https://github.com/google/material-design-icons/tree/master/iconfont

**Comment by Bitcoinera** [comment]
Thank you Jordan! I am going for it!
