### ISSUE TITLE
404 error on /graphql ?

### ISSUE THREAD

**Issue by liangping** [luniehq/lunie#2922]
**Describe the bug**

I installed lunie following the tutorials.  Everything is ok, but there is a 404 error on /graphql. How can I fix this error? 
Should I install any extenstion libs or dependecies?

**Comment by faboweb** [comment]
Hi! Thank you for using Lunie!
We are working on a new backend where we standardize the API for different proof of stake systems. This is currently still in a very early phase and we don't feel comfortable releasing this just yet.
You can use Lunie in an earlier version (I think `1.0.0-beta.106` has no GraphQL dependency yet) until we release our backend publicly.
Can I ask what you are working on?

**Comment by liangping** [comment]
thanks @faboweb. 
I build a blockchain for my customer. and we need a trusted web wallet. 
I think that Lunio is the best option for us. 
Should I buy a license?

**Comment by jbibla** [comment]
hey @liangping! 

send me an email at jordan [@] lunie.io and we can chat about the options!

**Comment by fxfactorial** [comment]
Hi, I am very interested in using this repo but I am also running into the problem of getting started with the graphql aspect. Specifically, I want to run `graphiql` but I am not seeing how to. 

I've run the docker command, via `yarn start`, `yarn certificates` but when I go to `localhost:9080:/graphql` or `localhost:9080:/graphql/explore/__admin`, I get a 404. 

Can you please describe the right way to get started with this project, with graphql, with the data structures & schema. 

Thank you
