### ISSUE TITLE
Shorten addresses on Send confirmation screen

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2938]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5869273/64125702-3d1e2c00-cdab-11e9-8f3f-8bb6bf68334f.png)

AC:
- Addresses are shortened with the Bech32 component
- Addresses do not expand past the frame anymore

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by mariopino** [comment]
I think it's good for user to see the full destination address of their transaction. We can simply just add `word-break: break-word;` to `.tm-data-msg__subtitle` class so address don't expand over its container.

![image](https://user-images.githubusercontent.com/9256178/65862186-fbfb4680-e36d-11e9-8a77-1c92410ac02e.png)

**Comment by jbibla** [comment]
good solution. the width of the container should be set to fill the width.

**Comment by mariopino** [comment]
> good solution. the width of the container should be set to fill the width.

It's done!
