### ISSUE TITLE
Numbers with seed phrase

### ISSUE THREAD

**Issue by wimel** [luniehq/lunie#2961]
When you generate the seed phrase, the words should have a number first so you can keep track of which words are which. Copy and pasting this can be confusing and words can be jumbled.

Add the appropriate number in front of each seed word.

For new users I have seen that sometimes when copy/paste the words have problems to recover the wallet, as a help to new users could be useful.
Thanks for all!!

**Comment by jbibla** [comment]
great suggestion @wimel! i mentioned this to the team today 😄

**Comment by mariopino** [comment]
Yes! I was figuring out what component would fit best for this task in order to include it in the seed step of the new create flow.

I think the best option is a formatted table showing each word number with a copy to clipboard icon.

What do you think @jbibla?

**Comment by jbibla** [comment]
sounds like a great option!
