### ISSUE TITLE
ci/circleci: testUnit timeouts

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#2963]
**Describe the bug**

Timeout in ci/circleci testUnit execution. Current timeout is 120s.

**Comment by faboweb** [comment]
The timeout occures because of the long upload of the coverage data. Maybe the coverage upload can also be extracted into an own step.

**Comment by mariopino** [comment]
> The timeout occures because of the long upload of the coverage data. Maybe the coverage upload can also be extracted into an own step.

Ok, I'll check!
