### ISSUE TITLE
url for "activity" still points to "transactions"

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2966]
**Describe the bug**

The URL for the activity page is accessed via `/transactions`.

**Expected behavior**

- redirect `/transactions` to `/activity`
- add default route / URL for Activity to be `/activity`

**Comment by atharva3010** [comment]
Is someone working on it? This seems like an easy fix, can I work on this? @faboweb @jbibla

**Comment by faboweb** [comment]
Go for it!
