### ISSUE TITLE
hide delegations that are below a certain threshold

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2968]
**Describe the bug**

i undelegated from a validator but missed a tiny amount of rewards as time passed. the validator still appears in my portfolio with a 0 and this is the screenshot if i try to undelegate.

![Screen Shot 2019-09-09 at 1 36 16 PM](https://user-images.githubusercontent.com/6021933/64553209-f67a8580-d306-11e9-9fdc-027d903ac1c1.png)

i'm not sure what the problem is or what a solution could be.

**Comment by faboweb** [comment]
Yeah this is a downside of the gaia backend. We can just hide those delegations that are so small.

**Comment by jbibla** [comment]
@colw can we filter out delegations in the api for this?

**Comment by colw** [comment]
We can on an api or browser level. I'll go with API for now.

**Comment by jbibla** [comment]
ping @colw

**Comment by jbibla** [comment]
dupe / will be addressed by solution from #3009
