### ISSUE TITLE
switching networks should sign the user out

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#2982]
- if we don't sign users out there will be strange things happening with the data
- if users are signed in when switching we should confirm they want to sign out before it happens automatically

**Comment by atharva3010** [comment]
This would be an interesting implementation, however, the `Network Information API` (https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API) doesn't provide much info as to if there was a change from one wifi network to another, it only provides info regarding the change in connection type (i.e. `navigator.connection.type` property). This network type will be one of the following values: Bluetooth, cellular, ethernet, none, wifi, WiMAX, other and unknown. The value none represents there is no internet connection.

If this is what we want to implement, then I can listen for an `onchange` event and do the intended.

**Comment by faboweb** [comment]
The issue is not about switching actual wifi networks but blockchain networks inside Lunie.

**Comment by atharva3010** [comment]
Oh, okay. Thank you for clearing that out.

**Comment by jbibla** [comment]
yep! @Bitcoinera is working on it!
