### ISSUE TITLE
Allow for key generation in browser

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#2992]
**Is your feature request related to a problem? Please describe.**

Some of our users are lazy and just want to quickly generate a key in the browser. They don't care too much about security.

**Describe the solution you'd like**

Allow key generation (creation and import) in the browser

AC:
- key creation/import is visible in the browser
- in the browser key creation/import have as step a warning message
- the user needs to set a checkbox to confirm he has read the warning

Warning:

```
Did you know that storing your key in the browser is considered unsafe? We offer a more secure way to storing your keys via our _browser extension_. Check it out in a quiet minute.
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
i don't see any reason not to allow this. perhaps we can call it a "burner" wallet? 

how would this differ from cosmostations keystation?

**Comment by faboweb** [comment]
> how would this differ from cosmostations keystation?

completely different implementation. we would use the localstorage and encrypt the values.

**Comment by jbibla** [comment]
do you think we _should_?

**Comment by faboweb** [comment]
I already said we should :). But I would always have warning bar up stating that this is dangerous.
