### ISSUE TITLE
Dust amounts cannot be undelegated, range shown from 0.000001 to scientific notation

### ISSUE THREAD

**Issue by D-Nice** [luniehq/lunie#3009]
**Describe the bug**

When you try to unstake from a validator, where there are dust amount of atoms, the transaction dialog fails to proceed, and will either 
- encounter an error at the fee calculation, showing NaN, in the case you used "Set Max" and have a ATOM balance greater than 1.
- note a range error, denoting the "valid" range between 0.000001 and your delegated amount in scientific notation, however, no numeral between that range or below the scientific notation works.
- Give a warning that the amount needs to be a numeral, if using "Set Max" when below either 1 atom or 0.000001 (likely the latter).

**To Reproduce**

Try to unstake from a validator, where you have some dust amount lingering, potentially due to slashing.

**Expected behavior**

To be able to click "Set Max" on undelegation, and have it undelegate everything from the delegator, so the delegator no longer shows up in the active portfolio list.

**Screenshots**
If "Set Max" is clicked with dust

![photo4942940431059101850](https://user-images.githubusercontent.com/2888248/65981834-f2461180-e447-11e9-8695-e3373cf32179.jpg)

If what should be a valid numeral is entered
![photo4942940431059101851](https://user-images.githubusercontent.com/2888248/65981903-14d82a80-e448-11e9-96b8-edb6c9526152.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Brave + Ledger
 - Version: Latest

Relevant issues: https://github.com/luniehq/lunie/issues/2968 https://github.com/luniehq/lunie/issues/1442 

This PR had seen something similar: https://github.com/luniehq/lunie/pull/912#issuecomment-404208642 and there was mention of a new issue being created to fix some of the bugs within that PR, but I do not see any mention within that PR of any subsequent issues being filed pertaining to it.

**Comment by faboweb** [comment]
Awesome find. Thanks we will take care quickly.

**Comment by jbibla** [comment]
let's resolve this! it's annoying. @faboweb what is the proposed solution?

**Comment by mariopino** [comment]
Related problem:

1. Stake 1 STAKE
2. Unstake 0,9999999 STAKE
3. Click NEXT

![image](https://user-images.githubusercontent.com/9256178/69994991-79e6f400-154f-11ea-80d1-989c7a4f035d.png)

Unstaking 0,999999 STAKE will calculate the fee correctly.

Seems that fee and total have problems to handle numbers with more than 6 decimals.

**Comment by mariopino** [comment]
The proposed approach to fix that behaviour is to filter dust amount delegations at lunie-api (so don't show them).

Additionally we should validate that entered amounts have 6 max decimal places to be able to calculate transaction fee and total in a safe way.

**Comment by mariopino** [comment]
For another issue/pr, when you delegate an small amount less than 0 (let's say 0,9 ATOM), Portfolio shows 0:

![image](https://user-images.githubusercontent.com/9256178/70146818-46b57980-16a3-11ea-8b93-1d9310f78319.png)

I think we should show at least 1 decimal place.

**Comment by mariopino** [comment]
Fixed by https://github.com/luniehq/lunie-api/pull/171
