### ISSUE TITLE
Poor Inactive Validator Verbiage

### ISSUE THREAD

**Issue by alexanderbez** [luniehq/lunie#3020]
When viewing the list of validators that are inactive (i.e. unbonded), Lunie currently displays something along the lines of `Banned from the network` (e.g. [here](https://app.lunie.io/validators/cosmosvaloper1e0jnq2sun3dzjh8p2xq95kk0expwmd7sj6x59m)). For validators that are inactive solely due to now having enough power (i.e. not jailed), this verbiage is poor as the validator is not banned at all and even acts as a deterrent from having potential delegates.

**Comment by jbibla** [comment]
good catch. thanks @alexanderbez.

**Comment by faboweb** [comment]
@colw can we change this in the API to `Validator is not validating and therefor doesn't receive rewards` or similar?

**Comment by viktorbunin** [comment]
Bumping this please :)

**Comment by jbibla** [comment]
this has been improved
