### ISSUE TITLE
use Deploy contexts for nicer feature branch experience

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3038]
**Is your feature request related to a problem? Please describe.**

- using query params for graphql on feature branches is annoying as changing routes strips the param

**Describe the solution you'd like**

- use Deploy Contexts from netlify to set environment variables (https://docs.netlify.com/site-deploys/overview/#deploy-contexts)

something like:
```
master -> https://backend.lunie.io/v1/graphql
develop -> https://backend.lunie.io/v1/graphql
feature-branch -> https://localhost:4000/v1/graphql
```

**Comment by faboweb** [comment]
still relevant?
