### ISSUE TITLE
the signing method select box appears not to be selected

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3046]
**Describe the bug**

- the signing method select box has an option selected but it does not appear to be the case 

**To Reproduce**
1. go to send action modal
2. proceed to last screen
3. see sign method select

**Expected behavior**

- the sign method should appear as selected, when it's selected

**Screenshots**

![Screen Shot 2019-10-22 at 10 36 50 AM](https://user-images.githubusercontent.com/6021933/67297437-e7672580-f4b7-11e9-91da-be1ab4183539.png)
![Screen Shot 2019-10-22 at 10 36 56 AM](https://user-images.githubusercontent.com/6021933/67297438-e7672580-f4b7-11e9-9574-e0c122405aa7.png)

**Comment by mariopino** [comment]
Sorry @jbibla  but I'm not able to see the Signing Method field. I tried with develop using ledger and extension to signin. What I'm missing?

**Comment by jbibla** [comment]
what do you see on the third (sign) step of the action modal?

**Comment by mariopino** [comment]
Aam I see. That is shown when you sign in with an address in explore mode. I was using either the extension or the ledger to sign in. :-)

**Comment by mariopino** [comment]
This is what i see:

**Comment by jbibla** [comment]
this screen should not default to "Select option..." if there is already an option selected. it should default to the one that is already selected.

![image](https://user-images.githubusercontent.com/9256178/67414515-8d538680-f5c3-11e9-80ad-224a8951f29c.png)

**Comment by jbibla** [comment]
false alarm. it works as expected.
