### ISSUE TITLE
Add Sentry to Frontend

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3048]

**Comment by atharva3010** [comment]
I would like to pick this up @faboweb   
Can you give me a bit more information if you need anything other than the basic setup?

**Comment by faboweb** [comment]
I guess the basic setup is ok (all global errors should be catched and logged). We need to deploy the source maps to Sentry for all `master` deploys. Take a shot and let's see how it goes. @iambeone is also working on Sentry this week. Though ask here if anything is missing.

**Comment by jbibla** [comment]
@iambeone can you confirm this is working as expected? i think there is an issue blocking this.
