### ISSUE TITLE
U2F browser support and Https issue with Lunie on localhost on interacting with Ledger Nano S

### ISSUE THREAD

**Issue by apatifirstblood** [luniehq/lunie#3053]
Hi Team,

i am using google chrome having U2F support still I am getting issue  with Lunie on localhost when connecting ledger Nano S.
I am following  after connecting Ledger Nano-
click on Sign in-->click use an existing address-->click Use Ledger Nano-->Click Sign in

from config side ..I cloned Lunie wallet repo -->yarn install-->yarn certificates-->yarn start

Then I am getting below result-

 DONE  Compiled successfully in 8743ms                                2:59:47 PM

  App running at:
  - Local:   http://localhost:9080/ 
  - Network: http://192.168.1.18:9080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

When i run lunie on http://localhost:9080/ its running fine ..but on connecting ledger Nano and after click on Sign in-->click use an existing address-->click Use Ledger Nano-->Click Sign in
I am getting U2F browser support and Https issue with Lunie  error.

can anyone please help me on this..

**Comment by faboweb** [comment]
for ledger to be usable you need to run the website in https mode
you can do so by adding https to the devServer. 

https://webpack.js.org/configuration/dev-server/#devserverhttps

Add this in `vue.config.js` after `plugins`

**Comment by jbibla** [comment]
hey @apatifirstblood! few questions:

- what is your goal in running lunie locally? 
- which version of Lunie are you running (commit hash would be fine)?

does everything else work ok?

**Comment by faboweb** [comment]
This is how the config should look like for https:

```
const path = require(`path`)
const webpack = require(`webpack`)
const CSPWebpackPlugin = require(`csp-webpack-plugin`)

function resolve(dir) {
  return path.join(__dirname, dir)
}

const commitHash = require(`child_process`)
  .execSync(`git rev-parse HEAD`)
  .toString()
  .trim()

module.exports = {
  publicPath: `/`,
  configureWebpack: () => {
    const config = {
      resolve: {
        alias: {
          src: resolve(`src`),
          "@": resolve(`src`),
          assets: resolve(`src/assets`),
          scripts: resolve(`src/scripts`),
          common: resolve(`src/components/common`),
          governance: resolve(`src/components/governance`),
          network: resolve(`src/components/network`),
          staking: resolve(`src/components/staking`),
          transactions: resolve(`src/components/transactions`),
          wallet: resolve(`src/components/wallet`),
          test: resolve(`test`)
        },
        extensions: [`.js`, `.vue`, `.css`]
      },
      plugins: [
        new webpack.DefinePlugin({
          "process.env": {
            NODE_ENV: JSON.stringify(process.env.NODE_ENV),
            RPC: JSON.stringify(process.env.RPC),
            STARGATE: JSON.stringify(process.env.STARGATE),
            RELEASE: JSON.stringify(commitHash),
            GOOGLE_ANALYTICS_UID: JSON.stringify(
              process.env.GOOGLE_ANALYTICS_UID
            )
          }
        })
      ],
      devServer: {
        https: true
      }
    }

    if (process.env.NODE_ENV === `production` && !process.env.E2E_TESTS) {
      config.plugins.push(
        // adds the content security policy to the index.html
        new CSPWebpackPlugin({
          "object-src": `'none'`,
          "base-uri": `'self'`,
          "default-src": `'self'`,
          "script-src": [`'self'`, `https://*.lunie.io`],
          "worker-src": `'none'`,
          "style-src": [`'self'`, `'unsafe-inline'`],
          "connect-src": [
            // third party tools
            `https://api-iam.intercom.io`,
            // mainnet
            `https://stargate.lunie.io`,
            `wss://rpc.lunie.io:26657`,
            `https://stargate.cosmos.network`,
            `wss://rpc.cosmos.network:26657`,
            ...[process.env.STARGATE].filter(x => x !== undefined),
            ...[process.env.RPC]
              .filter(x => x !== undefined)
              .map(x => x.replace("https", "wss"))
          ],
          "frame-src": [`'self'`, `https://api-iam.intercom.io`],
          "img-src": [`'self'`, `https://www.google-analytics.com/`]
        })
      )
    }

    return config
  },

  pluginOptions: {
    lintStyleOnBuild: false,
    stylelint: {}
  }
}
```

**Comment by apatifirstblood** [comment]
![corserror](https://user-images.githubusercontent.com/55091954/67797774-6a840f00-faa8-11e9-8045-286a251ee46f.png)

above is the error screenshot...It seems there is some cors error

**Comment by faboweb** [comment]
Yes. I am sorry but the current Lunie version uses our backend which is not released to the public yet.
You could try an earlier Lunie version (maybe Version `1.0.0-beta.106`).

**Comment by apatifirstblood** [comment]
@faboweb  Ohk..are u going to release backend to public in realtime soon.If yes then by when it would be available?
Is backend for Version 1.0.0-beta.106 publicly available?

**Comment by apatifirstblood** [comment]
> hey @apatifirstblood! few questions:
> 
> * what is your goal in running lunie locally?
> * which version of Lunie are you running (commit hash would be fine)?
> 
> does everything else work ok?

HI @jbibla ..we are working on developing a stand-alone blockchain using Cosmos-SDK .Inorder to interact with it and make provisions for delegators and validators to sign transaction and other interactions,Lunie seems to be the perfect fit but its only for cosmos address(starting with "cosmos"123fz4rt5gh....) .So we want to customise Lunie to support our customised Bech32 address.
2. v-beta.132

**Comment by faboweb** [comment]
@apatifirstblood if I am correct 1.0.0-beta.106 doesn't need a backend. Please write us at contact@lunie.io. We may integrate your project into Lunie if you like.

**Comment by apatifirstblood** [comment]
@faboweb Thanks for the contact info..I will soon be in touch via mail..
Also need thing, Is the Lunie Extension for chrome opensource?

**Comment by faboweb** [comment]
> @faboweb Thanks for the contact info..I will soon be in touch via mail..
Also need thing, Is the Lunie Extension for chrome opensource?

Also not public yet.

**Comment by apatifirstblood** [comment]
Earlier  1.0.0-beta.106  there was connecttion to chain. now I am not able to connect to any node.
