### ISSUE TITLE
Remember the last network selected

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3063]
**Is your feature request related to a problem? Please describe.**

When I start Lunie I want to see the same network I last selected.

**Describe the solution you'd like**

The last selected network should be stored in localStorage.
On boot the last selected network should be loaded from localStorage. The according network config should be loaded from the API (endpoints could have been changed).

**Describe alternatives you've considered**

Store this remote in a user table maybe. But it's too early for this.

**Additional context**

**Comment by faboweb** [comment]
@atharva3010 interesting to you?

**Comment by atharva3010** [comment]
Yeah! We can use Vuex-persist

**Comment by faboweb** [comment]
I was aiming at just using localStorage without any plugin for simplicity.
But vuex-persist could also be interesting! Depends if we can filter out security critical information.

**Comment by atharva3010** [comment]
Ah I see! I would be comfortable either way. @faboweb just let me know what would be best suited for this use case.

**Comment by faboweb** [comment]
Might be interesting to replace all our "localStorage" calls with vuex-persist. But I don't know if there are any problems following this like react to existence and non-existence of entries. Are you interested in playing around with it?

**Comment by faboweb** [comment]
Not high priority! :) Good luck with your exams!

**Comment by atharva3010** [comment]
Thank you sir! @faboweb
