### ISSUE TITLE
Changelog file was not removed after update

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3071]
**Describe the bug**

In https://github.com/luniehq/lunie/pull/3066 the changelog file was not removed after the version update. Which would lead to udpates every day.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
i feel like this is fixed - did you fix this @faboweb ?

**Comment by faboweb** [comment]
This is not fixed.
