### ISSUE TITLE
Add previous/next in proposal page to improve proposals navigation

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3074]
**Is your feature request related to a problem? Please describe.**
There is not an intuitive way to navigate throught proposals. 

**Describe the solution you'd like**
Would be useful to add previous/next arrows linked to previous/next proposals in `PageProposal.vue`

**Describe alternatives you've considered**
Actually none.

**Additional context**

Could be something like:

![image](https://user-images.githubusercontent.com/9256178/67962435-61f11d00-fbfd-11e9-88ad-d91f5eadd69a.png)

**Comment by jbibla** [comment]
when we do this, we should add it to the block page as well (in the block explorer)
