### ISSUE TITLE
improve transaction styling

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3078]
**Is your feature request related to a problem? Please describe.**

- the transaction list appears cluttered and at times hard to read (mobile especially, but desktop as well

**Describe the solution you'd like**

- simplify the tx component for all tx types
- simple icon on left (new icons coming)
- type of transaction on left (Send, Withdrawal, Restaked)
- amount on right
- more details dropdown on click or tap

![Screen Shot 2019-11-01 at 12 37 06 PM](https://user-images.githubusercontent.com/6021933/68040276-67ee0900-fca4-11e9-9e4b-daeed356dc1d.png)

**Additional context**

<img width="371" alt="Screen Shot 2019-11-01 at 12 12 49 PM" src="https://user-images.githubusercontent.com/6021933/68038706-f2346e00-fca0-11e9-96e8-76486cc10e74.png">
<img width="369" alt="Screen Shot 2019-11-01 at 12 12 28 PM" src="https://user-images.githubusercontent.com/6021933/68038707-f2346e00-fca0-11e9-84dd-4ef63852b2b5.png">

---
feedback welcome
@faboweb @mariopino @colw @fedekunze

**Comment by mariopino** [comment]
What I like:

- Cleaner design!

I don't like:

- Old COSMOS icon

Thinking about:

- Include "From xxx (sender)" in received transaction
- Include "To yyy (destination)" in the case of sent transaction and
- Include "To zzz (validator)" in staking and restaking transactions.

What do you think?

**Comment by fedekunze** [comment]
The date is duplicated, you can just leave the time

**Comment by colw** [comment]
We could use the validator icons?

**Comment by faboweb** [comment]
> We could use the validator icons?

not a bad idea!

**Comment by jbibla** [comment]
yeah - really nice idea. what would you propose for the non-validator txs?

**Comment by colw** [comment]
> yeah - really nice idea. what would you propose for the non-validator txs?

We could do gravatars? Or find away to mix icons and addresses.

**Comment by mariopino** [comment]
TODO: Simplify TransactionMetadata component to accept one prop (tx), I think does not make sense to assign the tx properties individually, that way we can work with properties that maybe not defined, like `liquidDate`.
