### ISSUE TITLE
deposit improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3079]
https://app.lunie.io/proposals/18

- `Voting Start Date - December 31st 0000`, 18:42 is not correct
- this page should show when the deposit period is over

- ~"address you are trying to send to is not in the extension"~
- ~not spaced properly in the modal - too close to the steps~
- ~the error message should include an action (add it to the extension or choose another signing option)~
- ~this is not a send tx~

![Screen Shot 2019-11-01 at 12 45 09 PM](https://user-images.githubusercontent.com/6021933/68040810-7557c300-fca5-11e9-9e75-a5247ffd2164.png)

**Comment by mariopino** [comment]
Hey @jbibla, can you provide other example? https://app.lunie.io/proposals/18 does not exist now.

Meanwhile I will try to test it creating a proposal in a local testnet.

**Comment by jbibla** [comment]
yep, has to be on the testnet - no proposals in deposit period on mainnet right now.

**Comment by mariopino** [comment]
COSMOS RPC  query:

`https://stargate.cosmos.network/gov/proposals/20`

Response:

```
{
  "proposal_content": {
    "type": "gov/TextProposal",
    "value": {
      "title": "Lunie.io on iOS and Android 📱🔥🚀",
      "description": "Lunie Mobile now available in app stores near you!\n\n📲 iOS - http://bit.ly/lunie-ios\n📲 Android - http://bit.ly/lunie-android\n\n❣️This proposal was sent from the Lunie iOS app 😏"
    }
  },
  "proposal_id": "20",
  "proposal_status": "DepositPeriod",
  "final_tally_result": {
    "yes": "0",
    "abstain": "0",
    "no": "0",
    "no_with_veto": "0"
  },
  "submit_time": "2019-12-09T21:52:09.425216498Z",
  "deposit_end_time": "2019-12-23T21:52:09.425216498Z",
  "total_deposit": [
    {
      "denom": "uatom",
      "amount": "2"
    }
  ],
  "voting_start_time": "0001-01-01T00:00:00Z",
  "voting_end_time": "0001-01-01T00:00:00Z"
}
```

**Comment by mariopino** [comment]
GraphQL query:

```
{
  proposal(networkId: "cosmos-hub-mainnet", id: 20) {
  	id
    type
    title
    description
    creationTime
    status
    statusBeginTime
    statusEndTime
    tally {
      yes
      no
      veto
      abstain
      total
      totalVotedPercentage
    }
    deposit
    proposer,
    validator {
      name
    }
  }
}
```

Response:

```
{
  "data": {
    "proposal": {
      "id": 20,
      "type": "gov/TextProposal",
      "title": "Lunie.io on iOS and Android 📱🔥🚀",
      "description": "Lunie Mobile now available in app stores near you!\n\n📲 iOS - http://bit.ly/lunie-ios\n📲 Android - http://bit.ly/lunie-android\n\n❣️This proposal was sent from the Lunie iOS app 😏",
      "creationTime": "2019-12-09T21:52:09.425216498Z",
      "status": "DepositPeriod",
      "statusBeginTime": "2019-12-09T21:52:09.425216498Z",
      "statusEndTime": "0001-01-01T00:00:00Z",
      "tally": {
        "yes": "0.000000",
        "no": "0.000000",
        "veto": "0.000000",
        "abstain": "0.000000",
        "total": "0.000000",
        "totalVotedPercentage": 0
      },
      "deposit": "0.000002",
      "proposer": "cosmos1fxgsw7an2g4de2k8pgwjgqrqtgyt2ju9uqv5l6",
      "validator": null
    }
  }
}
```

**Comment by mariopino** [comment]
> * `Voting Start Date - December 31st 0000`, 18:42 is not correct

Actually we are not showing voting start date for proposals in deposit period.

> * this page should show when the deposit period is over

Fixed.

> * "address you are trying to send to is not in the extension"

I can't see this message even signin with an account in explore mode that it's different that the one I'm using in the extension.

> * this is not a send tx

What do you mean here?

**Comment by jbibla** [comment]
i crossed off a few items - don't worry about them for now. i think you've addressed the bugs that needed to be fixed 💪
