### ISSUE TITLE
Cache build files

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3086]
**Is your feature request related to a problem? Please describe.**

In CI for e2e tests, the app is rebuild on every new iteration even if only configs or tests have been changed. That is not necessary.

**Describe the solution you'd like**

Use https://www.npmjs.com/package/folder-hash to the source folder and has this plus the hash of the config.js file plus the package.json hash to cache the dist folder.
If so, skip building. Don't know how that works though.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
@iambeone looping you in for context.
