### ISSUE TITLE
withdrawing rewards doesn't update available balance until refresh

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3095]
😞

**Comment by faboweb** [comment]
Maybe dupe of #3183

**Comment by faboweb** [comment]
works for me in prodcution

**Comment by jbibla** [comment]
does not work for me in production or on mobile

**Comment by faboweb** [comment]
just tested again...

**Comment by faboweb** [comment]
hard referesh?

**Comment by jbibla** [comment]
ok i believe you

**Comment by faboweb** [comment]
@jbibla can you recheck? I just tested again and it works...
