### ISSUE TITLE
unstaking and clicking redelegation sets the to and from fields incorrectly

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3096]
if i go to unstake from a validator, but i click the redelegate button - the "to" field becomes the validator i was intending to unstake from. this should be the opposite. 

ideally, i'd propose we just use dropdowns for both "to" and "from" on the redelegation modal.

as well, maybe we should just put dropdowns for "to" and "from" for all staking modals.

**Comment by Bitcoinera** [comment]
Can you please add a screenshot of this? I only see redelegate as a highlighted word when I click "Undelegate". Like this:

![image](https://user-images.githubusercontent.com/40721795/69056719-d951e980-0a10-11ea-9c98-d8353853db67.png)

**Comment by jbibla** [comment]
yep! if you click the link you'll see the redelegation modal! 

there a bunch of issues with this flow:
- redelegation is kind of hidden (only shows a link to it from "undelegation")
- maybe this separate modal is unnecessary - the "job to be done" is always going to be delegate or undelegate - redelegation is just a means to an end. we could integrate this concept into the "delegation" and "undelegation" modal

i think a good quick solution would be to:
- make sure that the "from" field defaults to correct validator
- make both "to" and "from" fields selecetable dropdowns
