### ISSUE TITLE
Switching networks leaves data behind

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3129]
**Describe the bug**

switching between networks leaves some data behind (testnet proposals appear in mainnet proposal list)

**To Reproduce**

Reporter was @jbibla 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment]
Closed as cannot reproduce and the API returns correct proposals for network.
