### ISSUE TITLE
loading screen appears when using search bar

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3131]
**Describe the bug**

loading screen appears when using search bar but underneath results - this is probably not intended

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by mariopino** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/9256178/69041846-7fd9c280-09f0-11ea-9a53-436d77e87ed9.png)
