### ISSUE TITLE
Loader on Proposals Page missing

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3132]
**Describe the bug**

There is no loader on the proposals page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment]
Fixed in #3141
