### ISSUE TITLE
Loader on Networks Page missing

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3133]
**Describe the bug**

networks page needs a loader

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment]
Yes, true. Let's also think about different ways to show "loading". There might be alternative visual cues that "feel faster". Blank rows etc. Can put in our simple loader for now though.

**Comment by faboweb** [comment]
let's put our simple loader until we have something more sophisticated

**Comment by jbibla** [comment]
we have a few things for loading here: https://drive.google.com/drive/folders/1DgiPjy41j7eMIO3fAZvKRX-YxxfTW-6y

i can make modifications for the networks page - but i agree - simple loader for now!
