### ISSUE TITLE
mobile: handle no internet connection in mobile app

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3139]
**Is your feature request related to a problem? Please describe.**

- if there is a bad connection or no connection in the app it can be very frustrating.

**Describe the solution you'd like**

- we should display a message that explains this so the user understands what's wrong.

**Describe alternatives you've considered**

- not sure what the best practice is for this but i would be open to suggestions.

**Additional context**

**Comment by faboweb** [comment]
we should make this universal so also display a maintenance bar on desktop saying: "no internet connection". How this is triggered can be different on desktop and mobile.

Capacitor: https://akhromieiev.com/tutorials/network-detection-capacitor/
Web: https://davidwalsh.name/detecting-online

Maybe just the web thing is already enough and I would implement that one first.

**Comment by jbibla** [comment]
true! good idea!

**Comment by jbibla** [comment]
go away stalebot

**Comment by jbibla** [comment]
go away stalebot
