### ISSUE TITLE
Mobile app: Portfolio page does not fit in screen when there is no validadors

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3144]
**Describe the bug**

Portfolio page does not fit in screen when there is no validadors in mobile app.

**To Reproduce**

1. Open mobile app
2. Go to Portfolio

**Expected behavior**

We should avoid scrolling when possible.

**Screenshots**

![image](https://user-images.githubusercontent.com/9256178/68934358-dc41a580-0796-11ea-8e4a-2bc0521d1454.png)

**Smartphone (please complete the following information):**
 - Device: Android Studio emulator

**Additional context**

Possible options to reduce the message height in mobile:

- Remove unsatisfied icon.
- Reduce message title font size.
- Reduce top margin from 2rem to 1rem.

**Comment by jbibla** [comment]
yeah we can address this but i wouldn't consider this high priority. 

- i believe we have a better graphic to use for this page
- i would hide the "available ATOM" when the total is 0
- soon we can have a button or link to tell people how to get ATOMs

**Comment by mariopino** [comment]
Like that! Let me know when will be ready to implement it.
