### ISSUE TITLE
Voting period doesn't seem to be correct

### ISSUE THREAD

**Issue by azulmarino** [luniehq/lunie#3145]
**Describe the bug**

Voting period seems to be incorrect
End date is wrong.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by azulmarino** [comment]
If not incorrect and looking at Mintscan it is why can we still vote via UI ?

**Comment by faboweb** [comment]
Good catch and thanks for sharing! We did some major changes just now and this might have slipped through the cracks, I will investigate as soon as possible!

**Comment by Bitcoinera** [comment]
I think I just fixed this. Sent my PR :wink:
