### ISSUE TITLE
Insecure mode bug

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3146]
**Describe the bug**
Setting environment `MOBILE_APP=true` or passing the url param `?insecure=true` should set session.insecureMode to true, but it doesn't.

**To Reproduce**

1. Execute `yarn serve:mobile`
2. Open Lunie in the browser
3. Go to Sign In
4. Go to Create a new address
5. Insecure warn is showed

**Expected behavior**
You should be able to create a new address without the warn.

**Comment by jbibla** [comment]
`MOBILE_APP=true` should not impact insecure mode
