### ISSUE TITLE
Adapt cookie warn for mobile app

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3148]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but would be nice to adapt the cookie warn message to the mobile app.

**Describe the solution you'd like**
My proposal is to replace the text:

This site uses cookies to help improve your experience. By using Lunie, you accept our Terms of Service and Privacy Policy .

By:

By using Lunie, you accept our Terms of Service and Privacy Policy .

**Describe alternatives you've considered**
None

**Comment by faboweb** [comment]
Or we don't show the warning at all. Is it necessary to show in apps?

**Comment by mariopino** [comment]
> Or we don't show the warning at all. Is it necessary to show in apps?

Not really, It's a legal issue only. That would be easier to implement.

**Comment by jbibla** [comment]
let's not display it in mobile. (only in the apps - keep it in mobile browsers)
