### ISSUE TITLE
Add support for multisend transactions in transactions list

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3161]
**Is your feature request related to a problem? Please describe.**

Currently we don't have support for multisend transactions. The first step should be to show them correctly in transactions list.

**Describe the solution you'd like**

Display correct information about multisend transactions in transactions list.

**Describe alternatives you've considered**

None

**Additional context**

Currently we display multisend transaction as follow:

![image](https://user-images.githubusercontent.com/9256178/69045905-1fe71a00-09f8-11ea-9df2-75c99a25eba3.png)

**Testing:**

1. Sign in in explore mode with address `cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz`.
2. Go to transactions

**Comment by jbibla** [comment]
yep! nice one!

**Comment by mariopino** [comment]
This is already done is a basic way:

![image](https://user-images.githubusercontent.com/9256178/70617917-e9c14280-1c11-11ea-9075-d86a0015ab9b.png)

Should we close this issue and wait for a transaction refactor?

**Comment by jbibla** [comment]
this is an improvement but would be nice to have the UI display them together some how. 

let's just leave open for now - but doesn't need to be implemented right now.
