### ISSUE TITLE
Add close button to mobile menu

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3162]
**Describe the bug**

Currently a user can only close the mobile menu by clicking on a list item. Which he might not want. So let's add the close button to the mobile menu as well.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
this used to be there - with the lunie logo. somehow it disappeared.

**Comment by Bitcoinera** [comment]
If you look at my PR #3128 you will see the fix is just one line of code. A "position:fixed" line of CSS in the AppMenu.vue is the one causing this.
