### ISSUE TITLE
balance is not updating per block

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3183]
**Describe the bug**

- waiting to receive atoms in the mobile app but i had to restart the app for my balance to appear

**Comment by jbibla** [comment]
also: existing account is not an option on existing sesssion screen!

**Comment by faboweb** [comment]
This could be the problem: https://monitoring.lunie.io:9000/lunie/frontend/issues/36

**Comment by faboweb** [comment]
works for me in production

**Comment by jbibla** [comment]
does not work for me in production or on mobile

**Comment by Bitcoinera** [comment]
I just tried it in production and it worked like a charm. I'm on Android 6. 
How can I possibly try it on iOS, can you recommend me any emulator?

Unfortunately noone owns an iPhone here at home.
