### ISSUE TITLE
Handle no connection to backend

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3208]
**Is your feature request related to a problem? Please describe.**

If the backend is down Lunie will be blank. We should show a full page warning to advise the user.
We could poll slowly until the backend is up again.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
we have the same problem when there is no internet.

**Comment by atharva3010** [comment]
@faboweb is this issue still relevant? 

I think that if we periodically perform a gateway check (`GET /`), we can eliminate both the issues pointed out here. I am thinking from a broad perspective, not sure if this works for your use case.

Would love to hear what you think!

**Comment by jbibla** [comment]
this sounds more or less like the solution we need. there may be a check-in place already in `connection.js` but we are not triggering the "offline error page" yet.

**Comment by atharva3010** [comment]
I see, let me look into it.

**Comment by atharva3010** [comment]
From what I see, there is no gateway check specifically in the `connection.js`.

**Comment by jbibla** [comment]
yep. you're right.

this is still a relevant issue for us.

we want to let users know two things:
1. when there is no internet connection
2. if the API is down.

probably, we will want to use our full-screen error message. 

@faboweb can you weigh in?

**Comment by atharva3010** [comment]
@jbibla 
Since I don't have access to backend, I see this whenever I run lunie locally.
![image](https://user-images.githubusercontent.com/34229217/73608105-943b5d80-45e4-11ea-9ae9-e08671749126.png)

Have you or @faboweb have fixed this issue?

**Comment by faboweb** [comment]
This only works on the initial connection right? If you load the app ad then switch to offline mode in dev tools, nothing shows.

Instead of polling I found (but didn't work with this yet) https://www.w3schools.com/jsref/event_onoffline.asp Which should be a more native variation.

**Comment by atharva3010** [comment]
@faboweb I cannot say if the solution which is already present works only on initial load since I don’t have a connection to the backend to confirm that.

The solution which you are suggesting is, sadly, not supported on most browsers.

If the server doesn’t mind many pending requests, I would suggest long polling https://javascript.info/long-polling

**Comment by jbibla** [comment]
you can use our API as an environment variable: https://staging-api.lunie.io

**Comment by faboweb** [comment]
> The solution which you are suggesting is, sadly, not supported on most browsers.

ups, your right!

**Comment by faboweb** [comment]
We use websocket connections with the API anyway. How about leveraging these for connection statuses? Like here: https://stackoverflow.com/a/50893219

**Comment by atharva3010** [comment]
Websockets can be used, that would be the best approach to do so. I will look into the solution you have pointed to.
