### ISSUE TITLE
Prefetch validators for selected network

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3210]
**Is your feature request related to a problem? Please describe.**

Loading validators is slow sometimes. We could use a trick to improve the perceived speed:
We can preload the validators already when the user selecting the network on when he lands on the portfolio page.

**Describe the solution you'd like**

Prefetch the validators for the current network (after having loaded all other current view related data).

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
nice idea. but why is it slow? it should only be like 10 at a time, right?

**Comment by faboweb** [comment]
Good question. But it is slow. In theory they should be in memory in the API and be served in chunks. I don't think they are served in chunks though. @colw ?

**Comment by colw** [comment]
We only render 10 at a time. All are loaded right now. There are a few optimisations we could make, like stated above 👍
