### ISSUE TITLE
add network title to urls in lunie

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3213]
**Is your feature request related to a problem? Please describe.**

as we add more networks and links continue to be shared, we have to make sure they can resolve correctly. currently, there is no way to share a link for a specific network. if you share a proposal for example, but you have a different network selected it will just say "no data available". 

**Describe the solution you'd like**

let's add the network to the url for all supported networks
```
app.lunie.io/cosmos-hub/portfolio
app.lunie.io/cosmos-hub/validators
app.lunie.io/cosmos-hub/proposals/14
app.lunie.io/cosmos-hub (network page)
```

**Comment by faboweb** [comment]
Thought: we also want to give a short url to validators in the future. Validators exist cross network so prefixing them with a chain name doesn't work.
Proposal: if a short url like app.lunie.io/cosmos-hub-mainnet is called the slug is analyzed and then checks if this is a network name or validator id, forwarding to the validators profile in case.
So: this is not a problem for this implementation.

**Comment by jbibla** [comment]
good thought. i think what you're describing is a different feature.

> Validators exist cross network so prefixing them with a chain name doesn't work.

right now, profiles aren't "cross network" they will display data per network - so i think this should still be implemented as described.

**Comment by faboweb** [comment]
Which I shared was just trying to access future scenarios and how they fit with this strategy

**Comment by jbibla** [comment]
go away stalebot
