### ISSUE TITLE
For Lunie-1.0.0-beta.106 the connection with nodes is broken.

### ISSUE THREAD

**Issue by apatifirstblood** [luniehq/lunie#3217]
![lunie err](https://user-images.githubusercontent.com/55091954/69811429-0d4cbc00-1214-11ea-8805-6f63158b9678.png)

**Comment by coderasha** [comment]
Earlier it was connecting fine.Might be there was connection to Gai Testnet which was running locally or on Docker Container.Don't know the reason but the connection is broken. So can Lunie team look into this.?

**Comment by faboweb** [comment]
Hey! You are working with an old version which we are not supporting anymore.
What do you want Lunie to connect to? Your chain?
