### ISSUE TITLE
portfolio page should load more gracefully

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3225]
**Is your feature request related to a problem? Please describe.**

the portfolio page in the web and on mobile loads too slowly. in addition to this, we load an empty portfolio first, instead of a loading screen.

**Describe the solution you'd like**

- the user should never see the empty portfolio screen if the they have a balance, rewards, and a portfolio of validators
- the page should also load faster

**Describe alternatives you've considered**

- we have a placeholder graphic we could use here

**Additional context**

- the way this works now causes anxiety and confusion. it would be better for the user to be annoyed by a loading graphic than worried about their balance or portfolio if that needs to be the first step.

**Comment by faboweb** [comment]
Annoys me frequently. Easy to fix. Just use the TmPage properly :D

**Comment by mariopino** [comment]
Another upvote here! (more than 10 seconds to show the data with certain addresses ).

**Comment by jbibla** [comment]
> more than 10 seconds to show the data with certain addresses

@iambeone will solve all our performance problems 😆
