### ISSUE TITLE
Strange jumps of the size on mouseover on addresses on login with extension

### ISSUE THREAD

**Issue by iambeone** [luniehq/lunie#3242]
![chrome-capture](https://user-images.githubusercontent.com/9531274/70050297-6c357b00-15f0-11ea-9749-fcc32cf7486b.gif)
On this page http://localhost:9080/extension when there are two or more addresses moving the mouse over addresses affect block size, so it triggers scrolls

**Comment by jbibla** [comment]
i can't replicate this on a mac with chrome. 

what OS and browser @iambeone?
