### ISSUE TITLE
Cannot swipe left to go back

### ISSUE THREAD

**Issue by colw** [luniehq/lunie#3257]
**Describe the bug**

It is standard iOS behaviour to go back to the previous screen when swiping from the left of the screen.

Note: This should be enabled only from sub views (i.e. a validator view) to a main view (validator list). Not from Proposals back to Validator list.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS (possible Android)
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: ios
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Is this a bug or a feature?

**Comment by jbibla** [comment]
good question. this is feature, technically.
