### ISSUE TITLE
Tap address to copy is unclear

### ISSUE THREAD

**Issue by colw** [luniehq/lunie#3258]
**Describe the bug**

Tapping an address displays the little green tick, but no indication what has happened. It's not clear the address has been copied to the clipboard.

![9F4A0767-3757-4C45-914D-EB4ECC83433C](https://user-images.githubusercontent.com/360865/70308409-7bdcdb80-180b-11ea-85ee-4677299d3fb0.png)

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS (possible Android)
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: ios
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
maybe add a notification "copied address"

**Comment by jbibla** [comment]
we have this, but it's hidden on mobile i believe
