### ISSUE TITLE
Handling blocks of networks which haven't yet the feature activity implemented

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3282]
**Describe the bug**

You can see the blocks of networks which don't have yet the `activity` feature enabled. They look like empty, with no Chain ID.

**To Reproduce**

Connect to Livepeer ( which hasn't `activity` yet implemented) and click on the block on the bottom (`TmConnectedNetwork`). You will see this 'fake' empty block.

**Expected behavior**

I think the ideal would be to have here the same modal of `Feature not yet available`.

**Screenshots**

The fake empty block:

![image](https://user-images.githubusercontent.com/40721795/70558092-7e7d5f00-1b84-11ea-8ed3-91c1dfde047c.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
good catch. 

my idea would be to use a feature flag for it. if "block" is disabled, anywhere we show the block number should appear as plain text, not a link.

if enabled, they should be links. 

but this is just one idea - there may be better ways to deal with this!

**Comment by Bitcoinera** [comment]
> my idea would be to use a feature flag for it. if "block" is disabled, anywhere we show the block number should appear as plain text, not a link.
> 
> if enabled, they should be links.
> 
> but this is just one idea - there may be better ways to deal with this!
> 
> maybe the simplest thing to do is to show the "feature not available" screen for now.

I just realized we already have a feature flag for this :sweat_smile: It is called `feature_explorer`.

Yes, I know, quite confusing with the other one called `feature_explore` (which should be `feature_portfolio`), but this is working fine already. I just checked.

**Comment by Bitcoinera** [comment]
OK, handled in https://github.com/luniehq/lunie/pull/3411
