### ISSUE TITLE
Waiting for extension button doing weird things

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3306]
**Describe the bug**

Sometimes, when the Delegation modal grows in height to cover the whole screen, the `Waiting for extension` button will behave strangely, the fonts shifting to the right and the button itself staying on its correct position. 

**To Reproduce**

Just initiate a delegation and play with the screen size until you see this happening.

**Expected behavior**

The text should stay centered within the button
**Screenshots**

<img width="350px" src="https://user-images.githubusercontent.com/40721795/70861370-47fd6680-1f2d-11ea-8178-cd8402258ad8.png"/>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Brave 
 - Version: v1.1.20, Chromium 79.0.3945.74 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
@Bitcoinera i think it's important to include OS and browser for these types of bugs

**Comment by Bitcoinera** [comment]
Yes, you are right. I will edit now.

**Comment by Bitcoinera** [comment]
This is actually a really simple fix, just with `media query` and padding

**Comment by jbibla** [comment]
the fix is probably to change the button `width` to `min-width` - just guessing.

**Comment by Bitcoinera** [comment]
> the fix is probably to change the button `width` to `min-width` - just guessing.

Yes, you were right. `min-width` did the trick: https://github.com/luniehq/lunie/pull/3413
