### ISSUE TITLE
Withdraw staking rewards does not work if user has delegated to more then 5 validators.

### ISSUE THREAD

**Issue by pimato** [luniehq/lunie#3308]
**Describe the bug**
 I am using a Ledger Nano S and I have issues withdrawing my staking rewards. I have another Ledger Nano S with less then 5 validators delegating where I have no issues at all. It seems like if user has more then 5 delegations to different validators, withdrawing staking rewards is not working. Lunie lets you sign on your hardware wallet and it looks like the transaction got broadcasted but checking mintscan.io indicates that nothing happend. 

**To Reproduce**
1. Go to Lunie.io and pick Ledger Nano S to connect
2. Click on Portfolio
3. Click on Claim Rewards
4. Click Next on the "Claim Rewards"-Screen
5. Click Next
6. Click "Send"
7. Sign transaction on Ledger Nano S
8. Sent and confirming is showing
9. Error: Nothing happens and no transaction is beeing broadcasted.

**Expected behavior**
Withdrawing my rewards 

**Desktop (please complete the following information):**
 - OS: macOs 10.14.2 (18C54)
 - Browser: Brave
 - Version: Version 1.0.1 Chromium: 78.0.3904.108 (Offizieller Build) (64-Bit)

**Comment by faboweb** [comment]
Hey Tommy! Thanks for sharing this bug report! I will check it out asap.

**Comment by jbibla** [comment]
we've been investigating this issue closely. still trying to find a solution.

**Comment by faboweb** [comment]
A fix is available and will be released soon. You can preview it with this link: https://app.lunie.io/?graphql=https://staging-api.lunie.io

**Comment by jbibla** [comment]
@pimato we pushed a fix that solved this issue for some users. could you hard refresh and try again?

**Comment by pimato** [comment]
@jbibla @faboweb works! Thanks for the support and the new update!
