### ISSUE TITLE
Delegating failed: Signing failed: Ledger Native Error: Bad key handle : JSON Missing sequence.

### ISSUE THREAD

**Issue by nylira** [luniehq/lunie#3309]
**Describe the bug**
I can't stake from my Ledge Nano S.

**To Reproduce**
1. Go to a validator from your Portfolio page
2. Click on Stake and then enter in a number of ATOM
3. Click Next three times

**Expected behavior**
It should allow me to sign the staking tx from my ledger.

**Screenshots**
![image](https://user-images.githubusercontent.com/172531/70863756-7a9d6400-1f19-11ea-8036-4028dd4b1ba1.png)

**Desktop (please complete the following information):**

 - OS: macOS 10.15.1 (19B2106)
 - Browser: Brave
 - Version: Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)

**Comment by nylira** [comment]
The command line function works fine with my Ledger btw. This command:

```
gaiacli tx staking delegate $VALADDR 1000000uatom --from $MYKEY
```

**Comment by faboweb** [comment]
Hey Peng! Appreciate you sharing this issue! I will check it out asap.

**Comment by faboweb** [comment]
This was an issue with the vesting accounts. This is fixed on staging and will be deployed soon.
