### ISSUE TITLE
keep session per network instead of signing users out when switching networks

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3314]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
I see this tightly related to https://github.com/luniehq/lunie/issues/3200
It is about the same, changing the way we store the sessions to do it by network.

Good point. By implementing sessions this way we don't need to sign users out anymore :+1:

**Comment by jbibla** [comment]
ok nice! didn't see that one! 

yep, very closely related. 

though, i think it's important to show all the previously used addresses - when you select the regen one or cosmos one it should change networks for the user 😄

**Comment by faboweb** [comment]
> It is about the same, changing the way we store the sessions to do it by network.

I don't agree. They need to be stored separately right? All sessions (even per network) and the session that you are signed in with per network.

**Comment by Bitcoinera** [comment]
> > It is about the same, changing the way we store the sessions to do it by network.
> 
> Hmmm. Have you considered, that they need to be stored separately? All sessions (even per network) and the session that you are signed in with per network.

:thinking: Mmm, and in this PR you took care of the the sessions you are currently signed in, but not the rest?

**Comment by faboweb** [comment]
exactly. we thought we want to keep sessions in general for the (last addresses used). not per network.

**Comment by faboweb** [comment]
we still need to switch networks based on these addresses though.
