### ISSUE TITLE
Validator logo for #Dawns.world displays as broken link

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3324]
**Describe the bug**

There is a rogue validator in `cosmos-mainnet` whose logo is being displayes as a broken link instead of a identicon.
It happens both in `TableValidators` and in `PageValidator`.

Also in production! :scream: 

**To Reproduce**

Just go to the validators list for `cosmos-hub-3` and search for "#Dawns.world"

**Expected behavior**

**Screenshots**

<img width="370px" src="https://user-images.githubusercontent.com/40721795/71028269-45596780-210d-11ea-8a19-2280d1206f1e.png" />

<img width="310px" src="https://user-images.githubusercontent.com/40721795/71028276-47bbc180-210d-11ea-82c9-08ff447e8516.png" />

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Brave
 - Version: v1.1.20, Chromium 79.0.3945.74 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Somehow `picture` is the string `undefined` for this validator. I have the feeling we should do a cleanup in the API
