### ISSUE TITLE
Handle "transitive" redelegations

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3325]
**Describe the bug**

We don't currently handle "transitive" redelegations.

For example, if delegator D redelegates to validator X and then wants to further redelegate from X to another validator Y. Delegator D would have to wait the full UnbondingPeriod period to do this.

That redelegation constraint can cause a redelegation tx to fail silently, I mean you follow the entire redelegation flow and the tx is signed and broadcasted but it never will be confirmed.

**To Reproduce**

1. Open Lunie and sign in
2. Go to Portfolio
3. Click on a validator X you have a delegation.
4. Click on Unstake button.
5. Redelegate to another validator Y
6. Wait until transaction is confirmed
7. Go to Portfolio and click on validator Y.
8. Redelegate to another validator Z.
9. The transaction is never confirmed.

**Expected behavior**

We should warn user about these constraints, maybe disabling redelegation in the case of such as an existent constraint in effect and displaying the related information (i.e user needs to wait a full `UnbondingPeriod` to make a new redelegation) in some way.

**Additional context**

Related doc: https://blog.cosmos.network/re-delegations-in-the-cosmos-hub-7d2f5ea59f56

**Comment by faboweb** [comment]
Very good thinking.

We should also add a warning about the max undelegations (when the user has 5 or more)

**Comment by jbibla** [comment]
> Would be great to find a way to standardize handling these warnings.what do you mean by standardize? 

can you say more about this? what do you mean?

> they are edge cases in Cosmos alone.

i expect a lot of networks to have strange rules we'll have to account for
