### ISSUE TITLE
intercom is not working in mobile

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3326]
intercom has a whitelist and the URL gets obscured in the native apps so they cannot be whitelisted. i have contacted support and they recommended the intercom / ionic docs.

there is a way to install intercom for mobile apps with ionic that should be researched.

**Comment by faboweb** [comment]
not working on desktop either

**Comment by mariopino** [comment]
Related information:

https://ionicframework.com/docs/native/intercom

https://developers.intercom.com/installing-intercom/docs/cordova-phonegap-configuration

https://github.com/intercom/intercom-cordova

**Comment by faboweb** [comment]
How do you want to solve this? Maybe good to discuss a plan.

**Comment by mariopino** [comment]
Sure @faboweb! My plan is to integrate `cordova-plugin-intercom` cordova plugin into the ionic app. 

That way we should be able to add a custom launcher when needed using `intercom.displayMessenger();` call.

Another related link, an example cordova app using this:

https://github.com/intercom/intercom-cordova/tree/master/Example

**Comment by faboweb** [comment]
sounds good. let me know when we need to add the environment variables to the build pipeline. I would propose not doing push things for a first version. what do you think?

**Comment by mariopino** [comment]
> sounds good. let me know when we need to add the environment variables to the build pipeline. I would propose not doing push things for a first version. what do you think?

Agree, I'll send you a message before push to discuss the best way to do it

**Comment by mariopino** [comment]
The cordova plugin was giving me an error `ERROR: Could not get unknown property 'cdvCompileSdkVersion' for project ':app' of type org.gradle.api.Project.` and don't want to waste more time on it so I decided to try this capacitor plugin:

https://github.com/stewwan/capacitor-intercom

I have it working in Android, currently attached to portfolio page. 

Some thoughts about it:

* What should be the best intercom userId generation possibility, something like `lunie-android-1234`?
* IOS integration is pending (seems to be straighforward)
* Build environments vars to set api key is pending.
* Best way to only load in mobile.
* Best place to initialize intercom (`initializeApp.js`?)
* I think we should use the same css selector to load intercom either in mobile or desktop.

**Comment by faboweb** [comment]
> What should be the best intercom userId generation possibility, something like lunie-android-1234?

sounds good

> Best way to only load in mobile.

check here: https://github.com/luniehq/lunie/pull/3209/files#diff-1c90ff38a08209f9ebd4d05d1e43358eR53

> Best place to initialize intercom (initializeApp.js?)

sounds good. maybe check for config.isMobile

> I think we should use the same css selector to load intercom either in mobile or desktop.

can it be just the same button?

**Comment by mariopino** [comment]
> can it be just the same button?
Yep, this is what I mean.

**Comment by mariopino** [comment]
> check here: https://github.com/luniehq/lunie/pull/3209/files#diff-1c90ff38a08209f9ebd4d05d1e43358eR53

Perfect, Intercom needs push notifications just like in that pr using `PushNotifications.register()`.

**Comment by faboweb** [comment]
let's leave the push notification out for now?

**Comment by mariopino** [comment]
> let's leave the push notification out for now?

I think not, push notifications are needed by Intercom to receive the responses from the Lunie Team. 

We can enable it in this pr or wait until your pr gets merged. What do you think it's best?

**Comment by faboweb** [comment]
are you certain they don't receive the messages anyway when the app is open?

**Comment by mariopino** [comment]
Not needed, you are right!
