### ISSUE TITLE
validator links 404 from txs in page block

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3328]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by mariopino** [comment]
Bad URL:

`/blocks/staking/validators/cosmosvaloper1648ynlpdw7fqa2axt0w2yp3fk542junl7rsvq6`

Should be:

`/validators/cosmosvaloper1648ynlpdw7fqa2axt0w2yp3fk542junl7rsvq6`
