### ISSUE TITLE
send button is still enabled even when extension is not installed

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3330]
**Describe the bug**

if you select "extension" in an action modal as signing method, the message will ask the user to install the extension. however, the button is still enabled which means it can be "sent" even though this will never work.

**Expected behavior**

button should be disabled OR should be an "install" / "go to chrome store" button

**Comment by mariopino** [comment]
Hi @jbibla, I can't reproduce this on Windows/Chrome/Brave.

At least in my test, Send button is disabled with the message "Waiting for extension".

![image](https://user-images.githubusercontent.com/9256178/72739149-63e6ce80-3ba3-11ea-84b3-a00416bcf5ba.png)

**Comment by jbibla** [comment]
hmm. on mac with brave i can reproduce. 

also, there should be some instructions, no?

**Comment by mariopino** [comment]
I tested with extension disabled and uninstalled, I didn't see any instructions.

**Comment by faboweb** [comment]
I confirm that the Send button is enabled:
![image](https://user-images.githubusercontent.com/5869273/72757158-9e516b00-3ba5-11ea-9f82-acef3c9a438f.png)

**Comment by faboweb** [comment]
Adding: I don't like this step and still propose that we make this step: "To continue please sign in to your address"

**Comment by jbibla** [comment]
> I didn't see any instructions.

yeah this is a related bug. should be resolved.

**Comment by jbibla** [comment]
i'm working on it now.
