### ISSUE TITLE
Add feature-flag for "explore mode"

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3340]

**Comment by jbibla** [comment]
what should happen if this is disabled? do we show a message when you click "sign in"?

**Comment by faboweb** [comment]
when you go to the "Explore with address" page, it should show "feature not available" for now?

**Comment by jbibla** [comment]
sure i guess so. it would be preferred if the message included something about public data being available but account specific is coming soon — or something of that nature.

**Comment by jbibla** [comment]
not relevant right now as we don't have networks with this restriction (livepeer, maybe, in future)
