### ISSUE TITLE
deposit count is incorrect

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3348]
**Describe the bug**

https://app.lunie.io/proposals/21
https://hubble.figment.network/cosmos/chains/cosmoshub-3/governance/proposals/21

**Comment by faboweb** [comment]
server side problem it appears

**Comment by mariopino** [comment]
Hey @jbibla both links are broken now. What's the problem?

**Comment by faboweb** [comment]
Proposal 8 on the gaia testnet has 1 token deposited by me. But it shows 0. Even in the API response:

```
query proposal {
  proposal(networkId: "cosmos-hub-testnet", id: 8) {
    id
    type
    title
    description
    creationTime
    status
    statusBeginTime
    statusEndTime
    tally {
      yes
      no
      veto
      abstain
      total
      totalVotedPercentage
      __typename
    }
    deposit
    proposer
    validator {
      name
      __typename
    }
    __typename
  }
}
```

**Comment by mariopino** [comment]
> Proposal 8 on the gaia testnet has 1 token deposited by me. But it shows 0. Even in the API response:
> 
> ```
> query proposal {
>   proposal(networkId: "cosmos-hub-testnet", id: 8) {
>     id
>     type
>     title
>     description
>     creationTime
>     status
>     statusBeginTime
>     statusEndTime
>     tally {
>       yes
>       no
>       veto
>       abstain
>       total
>       totalVotedPercentage
>       __typename
>     }
>     deposit
>     proposer
>     validator {
>       name
>       __typename
>     }
>     __typename
>   }
> }
> ```

Hey @faboweb, that's helpful thanks! leave it to me ;-)

**Comment by mariopino** [comment]
The proposal returned by https://gaia-13007.lunie.io/gov/proposals

```
  {
    "content": {
      "type": "cosmos-sdk/TextProposal",
      "value": {
        "title": "Testing depositing",
        "description": "Hi from Lunie you wonderful community"
      }
    },
    "id": "8",
    "proposal_status": "VotingPeriod",
    "final_tally_result": {
      "yes": "0",
      "abstain": "0",
      "no": "0",
      "no_with_veto": "0"
    },
    "submit_time": "2020-01-10T18:41:20.16081563Z",
    "deposit_end_time": "2020-01-12T18:41:20.16081563Z",
    "total_deposit": [
      {
        "denom": "umuon",
        "amount": "1000000"
      }
    ],
    "voting_start_time": "2020-01-10T18:41:20.16081563Z",
    "voting_end_time": "2020-01-12T18:41:20.16081563Z"
  }
```

**Comment by mariopino** [comment]
Problem is at `proposalReducer`:

```
deposit: getDeposit(proposal, 'uatom'), // TODO use denom lookup
```

Denom `uatom` is hardcoded, should be `umuon` in this case, causing `getDeposit()` function to return 0.

We can improve that as the comment suggest :-), we can just let `getDeposit()` return the denom (and not pass denom to it as parameter of course).
