### ISSUE TITLE
Investigate MultiSendTransactions: why it only appears one single address both for inputs and outputs

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3360]
**Describe the bug**

We should investigate why, being an array both `inputs` and `outputs`, it appears one single address, or if this happens only for certain cases and in the rest we are ignoring the remaining addresses.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
can you share an example / some more context around this issue?

**Comment by Bitcoinera** [comment]
Sure.

[Here](https://cosmos-hub-3.lunie.io/txs/2362033F723217F142A10BE2920ED5D05B30685C220F369A385E6B0A50AAF3ED) is an example multisend transaction in cosmos-hub-3.

What we need to investigate is if the `inputs` and `outputs` arrays within tx.value.msg[0].value contain always one value or if, in the contrary, sometimes they can contain multiple ones.

This is relevant because currently we are handling them as if they'd always have only one (and therefore might be some valuable data).

![image](https://user-images.githubusercontent.com/40721795/72223600-ec94b780-3570-11ea-909f-854f9190005c.png)

**Comment by Bitcoinera** [comment]
Having a look right at [this particular account's](https://cosmos.bigdipper.live/account/cosmos144fzpepuvdftv4u4r9kq8t35ap2crruv4u3udz) activities, it looks like Multisends are not so multi actually :eyes: It is always one sender and one recipient in all txs.

Really strange. We should ask Bez I think :woman_shrugging:

**Comment by faboweb** [comment]
There is the potential to do multiple inputs and output. This could theoretically be done by the CLI I guess. But no one is actually using that feature apparently. We could wait until a user requests it. What do you think?

**Comment by Bitcoinera** [comment]
> There is the potential to do multiple inputs and output. This could theoretically be done by the CLI I guess. But no one is actually using that feature apparently. We could wait until a user requests it. What do you think?

Yes, we can keep this in the Todo for now. It is not a priority at all. We can leave this issue open as a reminder.

**Comment by Bitcoinera** [comment]
I think we found the first real MultiSendTransactions in Columbus-3. And our Columbus was @iambeone !

https://fcd.terra.dev/txs/B8D6510B9673BAF4F8D8F476568C831C93F33F4F86E5366F74CA365C98ACD28E

<img width="480px" src="https://user-images.githubusercontent.com/40721795/74328992-3b5f8800-4d8f-11ea-874a-df9f47ad3a04.png">

**Comment by Bitcoinera** [comment]
Now we are displaying MultiSend as Unknown transactions. I don't know what is the plan with this transaction type for the future. Maybe we can close this one for now?
