### ISSUE TITLE
How can I contribute to Lunie if there is no backend available

### ISSUE THREAD

**Issue by volkrass** [luniehq/lunie#3361]
I would like to work on Lunie to learn what we can do to improve services for delegators. 
Like described in your README the backend is not public available. Is there a test backend available I can connect to?

**Comment by jbibla** [comment]
Hey there! Thanks for your interest! We will be open-sourcing our backend systems in the new year.

**Comment by volkrass** [comment]
@jibbla, looking forward to contribute to this project. Wish you a happy new year.

**Comment by faboweb** [comment]
@volkrass you can connect to the staging backend by setting an environment variable: `VUE_APP_GRAPHQL_URL=https://staging-api.lunie.io`. This way you can contribute to the Lunie frontend already.

**Comment by jbibla** [comment]
this probably isn't in the readme yet 😄
