### ISSUE TITLE
Transaction shown when claiming rewards from multiple validators shows only the first validator

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3367]
**Describe the bug**

When I as an user claim rewards from multiple validators, when I look at this transaction in the Lunie explorer or in the Activity section, I see only the first validator I claimed from, and not the rest.

It looks as if I had only claimed rewards from that one validator.

**To Reproduce**

Claim rewards from multiple validators and look at the transaction in Lunie.

**Expected behavior**

We should be able to show inside transactions all the validators names we have claimed from.

IMO, we should have an specification where we say "Rewards from Multiple Validators", and only when we click and open that transaction we get to see the names of all the involved validators, to not clutter up the beautiful Transaction UI components we now have.

**Screenshots**

<img width="520px" src="https://user-images.githubusercontent.com/40721795/71730772-54e1eb80-2e43-11ea-8c9e-322a9a820926.png" />

<img width="610px" src="https://user-images.githubusercontent.com/40721795/71730696-2106c600-2e43-11ea-9208-9b1dac103e3f.png" />

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
duplicate of #3244 ?

**Comment by Bitcoinera** [comment]
Oh yes, it looks like it. I will close this one then
