### ISSUE TITLE
Finish "Received" transactions: not present in Activity currently

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3372]
**Is your feature request related to a problem? Please describe.**

Right now there is nowhere the transactions you receive in the Activity section.

**Describe the solution you'd like**

We need to create the components necessary to enable these transactions.
The SVG icon is in place.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
uses "SendMessageDetails" so no new component necessary.

**Comment by mariopino** [comment]
Closed via https://github.com/luniehq/lunie-api/pull/257

**Comment by faboweb** [comment]
The txs also show in the FE?

**Comment by mariopino** [comment]
> The txs also show in the FE?

Yep, I tested!

**Comment by faboweb** [comment]
Awesome
