### ISSUE TITLE
Rewards show more then 6 decimals

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3376]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5869273/71978753-81ef1f00-31f2-11ea-8205-3ecbce5b0410.png)

**To Reproduce**

**Expected behavior**

Should only show 6 decimals.
This should probably be handled in the API.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by mariopino** [comment]
I think in this case api is returning rewards as expected (6 decimal points):

Query:

```
{
  rewards(networkId: "cosmos-hub-mainnet", delegatorAddress: "cosmos16d7lk68ruw5556wumhc3tle9vj333lhzalnfmf") {
		validator {
			operatorAddress
    }
    amount
  }
}
```

Response:

```
{
  "data": {
    "rewards": [
      {
        "validator": {
          "operatorAddress": "cosmosvaloper1qwl879nx9t6kef4supyazayf7vjhennyh568ys"
        },
        "amount": "0.000492"
      },
      {
        "validator": {
          "operatorAddress": "cosmosvaloper15r4tc0m6hc7z8drq3dzlrtcs6rq2q9l2nvwher"
        },
        "amount": "0.000048"
      },
      {
        "validator": {
          "operatorAddress": "cosmosvaloper1k9a0cs97vul8w2vwknlfmpez6prv8klv03lv3d"
        },
        "amount": "0.000079"
      },
      {
        "validator": {
          "operatorAddress": "cosmosvaloper1uutuwrwt3z2a5z8z3uasml3rftlpmu25aga5c6"
        },
        "amount": "0.000052"
      }
    ]
  }
}
```

Problem is in frontend, this code is returning `0,0006709999999999999`:

```
totalRewards() {
      return this.rewards.reduce((sum, { amount }) => sum + Number(amount), 0)
    },
```

So to fix this behaviour we can change it to:

```
    totalRewards() {
      return this.rewards
        .reduce((sum, { amount }) => sum + Number(amount), 0)
        .toFixed(6)
    },
```

Which returns `0,000671` as desired.
