### ISSUE TITLE
Remove ugly "ActionModal" already open window

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3377]
**Is your feature request related to a problem? Please describe.**

When an ActionModal is open and you want to open an ActionModal, there appears an alert, that there is already an ActionModal open. It is butt ugly.

**Describe the solution you'd like**

How about just adding a little shaking animation to the existing ActionModal nudging the user to close that one.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
this feels so so low priority i was happy to see it closed. using a native browser feature for an edge case is totally fine for now!

**Comment by faboweb** [comment]
hurts my eyes every time!
