### ISSUE TITLE
add chain ID to transactions page and include "coming soon" for previous chains

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3387]
**Is your feature request related to a problem? Please describe.**

Users are confused about why their transaction history from hub 1 and 2 is gone. 

**Describe the solution you'd like**

Let's add chain ID above the transactions from hub 3, and add hub 2 and hub 1 as titles with a "coming soon" message including some explanation of why this data isn't there anymore.

**Comment by faboweb** [comment]
dupe? https://github.com/luniehq/lunie/issues/3383

**Comment by jbibla** [comment]
yep
