### ISSUE TITLE
When you sign in with an address, Lunie directly connects you to that address network

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3389]
**Is your feature request related to a problem? Please describe.**

Now (or very very soon) we can sign in with different networks addresses.

Still, when we sign in with an address, if we weren't previously connected to that address network, we get very ugly errors that the user will not even see and it will certainly be utterly confusing for them.

**Describe the solution you'd like**

It is the title of this feature request :smiley_cat: 

**Describe alternatives you've considered**

Warning messages when you are signing in with other networks addresses (which is not even a solution) or, another option would be that you can only sign in with addresses from the network you are currently connected to.

But this last option I don't like as much as the one I propose here, which just makes the UX a breeze. 

**Additional context**

This is what happens now when you sign in with another network address. Not ideal.

<img width="610px" src="https://user-images.githubusercontent.com/40721795/72014700-b4376580-3260-11ea-95e2-a0a706897970.png" >

**Comment by jbibla** [comment]
very important. thanks for flagging. 

to clarify your proposal — when a user signs in with an address, lunie should select the network that address belongs to and select that network for them?

**Comment by Bitcoinera** [comment]
> very important. thanks for flagging.
> 
> to clarify your proposal — when a user signs in with an address, lunie should select the network that address belongs to and select that network for them?

Yes, that's exactly what I am proposing here :ok_hand:

**Comment by faboweb** [comment]
Easiest fix for now is maybe to just only to use the addresses for this network.

**Comment by jbibla** [comment]
alternatively, we could add the network selector component to this screen and display addresses from that network.

whatever is simplest!

**Comment by Bitcoinera** [comment]
> alternatively, we could add the network selector component to this screen and display addresses from that network.
> 
> whatever is simplest!

Too much information for one screen I think.

It looks like we are going for what Fabo proposed: show only addresses of the network you are currently connected to.

**Comment by faboweb** [comment]
This will anyway be rewritten in the new design. Let's go for the simplest thing that works.

**Comment by Bitcoinera** [comment]
> This will anyway be rewritten in the new design. Let's go for the simplest thing that works.

You mean from the UI perspective or how rewritten? The flow is planned to stay the same right?
