### ISSUE TITLE
Remove ugly scrollbars on Windows

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3400]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/5869273/72179010-8bc37e80-33ba-11ea-9b81-e59d82ab2aec.png)

**Describe the solution you'd like**

How about https://github.com/mdbootstrap/perfect-scrollbar ^^

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
i don't know if we need a plugin for this. this scroll bar appeared because of a fix related to the mobile menu scrolling. i suspect a little css tweak will remove the need for this scrollbar on desktop when not necessary / helpful. 

styling it would be nice too - but kind of a separate issue.

**Comment by faboweb** [comment]
Have you considered this scrolling thing happening also on window resizes?
