### ISSUE TITLE
Address prefixes should be received from API

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3402]
**Is your feature request related to a problem? Please describe.**

To be able to scale networks without needing to update the client we should deliver as much data from the API as possible. Currently the bech 32 prefixes for the Ledger handling are in config.js. These should be received from the API (networks query). Same goes for identifying valid addresses in the explore input.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
Actually this is already working xD

I think we just didn't notice... :woman_shrugging: 

<img width="530px" src="https://user-images.githubusercontent.com/40721795/72824338-60bc1300-3c75-11ea-85cf-99b1ad68815a.png">


I guess will need to refactor a couple of things

**Comment by faboweb** [comment]
But this is not used in the FE. We are hardcoding network to prefix lookup rn.

**Comment by Bitcoinera** [comment]
> But this is not used in the FE. We are hardcoding network to prefix lookup rn.

Exactly. Today I am making a PR to refactor this

**Comment by jbibla** [comment]
this is done already?

**Comment by Bitcoinera** [comment]
> this is done already?

Yes, we just need to merge it. It is [here](https://github.com/luniehq/lunie/pull/3456)
