### ISSUE TITLE
Terra transactions only display slide details, but not main container

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3412]
**Describe the bug**

For some reason, in Activity Terra transactions are displayed like empty divs, although there is no error to be seen in the browser console.

Still, the slide metada does work correctly.

![image](https://user-images.githubusercontent.com/40721795/72296338-a5362600-3659-11ea-9dc1-3cd119588667.png)

I presume this has to do with how Terra data structure's a bit different...

**Comment by faboweb** [comment]
The types of terra txs are different so they don't map to our components rn

**Comment by Bitcoinera** [comment]
Also the same goes for e-Money:

<img width="520px" src="https://user-images.githubusercontent.com/40721795/72551477-3218f380-3895-11ea-8edc-d2a8eb625fb0.png">
