### ISSUE TITLE
Support older ledger nano firmware

### ISSUE THREAD

**Issue by hrishikeshio** [luniehq/lunie#3414]
I used ledger nano S and lunie to delegate my atoms.
But now lunie doesn't support my nano as it is older firmware.
I can't upgrade the nano firmware because I dont have the backup of mnemonic.
How can I run an older version of lunie to get back my atoms and transfer them at a safe place, so that I can upgrade my firmware?
Any alternative ideas?

**Comment by faboweb** [comment]
Have you checked out the CLI to transfer your atoms? https://github.com/cosmos/gaia/blob/495feeca8e8ba48bb59c49677ed16d01e16e61e3/docs/delegators/delegator-guide-cli.md

**Comment by hrishikeshio** [comment]
I tried the latest cli. but it also needs updated firmware.
v1.0.0 works to sign the tx. but it gives error "insufficient funds"
