### ISSUE TITLE
Finish tutorials

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3432]
**Is your feature request related to a problem? Please describe.**

We need to:

* Reduce dimensions of the component to half of their size (follow Zeplin measures)
* Add content
* Discuss how to trigger tutorials (i.e if balance in mainnet = 0 then show "how to get mainnet tokens?" tutorial with instructions to buy tokens from a exchange, if we are on testnet and balance = 0 then show "how to get tokens?" tutorial with instructions to get tokens from a faucet.
* Do we need to store read/closed tutorials in a cookie? That way we can avoid anoying our users.
* Do we need to emit Google Analytics events for tutorials (started, finished, closed)?

**Comment by faboweb** [comment]
> Discuss how to trigger tutorials (i.e if balance in mainnet = 0 then show "how to get mainnet tokens?" tutorial with instructions to buy tokens from a exchange, if we are on testnet and balance = 0 then show "how to get tokens?" tutorial with instructions to get tokens from a faucet.

yep. check with Charlie on that maybe

> Do we need to store read/closed tutorials in a cookie? That way we can avoid anoying our users.

hmm no, the user should always be able to trigger the tutorials. they are not opened automatically

> Do we need to emit Google Analytics events for tutorials (started, finished, closed)?

that's a great idea

**Comment by jbibla** [comment]
regarding triggers:

- should only pop up when the user clicks a button or link
- this first version will only be for Cosmos

- keys: on create screen
- tokens: on portfolio page in balance header
- governance: on proposals page and deposit / vote action modal
- staking: on validator profile page and staking, unstaking action modal

**Comment by mariopino** [comment]
> * **keys**: on create screen

You mean here?

![image](https://user-images.githubusercontent.com/9256178/72905591-1009f000-3d31-11ea-9325-a21462af0223.png)

We can use a text link here. BTW the text should be updated.

> * **tokens**: on portfolio page in balance header

We can use a button with `How to get tokens?` text.

> * **governance**: on proposals page and deposit / vote action modal

On proposal page we can use a button next to Create proposal with the text `How Cosmos Governance Works`.

What do you propose to use on modals? I think it's enough to show it only on the proposals page.

> * **staking**: on validator profile page and staking, unstaking action modal

Same here, I think it's enough to show it only on the validator profile page.

**Comment by mariopino** [comment]
This is done! https://deploy-preview-3453--lunieio.netlify.com/portfolio?experimental=true
