### ISSUE TITLE
address filter in extension sign in step

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3446]
Note: The filter needs to be also applied for the extension sign in step.

_Originally posted by @faboweb in https://github.com/luniehq/lunie/pull/3438#issuecomment-576421524_

**Comment by Bitcoinera** [comment]
I would like to know what the steps are to apply modifications in a submodule (in this case, the "lunie" submodule inside lunie-browser-extension)

**Comment by jbibla** [comment]
the submodule can just be your lunie repo. then you can make changes there without any trouble and with livereload.

**Comment by Bitcoinera** [comment]
> the submodule can just be your lunie repo. then you can make changes there without any trouble and with livereload.

Thank you so much for your explanation. 

This evening I was playing around with it and getting the grip of it all. Also changing commits in the submodule. [This SO thread](https://stackoverflow.com/questions/25240634/how-to-change-head-of-git-submodule) helped too.

**Comment by jbibla** [comment]
this is one of the reasons we want to move towards a monorepo 😄
