### ISSUE TITLE
insufficient funds to pay for fees with Ledger

### ISSUE THREAD

**Issue by NodeGuy** [luniehq/lunie#3461]
Hi guys, I like the new name.  ;-)

**Describe the bug**

My attempts to send ATOMs is failing with the error message `Sending tokens failed: Broadcast was not successful: insufficient funds to pay for fees; < 13750uatom.`

**To Reproduce**

1.  Click `Send`.
2.  Enter address and memo.
3.  Enter 1 ATOM in the Amount field.
4.  Click `Next`.
5.  See confirmation modal with incorrect Total amount:

<img width="575" alt="Screen Shot 2020-01-23 at 2 32 29 PM" src="https://user-images.githubusercontent.com/2148537/73019448-96860680-3df1-11ea-8f31-046f4062ce5a.png">

6.  Click `Next` and sign transaction on Ledger.
7.  See error message:

<img width="586" alt="Screen Shot 2020-01-23 at 2 36 45 PM" src="https://user-images.githubusercontent.com/2148537/73019510-b5849880-3df1-11ea-9d7d-fe7df4de6485.png">

Attempting to send 2 ATOMs fails with the same error message, though the Total amount is correct in this case:

<img width="577" alt="Screen Shot 2020-01-23 at 2 34 52 PM" src="https://user-images.githubusercontent.com/2148537/73019545-ca612c00-3df1-11ea-9592-dfaf9e24dbc4.png">

**Expected behavior**

I have enough funds so I expect the transaction to be successful.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macOS
 - Browser:  Brave
 - Version:  V1.2.43

**Comment by jbibla** [comment]
hello @NodeGuy! sorry about this. hope all is well! 

we will investigate!

**Comment by Bitcoinera** [comment]
Mmm, strange, I thought we already have solved this bug :thinking: It was related to the `microDenom` filter if my memory doesn't fail. 

I think this can be related to our issue with old webpack chunks. Can you try deleting your cache @NodeGuy if you haven't already?

I will look further into it tomorrow.

**Comment by NodeGuy** [comment]
I tried deleting the cache but it didn't help.  I'm now seeing the same bug on Cosmostation and gaiacli (with my own full node), despite there being sufficient funds in the account.  🤔

**Comment by NodeGuy** [comment]
Please see a bug I filed with cosmos-sdk for reference: https://github.com/cosmos/cosmos-sdk/issues/5567

**Comment by Bitcoinera** [comment]
> Please see a bug I filed with cosmos-sdk for reference: [cosmos/cosmos-sdk#5567](https://github.com/cosmos/cosmos-sdk/issues/5567)

Awesome. Yes, this definitely looks like some Cosmos core bug.

We will for sure follow up any updates. In the meantime, I will close this issue since it is clearly not directly Lunie-related.

All the best with your case!

**Comment by NodeGuy** [comment]
Thanks for your well-wishes!

**Comment by faboweb** [comment]
Hope you are well David!!

**Comment by NodeGuy** [comment]
Thanks @faboweb, I am well.  It's exciting to see you and Jordan carrying Lunie forward!
