### ISSUE TITLE
Intercom doesn't work on Lunie mobile

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3489]
**Describe the #1 bug**

Testnet networks images not loading

<img width="410px" src="https://user-images.githubusercontent.com/40721795/73252058-6310f680-41ba-11ea-98ee-c046186423d2.png">

**Describe the #2 bug**

Indent bug in the Terms of Services section.

When you tap on "Terms of Services" or "Privacy Policy" and start scrolling, once you tap the “Menu” icon, the nav will disappear and make this bug.

<img width="410px" src="https://user-images.githubusercontent.com/40721795/73252125-876cd300-41ba-11ea-8b02-85d3cb46c585.png">

**Describe the #3 bug**

Intercom bug. 

The Help / Feedback button is not working on my device, it doesn’t do anything.

**Smartphone (please complete the following information):**
 - Device: iOS iP11
 - OS: iOS11 I guess?
 - Browser 
 - Version

**Comment by Bitcoinera** [comment]
I guess this is still relevant? I saw Jordan made a build yesterday?

**Comment by jbibla** [comment]
everything is done here except for the intercom issues.

**Comment by jbibla** [comment]
we have to register users. 

to avoid spamming, we will only register them on click of the button.

<img width="504" alt="Screen Shot 2020-03-03 at 2 35 11 PM" src="https://user-images.githubusercontent.com/6021933/75826349-32455380-5d5c-11ea-86d3-3571d33d8473.png">
