### ISSUE TITLE
The "Show on Ledger" link should appear only when the Nano Ledger is connected

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3491]
**Describe the bug**

The "Show on Ledger" link should only appear when the Nano Ledger is effectively connected :wink: 

![image](https://user-images.githubusercontent.com/40721795/73257015-4c22d200-41c3-11ea-9ec0-7ca8005ddab6.png)

**Comment by jbibla** [comment]
how can someone reproduce this?

**Comment by Bitcoinera** [comment]
> how can someone reproduce this?

You just sign in using one of the Ledger accounts without having the Ledger connected.

**Comment by jbibla** [comment]
right now, it just checks if you signed in with a ledger which seems fine to me. if the user is not connected, it will ask them to connect and then will show the address - no?

**Comment by Bitcoinera** [comment]
> right now, it just checks if you signed in with a ledger which seems fine to me. if the user is not connected, it will ask them to connect and then will show the address - no?

Well, yes, it opens a popup in the browser saying "No compatible devices found". We can leave it like that too I guess :woman_shrugging: 

Not a bug, you are right Jordan
