### ISSUE TITLE
keyboard config is not being set properly on mobile

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3494]
**Describe the bug**

capacitor has a configuration property for whether or not the keyboard should push content in the viewport or just go over top of it. our config is not set properly.

there are three capacitor configs:
1. https://github.com/luniehq/lunie/blob/develop/capacitor.config.json
2. iOS - https://github.com/luniehq/lunie/blob/develop/ios/App/App/capacitor.config.json
3. Android - https://github.com/luniehq/lunie/blob/develop/android/app/src/main/assets/capacitor.config.json

i am not sure which one is being applied but we should figure this out.

**Comment by mariopino** [comment]
Hey, @jbibla Why our config is not properly set?

I see in the doc: https://capacitor.ionicframework.com/docs/apis/keyboard:

> Keyboard configuration **(iOS only)**
> The keyboard plugin allows the following configuration values to be added in capacitor.config.json for the iOS platform:

Current iOS capacitor config file (`ios/App/App/capacitor.config.json`) already include that param:

```
{
  "appId": "org.lunie.lunie",
  "appName": "Lunie",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "dist",
  "server": {
    "url": "http://localhost:9080/"
  },
  "plugins": {
    "Keyboard": {
      "resize": "none",
      "style": "dark"
    },
    "IntercomPlugin": {
      "ios-apiKey": "ios_sdk-xxxx",
      "ios-appId": "yyyy"
    }
  }
}
```

**Comment by jbibla** [comment]
it's set to `none`, and I think this means we shouldn't see the button bar float up above the keyboard like this:

i could be wrong. does this happen on android?

![IMG_2425](https://user-images.githubusercontent.com/6021933/73844998-afc68400-47ef-11ea-8674-0a0f80234969.PNG)

**Comment by mariopino** [comment]
So, if I understand well:

- In IOS the keyboard plugin properties don't work as expected.
- The keyboard plugin properties don't apply to Android as stated in documentation.

**Comment by jbibla** [comment]
yeah i think so. this may be fixed by removing the absolute or fixed styling for the button bar.

**Comment by mariopino** [comment]
Yap, that alignment is always a tricky thing, I personally prefer a lightly ugly button close to the input field that this behaviour.

**Comment by jbibla** [comment]
> Yap, that alignment is always a tricky thing, I personally prefer a lightly ugly button close to the input field that this behaviour.

i think if we remove the absolute or fixed styling, the mobile keyboard button will be ok (on mobile apps) - we should leave the styling for mobile browsers though.

**Comment by mariopino** [comment]
Ok, I'm going to work on this.

**Comment by faboweb** [comment]
Solution seems complex so deprio

**Comment by jbibla** [comment]
this isn't an issue anymore
