### ISSUE TITLE
Refactor all update fields in SmartQueries

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3496]
All `update` functions inside SmartQuery should now add a check to see if the data was succesfully fetched:

```
      update(data) {
        if (!data.overview) {
          return {
            totalRewards: 0
          }
        }
        /* istanbul ignore next */
        return {
          ...data.overview,
          totalRewards: Number(data.overview.totalRewards)
        }
      }
```

In case it wasn't, we return either "", 0 or {} depending on the case.

As I understood it from the meeting we just had, this should now be applied to <b>every</b> SmartQuery, doesn't matter if it has nested values or not.

**Comment by faboweb** [comment]
To prevent downstream issues, those queries should probably never return undefined so they should return the expected format (array or object or number)

**Comment by Bitcoinera** [comment]
I am checking this now, but as I see it, it doesn't make so much sense to do a check like this:

```
      update(data) {
        return data.validators || []
      }
```

which is already existing in UndelegationModal, lines 388-391.

With the debugger I see that if it comes empty, it returns an empty array.

So just to confirm, the check should be done on `data` directly right? Or there is no way that `data` comes as `undefined`/`null` ?

I will push what I got now, but as I say, looking through the debugger, I see so much sense in the `data.field || []` checks

**Comment by iambeone** [comment]
I have another solution, https://github.com/luniehq/lunie/blob/aleksei/error_handling/src/gql/apollo.js — that will allow us to suspect errors, so we can just show some alert to the user. The end function could be not called or called with some params.

**Comment by Bitcoinera** [comment]
Aleksei's solution is by far superior than this one is from all points of view.

So I will close this one.
