### ISSUE TITLE
Sign Up component CSS bug

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3515]
**Describe the bug**

The main app background shows up when we shrink the screen below 667px during the session sign in / sign up flow.

<img width="430px" src="https://user-images.githubusercontent.com/40721795/73547419-2bff4700-443f-11ea-8693-565fd519cb94.png">

**Expected behavior**

The black background should be kept across the whole sign in / sign up flow.

**Desktop (please complete the following information):**
 - OS:
 - Browser: I am afraid this happens across all browsers and OS

**Comment by mariopino** [comment]
Should be fixed by https://github.com/luniehq/lunie/pull/3571

**Comment by mariopino** [comment]
Fixed by https://github.com/luniehq/lunie/pull/3571
