### ISSUE TITLE
Transaction abstraction dry run

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3522]
Transaction Abstraction Dry Run Implementation:

I have been thinking about a way we can more efficiently implement new features, such as this one, the transaction abstraction (yes, I know, the name still sounds kind of weird for me too xD). This feature is tremendously important for adding non-Tendermint networks such as Polkadot. I believe we really need to have it in place asap if we want to be able to handle both Tendermint and Polkadot transactions with the same logic.

I want to experiment with a possible solution for the problem of how we can skip rewrites & have a clear view & save time when we are to deploy a new feature. This is simply making first a "dry run" implementation i.e. write a draft for the structure / steps you have in mind to bring the feature into reality, presenting it as pseudo code or just writing down the exact way you'd do it.

Here is my attempt to do this with the transaction abstraction feature as an experiment:

First, I'd change all the existing transactionReducers to the estructure described in luniehq/lunie-api#259.
There is only one now, used by all Tendermint networks, located in cosmosV0-reducers.js.

It would look like this:

```
{
  id: idReducer(transaction.tx.hash, transaction.tx.value.msg[0].type),
  type: typeReducer(transaction.tx.value.msg[0].type), // Lunie type, not original type
  title: titleReducer(/*I don't know what this is for certain*/), // in question
  subTitle: subtitleReducer(...), // in question
  value: { 
	amount: amountReducer(...), 
	to: toReducer(...),
	from: fromReducer,
	payload: ** // in question
	... } // type specific properties
  feeAmount: feeReducer(transaction.tx.value.fee.amount[0]), // what to do with fees in mutliple denoms?
  hash: transaction.txhash,
  block: (/*We'd need to pass this from the source file*/),
  timeStamp: transaction.timestamp // dateTime to display internationalized
}
```

Nearly every field would have a reducer in order to return data as processed and standardized as possible.

In the Polkadot reducers we would add the exact same structure.

Then, I think it would be a good idea to add an additional step, a file called `transaction-validation.js`, 
where all transactions have to pass through before they get to the FE.

It would look like this:

```
{
  id: Joi.string().required,
  type: Joi.string().required,
  title: Joi.string().required,
  subTitle: Joi.string().required, // maybe this one doesn't need to be required
  value: { 
	amount: Joi.string().required, 
	to: ** here we need to see if this is going to be an array or how we do it **,
	from: Joi.string().required,
	payload: ** // in question
	... }
  feeAmount: Joi.string().required, // what to do with fees in mutliple denoms?
  hash: Joi.string().required,
  block: Joi.string(), // in Livepeer there are no blocks.. or we could add Ethereum blocks or handle rounds as blocks
  timeStamp: Joi.date().required()
}
```

This file could be located in a new folder called global.

We would also need to change of course the Transaction type in `schema.js` and `message-types.js`. 

And this would be it for the API.

Now for the FE, this is where the fun comes. There are a lot of things to modify here. Concretely all the components inside the `transactions` folder and its corresponding unit tests files. And then the following files:

- PageBlock.vue
- testTransactions.js
- messageTypes.js (and therefore also this part in ActionManager.js)
- transaction-utils.js
- index.js in `gql` folder (`UserTransactionAdded`)

And probably there are a couple I am missing there but that would be mostly it.

To be continued... (Now I cannot come up with anything else 😅 )

**Comment by faboweb** [comment]
Good Initiative, but why didn't you just use the existing issue?

Do we need transaction validation? Doesn't Graphql with it's schema already do a validation of the response to the FE?

**Comment by Bitcoinera** [comment]
> Good Initiative, but why didn't you just use the existing issue?

I thought this would be too large to put it in there plus I wanted to have a title stating "dry run" 😜 
 
> Do we need transaction validation? Doesn't Graphql with it's schema already do a validation of the response to the FE?

Yes, this is something I forgot to include in the specification. My aim here adding this validation step is to prevent the schema error to ever reach the FE. So we add this layer first and if something is wrong, we don't send the transaction to the FE.

**Comment by faboweb** [comment]
> Yes, this is something I forgot to include in the specification. My aim here adding this validation step is to prevent the schema error to ever reach the FE. So we add this layer first and if something is wrong, we don't send the transaction to the FE.

Hmm, sounds complex. Can we add the extra layer when this becomes a problem?

**Comment by faboweb** [comment]
Closing in favor of https://github.com/luniehq/lunie/issues/259
