### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by JakeHartnell** [luniehq/lunie#3536]
**Describe the bug**

Clicking on the extension reveals a blank popup.

Error in the inspector:
```﻿
popup.js:118 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Co (popup.js:118)
    at Module.<anonymous> (popup.js:118)
    at r (popup.js:1)
    at popup.js:1
    at popup.js:1
```

**To Reproduce**

Click on the Lunie Icon in the extension menu, witness a blank popup.

**Expected behavior**

I would expect to click on the extension and not see a blank popup.

**Screenshots**

![blankpopup](https://user-images.githubusercontent.com/521978/73902260-0a8cc980-484a-11ea-902b-735fa1ab36e6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Brave Browser (1.2.43)
 - Version: Lunie 1.0.11

**Comment by faboweb** [comment]
A fix is on the way! Thanks so much for reporting that quick.

**Comment by JakeHartnell** [comment]
Thanks for the fix, works great now.

**Comment by faboweb** [comment]
Thank you for the feedback that it works
