### ISSUE TITLE
Confusing behaviour using "select testnet" checkbox

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3557]
**Describe the bug**

Confusing behaviour when you select a testnet network and then sign in with a testnet account.

**To Reproduce**
1. Select network Gaia Testnet
2. Sign in Explore mode with a gaia address (it's easy to accidentally forgot to check the "select testnet" checkbox.
3. You end in mainnet (cosmoshub-3) with a testnet address so probably no funds being showed in portfolio.

Also, the network of the account is not shown in explore mode, so if you have mixed testnet and mainnet accounts there, it's easy that the previously described situation happens.

**Expected behavior**
Maybe as @jbibla suggested we can check by default the checkbox when signin in with a local account but we can't do the same in explore mode in the case of mixed testnet/mainnet accounts so we can discuss a solution here :-)

**Comment by jbibla** [comment]
nice mario! thanks for this.

i encountered this a couple times yesterday and it was confusing.

- let's make sure the checkbox is selected when a testnet is the selected network
- charlie's new designs have a tab that splits account lists by mainnet / testnet. if we implement this, this would solve the issue for the explore-select-account component

unfortunately, i don't think this is a bug - just a less-than-ideal ux. we'll have to move to the backlog for now.

**Comment by jbibla** [comment]
> let's make sure the checkbox is selected when a testnet is the selected network

a simple check would be great

**Comment by mariopino** [comment]
> > let's make sure the checkbox is selected when a testnet is the selected network
> 
> a simple check would be great

Sure @jbibla I'll add it tomorrow!

**Comment by jbibla** [comment]
@mariopino did you start on this?

**Comment by mariopino** [comment]
> @mariopino did you start on this?

Nop! time to do it
