### ISSUE TITLE
Terra & e-Money Wrap-up

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3572]
I think we can finally safely state that there is little to finish the next two mainnets to add to Lunie. Wohoooo 🎉 

OK, I actually had this nearly finished but I pressed tab and it all disappeared. Great UX GitHub 😆

It is OK, I will rewrite it all once more.

What is left to be done:

- luniehq/lunie#3559: Accounts presentation standardization:

All accounts should be presented with their alt-tokens balances centered in TmBalance no matter how many alt-tokens balances they hold.

- luniehq/lunie#3565: Paying fees in any token.

- [x] The gas price is still not showing the one picked up from the API.
- [x] Sometimes the "Wait for transaction to complete" just stays forever, although the transaction has already long succeeded. (EDIT: this actually only happened the first couple of times)
- [x] (I will do this shortly) Change the logic to select the paying-fee token. Right now I select always the highest balance one but I think it is best to automatically select the one you are doing the action with (if it has still enough funds. Otherwise default to stakingDenom. If not enough staking tokens available, then go for the highest balance once more).
- [x] After the first try sending a transaction, if there is an error, then gasPrice automatically defaults to 0.000000001, its original value for ATOMs. Really weird behavior.

EDIT: Extra: Fixed! ~~tokens don't automatically update when sending / staking!~~

And that's it.

Also I should read this documentation on Terra's gas prices: https://docs.terra.money/docs/dev-spec-treasury#monetary-policy-levers (I can do it, no worries 😆 )

**Comment by faboweb** [comment]
fees are better documented here: https://docs.terra.money/docs/dev-spec-auth#gas-fee

**Comment by Bitcoinera** [comment]
All these issues have been fixed now and it seems we are in fact wrapping this whole thing up!

Two new mainnet networks for Lunie! Yeah! 💪 

I close this then
