### ISSUE TITLE
Integrate new transaction abstraction in frontend

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3573]
**Is your feature request related to a problem? Please describe.**

We can reduce the logic in the frontend as the API is ready to serve tx using the new TransactionV2 model (Related: https://github.com/luniehq/lunie-api/pull/336):

- All transactions are flattened (no multi-messages)
- We only support only basic txs related to staking and governance:

```
const lunieMessageTypes = {
  SEND: `SendTx`,
  STAKE: `StakeTx`,
  RESTAKE: `RestakeTx`,
  UNSTAKE: `UnstakeTx`,
  VOTE: `VoteTx`,
  DEPOSIT: `DepositTx`,
  WITHDRAW_DELEGATION_REWARDS: `ClaimRewardsTx`,
  SUBMIT_PROPOSAL: `SubmitProposalTx`,
  UNKNOWN: `UnknownTx`
}
```
- Other tx should be rendered as `Unknown` show common tx fields (height, hash, fees, etc) and include a link to a reputable block explorer to help the user to track it.

**Comment by mariopino** [comment]
We need to implement this on frontend:
https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces

**Comment by Bitcoinera** [comment]
I'm loving how this is coming out, guys! Amazing!
