### ISSUE TITLE
sign out while li-validator component is present leaves data in view

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3587]
**Describe the bug**

if you sign out while the li-validator component is in view and the user has delegations and rewards, the delegation count and reward will persist after sign out. not a big deal, but likely a simple fix.

**Expected behavior**

when a user signs out, their user-specific data should disappear

**Screenshots**
note: user is signed out but data persists:

<img width="854" alt="Screen Shot 2020-02-24 at 9 00 32 AM" src="https://user-images.githubusercontent.com/6021933/75158655-9032c500-56e4-11ea-842d-1acc246e3d02.png">

**Comment by Bitcoinera** [comment]
I think this must be a quite easy fix. Just doing some apollo refecth on disconnect or something like that. Let me check
