### ISSUE TITLE
Ignore Ledger errors on Sentry

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3595]
As we track all the Ledger issues like "Cosmos App not open" those end up in Sentry and are creating noise. We can safely ignore them, as they are descriptive and nobody every complained. Ignoring means going into Sentry and click "Ignore" on that issue.

0 line change :unicorn:

**Comment by Bitcoinera** [comment]
I think it is done. Ignored all of them in the frontend

**Comment by Bitcoinera** [comment]
It took me like 2 min xD

**Comment by faboweb** [comment]
small tasks are good
