### ISSUE TITLE
When selecting an extension account from within Lunie the network is always cosmos

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3601]
**Describe the bug**

When selecting an extension account from within Lunie the network is always cosmos hub where it should be another network

**To Reproduce**

Create an account for any non cosmos hub mainnet network in the extension
Go to sign in with existing account > extension > select the new account
Lunie goes to Cosmos hub

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by Bitcoinera** [comment]
Wasn't this fixed? 👀 By you actually. It was working for me (until the extension broke xD)
