### ISSUE TITLE
Polkadot Account Management

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3621]
Polkadot accounts look a little different then Cosmos ones
- we will not need a pubkey for signing or displaying
- we can't extract the privatekey somehow (will just store seed and restore key when signing)

Need to fix prefix logic in sign in processes (done)

On account creation we need to make the controller account the same as the stash account for simplicity: https://wiki.polkadot.network/docs/en/learn-staking#accounts

**Comment by Bitcoinera** [comment]
> We need to store the accounts lists individually rn and load them individually

What do you mean exactly here?

Store each Polkadot user account separately from the rest instead of storing them all as a list? This is what you mean? Why?

> Need to fix prefix logic in sign in processes

I thought the fix was to simply create them with the `polka` prefix

**Comment by faboweb** [comment]
> We need to store the accounts lists individually rn and load them individually

exploring this I figured, this is not needed. we can store in the same data structure

>I thought the fix was to simply create them with the polka prefix

that would be nice, but probably be confusing for most polkadot users. I already fixed this.
