### ISSUE TITLE
e-Money final Wrap-up (this time for real)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3641]
I thought it is a good idea to have in one issue all that is left to finish & deliver e-Money.

From Martin himself:

- [x] Your portfolio will need to have access to market data to be able to convert the individual balances to USD (say, know the exchange rate of CHF -> USD)

This is actually kind of done. Maybe it would be good to include a purely converter function, since now every time we are running the `calculateFiatValue` function in emoney-source or maybe this is just fine like that.

It is true though that the way it is working now is not converting **individual** balances, but all of them at once. Should discuss it with them? In any case, super easy to implement, except the UI part.

- [x] Rewards have same issue as above (needs ability to convert individual reward balances to USD) i.e. rewards should show their fiat value when a fiat currency is selected

Very easy to do. We just need to add `fiatValue` to rewards and boom.

- [ ] The staking token (NGM) will typically not be owned by the average user, they can pay fees using currency-backed tokens (eeur etc.), so not sure it should have such a “prominent” display

Not prominent but indeed distinct. @jbibla is already working on this in #3617, so this will be done as well really soon.

- [x] It’s not possible to withdraw a single denom, so it is all-or-nothing

I think this is already the way it is working by standard? Can someone confirm?

- [x] Add validators images to database

Other matters to discuss:

- Do we need to remove the “little e” (eJPY) from the API?

This would mean changing a bit the default logic to show a different denom than the one the node is returning. It is undoubtedly worth discussing with them.

**Comment by Bitcoinera** [comment]
Rewards fiat values added in luniehq/lunie-api#396

**Comment by Bitcoinera** [comment]
Here it is only the new Portfolio missing really

**Comment by jbibla** [comment]
https://github.com/luniehq/lunie/pull/3695

**Comment by Bitcoinera** [comment]
> #3695

Amazing! I will review it tomorrow :wink:
