### ISSUE TITLE
Add Intercom shutdown method so user data is not saved session to session

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#3652]
https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app#how-to-end-a-session

Users reporting some data saved on shared computer from user to user. Implementing this method will prevent this even if a user does not clear their cache and browsing history after using Lunie. 

**Describe the solution you'd like**
When a user closes their browser Lunie's intercom instance will not preserve records of their identity or conversation. 

**Describe alternatives you've considered**
Telling users to delete cache and history every time. 

**Additional context**
This is the only solution Intercom has for this issue

**Comment by faboweb** [comment]
Nice! Already providing us with customer issues ♥️

**Comment by mariopino** [comment]
Maybe we can simply just issue a shutdown call in frontend initialization (before connecting), just to make sure we clean possible stored info.
