### ISSUE TITLE
Networks gets hidden in AppMenu when signed in with Ledger

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3654]
**Describe the bug**
The "Networks" link on AppMenu is not visible anymore and there is no scroll that tells the user there is another option down there.

**To Reproduce**

**FIRST: You need to be signed in with a Ledger**
Go to app.lunie.io and sign in with a Ledger. The screen must be 14'' (usual for a laptop)

**Screenshots**

![image](https://user-images.githubusercontent.com/40721795/76149990-e9680480-60a5-11ea-94db-c9aded4f5970.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser:  Brave
 - Version:

**Comment by jbibla** [comment]
i cannot reproduce on a mac.

<img width="223" alt="Screen Shot 2020-03-15 at 5 06 32 PM" src="https://user-images.githubusercontent.com/6021933/76710618-57807d00-66df-11ea-872d-286e9c9e29d7.png">

**Comment by Bitcoinera** [comment]
> i cannot reproduce on a mac.

You are not signed in here with a Ledger

**Comment by jbibla** [comment]
🤦‍♂

**Comment by jbibla** [comment]
confirmed - cannot reproduce on a mac with brave.

**Comment by Bitcoinera** [comment]
I guess I will have to fix that then. Can someone else reproduce?
