### ISSUE TITLE
ActionModal gets stuck in Data Loading (in production)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3655]
**Describe the bug**

After pressing the action button the ActionModal just stays frozen in the Data Loading view and nothing happens. You need to close it and reopen it again to be able to do something

**To Reproduce**
For now I just tried with the SendModal. It happens like one time out of three or more

**Screenshots**

<img width="430px" src="https://user-images.githubusercontent.com/40721795/76150299-284b8980-60a9-11ea-934f-642ab58ff4f8.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 

**Additional context**
There are no errors to be seen in the Devtools console

**Comment by faboweb** [comment]
Solution could be #3670

**Comment by Bitcoinera** [comment]
I was just checking for a good while and I can state this is fixed now
