### ISSUE TITLE
Help-Desk Published: Using The Memo Option When Sending Tokens To and From Exchanges

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#3660]
help-center article about using memo when sending to/from exchanges is live:

https://intercom.help/lunie/en/articles/3776563-using-the-memo-option-when-sending-tokens-to-and-from-exchanges

**Comment by Bitcoinera** [comment]
Amazing! Very detailed! 👏 

@Charlie (not here 😅 )@jbibla @faboweb  What are the plans now to include the link to this article into the SendModal?

Should we go back to hiding the memo field (as shown in this article 👀 )

**Comment by jrmoreau** [comment]
@jbibla @Bitcoinera is there a specific place this link should go in the app? Maybe only useful if the user clicks a "receive" button

**Comment by jbibla** [comment]
true. this is most important when receiving. we don't have a receive button yet - so this can wait until then.

**Comment by jbibla** [comment]
![Screen Shot 2020-04-07 at 10 25 42 AM](https://user-images.githubusercontent.com/6021933/78681254-7b884600-78ba-11ea-92a3-a960c32ef539.png)

**Comment by Bitcoinera** [comment]
What do you think @jrmoreau 

I personally think there is a good place

**Comment by jrmoreau** [comment]
@Bitcoinera I think so, but I don't think it should be a link that opens in a new browser - could be confusing and lead to problems. 

@jbibla could we do a tutorial modal if someone clicks the memo hyperlink?

**Comment by Bitcoinera** [comment]
I actually love new tabs opening. I prefer that than redirecting me in the same tab actually. Helps me to get better organized (maybe I cannot go back to the previous original page & I miss it)

**Comment by jrmoreau** [comment]
You're correct. Redirecting in the current tab is the least desirable, the second being opening a new tab and i think the best would be the tutorial modal (if it's possible)

**Comment by jbibla** [comment]
tutorial modals are a bit involved. have to get an asset from charlie, pick the right sentences for the flow, and add the component in a new place. it will overlap the action modal where the link to open the modal will be — maybe that's ok.

i think we should just use a link and open it in a new tab for now.

**Comment by jrmoreau** [comment]
Sounds good! Opening in a new tab would be fine.

**Comment by Bitcoinera** [comment]
What is the plan here? Are we going to add some article link to the SendModal?

**Comment by jrmoreau** [comment]
I thought so, yes

**Comment by faboweb** [comment]
James wanted to do it. Maybe we should help him.

**Comment by Bitcoinera** [comment]
@jrmoreau I can help you to add the link to the article in there

**Comment by Bitcoinera** [comment]
Are we going to do this? Or we just leave the memo field blank?

**Comment by jrmoreau** [comment]
@Bitcoinera I am out of commission to get involved with any coding until I get my computer back unfortunately

**Comment by jbibla** [comment]
@Bitcoinera let's just add the link and close the issue!

**Comment by Bitcoinera** [comment]
Ok
