### ISSUE TITLE
Refactor folders in the FE to delete the `src/components/wallet` folder

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3699]
This `wallet` folder in components is too confusing.

`PageTransactions` should go into the `transactions` folder and `PagePortfolio` into `common`.

Unit tests should also apply these changes

**Comment by jbibla** [comment]
a higher impact refactor would involve splitting the common folder up - it's too big!

**Comment by Bitcoinera** [comment]
> a higher impact refactor would involve splitting the common folder up - it's too big!

Yeah, that is true. All the session components should have their own folder

**Comment by Bitcoinera** [comment]
OK, adding this to my TODO list for the week too!

**Comment by Bitcoinera** [comment]
I'm going to do this. Simple thing & very easy to do!
