### ISSUE TITLE
Activity/PageTransactions: Invariant Violation: Must contain a query definition

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3700]
**Describe the bug**

Anytime you go to the Activity section, you get greeted by this error coming from the `subscribeToMore` query.

![image](https://user-images.githubusercontent.com/40721795/76706261-6cacda00-66e6-11ea-87ab-4ab3ec9b7754.png)

**Additional Context**

Skipping the query "fixes" it.

Also I noticed there is almost the same query repeated. One inside the transactions query (lines 201 - 226) and the other one outside as a separate query (this is the failing one) in lines 228 - 263).

I don't know if this is an error or if the one outside is just there for tests (in that case, we could skip it in execution)

**Comment by Bitcoinera** [comment]
I don't understand how but it seems the same error is still present. 

While testing Aleksei's PR #3735 the error was one and this one has been merged, so it is quite surprising 🤷‍♀

**Comment by Bitcoinera** [comment]
This is how the error looks like now. The message changed a bit:

<img width="380px" src="https://user-images.githubusercontent.com/40721795/77227170-7a4adf80-6b7e-11ea-8645-59f16a788faa.png">

**Comment by faboweb** [comment]
I saw the same. Maybe I bad fixed something. What was the initial solution?

**Comment by faboweb** [comment]
did you update the backend? did you run against staging?

**Comment by Bitcoinera** [comment]
I am running it against staging yes. The solution was just merged yesterday, in #3735 

While testing this PR these errors weren't appearing. 

Why do you think you were the one causing this?

**Comment by faboweb** [comment]
There were merge conflicts

**Comment by faboweb** [comment]
At least there are no visible errors

**Comment by jbibla** [comment]
on develop and production i'm not getting any errors anymore - but I'm also not seeing any transactions (cosmos17njs9mgaszmhvanzx7dpuv7cyngs7wffk6g4s4)

**Comment by Bitcoinera** [comment]
Seems to closed by #3751
