### ISSUE TITLE
Un-staking amount issue

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#3717]
**Describe the bug**
User trying un-stake max amount (also tried smaller amount) and the step two shows withdraw amount taking fees from staked amount. 

**To Reproduce**
![Captura de Tela 2020-03-16 às 19 08 13](https://user-images.githubusercontent.com/1614127/76864101-ece25500-6836-11ea-8078-409f2c7ca308.png)
![Captura de Tela 2020-03-16 às 19 23 53](https://user-images.githubusercontent.com/1614127/76864103-ece25500-6836-11ea-8ee3-6477e9f4b1b5.png)

**Expected behavior**
Their full balance staked should have been withdrawn minus fees

**Desktop (please complete the following information):**
unknown (update)

**Smartphone (please complete the following information):**
unknown (will update)

**Additional context**

**Comment by jbibla** [comment]
closed by https://github.com/luniehq/lunie/pull/3631
