### ISSUE TITLE
Lunie signin with Ledger error (Cannot read property 'networks' of undefined)

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#3724]
**Describe the bug**
cannot login to Lunie with Ledger after getting stuck on Terra network and logging out and trying to log back in

**To Reproduce**
Tried logging into my Lunie Cosmos wallet with my Ledger. Page was previously set on my Terra wallet. Did a hard refresh, but the network did not switch. I logged out of my account and tried logging back in with my Ledger and keep getting the error 

`Cannot read property 'networks' of undefined`

**Expected behavior**
Normally just logs me right back in

**Screenshots**
 
<img width="1479" alt="Screen Shot 2020-03-17 at 11 02 39 PM" src="https://user-images.githubusercontent.com/1614127/76921261-f2c24f80-68a3-11ea-8339-7212811e9c86.png">

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Browser: Chrome and Brave

**Comment by jilanimu** [comment]
I am having the same issue

**Comment by Bitcoinera** [comment]
Let me check this
