### ISSUE TITLE
When signing in with extension, sometimes you sign in to the currently selected network

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3737]
**Describe the bug**

When signing in with extension, sometimes you sign in to the currently selected network

**To Reproduce**

Fresh lunie
Create an account for a not cosmos-hub network in the extension
Go in lunie to cosmos-hub
Go to sign in with extension
Click on your account
You will be redirected to the target network but not signed in
On cosmos-hub you are now signed in with the account you wanted to be signed in for the target network

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by iambeone** [comment]
Can't reproduce. There was a bug, but it's fixed week ago
