### ISSUE TITLE
Validators search bar losing focus or page suddenly reloading

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3747]
**Describe the bug**

When you type in the validators search bar in Validators (especially by deleting or using spaces) either the page gets reloaded all the time or the search bar gets unfocused making it very difficult to search for anything.

Also happening in production.

**To Reproduce**

Try to search for validators deleting your previous search or using spaces

**Expected behavior**

The page shouldn't reload by searching and also it should treat deletes & spaces normally, without the search bar losing focus

**Screenshots**

<img witdth="150px" src="https://user-images.githubusercontent.com/40721795/77232134-885d2800-6b9f-11ea-9194-4a29eaa54bd6.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Need to add `loaded` property. @jbibla you forget that.
