### ISSUE TITLE
Remember currency selected

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3750]
**Is your feature request related to a problem? Please describe.**

Currently you have to choose the desired currency every time.

**Describe the solution you'd like**

Store the currency in localStorage
- using the `session.js` module and the actions `getSelectedCurrency` and `setSelectedCurrency`

**Describe alternatives you've considered**

**Additional context**

@jrmoreau interested?

**Comment by Bitcoinera** [comment]
True! My solution doesn't work anymore somehow. What happened?

Let me take this on
