### ISSUE TITLE
Let FE know if it is outdated

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3760]
**Is your feature request related to a problem? Please describe.**

Sometimes our FE is outdated as the files keep being cached.

**Describe the solution you'd like**

Based on:
https://medium.com/hypefactors/busting-spa-chunk-cache-for-active-users-after-a-deploy-a9a06242edb1

We may do this as we already talked about once:
- [ ] on deploy in Netlify trigger a mutation in Apollo to write in the table `versions` a record for the latest deployed version in `production` and ` staging`
- [ ] clients load/subscribe to the version
- [ ] clients show a reload message if there is new version while the app is open
- [ ] clicking on the outdated warning should force refresh the app
- [ ] clients refresh when the version is different then the current version on inital load

**Describe alternatives you've considered**

We already tried shipping the version together with the app on `/version.json` which has similar caching issues.

We can also figure out, why the index.html is not properly rechecked on every load.

**Additional context**

**Comment by atharva3010** [comment]
Have you tried leveraging the service worker’s `updated()` method?

**Comment by Bitcoinera** [comment]
> Have you tried leveraging the service worker’s `updated()` method?

We removed our service worker right @faboweb ?

**Comment by faboweb** [comment]
Yep, I think it's still there for old users. I think we still need to remove old ones. https://love2dev.com/blog/how-to-uninstall-a-service-worker/

**Comment by Bitcoinera** [comment]
This is going to be fixed also by #3837
