### ISSUE TITLE
single seed based account management

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3782]
**Is your feature request related to a problem? Please describe.**

There appeared issues around tieing accounts to networks. People might want to use the same address on mainnet and testnet or use one seed across all networks.

**Describe the solution you'd like**

Base accounts only around the seed. When signing in, you would select the network and the account. The address is generated on the fly. Signing happens based on the seed and network.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
> When signing in, you would select the network and the account

what do you mean by "account" here?

**Comment by faboweb** [comment]
an account is a name+seed

**Comment by jbibla** [comment]
ah. you're saying there could still be more than one account.

**Comment by faboweb** [comment]
yes! also important for backwards compatibility

**Comment by Bitcoinera** [comment]
> ah. you're saying there could still be more than one account and more than one seed.

I thought we were going to offer only one seed for all networks & future accounts?

Multiple seeds could be Premium 
<img width="140px" src="https://user-images.githubusercontent.com/40721795/80384252-eec31d80-88a4-11ea-84c0-f2161b37312a.png">

**Comment by Bitcoinera** [comment]
Where would we store that unique seed? In our database encrypted?

**Comment by faboweb** [comment]
we would store it the same way as we do right now clientside.

**Comment by jbibla** [comment]
we should inquire with users who use multiple networks if they would like to use 1 seed or 2 seeds

**Comment by Bitcoinera** [comment]
Probably it is going to take us a bit to get there, as email addresses are coming first, but definitely quite relevant

**Comment by Bitcoinera** [comment]
Definitely relevant: this is the next step after having the user accounts logic in together with Premium restrictions & paywall

**Comment by Bitcoinera** [comment]
I want to do this :star_struck:  I even have a PR open for this in the `cosmos-keys` repo (luniehq/cosmos-keys#33 :heart: )

**Comment by jbibla** [comment]
> I want to do this 🤩 I even have a PR open for this in the cosmos-keys repo

i wish github had the face palm emoji for comments 🤦 

<img width="186" alt="Screen Shot 2020-07-25 at 9 33 47 AM" src="https://user-images.githubusercontent.com/6021933/88458154-f4a3ad00-ce59-11ea-8d0f-b0421ced68e0.png">

**Comment by Bitcoinera** [comment]
> i wish github had the face palm emoji for comments :facepalm: 

:facepalm:

**Comment by Bitcoinera** [comment]
:stuck_out_tongue:

**Comment by jbibla** [comment]
how much effort is required for 1 seed to be possible?

**Comment by Bitcoinera** [comment]
> how much effort is required for 1 seed to be possible?

Not sure, a bit more than handling different algos was or similar, imo. The only thing is that if we want to add "Forget seed" or "Add new seed" features it will take a bit more.

Another thing I'm thinking is that there is another possible implementation for this, without even storing the encrypted seed. It would be that the user needs to input always their address. Like, you open Lunie for the first time and you get your Lunie address, and you need to input this one manually each time you create an address. But probably most users will prefer using the stored encrypted option

**Comment by Bitcoinera** [comment]
Yes, this one my take a bit longer to bring in
