### ISSUE TITLE
Transactions not getting to Success screen on Terra (mainnet)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3783]
**Describe the bug**

After sending aroung 10 transactions on Terra mainnet, I have been noticing that a good number of the transactions are successful but ActionModal doesn't get to display the Success screen (maybe about half of them). Both with Send and Stake transactions.

I'd need to recheck Terra testnet to see if it is also happening there.

**To Reproduce**

Try making transaction on Terra mainnet

**Expected behavior**

If transaction is successful, we should also get the success message

**Screenshots**

<img width="410px" src="https://user-images.githubusercontent.com/40721795/77670260-3c86f600-6f86-11ea-957d-9435d49d9658.png">

**Additional context**

Using latest develop on both FE and API

**Comment by faboweb** [comment]
same using staging-api?

**Comment by Bitcoinera** [comment]
Staging api is the same than latest API develop, so yes

**Comment by faboweb** [comment]
difference between local and deployed though

**Comment by Bitcoinera** [comment]
Which is the difference? The code is the same right?

OK, I will test with staging then now

**Comment by faboweb** [comment]
Can you try staging API so we can see errors in the logs https://grafana.lunie.io/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bhost%3D%5C%22Lunie-API-staging%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by Bitcoinera** [comment]
I will keep checking, but those Terra transactions went actually through.

Still, I think today we got quite closer to the actual issue: it seems to happen when the gas is quite close to get completely exhausted. 

This happens as well in e-Money when you stake with gas estimate 200000. It goes through, but the Success message never appears.

If we can now reproduce it, we can also fix it 😉

**Comment by Bitcoinera** [comment]
I close this as the actual issue here is #3786 and this has been already fixed by increasing Terra gas estimate to 300000 (#3789 )

**Comment by jbibla** [comment]
is it possible this out of gas issue is breaking e2e right now?

**Comment by Bitcoinera** [comment]
Good question... yes, there was an issue with a Redelegation modal not showing.. 🤔 In that case now it should be fixed
