### ISSUE TITLE
Have better linting

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3785]
There is still changes in the code resulting from linting on different devices. It would be good if the formatting is always standardized.

**Comment by Bitcoinera** [comment]
Yes, let's do this!

But how to start, where are those differences actually coming from?

**Comment by jbibla** [comment]
@faboweb do you have any idea where the source of conflict is?

**Comment by faboweb** [comment]
Sadly no.

**Comment by Bitcoinera** [comment]
We'll need to make our own research then.

The first question that comes in mind is: eslint, prettier, husky (this one just runs eslint no?)... VSCode itself (shouldn't be since the .vscode folder in the repo)

**Comment by Bitcoinera** [comment]
Maybe this is the issue, workspaces? @faboweb do you always run push / linting from the workspace or sometimes you open the repo directly?

I always do everything from the workspace

![image](https://user-images.githubusercontent.com/40721795/79486504-16012b80-8017-11ea-985b-203fabc8173b.png)

**Comment by faboweb** [comment]
What do you mean by opening it directly? I have a workspace. I normally lint via "yarn lint --fix"

**Comment by Bitcoinera** [comment]
Yeah, probably it is not that. Yesterday I was checking and I was getting the same result linting from workspace and from repo directly. Need to keep looking

**Comment by jbibla** [comment]
any updates here? super annoying problem!

**Comment by Bitcoinera** [comment]
maybe fixed already by #4060 ?

**Comment by jbibla** [comment]
maybe 🤞
