### ISSUE TITLE
Display "out of gas" error to users

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3786]
**Is your feature request related to a problem? Please describe.**

Right now every time a sent transaction runs out of gas users don't get to know what is going on. They will just see the spinner turning and turning on the ActionModal. Later they will realize that their transaction didn't make it and will just blame Lunie for it.

**Describe the solution you'd like**

Inside our transaction polling system we should have also a way to capture the out of gas error, send it to FE and display it to our users.

**Describe alternatives you've considered**

I don't see any other alternative. We need to let users know this important fact so they know they just need to add more gas for their transaction to succeed.

**Comment by faboweb** [comment]
See also #3775

**Comment by jbibla** [comment]
> blame Lunie for it
😨 

i don't think users should need to know about gas. if this happens, we should show a retry #3775 and say "we tried to save you some money, but the fees were too low".

**Comment by Bitcoinera** [comment]
Yeah, probably better not to mention the word "gas" or any technicism at all. Good catch

**Comment by faboweb** [comment]
Consider #3775

**Comment by Bitcoinera** [comment]
> Consider #3775

Yeah, you are right. Much better UX definitely. Instead of displaying anything to the user just retry on the background.

Let me close this one then in favor of #3775
