### ISSUE TITLE
Allow 12 word seed import for Polkadot

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3793]
**Is your feature request related to a problem? Please describe.**

Most seeds created in PolkadotJS are 12 words. We don't support importing those rn. 

**Describe the solution you'd like**

To allow users to use Lunie as well, we should allow 12 word seed import.

Also the messaging should say: `24 word or 12 word back up code or raw backup code`.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
will we always show 24 spaces but let users only use 12? is that the idea?

**Comment by faboweb** [comment]
what do you mean by spaces? this treats imports not account creation

**Comment by jbibla** [comment]
<img width="387" alt="Screen Shot 2020-03-31 at 1 30 46 PM" src="https://user-images.githubusercontent.com/6021933/78056901-d74f4e00-7353-11ea-909f-4425cdc58a4e.png">

**Comment by faboweb** [comment]
hmm maybe can't be that sophisticated or we need a switch to select the format in advance
