### ISSUE TITLE
Undelegation End Time seems to be off by 1 day (i.e. 1 day too short)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3796]
**Describe the bug**

We have already got two users reporting this. One of them was trying to Redelegate during the day he thought he could, but he actually needed 24h to ellapse to be able to do it.

**To Reproduce**

We can monitor if we have any pending undelegation, although the waiting time is kind of long

**Expected behavior**

21 days equals to 504h. We need to make sure that the calculation in the FE is correct and that pending undelegations keep being displayed while an undelegation is pending

**Comment by faboweb** [comment]
Do we have example accounts? Is this in the response from the BE or in the FE?

**Comment by Bitcoinera** [comment]
I think it is in the FE the problem. I had an account with an undelegation of 3 days.. Let me see if I can find it

**Comment by Bitcoinera** [comment]
I am reproducing it! Look!

http://gaia-13007--lcd--archive.datahub.figment.network/apikey/124a234fb3c6bccf430bfd298bd160ae/staking/delegators/cosmos1rfg85mh5pmm5f0m05wmqg5qaknv3u7rfyqp36t/unbonding_delegations

And if you check that address in Lunie, cosmos1rfg85mh5pmm5f0m05wmqg5qaknv3u7rfyqp36t, there is no undelegation showing! 😨 

Going to fix this! 💪

**Comment by jbibla** [comment]
i can't reproduce this issue. 
<img width="1101" alt="Screen Shot 2020-04-01 at 8 44 01 AM" src="https://user-images.githubusercontent.com/6021933/78138471-f2be6580-73f4-11ea-9f43-d5101b51617b.png">

**Comment by Bitcoinera** [comment]
Yep, I was monitoring an undelegation and everything seems to be fine. No bug
