### ISSUE TITLE
Staking max amount not working as it should

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3825]
**Describe the bug**

When in the Stake modal you select "Max" to stake all available token, still there are fees being added on top of that max amount, in a way that forces the user to go back and change the amount to stake manually. 

Cannot just go and  try pay 0 fees.

**To Reproduce**

Try to stake max amount in any network. You will see the validation error just in the second screen

**Expected behavior**

When you select max amount, it should not add any fees on top

**Screenshots**

<img width="480px" src="https://user-images.githubusercontent.com/40721795/78164139-98032900-7449-11ea-83a8-72001b9cfc77.png">

**Comment by Bitcoinera** [comment]
I saw something like "similar to 4 other issues" right before submitting... How can I see those now?

**Comment by faboweb** [comment]
You can click on the link

**Comment by Bitcoinera** [comment]
Yes, but now it is gone 👀  😅

**Comment by faboweb** [comment]
So this is a bug. The logic was there before to reduce the fees to the maximum the user can pay. In this case they would be reduced to 0.
