### ISSUE TITLE
blocks page does not display transactions on terra

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3835]
**Describe the bug**

when you visit a blocks page on terra, no transactions appear.

**To Reproduce**

1. visit https://app.lunie.io/terra/blocks/1454879
2. see this: 
<img width="882" alt="Screen Shot 2020-04-03 at 10 53 10 AM" src="https://user-images.githubusercontent.com/6021933/78374047-5ed9ce80-7599-11ea-9050-1ee95def7b8b.png">

**Expected behavior**

we should show the transactions in the block.

**Comment by faboweb** [comment]
The issue is, that these are `UnknownTx` which we don't show. We could show them as unknown. Or add messaging "Not Lunie relevant txs are not showing here".

**Comment by jbibla** [comment]
ok interesting. maybe we should just get rid of this page. it's not so useful as it is...

right now it's only linked from our successful transaction page and from TmConnectedNetwork. We could remove this from TmConnectedNetwork and send users to their portfolio after a successful transaction which would be a much better experience anyways. 

this would simplify our codebase and user experience. 

the alternative is to invest some time and energy into making this page more functional. 

- find a way to show all data
- allow searching and pagination between blocks
- other block explorer things 🙃

**Comment by faboweb** [comment]
We wanted to partner with explorers right? Then we can remove it.
But I am also very open to make this a proper explorer. We have a lot of the data.

**Comment by Bitcoinera** [comment]
We could use PageBlock to add the links to the explorers we partner with.

I also wouldn't remove TmConnectedNetwork, as I find it very reassuring for our users to see live the blocks they are making transactions in.

**Comment by jbibla** [comment]
https://docs.google.com/document/d/1KTIg4SfyigWTXpynTS6VrYav49fMJ9sMnPPAzaZEnc4/edit
