### ISSUE TITLE
Deprecate `between` check on amount inputs

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3839]
**Is your feature request related to a problem? Please describe.**

The error shown for the `between` validation is partially confusing.

**Describe the solution you'd like**

Deprecate the between check in favor of `max` `min` and `noBalance` checks so we can show better error messages.

**Describe alternatives you've considered**

Create the error messages in JS instead of using validations

**Additional context**

**Comment by Bitcoinera** [comment]
Nice! But what would be the use case for `min`? Can you give an example?

**Comment by faboweb** [comment]
the user should not be able to enter 0.0000001 in Cosmos. As the precision is only 6 decimals

**Comment by Bitcoinera** [comment]
Oh! Thanks! I hadn't thought of that

**Comment by faboweb** [comment]
Maybe we can actually do this in a different way so 0.1000001 also fails

**Comment by Bitcoinera** [comment]
yes. It should be called maxDecimals actually. And `max` is enough for what `between` was doing
