### ISSUE TITLE
Inactive validators shown in Restake lists

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3876]
**Describe the bug**

When you are on the Restake modal, you get a complete list of validators in the "To" dropdown menu, also including inactive validators.

**To Reproduce**

Try restaking and check on another tab if the validators are active or not. Some are not.

Especially easy to check in testnets, as there many are not active anymore

**Expected behavior**

The validators list to restake to should only contain active validators

**Comment by Bitcoinera** [comment]
Leaving this open as a reminder that we need to rewrite the validators dropdown on Restake modal.

There should be something (maybe a color?) to indicate if a validator is active or inactive

**Comment by jbibla** [comment]
i don't think this is a bug. sometimes, a user may want to stake to an inactive validator to help them become an active validator. 

strongly agree we should improve the list and make it visible. i think the plan is to use the existing li-validator components. something like this: https://www.sketch.com/s/Oy9lm/a/GaKa5L

**Comment by Bitcoinera** [comment]
> something like this: https://www.sketch.com/s/Oy9lm/a/GaKa5L

Oh, I love the design 🤩

**Comment by Bitcoinera** [comment]
Sometime, right?
