### ISSUE TITLE
e-money should live at app.lunie.io/e-money (not app.lunie.io/emoney)

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3877]
**Is your feature request related to a problem? Please describe.**

the e-money network has a hyphen in the name

**Describe the solution you'd like**

we should respect the hyphen and include it in e-money URLs. we should use a redirect to redirect from `emoney` to `e-money`. 

**Describe alternatives you've considered**

**Additional context**

**Comment by faboweb** [comment]
change the slug it in the networks config.
