### ISSUE TITLE
Add account type selector in polkadot account import (experimental)

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#3889]
**Is your feature request related to a problem? Please describe.**

To provide better compatibility with already created polkadot accounts we can add an account type selector (with Schnorrkel sr25519 or Edwards ed25519 options) in account import.

As @faboweb suggested we can add this under experimental flag, as this is only intended for power users.

**Comment by jbibla** [comment]
does polkadot js let you pick? and why would someone pick one over the over?

**Comment by faboweb** [comment]
currently it would only be for us to use our vanity accounts, but we can just wire our tokens to another sr25519 account

**Comment by jbibla** [comment]
this seems like an advanced feature that we should not even be implementing or thinking about.

**Comment by mariopino** [comment]
oki, I'll close it then.
