### ISSUE TITLE
validator list UX improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3894]
**Is your feature request related to a problem? Please describe.**

- our validator list is an important page for our users to view, search, and assess the staking opportunities on a network
- there are many anonymous validators (no moniker, just address) and many without images which provide no information for users in a UI product. this reflects poorly on us and makes the list we show seem complex and unapproachable. 
- right now, we default to sort by rewards - but the top 20 or so all have the same rewards (0% commission). this means the above-the-fold view of our list includes a bunch of anonymous and undifferentiated validators.

AC:
- validators without profile pictures are not visible by default on Lunie
- on mobile you can sort validators by any visible property

**Describe the solution you'd like**

- - [ ] API: let's remove them anonyomous validators from the "active" list and put make them visible with the "all" button.
~~- FE: we should make the "contact us" button more prominent for validators that want to add a name / update an image including adding it to the li-validator component (if missing an image or a name)~~
~~- we should sort the list by something that is special to Lunie — like popularity. this would give users a reason to check the list frequently to see which validators are trending and could incentivize validators to send people to Lunie (to improve their position in the list)~~
- - [ ] FE: on mobile, let users sort the list by more than 1 detail (popularity, voting power, yield)

**Additional context**

need to implement https://github.com/luniehq/lunie-api/issues/615

**Comment by Bitcoinera** [comment]
Why do this only on mobile?

```
on mobile, let users sort the list by more than 1 detail (popularity, voting power, yield)
```

**Comment by faboweb** [comment]
because on mobile you can only sort by yield right now.

**Comment by Bitcoinera** [comment]
Popularity could be number of views of the validator page or how would that be estimated?

**Comment by faboweb** [comment]
https://github.com/luniehq/lunie-api/issues/615
