### ISSUE TITLE
memo field improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3898]
https://github.com/luniehq/lunie/issues/2673

**Comment by faboweb** [comment]
removing the default message?

**Comment by jbibla** [comment]
sorry.

yeah, we used to hide the memo field. now we show it always because people don't realize they need to add a memo for binance. 

when it was hidden, a user said this was very annoying that they always had to delete the memo first.

we should append the memo for all txs but the user shouldn't have to see it / deal with it. the inputs should always be empty and we need james to implement the memo link to help center.

**Comment by jbibla** [comment]
can we just remove the memo message? it doesn't provide any real value and is annoying for some users.

**Comment by faboweb** [comment]
Needed for sending to exchanges...

**Comment by jbibla** [comment]
yeah, we should leave the memo field - but we probably don't need the memo message

**Comment by jbibla** [comment]
this is done
