### ISSUE TITLE
Check if we can enforce CSP on mobile

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3916]
CSP (Content Security Policy headers) are a great security tool.

We should check if it is possible to enforce them too on Lunie mobile

**Comment by faboweb** [comment]
If we use the CSP in HTML this is automatically also valid in the app. So we should switch again to providing the CSP in index.html

**Comment by faboweb** [comment]
https://github.com/apache/cordova-plugin-whitelist#content-security-policy

**Comment by Bitcoinera** [comment]
Yes, super relevant, in fact

**Comment by Bitcoinera** [comment]
Oops, we forgot to do this. But would be cool if we could have this, since now we will have users accounts.

I mean, but is this even needed within a mobile app? :shrug:

**Comment by faboweb** [comment]
This is about avoiding that malicious code can be executed and connect to a remote source to transmit data

**Comment by faboweb** [comment]
We should do this. It is actually easy: We need to move the CSP headers from netlify.toml to index.html

**Comment by Bitcoinera** [comment]
> ALso gives us the possibility to remove netlify links in production

Mmm, not sure what do you mean by this? What links are we using now in production?

**Comment by faboweb** [comment]
In production we are alloying *.netlify.app as a source which is not desired as this could be any site.

**Comment by Bitcoinera** [comment]
Oops, we never actually try this. But being an app it is already quite secure, isn't it?

**Comment by Bitcoinera** [comment]
Maybe it is OK. I think apps are environments secure enough
