### ISSUE TITLE
Add proper keyboard input for mobile for Android 6 where there is no dot for decimals

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3925]
Kusama final battle!

**Comment by Bitcoinera** [comment]
Related to #3494

**Comment by mariopino** [comment]
Interesting issue with some solutions:

https://github.com/ionic-team/ionic-plugin-keyboard/issues/74

**Comment by mariopino** [comment]
I dont like too much the proposed solutions, so trying another way, let's add a `step="0.1"` to the input number and see if Ionic is smart enough to detect that decimal point is required.

**Comment by faboweb** [comment]
If not the cordova plugin might work? https://github.com/mrchandoo/cordova-plugin-decimal-keyboard

**Comment by mariopino** [comment]
> If not the cordova plugin might work? https://github.com/mrchandoo/cordova-plugin-decimal-keyboard

Yep, I checked but I think we always have the possibility to use a text input type without the need to use that plugin. Also seems that it's only for iPhone and doesn't handle screen rotations.

**Comment by mariopino** [comment]
Closing by now, as it's an old Android release (2015).

**Comment by Bitcoinera** [comment]
On Cosmostation they sorted it out:

<img width="430px" src="https://user-images.githubusercontent.com/40721795/80984151-c8195f80-8e2d-11ea-9931-8fb87185f54d.png">

But yeah, they are native Java... 🤔 

What do you think? Could we add some native code snippet to sort this out?

**Comment by faboweb** [comment]
Did you try https://stackoverflow.com/a/29388523 ? we can use the chainToViewConversionFactor for the step or we just set it to `0.000001`

**Comment by Bitcoinera** [comment]
> Did you try https://stackoverflow.com/a/29388523 ? we can use the chainToViewConversionFactor for the step or we just set it to `0.000001`

But I have an LG phone... but the step thing seems definitely worth a try
