### ISSUE TITLE
Handle different Kusama algorithms (Schnorrkel and Edwards)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3929]
We should offer both as an option for account creation/ restore or, at the very least, add some information message in case we don't support Edwards for release.

But, ideally, we should support both

**Comment by Bitcoinera** [comment]
Should we then close this? I have a branch with work started on this

**Comment by Bitcoinera** [comment]
Sneak peak:

<img width="460px" src="https://user-images.githubusercontent.com/40721795/80830501-5b158800-8be9-11ea-82aa-1a2126447280.png">

**Comment by jbibla** [comment]
as opposed to offering options, we should optimize for the happy path and provide the simplest experience possible with minimal UI changes. warnings should always be a last resort.

step 1 - user puts in any seed (12 words, 24 words, raw seed) and hits next
step 2 - on the "choose name" screen, there can be a little retry button next to the address with a tooltip that says "currently using schnorkel: try a different signature scheme". 
step 3 - if the user clicks this it will show the loading icon again and display a different address based on a new scheme.

<img width="582" alt="Screen Shot 2020-05-12 at 10 51 40 AM" src="https://user-images.githubusercontent.com/6021933/81707805-dd4e4980-943e-11ea-9f1e-2bc70b9c5c24.png">

**Comment by faboweb** [comment]
Retry button feels intransparent. How about a secondary drop down "Address wrong?" which reveals the schemas.

**Comment by Bitcoinera** [comment]
But how do we know the address is wrong? It is only the user who can know

**Comment by faboweb** [comment]
That is what I mean. If the user thinks the address is wrong, let him pick a different curve. But don't confuse him before

**Comment by jbibla** [comment]
i'm comfortable "hiding it" behind a tooltip because it's an advanced feature. i'd prefer not to make the average lunie user (happy path) doubt they have the right address.

**Comment by Bitcoinera** [comment]
So it would be then a button with a tooltip right? And the button would read "Retry"?

**Comment by jbibla** [comment]
> So it would be then a button with a tooltip right? 
i imagine a hoverable icon. the action could be triggered by clicking the icon or clicking a button inside the tooltip.

**Comment by Bitcoinera** [comment]
But how would newcomers know this icon is for that? It needs to be a very descriptive icon I imagine.

Can you upload some draft? 👀

**Comment by faboweb** [comment]
I feel against the retry. This is a concept no user understands I fear. Let's continue brainstorming.

**Comment by Bitcoinera** [comment]
What about a span that only appears on Kusama once you get the address (name step) and reads "Not your address?". Same styles than for the "Want to create another account?" span on extension.

You click it and it automatically derives the seed using the other algorithm. The span would stay.

Good UX right?

**Comment by faboweb** [comment]
That is the same as "Retry" which I think is confusing

**Comment by Bitcoinera** [comment]
🤔 I don't see why you find it confusing

**Comment by jbibla** [comment]
it's not a "retry" it's "use different signature scheme" - i think any user who inputs their seed and sees an unexpected address will consider looking for more information.

i agree with ana's thinking here.

there are only two opportunities to find out what scheme they are using - before and after.

**Comment by Bitcoinera** [comment]
I think it is much more natural to realize something went wrong afterwards, when you already got the address. Then you would see the "Not your address?" span, click it, and boom, right address (after the bit that polkadot/api always needs).

I see it super simple and straightforward. Also no options, just a click to change it if this address is not what you were looking for

**Comment by faboweb** [comment]
How about showing both addresses with a select/dropdown?

**Comment by faboweb** [comment]
"Retry" = something went wrong and you are doing the same action again expecting that it doesn't go wrong this time. Which is not the same here as the action actually changes.

**Comment by jbibla** [comment]
> How about showing both addresses with a select/dropdown?

this doesn't sound like reducing friction and complexity for our users. why should we make everyone choose?

**Comment by faboweb** [comment]
we would default to sr25519. the user can just continue

**Comment by jbibla** [comment]
> we would default to sr25519. the user can just continue

yeah i see what you're saying, however i think showing these options is going to be confusing for most people and will add unnecessary information for most cases.

**Comment by Bitcoinera** [comment]
Hey, I just came with a different solution for this.

What if what we do is that we by default derive with the two algos and in the name step we present both results, one above each other (like LiSessions). Then the user simply selects the correct one.

I can make later some dummy code to just "draw" what I mean, if you think it is needed

**Comment by faboweb** [comment]
Problem persists: We want to not present the user with options.

**Comment by Bitcoinera** [comment]
I think "Select your address" doesn't confuse at all? 🤷

**Comment by faboweb** [comment]
Which address should the user select? He doesn't necessarily know his address.

**Comment by faboweb** [comment]
I am not super opposed to "Select your address"

**Comment by Bitcoinera** [comment]
> I am not super opposed to "Select your address"

Let'd do it then!

@jbibla, what are your thoughts?

**Comment by jbibla** [comment]
i don't think giving users more options and more decisions to make is the right approach. this is the same as just asking them which algorithm they'd like to use. the point is that most users don't care and don't need to know. 

this is why i am proposing that we default to one (the one that will be most common) and let advanced users who necessarily have more context decide to override it if they know / care. my thinking is that this will address this complexity for most people, most of the time.

**Comment by jbibla** [comment]
> How about a secondary drop down “Address wrong?” which reveals the schemas.

let's do something like this: "Expecting a different address?" then if a user clicks it it should display the signature scheme in the top right of the input field, switch to loading state and display the new address. if the user clicks again it will go back.

**Comment by faboweb** [comment]
I could live with that.

**Comment by jbibla** [comment]
wow. only took a month!
