### ISSUE TITLE
Variable "$address" of non-null type "String!" must not be null on PageValidator

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3933]
This error seems to happen only in Kusama in PageValidator when you are not signed in.

Even though all queries have 
```
skip() {
return !this.userAddress
}
```

Mysterious

**Comment by Bitcoinera** [comment]
This is really strange. Not happening in production with the exact same code in `PageValidator`

**Comment by Bitcoinera** [comment]
Ah, coming from API for sure

**Comment by mariopino** [comment]
Very weird, spent some time debugging it and makes no sense :-/, tomorrow will be another day :-)

**Comment by Bitcoinera** [comment]
Yeah, for me the same today. I tried everything possible, and still it doesn't make any sense. Why is it different in Polkadot?

I will add the "needs help" tag.

**Comment by Bitcoinera** [comment]
We might end up helping ourselves 😅 maybe at some point we reach enlightment

**Comment by faboweb** [comment]
This comes from DelegationModal the logic in `totalStaked`

**Comment by Bitcoinera** [comment]
Oh wow!

**Comment by Bitcoinera** [comment]
Give me a sec and I try that
