### ISSUE TITLE
e-Money: hanging validator on Portfolio with 0 stake

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3968]
I don't know how to reproduce this, but on the famous e-Money faucet account I encountered this issue: a validator I unstaked all my funds from is still appearing in Porfolio:

![image](https://user-images.githubusercontent.com/40721795/80990334-76290780-8e36-11ea-9471-8fb97b0de1c6.png)

If I go to the validator's page, the "Unstake" button is disabled. Really worth investigating. Probably a very silly bug? 🤷

**Comment by Bitcoinera** [comment]
This is the e-Money faucet account: emoney1j7sq6dadld46vruk92r0se0tv0f3uc4pvl4ntd

**Comment by faboweb** [comment]
There might be less then 0.000001 stake on the validator. We should filter those out.

**Comment by Bitcoinera** [comment]
Nice, that was it
