### ISSUE TITLE
Multi-issue: styles glitches

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3971]
Here I will collect all the styles glitches in the new themes and will be editing the ones that are fixed. 

Basically it is going to be a list of screenshots:

<h2>Lunie (app):</h2>

The transaction icons look a bit weird. We should apply some filter over them:

<img width="410px" src="https://user-images.githubusercontent.com/40721795/80994614-33b6f900-8e3d-11ea-9145-8d0f2e76b7ed.png">

<hr>

Fixed in a PR to be merged:

![image](https://user-images.githubusercontent.com/40721795/80994652-403b5180-8e3d-11ea-860d-e9aa497c5db2.png)

**Comment by Bitcoinera** [comment]
@jbibla I choose you! xD

**Comment by jbibla** [comment]
most of these things are already fixed here: https://github.com/luniehq/lunie/pull/3960

**Comment by jbibla** [comment]
> Approved Transaction screen still has the old theme:

this should go in the extension repo

**Comment by Bitcoinera** [comment]
> most of these things are already fixed here: #3960

I left a comment

**Comment by Bitcoinera** [comment]
> > Approved Transaction screen still has the old theme:
> 
> this should go in the extension repo

True.. just wanted to have a multi-issue with all of them

**Comment by Bitcoinera** [comment]
Updated

**Comment by Bitcoinera** [comment]
One question: do we have now a default theme? `lunie-dark` right? Just to confirm

**Comment by jbibla** [comment]
it exists — i haven't tested it in lunie and it is not applied by default.

**Comment by jbibla** [comment]
i believe everything here is done after this is merged: https://github.com/luniehq/lunie-browser-extension/pull/210

**Comment by Bitcoinera** [comment]
> it exists — i haven't tested it in lunie and it is not applied by default.

Earlier today I tested it using `polkadot-testnet` without the theme there and it was again the weird white one

**Comment by Bitcoinera** [comment]
Only three items left! (maybe the voting thing is fixed?)

And the default theme I'd need to recheck but I think it is not fixed yet

**Comment by jbibla** [comment]
voting is fixed

**Comment by Bitcoinera** [comment]
OK, so we should close this one? Or better wait until we have that PR with the default theme merged

**Comment by jbibla** [comment]
we don't need a default theme in lunie app for now. let's close for now and open if this is an issue again.
