### ISSUE TITLE
kusama integration feedback

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3977]
> When I try to login, I need to agree that it’s a testnet address. Kusama shouldn’t be referred to as a testnet, see the following article https://medium.com/polkadot-network/kusama-polkadot-comparing-the-cousins-170e4fe6c280.

> “Waiting for confirmation from polkadot-testnet” should be changed. It’s not a testnet see above ;-).

i guess we'll just call it a mainnet of sorts. let's switch the chain-id to `kusama` or `polkadot-canary` instead of `polkadot-testnet`?

> On Kusama it only takes 7 days to unlock your tokens and not 21 (notification when I stake)

simple fix. let's update the language. ideally, we would pull this from somewhere instead of hardcoding — but for now let's just adjust the message assuming cosmos is 21 and polka/kusama is 7.

> When I click on stake or sending tokens it doesn’t show any transaction fee, but it removes the fee.

bug?

> Staking doesn’t seem to work. “No validators in your portfolio” 

bug again?

> KSM currently has no currency on android, even though it let’s you select Euro, Dollar, etc.

does coingecko have KSM support?

> I think a 1) transaction history or an 2) address book would be super useful.

1) let's change the message on the success screen in the action modal to link to the activity page instead of the block page.

2) one day @michielmulders 

> The recovery feature seems to be loading the address forever and if I just continue with the password and click on create it’s say unreachable.

bug again?

**Comment by Bitcoinera** [comment]
`Staking doesn’t seem to work. “No validators in your portfolio”`

This one is very strange... Maybe this was before we fixed it?

`I think a 1) transaction history or an 2) address book would be super useful.`

This is another milestone and another grant ;)

**Comment by jbibla** [comment]
> This one is very strange... Maybe this was before we fixed it?

probably the same issue you reported yesterday. sometimes the portfolio is empty.

> This is another milestone and another grant ;)

correct!

**Comment by Bitcoinera** [comment]
`Staking doesn’t seem to work. “No validators in your portfolio”`

I think this due to API restarting and validators not being loaded yet. I kind of confirmed. But for them it was probably one of the other bugs we fixed during the weekend. There were so many I cannot remember xD

**Comment by Bitcoinera** [comment]
> 1. let's change the message on the success screen in the action modal to link to the activity page instead of the block page.

Should this be done for all networks or just Kusama?

**Comment by faboweb** [comment]
> Should this be done for all networks or just Kusama?

For all networks

**Comment by Bitcoinera** [comment]
Only missing #3997
