### ISSUE TITLE
Create PageTransaction

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3979]
This is a very important missing piece in our app and actually quite easy to do.

Push notifications for transactions would redirect here.

**Comment by faboweb** [comment]
We are working with Charlie on the designs rn

**Comment by Bitcoinera** [comment]
Let's do this!! 💪 🔪

**Comment by jbibla** [comment]
> 🔪

lol

**Comment by jbibla** [comment]
when this page exists i would also like to link here instead of the block page on action modal success screens. also, we'll need to modify existing txs to link to this full page. right now, click will open the drawer - so we'll need another clickable area or to think about the ux.

**Comment by Bitcoinera** [comment]
> also, we'll need to modify existing txs to link to this full page. right now, click will open the drawer - so we'll need another clickable area or to think about the ux.

I'd say the hash can serve as the link to the full PageTransaction. What do you think?

**Comment by faboweb** [comment]
or the PageTransaction is actually an overlay that opens when you click on the tx
if the user goes to /transactions/HASHXYZ the activity page opens and the modal for that tx
just sharing ideas

**Comment by Bitcoinera** [comment]
> or the PageTransaction is actually an overlay

This is what I was thinking today actually 🤩 

It happened again OMG (with a week delay but ok)

![fiba3x3-olympics-fiba-3x3-dsKyNUcVeMlnLk8P9l](https://media.giphy.com/media/4NgzOc3sZRHeIWkd3J/giphy.gif)

**Comment by Bitcoinera** [comment]
OK, I actually would love to do this! And yeah, I would go with overlay

**Comment by jbibla** [comment]
i have a slight preference for a standalone page.

**Comment by faboweb** [comment]
> would we expect this feature to work if the activity page is not implemented?

if we have the ability to show all transactions, we can also have the activity page. so I think they go hand in hand.

**Comment by faboweb** [comment]
why do you prefer a standalone page?

**Comment by jbibla** [comment]
we see a lot of users linking theses individual pages. if ours is a modal loaded on top of the activity page it will be slower (will load txs behind modal and have to spring the modal up).

**Comment by faboweb** [comment]
true. let's do an individual page then.

**Comment by Bitcoinera** [comment]
Yes, still relevant. We are just a small team :wink:

**Comment by Bitcoinera** [comment]
Some day, little bot

**Comment by jbibla** [comment]
revisiting this - i feel we should not do this and should instead link to a block explorer... and even consider not doing the transactions page anymore as well.

less is more!

**Comment by Bitcoinera** [comment]
Yes, it would be a huge investment. Specially if we host more networks. How to fit extrinsics in... Probably we should just link to Polkascan (or Polkastats!) in the success modal

**Comment by jbibla** [comment]
definitely polkastats @mariopino

**Comment by Bitcoinera** [comment]
One day, stalebot

**Comment by faboweb** [comment]
Let's close for now as we are thinking of getting rid of the explorer feature
