### ISSUE TITLE
Problems with push notifications not showing up in Brave browser (M2)

### ISSUE THREAD

**Issue by michielmulders** [luniehq/lunie#3982]
**Describe the bug**
Need more testing on push notifications for the Brave browser.
Check if this solution about enabling notifications works.

![image](https://user-images.githubusercontent.com/26482710/81160023-e300e680-8f89-11ea-906f-1bb2fa57b8b0.png)

If yes, display a popup bar in app.lunie.io to educate the user about this.

**Comment by michielmulders** [comment]
https://community.brave.com/t/brave-dont-show-me-notification/69618

**Comment by Bitcoinera** [comment]
I enabled Google Services for Push Notifications and disabled my shields for localhost:9080 and still didn't get any notification...

**Comment by Bitcoinera** [comment]
![image](https://user-images.githubusercontent.com/40721795/81167596-c23e8e00-8f95-11ea-969b-eb5e9917816b.png)

🤷

**Comment by jbibla** [comment]
so this was a pretty big oversight. we have a lot of brave users. how complex would it be to switch to a different notifications service?

an alternative idea: we could use the Lunie API to send messages / notifications that we display in Lunie with HTML / CSS. 

the most important notifications will be email and push to mobile devices. but this is kind of unfortunate.
