### ISSUE TITLE
Kusama: all validators are ACTIVE

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3987]
Bug discovered by Mario yesterday. Suddenly there are no inactive validators in Kusama:

![image](https://user-images.githubusercontent.com/40721795/81186282-e9578880-8fb2-11ea-8df1-eb56e29a35e2.png)

We need to investigate this

**Comment by faboweb** [comment]
Does that coincides with the validators sometimes missing?

**Comment by mariopino** [comment]
I think this was caused by a local problem, later I was able to see inactive ones. 

I can see inactive val. now in https://develop--lunieio.netlify.app/kusama/validators so assuming this was a demo issue ^^
