### ISSUE TITLE
Kusama Portfolio: String cannot represent value: []

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#3998]
Getting this with latest develops on Kusama Portfolio:

![image](https://user-images.githubusercontent.com/40721795/81328989-1a60b780-909e-11ea-9c74-66fe204a36f4.png)

**Comment by Bitcoinera** [comment]
Also I cannot see any validator xD

**Comment by faboweb** [comment]
@mariopino returns calculation breaks?

**Comment by mariopino** [comment]
Ouch, seems to!

**Comment by mariopino** [comment]
I see in staging-db that expectedReturns is still NULL for all validators, maybe we need to clean the table?
