### ISSUE TITLE
Claim rewards fees take a LOT of time to load

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4000]
It took longer than a minute to load...

Maybe we should hardcode at least for this one?

<img width="440px" src="https://user-images.githubusercontent.com/40721795/81335272-a3302100-90a7-11ea-8976-547a54a69a15.png">

**Comment by jbibla** [comment]
yep good call.

but this is not part of M1 or M2!

**Comment by faboweb** [comment]
good call. Problem is transaction might fail if the user doesn't have enough to pay for fees. but we can disable it for now.

**Comment by faboweb** [comment]
https://github.com/luniehq/lunie/pull/4001

**Comment by Bitcoinera** [comment]
> yep good call.
> 
> but this is not part of M1 or M2!

But it was on their feedback... Agree on some bonus 😅 🤷

**Comment by Bitcoinera** [comment]
I think I will close it. We already know it is the way it is 🤷

**Comment by faboweb** [comment]
I would love to see the performance improved here when we find a minute.
