### ISSUE TITLE
Mobile App E2E testing

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4011]
**Is your feature request related to a problem? Please describe.**

We need to test if apps start properly.

**Describe the solution you'd like**

We can do this as well with Browserstack and Appium the same way we do for the browser.

https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/debug-test/appium-setup?view=toolsforcordova-2017
https://www.browserstack.com/app-automate/appium-webdriverio

In Bitrise we can use the environment variable $BITRISE_APK_PATH after the app was created to upload the APK

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
Why do you think this is necessary & What specific errors are you aiming for?

**Comment by faboweb** [comment]
I want to avoid publishing an app that doesn't open.

**Comment by Bitcoinera** [comment]
Good point 😉
