### ISSUE TITLE
Allow actions based on the account type in Polkadot

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4017]
In Polkadot there are 2 account types: Stash and Controller. In Lunie we set both to be the same. But certain actions need certain account types. If not signing will fail.

TO DO:
1. PR
- [x] identify account type when logging into a Polkadot network
2. PR
- [ ] if Stash account and not the controller account for that account, disable delegation to validators (keep bonding enabled, disable validator selection)
- [ ] if Stash account and not the controller account for that account, show a warning "For staking to validators you need to sign in with your controller account ACCOUNT HERE. You can still stake tokens."
- [ ] if Controller account show a warning on the portfolio: "this is a controller account, if you want to see your validators, sign in with your stash account."
3. PR
- [ ] check batch message construction to not include the wrong tx

**Comment by faboweb** [comment]
ping @jbibla for wording

**Comment by Bitcoinera** [comment]
> if Stash account, disable delegation to validators (keep bonding enabled, disable validator selection)

How would this go? "Stake" button on the valitador page disabled right

**Comment by Bitcoinera** [comment]
I'm struggling with the first one xD

**Comment by faboweb** [comment]
> > if Stash account, disable delegation to validators (keep bonding enabled, disable validator selection)

> How would this go? "Stake" button on the valitador page disabled right

@jbibla any idea for the UI? I would on a stash account set the validator to undefined.

**Comment by jbibla** [comment]
would the simplest thing be to identify stash accounts and block all staking related transactions? staking modal would pop up and say — "sorry this is stash account - please use a controller account you polka-ninja".

we could get more complex and try to cover all the edge cases but i'd start like this probably.

**Comment by Bitcoinera** [comment]
I love polka-ninja! 😍

**Comment by faboweb** [comment]
@jbibla ping re messaging for PR3
@Bitcoinera can you take care of PR3?

**Comment by mariopino** [comment]
### **Possible cases (updated!)**

- **stash/controller**: same address is controller and stash, all actions allowed.

```
const address = `Ckus4fsdJHxVg69FMDPVbqre3cLUc5R6fWxkMR1HuyQC1Dk` // controller address = stash address
const bond = await api.query.staking.bonded(address)
if (bond === address) {
  console.log(`Address ${address} is stash/controller`)
}
```

- **controller**: address is a controller (!= stash), all actions allowed, currently we can not see the delegations, as they are indexed by stash and we can not derive the stash from controller yet (see NOTE2).

```
const address = `EksmaF7D2fWWjcX9LvZ48g9j1y4TpexY2ixNraHTfMWRton` // controller address
const bond = await api.query.staking.bonded(address)
if (!bond) {
  console.log(`Address ${address} can be either a controller or a address with no bonded funds`)
}
```

**NOTE**: We can not distinguish a controller from a address without bond (so no controller is set yet)

**NOTE2**: Actually we can derive stash from controller using a dictionary like that:

```
const t1 = new Date().getTime();
const bonded = await api.query.staking.bonded.entries();
let count = 0;
bonded.map(([key, bond]) => {
  console.log(`stash: ${key.toHuman()[0]} controller: ${bond}`);
  count++
});
console.log(count);
const t2 = new Date().getTime();
console.log(`exec time: ${(t2 - t1)/1000} seg`);
```
- **stash**: address is a stash (!= controller), no staking is allowed but user still can send tokens.

```
const address = `FPSTat7A7pkuMK6kfvsXX8xs5xqpbczitsYLaViKPmWyUYG` // stash address
const bond = await api.query.staking.bonded(address)
if (bond && bond !== address) {
  console.log(`Address ${address} is a stash`)
}
```

- **none**: no controller is set, all actions allowed, in this case we just need to set the controller in the staking tx (as we already do) so it should be converted to a stash/controller type. This is the case when we create a account in Lunie.


**NOTE**: We can not distinguish a controller from a address without bond (so no controller is set yet)

```
const address = `DLUnieSNaqu2FTvyEUQNXTjdjkYNmnCxvqYZtKw3QKMRqr4` // address with no controller set
const bond = await api.query.staking.bonded(address)
if (!bond) {
  console.log(`Address ${address} can be either a controller or a address with no bonded funds`)
}
```

- **undefined**: for non polkadot networks.

**Comment by mariopino** [comment]
Proposed plan (only way to distinguish controller from none!):

- Add a query to Lunie API to allow get the polkadot address role (It can last up to 10s).

Frontend:

- When user signing user role is undefined, in this case only send tokens is allowed, then we call API to get polkadot address role, when role is returned we save it on store/session so then we can filter the actions based on it.

**Comment by faboweb** [comment]
when an account is created in Lunie we can assume it is stash/controller
when an account is imported we can assume it is already in the store. no need to wait

**Comment by faboweb** [comment]
> Add a query to Lunie API to allow get the polkadot address role (It can last up to 10s).

this can be done together with the block handler in parallel to the rest
