### ISSUE TITLE
App menu style glitch on develop when using developer tools

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4033]
![Screen Shot 2020-05-13 at 11 50 43 AM](https://user-images.githubusercontent.com/1614127/81835358-29b58a00-9510-11ea-9e7a-5674952998c9.png)

When using the develop link I am seeing a glitch when Google Tools inspect is open

The only way to use many of the menu items is by clicking a three dot dropdown, otherwise most functionality is hidden while dev tools are open. 

This is on my external monitor and Macbook Pro

**Comment by jbibla** [comment]
can you share a screenshot of the whole window, not just lunie?

**Comment by jrmoreau** [comment]
![Screen Shot 2020-05-13 at 12 04 31 PM](https://user-images.githubusercontent.com/1614127/81836764-ecea9280-9511-11ea-8ff8-2bab159bf502.png)

here it is @jbibla !

**Comment by jbibla** [comment]
i don't understand what you're reporting 😅

**Comment by jrmoreau** [comment]
@jbibla when I was debugging with @Bitcoinera I had opened the console/dev tools which changed the screen from this:

![Screen Shot 2020-05-13 at 12 28 54 PM](https://user-images.githubusercontent.com/1614127/81839322-6041d380-9515-11ea-88b9-4f6159ae1a36.png)

to this:

![Screen Shot 2020-05-13 at 12 29 09 PM](https://user-images.githubusercontent.com/1614127/81839348-68017800-9515-11ea-991d-9fcda1505d14.png)

 Individual token send buttons are gone and sidebar is gone. You need to click the three dot dropdown menu to get the sidebar and there's only one send button.

**Comment by Bitcoinera** [comment]
This is an UX problem... those three dots are kind of hidden. This would be on tablet view.

I will try later installing Lunie on my tablet and see how that looks like

**Comment by jbibla** [comment]
got it. so some opportunities here to improve responsiveness of lunie. yep!
