### ISSUE TITLE
refactor TmPage

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4042]
**Is your feature request related to a problem? Please describe.**

- padding is inconsistent across pages
- there is some unused code
- css may be duplicated / not in the correct component file

**Comment by faboweb** [comment]
> padding is inconsistent across pages

padding is missing on the page component

> there is some unused code

take balance header out (consider balancesV2)

> css may be duplicated / not in the correct component file

page styles should be in this component imo not in global styles
