### ISSUE TITLE
Add CoinGecko acknowledgement "Powered by CoinGecko API" to currency modal (when it exists)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4044]
We should add this acknowledgment as requested in their site https://www.coingecko.com/en/api to thank them for offering us their really nice fiatValues API for free.

Especially now that they listed as a wallet! :tada

**Comment by Bitcoinera** [comment]
We should do this as we could also get Lunie on the CoinGecko page. Symbiosis

**Comment by jbibla** [comment]
>  Lunie on the CoinGecko

already done.

---

we can add this to our new settings page when we have one

**Comment by Bitcoinera** [comment]
> already done.

I don't see us... :eyes: But I see Cosmostation :hocho: :fire: 

![image](https://user-images.githubusercontent.com/40721795/85340435-63ea5200-b4e6-11ea-9dde-50f2cba66c4c.png)

**Comment by Bitcoinera** [comment]
Waiting to have one of these components to get this done:

- a settings page (which we don't have yet) OR 

- a fiat currency selector modal

**Comment by Bitcoinera** [comment]
It is probably to take a while until we have those things, right?

**Comment by jbibla** [comment]
> a fiat currency selector modal

i started working on this actually!

**Comment by Bitcoinera** [comment]
> i started working on this actually!

yeeeey!! :tada:

**Comment by Bitcoinera** [comment]
Mmm, what is happening here? Yeah, low-priority but would be great to be among that list

**Comment by Bitcoinera** [comment]
I wouldn't close this one. It is actually quite easy to do and we would get a good deal of promotion getting into that list

**Comment by jbibla** [comment]
let's add this when change how currency selection works!

**Comment by Bitcoinera** [comment]
Ah, I didn't know we were going to change that. Yes, cool, good idea. How will the new design / flow look like?

**Comment by jbibla** [comment]
probably a modal or user settings page. not a high priority for now.
