### ISSUE TITLE
Add fee denom selector on feesStep in ActionModal

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4050]
Many users have requested this and I think it is also something our competitors allow: we should enable a fee selector so users can set their fee.

Some challenges:
- Kava and e-Money don't allow discounts: so going any lower than gasEstimate * gasPrice always results in an error and inability to broadcast.

- Some transactions will result in out of gas errors and users will only notice when they cannot find that transaction. Maybe we should capture this errors in the polling logic of our API and display some message in FE. But probably we'd need notifications working to do this properly

**Comment by faboweb** [comment]
This is not what I meant. I meant selecting the denom in which you pay fees.

**Comment by Bitcoinera** [comment]
Oh I see xD well, now it is done in an automatic way. Defaults to staking denom and if you don't have any then you pay in the next balance in the balances Array with funds

**Comment by faboweb** [comment]
regarding the emoney issue with paying fees: you should probably adjust the logic:

IF emoney AND user doesn't have enough of the current fee denom to pay the fees THEN pick the first denom he has enough to pay for fees ELSE show current fee denom and a warning that he doesn't have enough to pay for fees

**Comment by Bitcoinera** [comment]
Sounds like a great idea! Let's first merge #4043 and I will open a new PR to enable this
