### ISSUE TITLE
Unable to send KRT using Lunie Mobile on Terra

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4068]
**Describe the bug**
User shows that they cannot send any amount of KRT even though they have an adequate balance. 

**To Reproduce**
User inputs any amount to send in KRT, gets error
Tried to send full balance of 2590 KRT got
`Sending tokens failed: Broadcast was not successful: insufficient fees to pay for taxes; 18130000ukrw < 18777500ukrw.
`

Tried to send 1000 KRT and got `Sending tokens failed: Broadcast was not successful: insufficient fees to pay for taxes; 7000000ukrw < 7250000ukrw.`

**Expected behavior**
No matter what amount user enters to send in KRW, they are told they don't have enough to pay for fees and tax

**Screenshots**
![terra](https://user-images.githubusercontent.com/1614127/82243254-46d1ca80-990d-11ea-915b-43c5f67d739f.jpeg)
![terra1](https://user-images.githubusercontent.com/1614127/82243256-46d1ca80-990d-11ea-8258-5fc832ab4053.jpeg)
![terra2](https://user-images.githubusercontent.com/1614127/82243258-46d1ca80-990d-11ea-85fe-f3d4a05b6aa2.jpeg)

**Smartphone (please complete the following information):**

 - OS: Android 10

![mobile](https://user-images.githubusercontent.com/1614127/82241145-a4fcae80-9909-11ea-9735-c79f8d26d759.jpeg)
![mobile1](https://user-images.githubusercontent.com/1614127/82241162-aaf28f80-9909-11ea-968e-cde5c20edc3c.jpeg)

**Comment by Bitcoinera** [comment]
Ok, thank you for this James.

The underlying reason is quite simple: https://lcd.terra.dev/treasury/tax_rate

The tax rate is dynamically increasing now by 0.00025 quite often.

Solution: instead of hardcode them, fetch this value regularly for API. Easy. Will do now

**Comment by Bitcoinera** [comment]
This has been released to master @jrmoreau . So the user should now be able to perform the transaction

**Comment by jrmoreau** [comment]
Indeed - they tried again this morning and it worked. Solved. Thank you!
