### ISSUE TITLE
Claim Rewards disabled for Kava-mainnet

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4077]
I was QAing with James and this is the only bug we could find. 

![image](https://user-images.githubusercontent.com/40721795/82351336-becaee00-99fc-11ea-8de3-c73803318e63.png)

As a side note, `kava-testnet` endpoint is currently down but will soon be up

**Comment by faboweb** [comment]
because there are no rewards?

**Comment by Bitcoinera** [comment]
I debugged a little bit and there was some weird undefined in `readyWithdraw`. Probably a very easy fix

**Comment by Bitcoinera** [comment]
OK, yeah, you were right. I got no rewards 🤷  So it is not a bug. Just hard to get rewards on this network apparently
