### ISSUE TITLE
Confusing validation message in stake using a stash account in polkadot

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4108]
**Describe the bug**

We see the validation message `You are about to stake to an inactive validator (Validator is online and generating rewards)` when staking using a stash account in polkadot.

**To Reproduce**

**Expected behavior**

Don't show the message.

**Screenshots**

![image](https://user-images.githubusercontent.com/9256178/82611417-ca671200-9bc0-11ea-95ad-b3c33391cdea.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by faboweb** [comment]
Probably remove the whole "to" sectoin

**Comment by mariopino** [comment]
> Probably remove the whole "to" sectoin

Finally opted to keep it to maintain ux consistent, btw problem was caused by a dumb bug (my fault ^^).

**Comment by mariopino** [comment]
Closing in favor of #4110
