### ISSUE TITLE
kusama ux improvement ideas

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4110]
1) signed in with stash only account
<img width="952" alt="Screen Shot 2020-05-21 at 6 21 45 PM" src="https://user-images.githubusercontent.com/6021933/82612041-eef6c600-9b8f-11ea-9733-bebfa2e882de.png">

`To: --` probably doesn’t even need to be on the modal. let’s v-if it!

`From` styling is broken. i think we should also stay consistent and hide all the characters in the address except for the first 4 and last 4 on this screen.

`Amount` should not say "(Optional)" because it's not for stash only addresses

2) signed in with controller only account
<img width="1323" alt="Screen Shot 2020-05-21 at 6 24 18 PM" src="https://user-images.githubusercontent.com/6021933/82612200-4ac14f00-9b90-11ea-9e2a-70a06d77f840.png">
- let's change this message to something like “controller addresses don’t “have” validators — use your stash account to see your validator portfolio”"
- let's add the "stake" button beside the "send" button (charlie has designs for this). this should appear for stash+controller and controller (but not stash only)

<img width="721" alt="Screen Shot 2020-05-21 at 6 25 18 PM" src="https://user-images.githubusercontent.com/6021933/82612268-6f1d2b80-9b90-11ea-84be-c7c79408e8b2.png">
- let's hide the `amount` field
- `From` doesn't need to be a dropdown

**Comment by Bitcoinera** [comment]
> let's change this message to something like “controller addresses don’t “have” validators — use your stash account to see your validator portfolio”"

This isn't true since we merge luniehq/lunie-api#775. Now you can see your delegations with a controller address
