### ISSUE TITLE
validator voting power --

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4112]
1) is `--` correct?
2) either way it should be weighted as 0

<img width="946" alt="Screen Shot 2020-05-22 at 8 35 05 AM" src="https://user-images.githubusercontent.com/6021933/82668175-3704ff80-9c07-11ea-83ce-98f9608d0abe.png">

**Comment by Bitcoinera** [comment]
I don't think "unknown" should be considered same as `0`. If you display `0`, you are stating that you know the expected returns percentage for that validator, but in this case we don't know

**Comment by faboweb** [comment]
The rewards should display though as @mariopino implemented that already

**Comment by mariopino** [comment]
Validators with `--` rewards were not online in the last era.

I also think that displaying `--` is the best way, the problem is that the default validator order is reward (desc) and we are showing those validators on top, which is maybe not super effective.

Maybe we can tweak ordering to place `--` at bottom?

**Comment by mariopino** [comment]
> Validators with `--` rewards were not online in the last era.
> 
> I also think that displaying `--` is the best way, as we need to distinguish from i.e validators with 100% commission which gives you an effective 0% reward.
> 
> I think the problem is that the default validator order is reward (desc) and we are showing those validators on top, which is maybe not super effective.
> 
> Maybe we can tweak table ordering to place `--` at bottom?

Returning an empty string instead of `undefined` in API for `expectedReturns` seems to do the trick, placing `--` after `0%` in validators table.
