### ISSUE TITLE
Bug in Unstake using a controller address in polkadot

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4145]
**Describe the bug**

- When we sign in using a controller address and we want to unstake, it allows you to continue if the amount is 0, this should never happen. 
- Set max button does nothing when you want to unstake from a validator you are not actively staking.

**Expected behavior**

- Validation should fail in that case preventing user to continue.
- Set max button should set the total bonded amount in all cases.

**Comment by faboweb** [comment]
Agreed
