### ISSUE TITLE
Implement Firebase auth

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4147]
AC:
Developer is able to sign in to Lunie and the sign in state is visible in the store.

Ref
https://garywoodfine.com/vue-app-with-firebase-authentication/
https://firebase.google.com/docs/auth/web/email-link-auth

Add your own project to test to FIrebase
Add firebase credentials via env variable `VUE_APP_GOODLE_AUTHENTICATION`

Add module user
In outer function init firebase with the credentials
Call authentication callback in user.js in outer function
Dispatch calls `userSignedIn` and `userSignedOut`
Set user name in user.js via `setUserInformation`
Add action `signInUser` which triggers a magic link authentication via firebase
Add action `signOutUser` which triggers firebase sign out and removes the set user.

Add page "Successfull sign up" to `/email-authentication`. Don't invest in styles.

In initializeApp check if the link is a signup link and forward in that case to `/email-authentication`. 

To test add email input and sign in button to the portfolio and dispatch `signInUser` with the email. Flag with experimental. Don't invest in any styling.

**Comment by Bitcoinera** [comment]
`userSignedOut` is not really necessary no? It would be `state.userSignedIn === false`

**Comment by Bitcoinera** [comment]
I don't see here anything about a callback or Firebase sign in state handler xDD

**Comment by Bitcoinera** [comment]
https://github.com/luniehq/lunie/pull/4242#discussion_r438160162

I didnt ignore anything, it is not here :innocent:
