### ISSUE TITLE
Add authentication to apollo

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4149]
**Is your feature request related to a problem? Please describe.**

We want to know if client side signed in users are actual users in the API.

**Describe the solution you'd like**

We send the users uid as a header in apollo.
https://medium.com/risan/set-authorization-header-with-apollo-client-e934e6517ccf
Get the token of the user via `await firebase.auth().currentUser.getIdToken()`

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
This is actually done? Or what is it missing here exactly?

What we should start doing once #4275 is merged is adding some kind of routerGuard rule for premiums right (related to paywall)

**Comment by faboweb** [comment]
Where is this already implemented?

**Comment by Bitcoinera** [comment]
> Where is this already implemented?

OK, maybe I misread a little bit :sweat_smile: Mistook with the uid token verification on storeUser

**Comment by Bitcoinera** [comment]
I want to do this! :star_struck:
