### ISSUE TITLE
new sidebar and menu changes causes overlap of session window at certain screen sizes

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4150]
<img width="1019" alt="Screen Shot 2020-05-26 at 8 18 28 PM" src="https://user-images.githubusercontent.com/6021933/82962410-28637300-9f8e-11ea-83ed-aa9002803c77.png">

**Comment by Bitcoinera** [comment]
This time it is not me 😛

**Comment by faboweb** [comment]
Is this still a problem?

**Comment by Bitcoinera** [comment]
I think it is not. Just checked
