### ISSUE TITLE
Move balances, rewards queries to Store (and probably also delegations & undelegations) 

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4157]
**Is your feature request related to a problem? Please describe.**

I think in itself it helps code reduction and simplification, gives us more control (same query all accross the app, not five different skips, missing `updates` and so on...). So I think it is good in itself.

But also could be a final solution for the bugs we are currently experiencing with mixing balances both in TmBalance and ActionModal from different networks / sessions. 

**Describe the solution you'd like**

Move all session/account related queries (balances, rewards, delegations and undelegations) to store. To the session module concretely.

To update these values we would have like now, in `blockAdded` in TmBalance, except instead of an `$apollo.refetch` it would be a `$store.dispatch`

**Describe alternatives you've considered**

Leave it like it is? We have four balances queries across Lunie. Probably they get cached, but we are not so sure how this actually works. And why have code replication?

**Additional context**

**Comment by Bitcoinera** [comment]
Another error related to the same, rewards not being updated in this case across networks:

![image](https://user-images.githubusercontent.com/40721795/83136188-57412c80-a0e7-11ea-83e2-42fabad284c5.png)

If we go to the function, we see that it is searching for a reward that matched the stakingDenom, but the rewards it is searching in are the old ones, from another network, so it cannot find any and thus these errors:

```
    filterStakingDenomReward() {
      if (this.rewards && this.rewards.length > 0) {
        const stakingDenomRewards = this.rewards.filter(
          (reward) => reward.denom === this.stakingDenom
        )
        return stakingDenomRewards[0].amount
      }
    },
```

**Comment by Bitcoinera** [comment]
So we are going for it?

Or for now we fix all this with the dynamic refs?

I'd go for it

**Comment by jbibla** [comment]
up to you and @faboweb

**Comment by faboweb** [comment]
Let's find the actual bug.

**Comment by Bitcoinera** [comment]
> Let's find the actual bug.

OK, and after that we do this! 🤩 Because it is just cleaner

**Comment by Bitcoinera** [comment]
I think we really should do this

**Comment by mariopino** [comment]
I like this solution, should improve UX and reduce the number of API queries.

**Comment by Bitcoinera** [comment]
I still think this makes more sense than the current architecture

**Comment by faboweb** [comment]
https://github.com/luniehq/lunie/issues/4157#issuecomment-636903834

:P I don't think creating an own apollo caching implementation will be cleaner than theirs

**Comment by Bitcoinera** [comment]
> :P I don't think creating an own apollo caching implementation will be cleaner than theirs

I just think it is cleaner, more beautiful architecture and gives us more control over everything :shrug:

**Comment by Bitcoinera** [comment]
Well, maybe this is not something we will have the time to do for a long time, so closing for now.
