### ISSUE TITLE
Make 'setMaxAmount' in action modals "smart" (discount fees)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4159]
Fees are now going to live exclusively in ActionModal.

We need to find a good way to make the `setMaxAmounts` functions in the modals take them into account

**Comment by faboweb** [comment]
You can still query the fees in the sendmodal using Apollo? We can cache the response a minute or so (server side)

**Comment by Bitcoinera** [comment]
> You can still query the fees in the sendmodal using Apollo? We can cache the response a minute or so (server side)

Yeah, true
