### ISSUE TITLE
User cannot claim rewards on Cosmos Hub with browser extension

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4166]
**Describe the bug**
this is the error
`Withdrawal failed: Cannot read property 'chainToViewConversionFactor' of undefined.`

![error](https://user-images.githubusercontent.com/1614127/83196158-646f1300-a109-11ea-9184-bd3d80cba1f6.jpg)

**Comment by jrmoreau** [comment]
@faboweb @Bitcoinera pinging you for visibility

**Comment by faboweb** [comment]
This is still the case?

**Comment by jrmoreau** [comment]
As of Friday it was.

**Comment by Bitcoinera** [comment]
I insist this is the same bug we've been having since the slack navbar introduction: our queries are bringing data from other networks in.

So, in this case, the user had another network in the FE and when it checked for a network with that network-id, it was undefined

**Comment by faboweb** [comment]
Can you try to reproduce?

**Comment by Bitcoinera** [comment]
I have been trying but wasn't able 🤔 Strange
