### ISSUE TITLE
proposal voting modal in Kava selection not working

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4169]
**Describe the bug**
Clicking any of the voting model options does not show as selected, which makes it unclear if you selected the right option before proceeding. 

**To Reproduce**
![Screen Shot 2020-05-29 at 11 03 51 AM](https://user-images.githubusercontent.com/1614127/83274798-41da0a00-a19c-11ea-8476-7f2826188984.png)

**Expected behavior**
When you click it should shade/change colors to indicate which option you chose

**Comment by jrmoreau** [comment]
@Bitcoinera FYI, maybe we missed this when doing QA? Seems like a simple fix?

**Comment by Bitcoinera** [comment]
> @Bitcoinera FYI, maybe we missed this when doing QA? Seems like a simple fix?

Weird, I remember QAing this. Will recheck. It is a styles bug then
