### ISSUE TITLE
User cannot claim rewards with Ledger Nano X network fee showing 0

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4171]
**Describe the bug**
User says they cannot claim rewards using their Ledger Nano X and the network fee is showing 0

**To Reproduce**
user did a hard refresh, logged out, cleared cache and problem persists. 

![IMG_1865](https://user-images.githubusercontent.com/1614127/83279454-1eff2400-a1a3-11ea-99a8-2e337abd45f2.JPG)

ledger firmware is 1.2.4-1
cosmos is 2.12.0
Using Mac OS Catalina version 10.15.4 
chrome version 81.0.4044.138

**Comment by jrmoreau** [comment]
@faboweb let me know if you need any other info from the user on this

**Comment by faboweb** [comment]
This issue should be fixed. This was an API issue which got resolved

**Comment by jrmoreau** [comment]
They emailed support again today saying it wouldn't work, which prompted me to login and check. 

Let me ask them if a hard refresh fixes it. I didn't know the API issue was resolved.

**Comment by jrmoreau** [comment]
Sorry @faboweb as of yesterday morning it still wasn't working for them

**Comment by Bitcoinera** [comment]
I cannot reproduce it, at least in Gaia. I also have a Ledger Nano X. Fees are displayed correctly.

What versions are they using for both Ledger firmware and Cosmos app?

**Comment by jrmoreau** [comment]
@Bitcoinera versions noted in the issue:

ledger firmware is 1.2.4-1
cosmos is 2.12.0
Using Mac OS Catalina version 10.15.4
chrome version 81.0.4044.138

**Comment by faboweb** [comment]
Fee showing 0 should be fixed

**Comment by Bitcoinera** [comment]
I think this is fixed
