### ISSUE TITLE
Claim Rewards transactions are shown as "Unknown" in Kava

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4177]
They work but appear as "Unknown" in out block explorer and therefore claimed rewards are not displayed:

![image](https://user-images.githubusercontent.com/40721795/83421959-2172af80-a429-11ea-9356-9a5dedfa38b1.png)

**Comment by faboweb** [comment]
Mapping for kava transactions in the API broke?

**Comment by Bitcoinera** [comment]
I will check right away. Probably they are messing with types again
