### ISSUE TITLE
Annoying TypeError: Cannot read property 'feature_portfolio' of undefined

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4188]
**Describe the bug**

We are frequently get this error in Sentry. As @faboweb the problem is related with a non existent route.

**Example report:**

https://monitoring.lunie.io:9000/lunie/frontend/issues/815/?referrer=slack

**Proposed plan:**

Implement a route guard for path `/:networkId` that checks that first URL parameter is a valid network slug, if not redirect to 404 page.

**To Reproduce**

Open the URL: https://app.lunie.io/123

**Expected behavior**

To show 404 error page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by michielmulders** [comment]
Prefer redirecting to the network selector page instead of displaying a 404. A 404 doesn't help a user much further whereas the network selector does.
