### ISSUE TITLE
Kusama transaction message creation & signing is too slow

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4191]
Move `kusama.js` to API to speed up Polkadot transactions flow.

Make it in a way that doesn't break extension (should just deprecate the Polkadot parser)

**Comment by faboweb** [comment]
I don't get what you want to do here. Can you clarify what problem you want to solve?

**Comment by Bitcoinera** [comment]
> I don't get what you want to do here. Can you clarify what problem you want to solve?

What we briefly talked about in the meeting today. Transaction message creation & signing is too slow to do it for Polkadot client side. Let's do it in the BE

**Comment by faboweb** [comment]
> What we briefly talked about in the meeting today. Transaction message creation & signing is too slow to do it for Polkadot client side. Let's do it in the BE

That is dangerous as an attacker could send a wrong tx to sign

**Comment by Bitcoinera** [comment]
True... how to speed things up in the FE then? Or should we do the emoji/GIF thing? 🤩 

Entropyyyy

**Comment by faboweb** [comment]
Instead we should connect to the API as soon as possible: When the user connects to the network, in the background.

**Comment by Bitcoinera** [comment]
> Instead we should connect to the API as soon as possible: When the user connects to the network, in the background.

Interesting idea! But what would we run in the API to help speed FE up?

**Comment by faboweb** [comment]
> But what would we run in the API to help speed FE up?

What we can do is actually stitch the transaction in the FE and getting the metadata from the API. But this sounds like a huge hassle as we need to research how to do that properly.

**Comment by Bitcoinera** [comment]
This can be our answer: https://github.com/paritytech/txwrapper

But yes, with #4373 I don't actually perceive any difference between transactions in Tendermint and transactions in Polkadot. Maybe Claim Rewards only

**Comment by Bitcoinera** [comment]
Yes, this is now fixed pre-connecting to the Polkadot API
