### ISSUE TITLE
Notifications M3

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4228]
Users should receive proactive notifications

AC:
- Mobile push notifications https://github.com/luniehq/lunie/issues/4476
- Opt-In EMail notifications https://github.com/luniehq/lunie/issues/4387

**Comment by Bitcoinera** [comment]
Could we split these into smaller issues or maybe just be more descriptive on what is to be done for each?

**Comment by faboweb** [comment]
Done

**Comment by Bitcoinera** [comment]
Only testing mobile push notifications is left. And deactivating missed block notifications for now, although I think that is not part of this milestone

**Comment by jbibla** [comment]
we're done 💯 💯 💯

**Comment by Bitcoinera** [comment]
Yeeeey!!! :woman_dancing:
