### ISSUE TITLE
Extension - Seed extraction

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4233]

**Comment by Bitcoinera** [comment]
Any insights here? I mean, where should it exactly appear, the "Reveal Seed" button?

Also not sure if I'm missing something here, because I don't get yet why we cannot recover current users' seeds (we should have both the encrypted wallet in localStorage and the user has their password)

**Comment by faboweb** [comment]
> Also not sure if I'm missing something here, because I don't get yet why we cannot recover current users' seeds (we should have both the encrypted wallet in localStorage and the user has their password)

nobody said we can't ^^

**Comment by faboweb** [comment]
Designs: https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/p/browser-extension-account-management

**Comment by faboweb** [comment]
On click button slides to the left (use transition)

**Comment by Bitcoinera** [comment]
There is something I don't understand about these designs. I see the TmLiSessions and the buttons. But in which moment does the user select which account they want to see the seed from? First they need to select one right?

I was thinking maybe a dropdown like in Polkadot JS Extension?

![image](https://user-images.githubusercontent.com/40721795/84421449-e25c0f80-ac1b-11ea-8ca9-172cf8f3b359.png)

**Comment by faboweb** [comment]
Isn't this very clear: https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/jLpryG

**Comment by faboweb** [comment]
You click on the new menu for the account you want to get the seed from

**Comment by Bitcoinera** [comment]
But why there are two accounts being displayed there? This design seems to be assuming the unique seed idea, no? Like the user got two different wallet for two different networks from the same seed. This is at least what I see on this design 🤷 

I'm now confused

**Comment by Bitcoinera** [comment]
I found there was already a `recover` module in place. But very very basic. Will use it for this

**Comment by faboweb** [comment]
The `recover` module is for importing seeds, right?

**Comment by Bitcoinera** [comment]
🤔 yes, true, something completely different
