### ISSUE TITLE
Akash transactions broadcast failing for Nano Ledger S, cosmos app v2.1X

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4251]
Thanks to our QA James and me discovered a kind of difficult to spot bug:

All Akash transactions are failing for Nano Ledger S, Cosmos App v2.12/14

Getting this error:

<img width="440px" src="https://user-images.githubusercontent.com/40721795/84288693-cbe18580-ab41-11ea-9193-04a42f1e3046.png">

**Comment by Bitcoinera** [comment]
@jrmoreau can you please try again? I just checked on develop and somehow it worked :eyes:

**Comment by jrmoreau** [comment]
Send, stake and un-stake tx's work. Action modal does not work in staging, but otherwise the tx's are being sent ok with my Ledger Nano S

**Comment by Bitcoinera** [comment]
I will close this now as it seems to have been some kind of extremely weird temporary glitch
