### ISSUE TITLE
Detect Network Upgrades (Future Feature Request)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4272]
Discussion on how we could achieve this. Some options:

- if endpoint doesn't change, we could detect a chain-id change, and this means a new network has been released. But this only works if endpoint stays the same (it actually should, in theory)

- React on changes on the network key repo: difficult, since the merge for the Kava-3 upgrade was done a couple of days before the actual upgrade, for example. The upgrade only comes into place when validators coordinate with the devs to upgrade.

- Create & promote some kind of feed on PoS networks upgrades. Coordinate this as a community effort

**Comment by faboweb** [comment]
I proposed before:
- add a mapping between chain-ids and data handlers so that when a chain upgrades we already handle the new data structures

We should also handle down/upgradig networks:
- set a flag in the networks objects to signal inavailability
- send a subscription to the FE to requery the new networks with the updated state

**Comment by Bitcoinera** [comment]
> * add a mapping between chain-ids and data handlers so that when a chain upgrades we already handle the new data structures
> * set a flag in the networks objects to signal inavailability
> * send a subscription to the FE to requery the new networks with the updated state

I love these ideas so much! 🤩

**Comment by Bitcoinera** [comment]
If we go with #4235 we could add the unavailability state in the DB table and handle everything in the FE to start with. What do you think?

**Comment by faboweb** [comment]
sounds good
we still may want the subscription as current clients wouldn't get the information that a network is down
