### ISSUE TITLE
Validator search goes extremely slow

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4280]
Testing in https://app.lunie.io validator search is going so slow now. It takes over 20 second or so to get the results... Could have to do with the popularity change? Maybe that is not optimized. Will check.

![image](https://user-images.githubusercontent.com/40721795/84600063-05cec680-ae77-11ea-928b-ae2d9013b247.png)

**Comment by faboweb** [comment]
is this slow outside of the e2e tests as well?

**Comment by faboweb** [comment]
It is outside e2e also veeery slow. some issue in our code as this should be instant as the validators are already in the cache. maybe the db request is slow, but we could cache the request easily.

**Comment by Bitcoinera** [comment]
Maybe it makes sense to have a separate function when there is a search term? There we don't really need to sort by popularity, right? We need the active thing, but that is already in the validator object, we don't need to add it like we do with popularity

**Comment by Bitcoinera** [comment]
Another thing I just realized is that the search doesn't work if you input the operatorAddress just like that. I will look into fixing that too

**Comment by Bitcoinera** [comment]
Oh, this was fixed already. Concretely by #4294
