### ISSUE TITLE
User Authentication: Deep Links

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4293]
This discussion is related to my PR #4242 and with the epic User Accounts #4237 

Everything was going just fine and happily with magic links until I was reminded about the app. Yes, how could users use the email magic link on the mobile app? I went on researching and realized that Dynamic links are a must to be able to have magic links work the expected way on mobile. This is easily noticeable because once you use the android field in the `[actionCodeSettings](https://firebase.google.com/docs/auth/web/passing-state-in-email-actions)` from Firebase, you automatically get the following error:

![image](https://user-images.githubusercontent.com/40721795/84795027-46554e00-aff7-11ea-8b00-a8a8e835abc3.png)

I just tried one of the magic links on mobile and, as I imagined, it directed me to the webapp. But the behavior we'd expect from the dynamic link on mobile would be to take the user to the app if they have it installed or even install it if they wouldn't have it (it is as easy as doing 

```
        android: {
          packageName: `org.lunie.lunie`, // no clue?
          installApp: true,
          minimunVersion: `minimum-version`
        },
```

So, to have the email sign in mobile app ready we need to set up the Firebase Dynamic Links, there is no question in that. Now, what @faboweb discovered is that in order to set them up, we'd need to have our app hosted on Firebase, which is too much of a tradeoff for what we want to achieve.

Possible solutions:

- We use another Firebase signin method. For starters, normal Email and Password. As a temporary solution, to later user the Email Magic links.

- We use another authentication service like OAuth or [Auth0](https://auth0.com/docs/connections/passwordless/guides/email-magic-link) using their magic link solution, or we could even [go native](https://medium.com/one-more-thing-studio/how-to-make-magic-links-with-node-1d164c036e29)! (although it has a lot of security concerns)

- We let mobile users login and use the webapp instead of the app for now? (Super bad solution)

**Comment by jbibla** [comment]
thank you ana! 

> We use another Firebase signin method. For starters, normal Email and Password. As a temporary solution, to later user the Email Magic links.

what would "later use email magic links" look like? what will happen later than can't happen now?

> We use another authentication service like OAuth or Auth0 using their magic link solution, or we could even go native! (although it has a lot of security concerns)

seems like a viable option - are there magic link services that won't require us to register our apps with them?

> We let mobile users login and use the webapp instead of the app for now? (Super bad solution)

we don't have many mobile users AND we don't have push notifications yet so why is this such a bad solution?

> @faboweb discovered is that in order to set them up, we'd need to have our app hosted on Firebase, which is too much of a tradeoff for what we want to achieve.

@faboweb can you share where you read this / how you know this? also, what is involved in hosting the app on firebase? are there other advantages / disadvantages? based on [this](https://firebase.google.com/docs/auth/web/passing-state-in-email-actions#configuring_firebase_dynamic_links) it seems like there is some configuration required but it doesn't say anything about hosting requirements. 

i guess as a side note: should we even be worried about mobile yet if we don't have push notifications and the magic links (any version of them) are going to be extra work? for an MVP we are probably ok to start with web + email only - which is where most of our users are anyways.

**Comment by Bitcoinera** [comment]
We're currently working on this

**Comment by faboweb** [comment]
We don't need dynamic links. This was a misconception. But we need deep links for authentication via magic links. And we need authentication for paywalling premium features like push notifications. We also likely need deep links for push notifications to link to content.
We don't need dynamic links as apps just attach to certain URLs if specified. So we can just link app.lunie.io to open the app if installed and read the magic link.

**Comment by Bitcoinera** [comment]
OK, so we should close this issue in fact

**Comment by jbibla** [comment]
no it seems this PR is going to close this issue: https://github.com/luniehq/lunie/pull/4496
