### ISSUE TITLE
Store user accounts in DB

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4295]
Moving this from the archived lunie-api to be able to comment, reference, etc.

Resolve an OAuth user in the resolver.js and store it in the db. The frontend will add a header to send the uid of the user. The authentication remains completely with firebase.

In the resolver we will need to get the user from firebase. The FE will send an ID token in the header.
Verify Token
https://firebase.google.com/docs/auth/admin/verify-id-tokens#web
https://firebase.google.com/docs/auth/admin/custom-claims

DB
Create Schema (EMails remain in firebase)

user {
  uid
  email
  premium
  createdAt
  lastActive
}
On every verified token in resolver.js check if the user exists and either create the user or update lastActive.

**Comment by Bitcoinera** [comment]
Work started

**Comment by faboweb** [comment]
Don't store emails for now.
