### ISSUE TITLE
getaddrinfo EAI_AGAIN staging-db.lunie.io: Request to https://staging-db.lunie.io/v1/graphql failed

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4303]
This error is happening quite often in our API nowadays (when interacting with our frontend):

![image](https://user-images.githubusercontent.com/40721795/84914354-cba23680-b0bb-11ea-920d-e05d9369335b.png)

Since it is persisting we should find a way to fix it

**Comment by Bitcoinera** [comment]
Today no more of this errors. Weird

**Comment by Bitcoinera** [comment]
Ah no, they are back 👀 Why is this happening

**Comment by Bitcoinera** [comment]
I am still getting this error actually :sweat-smile. I wouldn't close it

**Comment by faboweb** [comment]
It looks like a connection issue though

**Comment by Bitcoinera** [comment]
I never got this again. I think we can close it, at least for now
