### ISSUE TITLE
Terra available balances not showing correctly

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4311]
**Describe the bug**
User reported their available balance not showing correctly in Terra portfolio. Confirmed and reproduced that the Lunie balance does not reflect the balance shown in the block explorer. 

![Screen Shot 2020-06-18 at 12 37 26 PM](https://user-images.githubusercontent.com/1614127/85048031-b4695480-b160-11ea-8dc9-285070e267a1.png)
![Screen Shot 2020-06-18 at 12 38 30 PM](https://user-images.githubusercontent.com/1614127/85048032-b501eb00-b160-11ea-8dbe-fff61a14ef9c.png)

**Comment by faboweb** [comment]
help me find the difference

**Comment by jrmoreau** [comment]
Damn this is the second time I looked at this and realized that stablecoin rewards do not show as available @faboweb. User pointed out to me and I didn't even realize it. Sorry. 

On a side note, it's confusing that we don't list available balance of stablecoins in the available column even though they cannot be staked. 

I can close this.

**Comment by faboweb** [comment]
Good find, though! lets keep an eye on it
