### ISSUE TITLE
Terra send tx failing due to problem with fee calc

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4313]
**Describe the bug**
Sending any amount of KRT or any Terra token results in error message

`Sending tokens failed: Broadcast was not successful: {"codespace":"sdk","code":14,"message":"insufficient fees to pay for taxes; 479340000ukrw < 479361501ukrw"}.`

Seems we are incorrectly calculating fees.

**Comment by Bitcoinera** [comment]
Closed by #4316
