### ISSUE TITLE
Kusama: ClaimRewards fails. Transaction has a bad signature

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4325]
Can someone try to reproduce? I used a `stash/controller` account and had really little reward, as little as 0.000001. This is the account I tried with: `EahbE5KcDgsCHEtDnmrACjgJCxJd9pxLccaw6Xg5w5Lgv45`.

You might need to use #4324 because of the polkadot fee failing (which might be the same issue since the function is actually the same in both API and app)

<img width="440px" src="https://user-images.githubusercontent.com/40721795/85224075-ec260580-b3c7-11ea-9d14-09865cda7ad6.png">

**Comment by Bitcoinera** [comment]
Does it even make sense to offer this action on Substrate networks? Validators should do it anyway right

**Comment by faboweb** [comment]
THis is fixed, right?

**Comment by Bitcoinera** [comment]
I think it is actually not? But difficult to test, since my rewards are getting automatically claimed by the validators

![image](https://user-images.githubusercontent.com/40721795/91049994-52284680-e61e-11ea-9c3a-58c33917ca96.png)


Will check in Westend

**Comment by Bitcoinera** [comment]
Westend working:

![image](https://user-images.githubusercontent.com/40721795/91050154-87cd2f80-e61e-11ea-838a-6a8cb5c089f4.png)

Hopefully in the others too
