### ISSUE TITLE
Epic: add unit tests for all the new components

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4326]
Once we finish with user accounts and have the paywall in place for Premium we should take the time to create the unit tests for all the new components.

These are:

- all the ones in the account folder

- the account module in store

- the new `recoverFromPrivatekey` function in the keystore module in store

**Comment by jbibla** [comment]
unit tests should be written in the same PR as the new code ... 🙃

**Comment by Bitcoinera** [comment]
:sweat_smile: seems it haven't been the case lately
