### ISSUE TITLE
Implement Account Recovery via Private key

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4333]
**Is your feature request related to a problem? Please describe.**
Many accounts have no seedPhrase/mnemonic stored whatsoever. So in order to recover control over the wallet, we will allow users to recover accounts via private keys.

**Describe alternatives you've considered**

There really aren't any :shrug: 

**Additional context**

Very easy to do. The code can be found in the following commits I had to revert since they were out of scope:

For recovery through private key, almost finished (although not quite) & the keystore function `recoverFromPrivateKey`: https://github.com/luniehq/lunie/pull/4279/commits/93f2bc2c89abd8874547a84819d5e2c55fed42e4

Everything's should be in there

**Comment by Bitcoinera** [comment]
This only needs to change the validations in the Recovery steps and I think that's it. Very easy. We even have the functionality in `cosmos-keys` already

**Comment by jbibla** [comment]
why do we need to do this?

**Comment by Bitcoinera** [comment]
To help users recover their accounts using their private key, since old accounts don't have their seed stored

**Comment by Bitcoinera** [comment]
Whaaa? Why did it close this?

**Comment by jbibla** [comment]
we can close for now until someone needs it.
