### ISSUE TITLE
notifications ux improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4336]
**Is your feature request related to a problem? Please describe.**

the first version of notifications we have can be a bit overwhelming and confusing. it's not clear why you receive certain notifications and many don't contain enough information. 

**Describe the solution you'd like**

i think we can do a few simple things to make notifications even more accessible and useful

1. include a list of addresses a user is receiving notifications for (phase 2 - let them edit this list)
2. filtering / sorting / search on notifications page
3. each notification should include the time and network of origin
4. better default icons / images

**Comment by faboweb** [comment]
We could tag all notifications with addrss and network

**Comment by faboweb** [comment]
> filtering / sorting / search on notifications page

should be on server
