### ISSUE TITLE
new validator profile endpoint

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4337]
**Is your feature request related to a problem? Please describe.**

- our new validator profile page will require some new data points to make the front end implementation a breeze

**Describe the solution you'd like**

this is just a proposal but the endpoint should return the following:
```
name
rank on lunie
description
team members { name, url to photo, link to profile { twitter, linked in, github } }
website
telegram
github
twitter
blog
number of stakers (cross network)
total staked assets (cross network)
uptime (cross network)
contribution links { title, url, type { article, website, podcast, github }  }
networks (some from on chain, some manually entered?) { name, voting power, reward % }
feed (recent notifications including their address) 
```

**Additional context**

https://sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/n3EJKp

**Comment by faboweb** [comment]
> total staked assets (cross network)

needs to be in fiat value as we can't aggregate otherwise

> feed (recent notifications including their address) 

probably different endpoint?

> number of stakers (cross network)

still an issue here on Cosmos

In general I propose a db structure:

validators
validatorId, property, value (JSON or multiple)

validatorMappings
networkId, validatorAddress, validatorId

**Comment by jbibla** [comment]
> number of stakers (cross network)

doing this query for one validator shouldn't be an issue ...?

**Comment by jbibla** [comment]
i would propose we leave the existing endpoints for validator profiles for individual networks but add a new endpoint for individual cross-network validators

**Comment by Bitcoinera** [comment]
One question, the "total staked assets" field would be make just an `Int` or would it be more like a list of Objects like this, for example: 

`{denom: 'ATOM', amount: 2,000, fiatValue: 6,000$ }` ?

**Comment by Bitcoinera** [comment]
In `TeamMember` we could also add `quote` and `bio` fields :star_struck:  What do you think?

**Comment by jbibla** [comment]
> One question, the "total staked assets" field would be make just an Int or would it be more like a list of Objects like this, for example:

good question! it's _total_, so a sum of all in fiat (selectable by user). i like the array of objects you're suggesting too - but then we would have to do the math on the frontend.

> In TeamMember we could also add quote and bio fields 🤩 What do you think?

it's a nice idea - but there is no design for this.

**Comment by Bitcoinera** [comment]
> but then we would have to do the math on the frontend.

Not really, we can do it in the API. So that is a yes! :woman_dancing:

**Comment by faboweb** [comment]
things the valdator puts in manually:

name
description
team members { name, url to photo, link to profile { twitter, linked in, github } }
website
telegram
github
twitter
blog
contribution links { title, url, type { article, website, podcast, github }  }
networks (some from on chain, some manually entered?) { name }

**Comment by Bitcoinera** [comment]
ok, so the DB function to store the validator in DB would be call `registerPremiumValidator` or something like that right and there we would post all this info. Nice. Then add another function like `editPremiumValidator`.

And then finally the `validatorProfile` endpoint I was already working on. Cool. Now I have a better overview :+1:

**Comment by faboweb** [comment]
Why do you have a function registerPremiumValidator or editPremiumValidator ? We have no interface for validators to do this and will most likely just do it on our own for now. Please deliver the minimum feature set and not blow up the scope ;)

**Comment by Bitcoinera** [comment]
> Why do you have a function registerPremiumValidator or editPremiumValidator ?

Okok :ok_hand: I was just thinking delivering the whole API functionality ready, but true, I will stick to the scope. That can be another PR

**Comment by jbibla** [comment]
i don't know if `premium` is the right concept here. it's more like `augmented` or `edited`

**Comment by Bitcoinera** [comment]
> i don't know if `premium` is the right concept here. it's more like `augmented` or `edited`

I prefer premium, since they are paying customers

**Comment by jbibla** [comment]
> since they are paying customers

not really something we're pursuing right now.

**Comment by Bitcoinera** [comment]
This is not back to "In progress" yet. There are still some bugs & open PRs. Or should I leave everything behind and start working back on this?

I think it is better idea to wrap up governance definitely :shrug:

**Comment by jbibla** [comment]
```
name (on-chain)
rank on lunie (on-chain)
description (on-chain)
team members { name, url to photo, link to profile { twitter, linked in, github } } (db)
links { (on-chain when possible)
  website 
  telegram
  github
  twitter
  blog
}
number of stakers (on-chain)
total staked assets (on-chain - convert to fiat)
uptime (on-chain)
contribution links { title, url, type { article, website, podcast, github }  } (db)
network { name, voting power, reward % } (on-chain)
feed (notifications including their address) 
```
