### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by zealousWang** [luniehq/lunie#4347]
I have forked lunie repository and tested.

When i tried to send token i have got error on extension.

![Screenshot_1](https://user-images.githubusercontent.com/30057497/85424696-d02e8980-b5aa-11ea-854f-f7fb2b21cb8c.png)

**Comment by faboweb** [comment]
any error in the background.js?

**Comment by zealousWang** [comment]
> any error in the background.js?

yes. I think so

**Comment by zealousWang** [comment]
> any error in the background.js?

I can see only above messages on console tab.

**Comment by zealousWang** [comment]
Other features such as signin are working well. But When i click send button or stake button, i got above error and i can't do anything at all.
Please help me.

**Comment by faboweb** [comment]
If you go into the background.js (in the extension tab of chrome). You see the logs of the background process.

**Comment by faboweb** [comment]
the error is in the app or in the extension popup?

**Comment by zealousWang** [comment]
I have checked background.js log.

![image](https://user-images.githubusercontent.com/30057497/85435641-5bfbe200-b5ba-11ea-81a5-dbb745e7baf8.png)

I have error log on that. I think this is related with white list of extension.

How can i fix this issue?

**Comment by faboweb** [comment]
In `background.js` you find a set of whitelisted URLs. You should adjust to match your URL.

**Comment by Bitcoinera** [comment]
Should we close this then?

**Comment by zealousWang** [comment]
Yes. I have fixed it.
