### ISSUE TITLE
API hangs up when fetching staking info

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4362]
**Describe the bug**

API hangs up when fetching staking info for substrate networks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by faboweb** [comment]
What query exactly?

**Comment by Bitcoinera** [comment]
I believe he means this one `await api.query.staking.nominators(delegatorAddress)`

**Comment by faboweb** [comment]
That is a basic query. Your sure, that is what is causing the issues?

**Comment by Bitcoinera** [comment]
> That is a basic query. Your sure, that is what is causing the issues?

I will benchmark once I get my other PRs ready (specially #4373 )

**Comment by Bitcoinera** [comment]
Mmm, it seems this query is not called on startup. Is it used to get the inactive delegations of and address and for message creation and that's it

**Comment by faboweb** [comment]
So in what scenario the API actually hangs up @mariopino ?

**Comment by Bitcoinera** [comment]
Did we get to check if this is really the case?

**Comment by faboweb** [comment]
I don't see issues currently
