### ISSUE TITLE
Cache store in db

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4365]
**Is your feature request related to a problem? Please describe.**

On API startup the api takes a while to connect and therefore it takes a bit to deliver the first data.

**Describe the solution you'd like**

Write the whole store into the db on an update. The db should have one table `storeCaches`. This table should have columns:
- networkId
- store // JSON serialized store

On API start fetch the cached store and populate the store with the cache to reduce waiting times on start.

**Describe alternatives you've considered**

This issue only happens when we deploy the API for a couple of seconds. So maybe we could just ignore the issue.

**Additional context**

**Comment by Bitcoinera** [comment]
After too many trials and errors I have thrown the towel storing the whole store as it is in the DB. When you do `escape(value)` at line 31 in `helpers.js` hell breaks loose and half of the networks fail to store it. And it is super difficult to debug because store is huge.

So two solutions: either store the store in different columns (lastHeight, annualProvision) and validators would be a table on its own or, second solution, store store as a file, like we do now with validators.

I think the second solution is the best

**Comment by faboweb** [comment]
Question is, why do escaped inserts fail? Can we escape the entries in a different way? Do we need to escape? The code comes from the API so we can trust it? Are there values that could be malicious to the DB?

**Comment by Bitcoinera** [comment]
It seems we need to serialized stringified JSONs differently, there is no question to that. I have been trying this myself on the Hasura lab. Here I left you a related comment: https://github.com/luniehq/lunie/pull/4235#discussion_r448269708

I think the HTML escape method is not so reliable for JSONs, but not really sure why it fails. I also saw lots of :amp and other weird things after escaping store. We need to take into account that some validator names include emojis, so maybe this is one of the reasons

**Comment by faboweb** [comment]
ok, then let's add the "skip escape" flag again and add the store as serialized JSON

**Comment by Bitcoinera** [comment]
> ok, then let's add the "skip escape" flag again and add the store as serialized JSON

Maybe I'm missing something here but sending as a stringified JSON also doesn't work just like that. I was trying changing the quotes and so, but something fails. Would need to do some research here

**Comment by faboweb** [comment]
adding JSONs in mutations works a little different in GQL: https://hasura.io/blog/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/
