### ISSUE TITLE
GraphQL requests not comming from cache

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4367]
**Is your feature request related to a problem? Please describe.**

When opening the ActionModal we see, that requests are done against the API which slow down opening the ActionModal.

**Describe the solution you'd like**

The requests should be cached already and therefore should be instant. We need to investigate why this is not the case.
In the case of the ActionModal we should also investigate which requests are actually needed to be done there. The validators in Polkadot are 500 which is a huge payload. Maybe we can reduce them by defaulting to popular.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
Let's do this!!! 🔥
