### ISSUE TITLE
Connect to Polkadot API asap

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4369]
**Is your feature request related to a problem? Please describe.**

When the user wants to sign a tx we connect to the Polkadot API. This takes some time and causes the user to need to wait some seconds.

**Describe the solution you'd like**

Connect to the Polkadot API in the background when the user is signed to a Polkadot network. The connection still takes time, but by the time the user is at the sign step, the connection should be established.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
Let's do this!
