### ISSUE TITLE
Add the recoverFromPrivatekey functionality

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4385]
Since luniehq/cosmos-keys#76 was merged, we can now just add this function to the module and offer our users the possibility to restore their accounts from their private key (only option available for those who didn't get their seedPhrase stored).

In fact, the code for this function is already to be found in this commit and it wouldn't be necessary to add much: https://github.com/luniehq/lunie/pull/4279/commits/93f2bc2c89abd8874547a84819d5e2c55fed42e4

Steps:

- change SessionImport validations so it also allows privateKeys as well as seeds (as seen in that commit)
- add the `recoverFromPrivatekey` function to the keystore module in store

Another option would be to have a separate flow for privateKeys imports, but I don't think it makes so much sense.

**Comment by Bitcoinera** [comment]
Woah, 29th June... no wonder it went to stale

**Comment by jbibla** [comment]
we should do these because some users won't have seeds stored so "revealing" won't work as expected.

**Comment by Bitcoinera** [comment]
> we should do this because some users won't have seeds stored so "revealing" won't work as expected.

Yeah, I agree. The only thing preventing this from happening is the priorities order

**Comment by jbibla** [comment]
> only thing preventing this from happening is the priorities order

exactly 😄

**Comment by Bitcoinera** [comment]
I just added this in the backlog. Wasn't even there. Step by step

**Comment by Bitcoinera** [comment]
Should we add this to Lunie-light?

**Comment by jbibla** [comment]
no there will not be private keys there
