### ISSUE TITLE
E-Mail Notifications

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4387]
As a user, I want to be informed by E-Mail on critical notifications.

Topics:
- slashes (not there yet)
- PROPOSAL_CREATE
- PROPOSAL_UPDATE
- VALIDATOR_STATUS
- VALIDATOR_COMMISSION

E-Mail body should link back to the Notification Page noting that there is more to find there.
Add a note about unsubscribing by writing us an E-Mail.

PRs:
- Research: Find a mail provider (based on cost, do an estimate on amount of emails send)
- Api: Implement a way to send E-Mails to users based on any template
  - start with sending Hello World
  - continue with sending from a template
- Api: Send E-Mails to users on any of the critical topics
- Design: Design E-Mail template

**Comment by jbibla** [comment]
i think plaintext emails are a totally fine place to start. the things that need to be included are a message / template and a link to the relevant subject in lunie.

**Comment by faboweb** [comment]
Plan:
- register signed up users for all those events via 1 endpoint /email-notifications, the registrations go to the db and into local cache (for speed)
- on every notification check all registrations and collect which users to write an email
- get emails from firebase for all users we want to write
- create email from template
- send email to all those users
