### ISSUE TITLE
Wrong annualizedValidatorReward in Polkadot mainnet

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4402]
**Describe the bug**

Kusama has 4 eras per day, Polkadot has 1. 

We have this hardcoded:

```
const ERAS_PER_DAY = 4
```

We use this data to calculate annualized rewards so this needs to be refactored ASAP to display correct values for Polkadot.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by faboweb** [comment]
let's add the Eras to the networks object

**Comment by mariopino** [comment]
Reference: https://wiki.polkadot.network/docs/en/learn-staking#reward-distribution
