### ISSUE TITLE
Add polkadot mainnet missing profile pictures for validators

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4403]
**Is your feature request related to a problem? Please describe.**

Add polkadot mainnet missing profile pictures for validators

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by faboweb** [comment]
How about a mini page for maintaining the validator image for validators.

Just an input to upload an image
Show the hash of the image
Input for adding a signature (signin the hash with the operator PK)

@jbibla

**Comment by jbibla** [comment]
do you mean you want to make a page for validators to add their own images? 

our new validator profiles will require more information than just an image (team, country, social links, supporting links, etc.) so we should consider this info as well. 

now that we have emails, shouldn't we just use email auth for validators instead?

also, how does this idea relate to this: https://github.com/luniehq/lunie/issues/4405

**Comment by faboweb** [comment]
We still need to prove a validator is a validator

> also, how does this idea relate to this: #4405

not all validators will sign up. but we want to show the max in images.

> our new validator profiles will require more information than just an image (team, country, social links, supporting links, etc.) so we should consider this info as well.

We can have them edit their own data via an interface yes.

**Comment by jbibla** [comment]
> We still need to prove a validator is a validator

sounds like over-engineering. we can probably start with emails and go a long way.

**Comment by faboweb** [comment]
For now we use Twitter images
