### ISSUE TITLE
Westend Validators Filters

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4422]
Seems in Westend concretely there is a problem with validators being displayed on TableValidators. "All" shows actually only active and "Active" displays nothing.

But yes, it is a testnet so very low priority... Unless it means that at some point this will also change in the mainnets/canaries :shrug:

**Comment by faboweb** [comment]
> But yes, it is a testnet so very low priority... Unless it means that at some point this will also change in the mainnets/canaries 🤷

that is to expect. Any idea why the validators are not showing as active?
