### ISSUE TITLE
remaining problems with user auth and menu

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4435]
- [x] update menu copy (address sign in vs sign up)
- [x] clean up menu account list design (remove type and purple testnet icon?)
- [x] url should change when switching accounts @faboweb 
- [x] icon on session modal should be coloured and centered
- [ ] email validation is required for magic link email form @faboweb 
- [x] font sizing is wrong in new session modals
- [x] clean up urls (magic-link-sent-modal, sign-in-modal)

**Comment by faboweb** [comment]
What do you mean by "clean up urls (magic-link-sent-modal, sign-in-modal)" ?

Can you take the CSS tasks? I would check "url should change when switching accounts" and can "email validation is required for magic link email form"

**Comment by jbibla** [comment]
> What do you mean by "clean up urls (magic-link-sent-modal, sign-in-modal)" ?

i don't think the URLs should have "modal" in them and i want to check with the existing session modals to see if we can have some more consistency there. the combo of sign in, sign up, sign out, session, account, address is complex - wanted to see if things are consistent. 

> Can you take the CSS tasks

definitely. working on it already! 

> I would check "url should change when switching accounts" and can "email validation is required for magic link email form"

what do you mean by "check"?

**Comment by faboweb** [comment]
> what do you mean by "check"?

I can check why this happening

**Comment by faboweb** [comment]
> i don't think the URLs should have "modal" in them

doesn't feel like a strong problem to solve

**Comment by Bitcoinera** [comment]
>  email validation is required for magic link email form

I don't understand the problem here?

**Comment by Bitcoinera** [comment]
> url should change when switching accounts

This is actually working.

**Comment by faboweb** [comment]
> >  email validation is required for magic link email form
> 
> I don't understand the problem here?

The input should check if it is an email.

**Comment by Bitcoinera** [comment]
> The input should check if it is an email.

I believe Firebase already does it for us. Let me quickly check

**Comment by jbibla** [comment]
url changing is working! nice! 

@Bitcoinera it shouldn't even let the user go to the next modal that says "sent" if it's not a valid email address.

**Comment by Bitcoinera** [comment]
I tried again switching accounts, this time using extension accounts, and it is working well. No accounts mixings.

@faboweb can you check if can still reproduce this error? It would the last one to solve

**Comment by faboweb** [comment]
just checked and looks good

**Comment by Bitcoinera** [comment]
Mmm, strange. I cannot reproduce it locally, I think. I checked and I see the same code in `UserMenu` :thinking: 

Did you try locally and could also not reproduce?

**Comment by faboweb** [comment]
Did you try signing in with the extension? This is when the errors appear

**Comment by jbibla** [comment]
fabo, can you please share steps to reproduce this? i also cannot.

**Comment by faboweb** [comment]
click on "Create New Account" (Should be renamed to "Add Address")
use extension address (from Cosmos)
click on "Create New Account" (Should be renamed to "Add Address")
use extension address (from Polkadot)
you have now a Polkadot address in Cosmos Hub 🥳

**Comment by jbibla** [comment]
> (Should be renamed to "Add Address")

already done here: https://github.com/luniehq/lunie/pull/4453 

i can't reproduce it here https://5f03d30ea3d80a7f931cf7cd--lunieio.netlify.app

though the address you select from the extension isn't being added to the user menu for me... 😕

**Comment by jbibla** [comment]
update: i can reproduce it sometimes.
