### ISSUE TITLE
validator list ideas

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4437]
- the current validator list is quite limited in its abilities. we only display a subset of available and relevant info. ideally, users could see much more information or at least choose what data is important to them.

- using "popular" as a filter for images is really confusing. let's display popularity on lunie AND in terms of number of delegators as data points and leave popular as the default sorting function.

- i would propose a checkbox to display the anonymous validators. it will default to being unchecked so i user has the ability to see that if they click the checkbox, they will see anonymous validators.

**Comment by faboweb** [comment]
>  ideally, users could see much more information or at least choose what data is important to them.

not sure about that. I think there is a lot of power and not letting users pick to many things.

**Comment by faboweb** [comment]
can you sketch how this should look like? should we get rid of "active/inactive" and turn to something like "relevant/all"?

**Comment by jrmoreau** [comment]
Would a verified checkmark make sense? I mean, if a validator signs up for Lunie and updates their profile they can be "verified"

**Comment by jbibla** [comment]
@faboweb https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/jdjdW7

**Comment by faboweb** [comment]
Do we have designs for Desktop as well? Active/Inactive is still a good idea?

**Comment by jbibla** [comment]
no there aren't desktop designs but mario implemented this already. i have an idea for how to extend it to desktop.
![Uploading Screen Shot 2020-07-06 at 9.55.33 PM.png…]()

i think for now, active / inactive is the best we got! definitely open to exploring this though.
