### ISSUE TITLE
Cosmos Rewards are off

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4444]
**Describe the bug**

We are using the onchain expected annual rewards for our calculations but there are actually less blocks per year so the yiel is actually lower. Terra submitted this issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by jbibla** [comment]
what's involved to make this more accurate?

**Comment by faboweb** [comment]
we just check how much time has passed since n-10000 blocks and predict how many blocks there will be in the whole year. knowing this we can predict the actual rewards. the problem here is with emoney where the code diverges. so we need to do a not so simple refactor first.

**Comment by jbibla** [comment]
can we change our current (hardcoded) assumptions to be more accurate?

**Comment by faboweb** [comment]
where do we have hardcoded assumptions?

**Comment by jbibla** [comment]
i thought it was based on a 6s block time but in reality it's closer to 8s now

**Comment by jbibla** [comment]
@faboweb ?
