### ISSUE TITLE
Clarify importing parameters with supporting text for Kusama/Polkadot

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4461]
**Is your feature request related to a problem? Please describe.**
User unsure of formatting requirements to import/restore a Kusama or Polkadot account into Lunie from outside sources like Polkadot.js

**Describe the solution you'd like**
a pop up or modal describing how to import accounts with explanation of what a user needs to know (context)

**Describe alternatives you've considered**
Creating a guide on how to claim KSM/DOT from Polkadot.js and import on Lunie

**Additional context**
Cosmos and SDK based network importing of accounts is different enough from Kusama/Polkadot that consideration should be given to a fresh user's POV on what they need to do

**Comment by jbibla** [comment]
is this because the default seed phrase / way of restoring addresses in polkadot.js is different from a 12 / 24 word phrase?

**Comment by jrmoreau** [comment]
Considering we only `explicitly` accept 12 and 24 word seed phrases and also the raw seed, there's just open ended-ness about whether the user is doing it right or not. Hutch said "should I have a 24 word seed? Or a 12 word? Which is right?"

**Comment by jbibla** [comment]
i think i understand. so by describing the options we create room for doubt. is that what you / he means?

**Comment by jrmoreau** [comment]
Yes I think there's room for doubt, especially with it being a brand new network that just launched. Referring to the quote I shared in slack about a user not feeling comfortable putting in private keys. 

I think we overcome this with content and either reducing options for import or making them more explicit. 

`import your 24 word Lunie- generated backup code or your x-type seed generated from Polkadot. not sure what to do next? Read this post`

**Comment by jbibla** [comment]
polkadot JS might be the best path forward

**Comment by jbibla** [comment]
how's this?

![Screen Shot 2020-08-06 at 7 28 24 PM](https://user-images.githubusercontent.com/6021933/89592608-00f51600-d81b-11ea-8636-5431f52bc3a2.png)

**Comment by jrmoreau** [comment]
@jbibla this is quite a bit clearer and easier to understand

**Comment by jbibla** [comment]
great
