### ISSUE TITLE
Add expandable icon on rewards calculation for Kusama (especially for mobile)

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4462]
**Is your feature request related to a problem? Please describe.**
User was unable to glean what the reward rate meant for Kusama looking at it from mobile. An informational icon with additional information or a clickable link to an explanation would be better for context

**Describe the solution you'd like**
An icon that is clickable to expand in app or into another tab that explains the rewards rate calculation

**Describe alternatives you've considered**
Hovering over the rewards shows that they are annualized estimates but it's not clear on mobile especially as you're not using a mouse to hover

**Additional context**

**Comment by jbibla** [comment]
i'm not convinced our approach here was ideal in the first place. it's confusing and approximate (inaccurate). we also don't show any historical balance or reward data which makes the approx. % less meaningful IMO.

do you think it's better to...
- share the details of this calculation in a modal (complex, confusing, math)
- remove the approx. and only show on chain data (commission is a proxy for rewards) 
- something else?

**Comment by jrmoreau** [comment]
I just think context is crucial - `x% estimated annual return*` and the `*` or somewhere in the description has a hyperlink to `learn more` but I don't know how we can do this on mobile and have it look good.

**Comment by jbibla** [comment]
i think we should address this

**Comment by jrmoreau** [comment]
@jrmoreau would a modal be better or an article in the help center to click into?

**Comment by faboweb** [comment]
> Hovering over the rewards shows that they are annualized estimates but it's not clear on mobile especially as you're not using a mouse to hover

@jbibla this is the problem we should fix
