### ISSUE TITLE
Provide a validator set suggestion to users on Kusama/Polkadot for ideal returns

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4463]
**Is your feature request related to a problem? Please describe.**
Advanced users might be able to suitably pick a validator set but an entry level user would not know what to do or why

**Describe the solution you'd like**
Provide a validator set suggestion for staking to users similar to Polkadot.js

**Describe alternatives you've considered**
Can't think of any

**Comment by jbibla** [comment]
is this more about teaching people about staking or helping people optimize based on some specified outcome?

i think we could definitely do a better job guiding users to make it feel simpler and more approachable.

**Comment by jrmoreau** [comment]
@jbibla the competitor wallet explicitly offers validator set suggestions. It's a big plus for them.  @mariopino do you have any thoughts on this?

**Comment by jbibla** [comment]
> competitor wallet explicitly offers validator set suggestions

which one

**Comment by jrmoreau** [comment]
@jbibla Polkadot-js

**Comment by jbibla** [comment]
where? what does it look like?

**Comment by jrmoreau** [comment]
@jbibla going off what I am told by one of their community managers. I have not seen it myself. Asking for more details/screenshots/documentation. But he said it's news(ish) and recommends we have it

**Comment by jbibla** [comment]
ok we can keep an eye on what they are going to release - but i'm not sure we should make these kinds of recommendations.

**Comment by jrmoreau** [comment]
@jrmoreau got a screenshot from one of my peoples at w3f

<img width="1050" alt="nominator suggestions" src="https://user-images.githubusercontent.com/1614127/87716064-470b0c80-c77c-11ea-8042-d729eef3e10c.png">

There's very little subjectivity in this AFAIK -

**Comment by jbibla** [comment]
ah interesting. based on favourites and current network conditions.
