### ISSUE TITLE
Re-think `Claim` Button on Kusama/Polkadot to reflect rewards distribution behavior

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4464]
**Is your feature request related to a problem? Please describe.**
With Kusama/Polkadot staking rewards may be distributed in a validator set if another person or the validator initiates it, unlike Cosmos where you must claim your rewards

**Describe the solution you'd like**
Maybe an info popup that describes that rewards may be distributed to your balance without you needing to claim first.

**Comment by jbibla** [comment]
there is much to unpack here. 

```
The general rule for rewards across validator pools is that two validator pools get paid the same amount of DOTs for equal work, i.e. they are NOT paid proportional to the stakes in each pool. Within a validator pool, a (configurable) part of the reward goes to pay the validator's commission fees and the remainder is paid pro-rata (i.e. proportional to stake) to the nominators and validator. Notice in particular that the validator is rewarded twice: once as commission fees for validating, and once for nominating itself with stake.
```

- are validators doing this on behalf of the pool or do users actually sometimes have to claim rewards?
- what happens if no one claims in the 84 eras?
- should we alert users if no one claimed within the 84 eras?
- can we actually share how we calculate rewards? it's [extremely complex](https://github.com/luniehq/lunie/blob/7a32aa734088b8eff0ddf7c7c3ea5e4b86ef80fb/api/lib/source/polkadotV0-source.js#L224).

**Comment by jbibla** [comment]
> Maybe an info popup that describes that rewards may be distributed to your balance without you needing to claim first.

after a user stakes, this would be nice information to share. 

seems like notifications about eras and when someone else claims your rewards would be really helpful here as well

**Comment by jrmoreau** [comment]
I think the issue is that we are not showing an account tx summary on the dashboard for Kusama/Polkadot. If they saw that they had received rewards like they could see on the transactions page it would make more sense. Basically they seem total numbers change in their claim balance but no explanation.

**Comment by jbibla** [comment]
yep that is problematic

**Comment by faboweb** [comment]
It doesn't, but we could make that happen

**Comment by jrmoreau** [comment]
Do we think it would trigger a balance change alert?

**Comment by Bitcoinera** [comment]
I think notifications on your rewards being claimed (by the validator themselves or some other user) would be a top feature for Polkadot. Something definitely worth to work in and ask a grant for :innocent:
