### ISSUE TITLE
Make feedback/support button more prominent on mobile

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4465]
**Is your feature request related to a problem? Please describe.**
User is not able to easily find the help/support/feedback button in mobile

**Describe the solution you'd like**
Make the button to contact support/get help more pronounced in app

**Describe alternatives you've considered**

**Additional context**

**Comment by jbibla** [comment]
seems like many users are able to find it 😄

**Comment by jrmoreau** [comment]
@jbibla  fair
