### ISSUE TITLE
Mobile push notifications

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4476]
As a mobile user, I want to be informed by Push on critical notifications.

Topics:
- slashes (not there yet)
- PROPOSAL_CREATE
- PROPOSAL_UPDATE
- VALIDATOR_STATUS
- VALIDATOR_COMMISSION

PRs:
- Api: Implement a way to push notifications to registered topics (recover PR)
- Api: Implement receiving push notifications in mobile app (recover code)
- FE: Register mobile apps to receive push notifications
- FE: Display push notifications and link to deep linked content

**Comment by Bitcoinera** [comment]
Yeeey!!!

**Comment by Bitcoinera** [comment]
We still need to test this

**Comment by Bitcoinera** [comment]
We close it. I tested it and it is working. Also the link to the app. Only thing we need to change is that users shouldn't need to log in in the app as well. Webapp sessions should be enough to trigger the same notifications on mobile as for email
