### ISSUE TITLE
paywall needs to use variables and overflow is not working properly

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4489]
image 1:
<img width="774" alt="Screen Shot 2020-07-10 at 11 11 12 AM" src="https://user-images.githubusercontent.com/6021933/87169513-1b7cb380-c29e-11ea-89df-360b483b4e17.png">

image 2:
<img width="746" alt="Screen Shot 2020-07-10 at 11 11 19 AM" src="https://user-images.githubusercontent.com/6021933/87169515-1c154a00-c29e-11ea-97c5-5f22056804ce.png">

**Comment by Bitcoinera** [comment]
what is that thing covering the screen? The ActionModal?

**Comment by jbibla** [comment]
two separate images - on the paywall just scroll left and right to see

**Comment by Bitcoinera** [comment]
> two separate images - on the paywall just scroll left and right to see

wow! I hadn't even realized you could scroll there! :scream: noooo
