### ISSUE TITLE
Display bug showing zero ATOM balance despite several hundred ATOM delegated across several validators

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4490]
**Describe the bug**
Account has 0 available balance left, several hundred ATOM delegated across several validators but total ATOM balance shows as zero. 

**To Reproduce**

![zero balance](https://user-images.githubusercontent.com/1614127/87170228-0d7b6280-c29f-11ea-9848-a5be891310a1.PNG)
cosmos1xhvnjnp9g9zrswh8hyttq0m4jv5r5sn7p24jvw

For some reason this address breaks several other block explorers views as well.

**Comment by faboweb** [comment]
The nodes API doesn't show any balances for that user.

**Comment by faboweb** [comment]
The whole tx history doesn't imply that the user has liquid balances. The problem seems to be, that he has no liquid atoms. In the code maybe the list of balances now doesn't contain atoms and there for the total is not calculated. I will check.
