### ISSUE TITLE
Create a liveness/ missedBlocks query

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4493]
Specially useful for validators. Would return each missed block following the `Block` type plus a `total`, which would be the total number of missed blocks by that validator.

My proposal:

```
    query {
      missedBlocks(where:{networkId:{_eq:"${networkId}"}, operatorAddress:{_eq:"${operatorAddress}"}, order_by:{height:desc}) {
        block {
          height
          id # from Block
        }
        total # total number from blocks missed
      }
```

**Comment by faboweb** [comment]
what does the block object represent? the attributes should be GQL and not Hasura style

**Comment by Bitcoinera** [comment]
> what does the block object represent?

Well, yes, it should be `blockV2` actually

> the attributes should be GQL and not Hasura style

:eyes: ? You got me lost there

**Comment by jbibla** [comment]
what would we use this endpoint for?

**Comment by Bitcoinera** [comment]
> what would we use this endpoint for?

For validators to be able to see what blocks they missed & how many

**Comment by faboweb** [comment]
Is it important to know which block they missed?

**Comment by jbibla** [comment]
> For validators to be able to see what blocks they missed & how many

on the validator profile page? where do we show this? how would someone use it? sorry i don't really get what you're proposing.

**Comment by Bitcoinera** [comment]
> Is it important to know which block they missed?

I think so. THen they can search for the block and see what happened & why & try to fix it. At least they should know the height, yes

**Comment by Bitcoinera** [comment]
> on the validator profile page? where do we show this? how would someone use it? sorry i don't really get what you're proposing.

Not on the profile page publicly, but on their own backpage / dashboard. I think this information would be quite useful for them. This is something they monitor for, and we could include this info right there, together with how they manage their public exposure.

I think it is a good idea :shrug:

**Comment by faboweb** [comment]
We should put this into a possible epic "Validator Dashboard" but we shouldn't do that now

**Comment by Bitcoinera** [comment]
Oh yes, forgot about this. This is probably something so many validators would be also interested in

**Comment by jbibla** [comment]
we're not building this for validators yet! we'll re-open in the future.
