### ISSUE TITLE
improve liveness notifications

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4504]
logic needs some work to avoid spamming the user / event log

**Comment by jbibla** [comment]
what is this for @faboweb ?

**Comment by faboweb** [comment]
Notifications for validators being ofline

**Comment by jbibla** [comment]
oh yes. i thought this was implemented already but the logic needed some work?

**Comment by faboweb** [comment]
yep the logic needed some work to not spam the user / event log
