### ISSUE TITLE
Add `Forget Account` option on Lunie Extension like Polkadot-js

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4513]
Currently users must delete the Lunie browser extension to "forget" an account or to reset a password. This is also the case on other popular wallets like  MetaMask.

The forget account feature in Polkadot-js is an easy to use/understand feature that allows users to have finer control of their wallet/view. Lunie would benefit from this. 

![forget account](https://user-images.githubusercontent.com/1614127/87449856-b68dca00-c5cb-11ea-9714-45c1492f0e85.PNG)
![forget account1](https://user-images.githubusercontent.com/1614127/87449859-b7266080-c5cb-11ea-8452-f568b66dbbcc.PNG)

**Comment by faboweb** [comment]
We should do this

**Comment by faboweb** [comment]
To delete an address we should make the user enter their seed to confirm it works.

**Comment by faboweb** [comment]
Forgetting accounts has multiple paths:
- forget an explore/ledger address (doesn't need confirmation)
- delete extension account (confirmation via seed)
- delete local account (confirmation via seed)

**Comment by jrmoreau** [comment]
@faboweb I think the option 1 makes most sense to try if it's easier because the rest of the users might actually be happy with this and not need the latter 2 options.

**Comment by Bitcoinera** [comment]
I would go with a `forgottenAccountList` stored in extension localStorage for starters. I want to do this actually. Is a nice feature

First PR: forget account on extension

**Comment by Bitcoinera** [comment]
Would be nice to have #4762 fixed also...
