### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4518]
**Is your feature request related to a problem? Please describe.**

This is more a bug: Currently the user will have failing requests after using Lunie the next day as the idToken stored locally is invalid. We can't just create an idToken for every request as this would slow down the connection.

**Describe the solution you'd like**

Implement: https://firebase.google.com/docs/auth/admin/manage-cookies

**Describe alternatives you've considered**

Store the lifetime of the idToken locally and refresh the token before it expires (on app start check and set a timeout to check)

**Additional context**

**Comment by Bitcoinera** [comment]
But then the problem is on the admin side right? How can I reproduce these errors. I think I haven't seen them yet

**Comment by faboweb** [comment]
Reproduce:
- Sign in to Lunie
- Come back a day later
- Have the API throw errors because of an outdated idToken

**Comment by faboweb** [comment]
> But then the problem is on the admin side right

what problem are you seeing?

**Comment by Bitcoinera** [comment]
> what problem are you seeing?

OK, yes, I got the error now:

```
FirebaseAuthError: Firebase ID token has expired. Get a fresh ID token from your client app and try again (auth/id-token-expired). See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.
    at FirebaseAuthError.FirebaseError [as constructor] (/home/ana/lunie/lunie/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/home/ana/lunie/lunie/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAuthError (/home/ana/lunie/lunie/node_modules/firebase-admin/lib/utils/error.js:147:16)
    at /home/ana/lunie/lunie/node_modules/firebase-admin/lib/auth/token-verifier.js:199:39
    at Object.module.exports [as verify] (/home/ana/lunie/lunie/node_modules/jsonwebtoken/verify.js:126:14)
    at /home/ana/lunie/lunie/node_modules/firebase-admin/lib/auth/token-verifier.js:191:17
    at new Promise (<anonymous>)
    at FirebaseTokenVerifier.verifyJwtSignatureWithKey (/home/ana/lunie/lunie/node_modules/firebase-admin/lib/auth/token-verifier.js:190:16)
    at /home/ana/lunie/lunie/node_modules/firebase-admin/lib/auth/token-verifier.js:175:30
    at runMicrotasks (<anonymous>) {
  errorInfo: {
    code: 'auth/id-token-expired',
    message: 'Firebase ID token has expired. Get a fresh ID token from your client app and try again (auth/id-token-expired). See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
  },
  codePrefix: 'auth'
}
```

**Comment by Bitcoinera** [comment]
Ah yes, but in my case I think it is because of what is commented here: https://stackoverflow.com/questions/54058211/firebase-what-should-i-do-after-idtoken-expires

I was idle for more than an hour... So maybe we just need to use this `onIdTokenChanged`method to handle token expiration

**Comment by faboweb** [comment]
Great idea. Let's do that!

**Comment by faboweb** [comment]
Likely need to do this as signing in on mobile seems to kill sign in on desktop

**Comment by Bitcoinera** [comment]
> Likely need to do this as signing in on mobile seems to kill sign in on desktop

you mean we go on with the cookies and store if a session is happening on mobile or on desktop?

Well, we don't need any cookie for that, do we? We can just do as I suggested: if the sign in is happening on mobile then we add the `android-iOS` fragment in activeCodeSettings. Otherwise we don't. Simple logic

**Comment by faboweb** [comment]
the idToken invalidates after you sign in again. so when you first sign in on desktop and then on mobile, you session on desktop is not valid anymore. Why do we need to store where the session is happening?
