### ISSUE TITLE
Sort Networks alphabetically

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4521]
This here is something in between a bug report & feature request:

Currently we sort networks in both the Networks page and the navbar on the left according to default, so the default network will always appear on top. But what about the rest? These randomly change order all the time, making it unpredictable. 

The solution I propose: simple sort the remaining networks (not default ones) alphabetically.

**Comment by jbibla** [comment]
nice idea. counter proposal: should we sort them by popularity (manually)?

**Comment by Bitcoinera** [comment]
Or we fix statistics and then order them by number of users! What do you think?

**Comment by jbibla** [comment]
i like the idea but it feels a bit overcomplicated to me - let's just set them manually?

**Comment by Bitcoinera** [comment]
>  let's just set them manually?

We can add a new field in Network called "rank" or "position", so we can manually establish the order

**Comment by Bitcoinera** [comment]
The "rank" idea is the way to go IMO

**Comment by faboweb** [comment]
I don't see us doing this soon
