### ISSUE TITLE
Cleaning up notifications

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4525]
**now**
- [x] user menu ghost icon is not centred on windows
- [x] "Add an address" should go in user menu
- [x] `CardSignIn` should be modal instead of in page component
- [x] paywall variables and scroll bugs
- [x] message after sign in toggles states should be a modal that displays which addresses you'll receive notifications about -> link and CTA should go to notifications page
- [x] voting power changes message is broken (should show %)
- [x] remove new validator notification for now (and use network icon instead of lunie logo - for future use)
- [x] lunie theme on notifications page instead of network theme
- [x] hide app menu - add logo - deselect current network when on notifications page
- [x] notifications becomes home page / landing page if user is signed in with email
- [x] magic link copy needs to be updated
- [x] click the notifications icon from the paywall and the app gets stuck on a loading screen
- [x]  take user out from notifications back to Paywall when they sign out being on the notifications page

**next**
---
- [ ] connect user emails via intercom
- [ ] drip campaign 
- [ ] only display notifications that go back 30 days
- [ ] every user should have 1 notification from Lunie that says welcome

**Comment by Bitcoinera** [comment]
I like this multi-issue! So much stuff to do! :sunglasses:

**Comment by Bitcoinera** [comment]
> message after sign in toggles states should be a modal that displays which addresses you'll receive notifications about -> link and CTA should go to notifications page

You mean that the `email-authentication` page should be a modal with these characteristics? Sounds cool

**Comment by Bitcoinera** [comment]
> voting power changes message is broken (should show %)

Seems correct? What do you think is broken?

![image](https://user-images.githubusercontent.com/40721795/87673496-f5ab4f00-c774-11ea-897e-6e38e709e335.png)

**Comment by jbibla** [comment]
`increased from 0.214230 to 0.235088 (9.284% increase)`

should be

`increased from 0.21% to 0.24%`

**Comment by faboweb** [comment]
Remember to do the issues as individual PRs

**Comment by Bitcoinera** [comment]
> Remember to do the issues as individual PRs

But many of these things are super tiny... I would do all of the "now" ones simply in this PR

**Comment by Bitcoinera** [comment]
Yes, I know what you are about to say: it's a one line change :laughing:

**Comment by faboweb** [comment]
... I think this will be a lot smoother with multiple PRs

**Comment by Bitcoinera** [comment]
> ... I think this will be a lot smoother with multiple PRs

But not 12 PRs?

**Comment by jbibla** [comment]
bug - the form validation for sign-up-email is not strong enough. the user will see the error message but properly formatted emails will still go through to the API

![Screen Shot 2020-07-16 at 4 31 23 PM](https://user-images.githubusercontent.com/6021933/87719706-cb13c300-c781-11ea-9b30-5a4c16f7efc8.png)

**Comment by jbibla** [comment]
we should be using native validation too:

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

**Comment by Bitcoinera** [comment]
> we should be using native validation too:

Nice! Let's do it

**Comment by Bitcoinera** [comment]
Oops, there is one item missing!

- [ ] take user out from notifications back to Paywall when they sign out being on the notifications page

**Comment by Bitcoinera** [comment]
What do you mean in this one `hide app menu - add logo - deselect current network when on notifications page` when you say "add logo", @jbibla ?

**Comment by jbibla** [comment]
i'll handle it in my PR - no worries.

**Comment by Bitcoinera** [comment]
> i'll handle it in my PR - no worries.

Should it look like this?

![image](https://user-images.githubusercontent.com/40721795/87943541-7e402d00-ca9e-11ea-9e3d-a8f759dfcc0d.png)

**Comment by jbibla** [comment]
yes, but also deselect selected network. i already did this in my PR so please don't add it to your open PR.

**Comment by Bitcoinera** [comment]
> yes, but also deselect selected network. i already did this in my PR so please don't add it to your open PR.

OK. Should I then go for the last item on the list then? This:

"message after sign in toggles states should be a modal that displays which addresses you'll receive notifications about -> link and CTA should go to notifications page"

**Comment by jbibla** [comment]
you should get your open PRs merged. after that, yes.

**Comment by Bitcoinera** [comment]
> you should get your open PRs merged. after that, yes.

My PRs are just ready to be merged! (Except the two push notifications ones and the night mode one).

This one for example #4481 just needs your styles approval
This last one #4548 you just need to merge it

**Comment by jbibla** [comment]
ok i'll have a look.

what about: https://github.com/luniehq/lunie/pull/4546

**Comment by Bitcoinera** [comment]
> what about: #4546

This one I am trying to fix the validator list E2E error

**Comment by jbibla** [comment]
is the e2e issue because of westend being down?

**Comment by Bitcoinera** [comment]
what happened? Why did reopen this one?

**Comment by faboweb** [comment]
There are 2 items that are not done...

> message after sign in toggles states should be a modal that displays which addresses you'll receive notifications about -> link and CTA should go to notifications page

> magic link copy needs to be updated

**Comment by Bitcoinera** [comment]
True, I hadn't forgotten about the last one. Currently `email-authentication` looks quite ugly, 100% agreed

**Comment by faboweb** [comment]
Yep, this is mostly about the email-authentication page

**Comment by jbibla** [comment]
i will do this now
