### ISSUE TITLE
run yarn command then print errors on Mac

### ISSUE THREAD

**Issue by wade-liwei** [luniehq/lunie#4527]
warning "workspace-aggregator-d6030df9-a79a-4046-b39b-b120e16a416f > api > apollo-server > apollo-server-core > apollo-engine-reporting > apollo-graphql@0.4.4" has incorrect peer dependency "graphql@^14.2.1".
[4/4] 🔨  Building fresh packages...
[9/21] ⢀ ejs
[2/21] ⢀ bcrypto
[3/21] ⢀ tiny-secp256k1
[8/21] ⢀ fsevents
error /Users/a/go/src/github.com/luniehq/lunie/node_modules/bcrypto: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/a/go/src/github.com/luniehq/lunie/node_modules/bcrypto
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.20.0 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:607:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/a/.nvm/versions/node/v10.20.0/bin/node" "/Users/a/go/src/github.com/luniehq/lunie/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/a/go/src/github.com/luniehq/lunie/node_modules/bcrypto

**Comment by faboweb** [comment]
maybe try updating your node/yarn?

**Comment by jbibla** [comment]
@wade-liwei let us know if after updating node and yarn you still experience this issue.
