### ISSUE TITLE
increase decimal limit on Lunie

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4535]
Request from a user to increase decimal limits so small amounts of ATOM can be un-delegated rather than left in delegation perpetually:

```
I have dust delegated in my account.  0.000000635932095321469

Annoyingly, on all explorers it still shows up as a Validator I'm delegating to. I'm unable to undelegate this amount on Lunie and other tools because there is a 6 decimal place limit. Is there a reason this can't be increased to 21 decimal places or however places the Cosmos blockchain allows for?

```

**Comment by jrmoreau** [comment]
`I'd happily pay the 0.005 atom fee on top of this just to remove it. Provided I have enough balance in my account to cover the fees, I should be able to make the tx. Thanks. 
`

**Comment by jbibla** [comment]
we're not going to do this any time soon. though if we were, we would probably add a "dust" query param ... one day.
