### ISSUE TITLE
Kusama Balances are blank for user

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4547]
User reports no balance or transaction history in their Kusama view despite address showing funds

**Comment by jrmoreau** [comment]
address for example: EAG4KpKW7ygZizatCdSNnRQDcGQrGQbvERRP2RsWcwZXrrc

![lunie](https://user-images.githubusercontent.com/1614127/87946678-5639d500-ca70-11ea-9a61-01c772788421.JPG)
![lunie 2](https://user-images.githubusercontent.com/1614127/87946681-58039880-ca70-11ea-8526-fc75cea8df29.JPG)

**Comment by faboweb** [comment]
Can we get the address of the user?

**Comment by faboweb** [comment]
Can't replicate on production

**Comment by jrmoreau** [comment]
@faboweb will see if they have ad blockers or anything else that might interfere
