### ISSUE TITLE
GQL query error (Cannot query field) shouldn't break the app

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4549]
**Is your feature request related to a problem? Please describe.**

Lunie currently breaks if a query triggers a `Cannot query field error`

![image](https://user-images.githubusercontent.com/40721795/87965385-f36e2b00-cabb-11ea-9e81-7f5019864f03.png)

**Describe the solution you'd like**

Handle this error nicely so the whole app doesn't break

**Describe alternatives you've considered**

None

**Additional context**

E2E tests wouldn't completely break on PRs which both change API and FE

**Comment by faboweb** [comment]
Maybe we should just log here and not throw: https://github.com/luniehq/lunie/blob/develop/app/src/gql/apollo.js#L79

**Comment by Bitcoinera** [comment]
> Maybe we should just log here and not throw: https://github.com/luniehq/lunie/blob/develop/app/src/gql/apollo.js#L79

Yes, good point

**Comment by Bitcoinera** [comment]
:thinking: doesn't seem to be trivial this issue

**Comment by faboweb** [comment]
The last error looks like a different error

**Comment by Bitcoinera** [comment]
> The last error looks like a different error

It seems the API simply dies. Really strange

**Comment by jbibla** [comment]
@faboweb

**Comment by Bitcoinera** [comment]
I guess we don't really know. Maybe better close for now. Would be good to have some kind of directory or list with issues we close simply because we kick them forward. Otherwise we might wrongly think this was fixed

**Comment by faboweb** [comment]
Won't fix right iw
