### ISSUE TITLE
Validator Profile Endpoint Proposal

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4559]
Related to #4468 

#### The solution I have thought of:

My approach is to create a file called `global-store.js` inside the `stores` folder that will serve as a global store for all our networks. So that shared content/data across networks (validators is a very clear example for this) gets stored in here.

`GlobalStore` is a class composed by the following attributes:

```
  constructor() {
    this.stores = []
    this.db = database
    this.globalValidators = {}
}
```
With maybe more to come that would make sense as validators across networks do.

What do you think of this approach? What would you improve?

You can have a look at the current file [here](https://github.com/luniehq/lunie/blob/1ce919ff973e4f75bc92e4159356e6dbe5f7eda9/api/lib/stores/global-store.js). Yes, `getStore`doesn't work as we left this functionality aside for now. But I could just pass store from `network-container.js` or from `resolvers.js`.

**Comment by faboweb** [comment]
great idea. I would create the globalStore first and pass it on networkStore creation. Maybe consider a renaming of the old store to networkStore.

**Comment by Bitcoinera** [comment]
Ouch, this was when we still wanted to have a cross-network validator profile. Let's close it
