### ISSUE TITLE
Handling different algos: Ledger Follow Up

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4561]
**Is your feature request related to a problem? Please describe.**

We should also be able to handle different derivations paths / curves on the Ledger

**Describe the solution you'd like**

Just do it

**Additional context**

The problem here is how to test this. The Polkadot app hasn't been released yet and there seems to be no Terra Ledger app (still investigating)

![image](https://user-images.githubusercontent.com/40721795/88149903-fcb4e000-cc00-11ea-963b-5d5f4b4ac0eb.png)

**Comment by jbibla** [comment]
all the cosmos SDK chains use the cosmos ledger app

we will do this one day but not right now

**Comment by Bitcoinera** [comment]
Yeah, I also don't think it is something we need to pay so much attention to for now. At least, until the Polkadot Ledger app is not released

**Comment by Bitcoinera** [comment]
Will probably be released quite soon I guess? People are already asking on reddit: https://www.reddit.com/r/ledgerwallet/comments/iduwec/polkadot_in_ledger_live_and_support/

**Comment by jbibla** [comment]
this can be part of an epic around improving ledger ux.

**Comment by Bitcoinera** [comment]
I am not sure ho this would work out / how to do this, actually :thinking:

**Comment by faboweb** [comment]
Is this needed right now?

**Comment by Bitcoinera** [comment]
There should be a Hibernate option in GitHub. Otherwise I guess we will open the same issue again in the future. But guess that is not such a big deal anyway. I just like the recycling philosophy
