### ISSUE TITLE
Deprecate old balances query

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4564]
**Is your feature request related to a problem? Please describe.**

Currently the old balance query version is still being used in some ActionModals (ModalDeposit, ModalPropose and UndelegationModal, concretely).

We just need to replace it with the new version, `balancesV2`, so we can just get rid for once and for all of the old `balances`.

Overview will be only used in `transaction-manager.js` after we merge #4558  (if we don't erase it completely there already). AccountInformation should taken using the `transactionMetada` query instead.

**Comment by jbibla** [comment]
so this is a refactoring ticket?

**Comment by Bitcoinera** [comment]
> so this is a refactoring ticket?

more like a deprecation ticket. It is not very clean to be using two different queries for balances. More prone to bugs, as we have seen

**Comment by Bitcoinera** [comment]
We should still do this. Confusing right now with the two different balances queries

**Comment by Bitcoinera** [comment]
:muscle:
