### ISSUE TITLE
Create notification alert for Lunie Live telling users if Lunie is experiencing downtime or will undergo maintenance

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4578]
**Is your feature request related to a problem? Please describe.**
Ideas for notifications outside of topics

**Describe the solution you'd like**
If Lunie will have planned or un-planned maintenance or downtime we can push a notification to users telling them as such

**Comment by jbibla** [comment]
lol Lunie Live

we have a "Lunie" notification type - but not sure how we create them @Bitcoinera

**Comment by Bitcoinera** [comment]
We could just add this notification manually to DB I think. And just have some loop to check if there is any of this notifications type. Then we should delete the maintenance notification to trigger the watcher again the next time.

You create a notification type by adding it to the `notifications-types.js` file

**Comment by Bitcoinera** [comment]
Would be nice to have. Every time we set a maintenance bar, users receive a push/email notification

**Comment by jrmoreau** [comment]
This would be big - it's not a nice feeling to come to an app you need to use and unexpectedly see it's under maintenance. Sending an email or push notification would set expectations better.

**Comment by jbibla** [comment]
yep i think we can do this already (manually doable). 

we could add maintenance bars to notifications? @Bitcoinera @faboweb ?

**Comment by Bitcoinera** [comment]
we would just need some polling in a kind of meta-listener ("meta" because it would be beyond networks) in API

**Comment by jbibla** [comment]
same with extension - we should probably push not poll - but yes you're right.

**Comment by Bitcoinera** [comment]
> same with extension

What do you mean with the extension? You lost me there. Notifications for the extension?? :eyes:

**Comment by jbibla** [comment]
in the address improvement PR we switched from polling to relying on the extension to push a message to lunie

**Comment by Bitcoinera** [comment]
> in the address improvement PR we switched from polling to relying on the extension to push a message to lunie

But how can the DB push anything to API? You need to query DB instead (poll). Unless Hasura has some black magic to it I don't know of yet

**Comment by faboweb** [comment]
We could create an endpoint in the API where we can send messages to users secured with a shared password.

**Comment by Bitcoinera** [comment]
For premium users? What would prevent them from sharing this password with other unregistered people?
