### ISSUE TITLE
Create notification alert for Lunie Live telling users confirming their email associated with their account was changed

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4579]
**Is your feature request related to a problem? Please describe.**
Ideas for notifications outside of topics

**Describe the solution you'd like**
If an email is changed or updated on a user's account they get a notification confirming this in case they need to pay attention to someone else accessing their account

**Comment by jbibla** [comment]
@faboweb does this apply to our current model?

**Comment by faboweb** [comment]
I think Google handles this. But let's confirm.
