### ISSUE TITLE
Terra rewards balances showing incorrectly

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4590]
Rewards are not displaying correctly for address with multiple denoms with reward balances. 

Reference address: terra1mpf4eflxsduv05kh29zkh8y6ch4kgee8h3sfr2

**Comment by jrmoreau** [comment]
<img width="1678" alt="Screen Shot 2020-07-25 at 3 27 25 PM" src="https://user-images.githubusercontent.com/1614127/88464764-5a5c5d00-ce8b-11ea-87a8-c83497cd57da.png">

**Comment by faboweb** [comment]
What should it show?

**Comment by Bitcoinera** [comment]
True, it seems to be missing extra rewards from currencies that are only rewards, not balances:

![image](https://user-images.githubusercontent.com/40721795/88483250-ee4f2700-cf66-11ea-8c43-cb2ff0d91956.png)

https://terra.stake.id/?#/address/terra1mpf4eflxsduv05kh29zkh8y6ch4kgee8h3sfr2

Very interesting case

**Comment by faboweb** [comment]
Ok so in balancesv2 we need to also check if there are denoms where there are rewards but no balances

**Comment by Bitcoinera** [comment]
> Ok so in balancesv2 we need to also check if there are denoms where there are rewards but no balances

Yeah, let's do it!
