### ISSUE TITLE
Add a big ol' receive button on mobile

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4597]
**Is your feature request related to a problem? Please describe.**
User reported confusion not seeing a `receive` button anywhere on the mobile app 

**Describe the solution you'd like**
we should have a `receive` button that allows users to copy their address, share and/or display a QR code

**Describe alternatives you've considered**
we actually hide the option to copy the address from the main screen. 

**Additional context**
![Screenshot_20200727-112858](https://user-images.githubusercontent.com/1614127/88561055-e93cb700-cffc-11ea-8d08-6b3af7ff32aa.jpg)
![Screenshot_20200727-112853](https://user-images.githubusercontent.com/1614127/88561060-ecd03e00-cffc-11ea-9995-07d8221e58b7.jpg)

**Comment by jbibla** [comment]
yep i agree! we have designs for this which we will try to get in soon.

**Comment by jrmoreau** [comment]
@jbibla can we have an entirely different layout for explore mode? Something stripped down?

**Comment by jbibla** [comment]
i suppose so - but i was thinking more about on boarding / communicating the possibility.

**Comment by jrmoreau** [comment]
@jbibla I think it is inherently problematic having the same views/buttons for explore mode and actual logged-in mode. It sort of loses the distinction and requires exact knowledge from the user's perspective. They feel like very different and distinct modes of usage. I actually think there should be no action buttons on all explore mode personally.

**Comment by jbibla** [comment]
interesting. i haven't heard of any confusion once people are actually in explore mode. but i have heard and seen that people don't realize it's possible.

**Comment by jbibla** [comment]
maybe i don't understand why the buttons are the problem. i'd like to better understand your vision!

**Comment by jrmoreau** [comment]
@jbibla have you ever watched a video game preview where you're seeing the action un-fold but you're not able to play? That's the emotional feeling I am trying to convey 🤣

**Comment by jbibla** [comment]
lol ok nice. we could call it "whale mode" and we can pick a whale address people can try lunie with 😆

**Comment by jrmoreau** [comment]
@jbibla "be rich for a day" mode!~

**Comment by jbibla** [comment]
it would be great to do this - simple enough to implement and nice ux improvement.
