### ISSUE TITLE
Show actual error if polkadot tx fails

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4613]
**Is your feature request related to a problem? Please describe.**

We currently only show that a tx is not successful or successful. We should show the user what actually failed so he can act on that and is not confused (like me).

**Describe the solution you'd like**

Look for failure instead for success events. Then use the error codes in the failures together with this error lookup (https://github.com/polkadot-js/api/issues/2454#issuecomment-665091831) to get the error.

**Describe alternatives you've considered**

**Additional context**

**Comment by faboweb** [comment]
good task for you @mariopino if you find time

**Comment by mariopino** [comment]
@faboweb 

Can I add `error: String` to `TransactionV2` (optional) safely? Or it's better to create a TransactionV3, BlockV3, etc?

I think a error field in Transaction could be useful in general, so we can provide a better info to users.
