### ISSUE TITLE
Add new network when set to enabled

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4645]
I just realized while attempting to recover the akash-testnet network that, apparently, we don't have the logic there to add a new network from DB when setting it to enabled.

This should be fairly easy and we could include the logic for it in the same loop where we watch for other network changes, I think. It should be quite easy to do, in any case

**Comment by faboweb** [comment]
I agree. let'S do it

**Comment by Bitcoinera** [comment]
I think it is better to close this for now. It would require changing the logic a bit (some kind of meta networks container for all networks where we would loop to observe any changes)
