### ISSUE TITLE
Claiming rewards error in Cosmos

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4648]
for example address: cosmos1xhvnjnp9g9zrswh8hyttq0m4jv5r5sn7p24jvw

Error message: ```Withdrawal failed: Broadcast was not successful: {"codespace":"sdk","code":4,"message":"signature verification failed; verify correct account sequence and chain-id"}.```

**Comment by jrmoreau** [comment]
Image from user. I cannot reproduce. 

![IMG_0160](https://user-images.githubusercontent.com/1614127/89186551-f6f8bc00-d569-11ea-9502-e80dcb978c48.jpg)

**Comment by Bitcoinera** [comment]
Maybe an account sequence error somehow?Although we are taking the sequence from the chain itself so... :shrug:  I don't really know. Cache problem then?

How many times have they tried? Did they try to refresh / use another browser?

**Comment by jrmoreau** [comment]
Have not heard back about any other questions. Stay tuned.
