### ISSUE TITLE
Improve address management

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4665]
**Is your feature request related to a problem? Please describe.**

Currently, it is not possible to have 2 accounts for one network
Currently, we have several separate lists of addresses (local, extension) this is confusing

**Describe the solution you'd like**

part 1
- [x] add extension accounts to address list
- [x] add local accounts to address list
- [x] reduce card sign in: remove sign in with account, remove sign in with extension
- [x] (optional) on extension accounts update, update also Lunie

part 2
- [x] add more context (stash, controller)
- [x] use names in the user menu
- [x] add max height and scroll bar to user menu address list

part 3
- [ ] add button for forgetting an address
- [ ] add security warning popup with pw confirmation if trying to forget a local account
- [ ] add explanation popup for forgetting an extension account

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
`remove sign in with extension` 

:eyes:

**Comment by faboweb** [comment]
Remove the sign in with extension and local sign in options from the card sign in. They are not needed anymore when all addresses appear in the user menu.

**Comment by jbibla** [comment]
> remove sign in with extension

he just means the option on the card sign in modal - because the list should auto-magically appear in the user menu

**Comment by Bitcoinera** [comment]
ah ok, now I'm getting this task. Cool

**Comment by jbibla** [comment]
- [ ] add more context (stash, controller)
- [ ] use names in the user menu
- [ ] add max height and scroll bar to user menu address list

**Comment by Bitcoinera** [comment]
> use names in the user menu

But this would be a PR in itself no? The ability to allow people to tag their addresses with names. We'd need a edit function. Should it be a modal opening for editing or how it should look like?

**Comment by faboweb** [comment]
We would use the names from the extension and the local accounts. For Ledger it would say "Ledger" for explore mode it would say "Explore"

**Comment by Bitcoinera** [comment]
> We would use the names from the extension and the local accounts. For Ledger it would say "Ledger" for explore mode it would say "Explore"

OK, I am happy to work on this. Next thing I am doing after applying reviews to #4607

**Comment by Bitcoinera** [comment]
So how should I represent the account type (`local`, `ledger`, `extension`) ?

**Comment by Bitcoinera** [comment]
> * [x]  add more context (stash, controller)
> * [ ]  use names in the user menu
> * [x]  add max height and scroll bar to user menu address list

Just accounted for all these things. But we should also merge luniehq/cosmos-keys#103 to be able to display the addressRole for all Polkadot accounts, not only the current one

**Comment by Bitcoinera** [comment]
I'd have this one left, which is quite cool: `(optional) on extension accounts update, update also Lunie`

**Comment by Bitcoinera** [comment]
To make the `addresses` computed for UserMenu reactive I just had to add a `cache: false` directive, as explained here: https://github.com/vuejs/vue/issues/214#issuecomment-664665263 and here https://github.com/vuejs/vue/issues/214#issuecomment-610541388

**Comment by Bitcoinera** [comment]
@jbibla I can help you with this one, adding the logic: "add button for forgetting an address"

**Comment by jbibla** [comment]
i opened a new issue to discuss "forgetting" https://github.com/luniehq/lunie/issues/4751
