### ISSUE TITLE
Style Notification Emails

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4680]

**Comment by jbibla** [comment]
i really don't think we should spend time on styling these emails but if James wrote new content for the emails let's definitely add that! 

@jrmoreau where is the content?
@faboweb where can I edit these emails?

**Comment by faboweb** [comment]
`notificationController.js` > `getEmailContent`

**Comment by faboweb** [comment]
https://docs.google.com/document/d/1aqsnT92SQqPznEmm2UuF5OBUKsymprTOjVnqvtQtzVU/edit
