### ISSUE TITLE
remove validator rank changes from personal notification list for now

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4681]
**Is your feature request related to a problem? Please describe.**

the network wide validator changes are too noisy. especially on kusama and polkadot. 

**Describe the solution you'd like**

remove these notifications from the notifications page for now as they are not relevant for most users most of the time.

**Describe alternatives you've considered**

we could leave it and wait for users to complain - we would also have to fix the math because the percentage is not displaying correctly:

```
voting power increase from 0 to 0 doesn't make sense
voting power decrease from 0 to 0 doesn't make sense
voting power decrease from 0.01 to 0.01 (-10.25%) doesn't make sense
```

![](https://user-images.githubusercontent.com/6021933/89831912-9c90ca00-db2c-11ea-83ac-aa4fe6429561.png)

**Comment by faboweb** [comment]
Should this be removed or should we do total power changes instead of relative power changes?

**Comment by jbibla** [comment]
remove from personal notifications page for now - but yes, should be total power changes in the future
