### ISSUE TITLE
Network switching (Polkadot) not working on mobile

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4690]
User reports when switching to the Polkadot network the dashboard goes back to the Cosmos theme and doesn't load any data (see screenshots)

**Comment by jrmoreau** [comment]
User says the validator page displays fine for Polkadot (confirming with screenshots) in the Polkadot theme, but with the dashboard it does not load. 

![IMG_8244](https://user-images.githubusercontent.com/1614127/89952382-25763700-dbfb-11ea-98a1-b2b40c6f490d.png)
![IMG_8245](https://user-images.githubusercontent.com/1614127/89952384-26a76400-dbfb-11ea-978f-48418695aaa4.png)

**Comment by jrmoreau** [comment]
More screenshots of the background. @faboweb @jbibla how does this look to you? 

![IMG_8247](https://user-images.githubusercontent.com/1614127/89970310-954de700-dc26-11ea-84b5-b07febe61ee0.png)
![IMG_8248](https://user-images.githubusercontent.com/1614127/89970316-97b04100-dc26-11ea-99b1-b68e8d9e68f7.png)
![IMG_8249](https://user-images.githubusercontent.com/1614127/89970318-997a0480-dc26-11ea-81db-638b59b159a7.png)

**Comment by jrmoreau** [comment]
from the user

```U5
I cross checked with polkadot.js and I confirmed that the nominated validator list is identical.

3h · 
U5
One strange thing was that I failed to stake in mobile app saying “not allowed to sign in this network”. So I staked my coins through the web interface of Lunie. Maybe related?
```

**Comment by jbibla** [comment]
what version of the ios / android app?

**Comment by jrmoreau** [comment]
@jbibla 
```iOS 13.6, iPhone 11 Pro. 
```

**Comment by jbibla** [comment]
i'm looking for the version of the lunie app which can be found in test flight. mine is currently 1.0.223. if the user's is not 1.0.223 ask them to update the lunie app in testflight and reconfirm the bug.

**Comment by jrmoreau** [comment]
@jbibla I hit comment before realizing my paste was cut off. Testflight is App `1.0.206`so having him update and try again
