### ISSUE TITLE
Scriptrunner not working as expected

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4719]
Supposedly the scriptRunner should replace all validator images for a network every 24h. However, as the broken Polkadot images links in validatorprofiles has shown, this isn't at all the case.

<img width="450px" src="https://user-images.githubusercontent.com/40721795/90279240-201e2400-de69-11ea-8aff-0b65b6caa0c3.png">

Some images were recovered but most of them are still broken.

That's why we should investigate and fix scriptRunner, because next time instead of staging DB it could be production DB which gets broken and that would be quite problematic, if we don't have this under control.

**Comment by faboweb** [comment]
does the scriptrunner work locally?

**Comment by Bitcoinera** [comment]
> does the scriptrunner work locally?

How do you add the Authorization token to the request? The README is not very clear...

![image](https://user-images.githubusercontent.com/40721795/90334765-3c88a080-dfd0-11ea-8ecf-fcbf0171fb62.png)

Not sure of how to test it locally otherwise. Getting 403 Forbidden for every request :shrug:

**Comment by faboweb** [comment]
You need to start the scriptRunner with `HASURA_URL=https://staging-db.lunie.io/v1/graphql AUTHENTICATION_TOKEN=password docker-compose up` and then you can add a header "Authorization: password" to the request. This is well documented

**Comment by faboweb** [comment]
Instead of using the Authorization tab in postman, use the header tab and add the header thee

**Comment by Bitcoinera** [comment]
Where are the logs for scriptRunner? They seem to be gone :eyes: 

![image](https://user-images.githubusercontent.com/40721795/91051251-2017e400-e620-11ea-82d8-b68b21854657.png)

**Comment by faboweb** [comment]
All there
![image](https://user-images.githubusercontent.com/5869273/93911820-8566ff80-fcc8-11ea-8a7c-4a3869b41457.png)

**Comment by faboweb** [comment]
IS this still an issue??

**Comment by Bitcoinera** [comment]
I guess so. We never investigated it. But the polkadot images issue in staging DB really showed that it doesn't work as we thought (every 24h total update for all validators)

**Comment by faboweb** [comment]
which image is missing?

**Comment by Bitcoinera** [comment]
> which image is missing?

To fix all the Polkadot validators images it needed over a week. Now I think it finally updated all of them... but needed a lot of time to do so

**Comment by Bitcoinera** [comment]
Still relevant

**Comment by faboweb** [comment]
> Still relevant

sure? the picutres seem to be coming in now

**Comment by Bitcoinera** [comment]
all of them :eyes: ? Or only for some validators?

**Comment by faboweb** [comment]
I think all of them. We should filter out `https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png` as this equals to no image
