### ISSUE TITLE
DOT (old) redenomination display bug on mobile

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4720]
The `DOT (old)` redenomination ticker does not show properly on mobile. 

![Screenshot_20200815-172630](https://user-images.githubusercontent.com/1614127/90322032-2bcb2280-df1d-11ea-8d83-47f16282f7d8.jpg)

**Comment by Bitcoinera** [comment]
This is probably due to an old version. The user needs to go to Play Store and update their app

**Comment by Bitcoinera** [comment]
Unfortunately, I'm afraid once they do that they will be saluted by this screen:

<img width="350px" src="https://user-images.githubusercontent.com/40721795/90334929-6393a200-dfd1-11ea-9922-3ae103609f70.png">

**Comment by jrmoreau** [comment]
@Bitcoinera lol it's my app on my phone and there was no option to update on Google Play at the time! 😬
