### ISSUE TITLE
Enable Vote with Time Locking and Deposit in Polkadot/Substrate

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4738]
Part of #4456

**Comment by jbibla** [comment]
please refer to designs: 

https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/Ow07x8
https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/g3YZPq
https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/2yDeRJ
https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/DApAG4

**Comment by Bitcoinera** [comment]
Ah I see. So deposit is if you want to vote with conviction. Alright:

![image](https://user-images.githubusercontent.com/40721795/90768401-ee84dd00-e2ee-11ea-85d3-481f03492014.png)

**Comment by Bitcoinera** [comment]
I can do a PR enabling voting in Polkadot without deposit and then another PR including that specific modal from the design + the deposit logic.

Or maybe just do both in one :shrug:
