### ISSUE TITLE
refactor sessions, addresses, accounts, keystore, roles

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4753]
we are storing sessions, accounts, addresses in many ways with different data which is a ton of added complexity (see user menu). we should seek to standardize this. 

- what's the different between a session and account (not much ;)) ? 
- network or networkId or both - but not one or the other
- polkadot addresses should include role
- include an icon always

maybe the keystore module can take care of this so `accounts` is accessible as a getter and no enriching is happening in the components?

```
extensionAccounts {
  address:"cosmos1yfffl6ux2znhzlspyr2pyg9k52h2txeyscen60"
  name:"ext1"
  network:"cosmos-hub-mainnet"
}

session {
  addresses {
    address:"terra1v6kkfdypq58wtry9qdqxrk2uylmhh4szrzhw9g"
    networkId:"terra-mainnet"
    type:"explore"
  }
}

allSessionAddresses [
  {
    HDPath:"m/44'/118'/0'/0/0"
    address:"terra1v6kkfdypq58wtry9qdqxrk2uylmhh4szrzhw9g"
    curve:"ed25519"
    icon:"https://lunie.fra1.digitaloceanspaces.com/network-icons/terra.png"
    networkId:"terra-mainnet"
    sessionType:"explore"
    title:"Terra"
  }
]
```

**Comment by Bitcoinera** [comment]
> polkadot addresses should include role

Polkadot addresses will always need to be enriched with this info since it is dynamic

**Comment by Bitcoinera** [comment]
> include an icon always

why? You already have networkId :shrug: We just need to name the network icons consistently. I don't see the need

**Comment by Bitcoinera** [comment]
I agree on the rest, just I think the session module is more convenient. Simply include a new field called `allUsedAddresses` or `allUsedAccounts`, for that matter

**Comment by jbibla** [comment]
> Polkadot addresses will always need to be enriched with this info since it is dynamic

yes sure. but in the API not on the FE.

> why? You already have networkId 🤷 We just need to name the network icons consistently. I don't see the need

yeah, maybe if they are consistent it would be ok. `network` `networkId` `icon` makes displaying the icon a pain.

**Comment by Bitcoinera** [comment]
> yeah, maybe if they are consistent it would be ok. `network` `networkId` `icon` makes displaying the icon a pain.

just had a look at `public/img/networks` an the namings there look quite consistent to me

**Comment by jbibla** [comment]
i meant if the objecy keys are consistent:  `network` `networkId` `icon`
