### ISSUE TITLE
Logout button for Lunie notification view

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4754]
@jbibla 

After you've created an account on Lunie and have several accounts associated with your view in the profile button even when you're logged out as shown the addresses don't disappear. If you click on the accounts you can initiate a transaction for signing and if associated with the extension you will still get prompted to open the extension, enter pw and send. Also the same with the Ledger (if it's connected). 

I suppose a real "logout" button would clear all of these so you would not know which accounts were being viewed or used previously when logged in. 

<img width="1533" alt="Screen Shot 2020-08-21 at 10 59 12 PM" src="https://user-images.githubusercontent.com/1614127/90947187-eff2fa00-e401-11ea-905e-043e00513b4d.png">

**Comment by jbibla** [comment]
it's confusing that some of the data is in local storage 

- ux of sign in / sign out is clunky and confusing
- data is stored locally and in firebase (if signed up for notifications)
- address management is starting to use this
