### ISSUE TITLE
Add network specific pre-built DEX functionality in Lunie for Terra

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4755]
Per a user request - create a view in Lunie that contains pre-built DEX functionality. User specifically asked for Terra's DEX functionality to facilitate swaps of a variety of stablecoins issues as rewards against LUNA. 

Obviously this is more useful once IBC is enabled, but specific network users would benefit from this being exclusive to their integration.

**Comment by Bitcoinera** [comment]
I don't think we are doing anytime soon, James... it is just too much. And only one user requested it

**Comment by jrmoreau** [comment]
I strongly believe we should add valid feature requests if users ask for them. Even if we don't do them right away @Bitcoinera. And more than one person asked for this via my support work just FYI

**Comment by Bitcoinera** [comment]
We also need to think of :moneybag: Better focus on paying features for now, I think :shrug:

**Comment by jrmoreau** [comment]
We can get paid to integrate this @Bitcoinera

**Comment by jbibla** [comment]
i see the value but it's hard to imagine this getting on our roadmap very soon.
