### ISSUE TITLE
Add hover-over info popup for `New DOT`

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4757]
Request from Polkadot team to add an info popup when hovering over `New DOT`

`“On approximately August 21st at 16:40 UTC (block number 1,248,328), the DOT token underwent a redenomination from its original sale. New DOT are 100x smaller than DOT (old). Therefore, your DOT balance is 100x higher and the price per DOT is 100x lower. The percentage of the DOT you own relative to total supply is unchanged. This will not affect the total value of your position. See the Polkadot blog post for more information.”`

**Comment by jbibla** [comment]
redenomination is over so this is no longer needed
