### ISSUE TITLE
Enable multi-validator selection for Polkadot

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4758]
Request from Dragonstake in Telegram

Input from a large validator that this is a critical feature from their POV to recommend users away from Lunie to other Polkadot wallets.

`something crucial that I miss in Polkadot Lunie wallet is a feature to nominate more than one validator at a time. 
I have to admit that I stopped forwarding users (my nominators) to use Lunie because of that. Do you think it will be implemented in a close future?`

`Given that I encourage ppl to nominate up to 16 validators you could imagine what a nightmare it implies... It's not only fees`

**Comment by jbibla** [comment]
involves at least a couple things:

- adding validator list to action modal
- make it possible to select multiple validators from validator list
