### ISSUE TITLE
Error creating new account in Westend: Expected a keyring type of either 'ed25519', 'sr25519' or 'ecdsa', found ' sr25519

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4759]
**Describe the bug**

Failing creating a new account in Westend:

```
Expected a keyring type of either 'ed25519', 'sr25519' or 'ecdsa', found ' sr25519
```

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/9256178/91076866-6a10c200-e640-11ea-95ba-53c98eca7583.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Bitcoinera** [comment]
Fixed!
