### ISSUE TITLE
Extension hot reload failing: FILE NOT FOUND

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4762]
Probably just some silly webpack bug:

![image](https://user-images.githubusercontent.com/40721795/91085763-350b6c00-e64e-11ea-95b1-354754b85db5.png)

Steps to reproduce:

- build extension locally
- run `yarn watch:dev`
- make some change in the code and try to open extension again

You will get the above blank screen with the FILE NOT FOUND error.

To fix it you need to rerun `yarn watch:dev`

**Comment by Bitcoinera** [comment]
I'm investigating this and seems related to staging-API being down...

**Comment by Bitcoinera** [comment]
Ah ok, the problem is that after rebuilding when hot reloading it loses the manifest.json. Investigating

**Comment by Bitcoinera** [comment]
```
      {
        from: 'manifest.json',
        to: 'manifest.json',
        transform: (content) => {
          const jsonContent = JSON.parse(content)
          jsonContent.version = version

          if (config.mode === 'development') {
            jsonContent['content_security_policy'] =
              "script-src 'self' 'unsafe-eval' https://www.google-analytics.com/analytics.js; object-src 'self'"
          }

          return JSON.stringify(jsonContent, null, 2)
        }
      }
```

manifest.json gets renames as manifest.js :thinking:  We are missing some rule here?

**Comment by Bitcoinera** [comment]
@mariopino could you reproduce this?

**Comment by mariopino** [comment]
> @mariopino could you reproduce this?

Yep, I'll try to reproduce today

**Comment by Bitcoinera** [comment]
:eyes: 

![image](https://user-images.githubusercontent.com/40721795/92929305-9a2dd280-f440-11ea-81c6-6de9a8d62443.png)

Did you make any progress here? Should I take this?

**Comment by Bitcoinera** [comment]
Mmm, trying various things but nothing seems to work. `manifest.json` always disappears for some reason

**Comment by mariopino** [comment]
> > @mariopino could you reproduce this?
> 
> Yep, I'll try to reproduce today

Sorry to be late but yep, it can be reproduced in Windows 10 / Chrome:

![image](https://user-images.githubusercontent.com/9256178/93208205-85ad4b00-f75c-11ea-98f9-8d453b3ad93d.png)

**Comment by Bitcoinera** [comment]
This got staled and it is a very annoying bug for development. Someone has any idea?

**Comment by jbibla** [comment]
well, there is something going on with `webpack-extension-reloader` and `HMR`. 

webpack-extension-reloader doesn't work with HMR: 
<img width="544" alt="Screen Shot 2020-10-14 at 8 15 10 AM" src="https://user-images.githubusercontent.com/6021933/95987425-69e9a300-0df5-11eb-8cc6-d04d10ea8a70.png">

the docs recommend using `__dirname` but we are using a static folder. 

... not sure! 

@faboweb any ideas?

**Comment by Bitcoinera** [comment]
Mmm, interesting :thinking: Maybe we should rename `dist` as `__dirname`?

**Comment by jbibla** [comment]
no no https://nodejs.org/docs/latest/api/modules.html#modules_dirname
