### ISSUE TITLE
Remove hard coded denom lookup

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4771]
**Is your feature request related to a problem? Please describe.**

All denom lookups are already dynamic in the DB. But we still have `denomLookup` in `cosmosV0-reducers.js`.

**Describe the solution you'd like**

Remove the hard coded lookup and use the `coinLookup` from the `network` object.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
:eyes: 
Are you working on this?

Just noticed you had self-assigned when I already had half of it done :sweat_smile:

**Comment by Bitcoinera** [comment]
OK, I'm going to finish this then
