### ISSUE TITLE
polkadot ux improvements

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4773]
- [x] remove amount field for substrate validators on nomination action modal (only if the user has bonded tokens already)
- [x] portfolio > unstake on balance row (in "Your Stake" section)
- [x] portfolio > stake button on balance row
- [x] validator > select on validator profile
- [x] validator > deselect on validator profile
- [x] portfolio page > warning and call to action for tokens in purgatory

**Comment by Bitcoinera** [comment]
> portfolio > unstake on balance row

In the end we decided to have this on the bonded amount row, right?

**Comment by Bitcoinera** [comment]
> remove amount field for substrate validators on staking action modal

Well, the idea is that this modal is only accessible from portfolio, so it is a "global" stake. There we need indeed to show the amount field

**Comment by jbibla** [comment]
*nomination modal

**Comment by Bitcoinera** [comment]
> (only if the user has bonded tokens already)

This should be a query to API. Ah yeah, but if delegations have amount 0 then they are just nominations :thinking: Alright
