### ISSUE TITLE
User can enter negative amounts in Stake modal

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4781]
**Describe the bug**

User can enter negative amounts in Stake modal.

**To Reproduce**

 On latest develop:

1. Log in
2. Go to validators page
3. Click on Stake button
4. Enter a negative amount
5. Click on Next
6. No validation errors, now you can see a negative invoice

**Expected behavior**

Validation should prevent this.

**Screenshots**

![image](https://user-images.githubusercontent.com/9256178/91701181-34effc80-eb77-11ea-9959-fee81c22d4fe.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Bitcoinera** [comment]
Good catch

**Comment by mariopino** [comment]
Solved by @Bitcoinera
