### ISSUE TITLE
New Address Selection component

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4790]
We have instead of the card sign a new address selection component when clicking on portfolio and the user is not signed in there.

Title should be: "Which address do you want to use?"

It should be followed by the list of all addresses (for that network), like in the user menu. Attention: refactor list first and reuse.

Below the list should as well be a button: "Add an Address"

Plus:
Card Sign in title should say: "How do you want to add an address?"

**Comment by Bitcoinera** [comment]
OK, and it would look like the current CardSignInRequired but with these changes, right? SessionFrame

**Comment by faboweb** [comment]
Yes will be a SessionFrame
@jbibla can you sketch this quick to unblock Ana?

**Comment by jbibla** [comment]
- if there are no addresses in the list for that network it should show a "create new address" button
- "add an address" button should go to modified "card sign in"
- modified card sign in should say "add an address" and the options should be [Explore, Ledger, Create New]

![IMG_3173](https://user-images.githubusercontent.com/6021933/94435712-7f11d100-0169-11eb-8b62-440349f72c7a.JPG)

**Comment by Bitcoinera** [comment]
> * if there are no addresses in the list for that network it should show a "create new address" button
> * "add an address" button should go to modified "card sign in"
> * modified card sign in should say "add an address" and the options should be [Explore, Ledger, Create New]

Hey, looks super technical with the measurement board behind! We are making Science here! :test_tube: 

So if we move the "Add an address" option to the CardSignIn, then what would remain on UserMenu? Or it would the same than now, "Add an address" option on UserMenu opens this new CardSignIn. But yeah, then we can get rid of the "Create an address" option on UserMenu... ah no, OK, because "Create an address" only appears on the CardSignIn if there are no existing addresses for that network.

Am I getting this right? Is it new address per network or overall?

**Comment by jbibla** [comment]
- no changes to the user menu
- i don't think you need to change the new address flow

**Comment by Bitcoinera** [comment]
So what changes here actually? Just that you get a list of addresses instead of the Ledger & Extension options?

I prefer getting those options actually. I already miss the Extension option in fact

**Comment by jbibla** [comment]
we want to display a modal with all the addresses that might matter to someone.

when you click "add an address": 

> modified card sign in should say "add an address" and the options should be [Explore, Ledger, Create New]

**Comment by Bitcoinera** [comment]
Ah, this one. Are we going to do this in the end? Where? In Lunie-light only or also here?

**Comment by jbibla** [comment]
manage addresses kind of started this work. but we can close this for now.

**Comment by Bitcoinera** [comment]
OK. Actually it is just about re-utilizing the ManageAccounts component. Very easy to do
