### ISSUE TITLE
Un-stake failing on Kusama

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4793]
Error message: 

`Unstaking failed: Broadcast was not successful: 1010: Invalid Transaction: Transaction has a bad signature.`

**Comment by jrmoreau** [comment]
address: CdqgujMvS44SRpmbs1RL9KC4hw5q4WGwydUDhy1TPMa2maq

Lunie version 1.0.35.
Brave browser, Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit).
Windows 10 OS, version 10.0.19041 Build 19041.

**Comment by jrmoreau** [comment]
error log:

VM59:1 The value "1viewport-fit" for key "initial-scale" was truncated to its numeric prefix.

VM59:1 The key "cover" is not recognized and ignored.

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' data: <URL>".

instrument.js?2f61:110 Expecting backend at: https://production-api.lunie.io

contentScript.js:1 EXT Content Script Loaded

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

instrument.js?2f61:110 Connecting to: kusama

DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for chrome-extension://gannpgaobkkhmpomoijebaigcapoeebl/bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for chrome-extension://homifejhmckachdikhkgomachelakohh/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load SourceMap: Could not load content for http://localhost:8080/headless-content.js.map: Connection error: net::ERR_CONNECTION_REFUSED

VM16:1 POST https://monitoring.lunie.io:9000/api/3/store/?sentry_key=f052891fa3614d28b3f64e06268ec112&sentry_version=7 net::ERR_ABORTED 500

(anonymous) @ VM16:1

eval @ instrument.js?2f61:136

eval @ fetch.js?b1f7:46

SyncPromise @ syncpromise.js?bf04:73

FetchTransport.sendEvent @ fetch.js?b1f7:44

BaseBackend.sendEvent @ basebackend.js?7ce2:38

BaseClient._sendEvent @ baseclient.js?ffe5:318

BrowserClient._sendEvent @ client.js?1241:45

eval @ baseclient.js?ffe5:357

onfulfilled @ syncpromise.js?bf04:136

eval @ syncpromise.js?bf04:61

SyncPromise._executeHandlers @ syncpromise.js?bf04:55

SyncPromise._attachHandler @ syncpromise.js?bf04:46

eval @ syncpromise.js?bf04:126

SyncPromise @ syncpromise.js?bf04:73

SyncPromise.then @ syncpromise.js?bf04:125

eval @ baseclient.js?ffe5:348

SyncPromise @ syncpromise.js?bf04:73

BaseClient._processEvent @ baseclient.js?ffe5:346

BaseClient.captureEvent @ baseclient.js?ffe5:91

eval @ baseclient.js?ffe5:65

onfulfilled @ syncpromise.js?bf04:136

eval @ syncpromise.js?bf04:61

SyncPromise._executeHandlers @ syncpromise.js?bf04:55

SyncPromise._attachHandler @ syncpromise.js?bf04:46

eval @ syncpromise.js?bf04:126

SyncPromise @ syncpromise.js?bf04:73

SyncPromise.then @ syncpromise.js?bf04:125

BaseClient.captureException @ baseclient.js?ffe5:64

Hub._invokeClient @ hub.js?b6f8:57

Hub.captureException @ hub.js?b6f8:149

callOnHub @ index.js?ce06:16

captureException @ index.js?ce06:34

eval @ ActionModal.vue?f88e:739

Hub.withScope @ hub.js?b6f8:102

callOnHub @ index.js?ce06:16

withScope @ index.js?ce06:148

onSendingFailed @ ActionModal.vue?f88e:735

submit @ ActionModal.vue?f88e:705

async function (async)

submit @ ActionModal.vue?f88e:683

validateChangeStep @ ActionModal.vue?f88e:638

click @ ActionModal.vue?ccfe:13

invokeWithErrorHandling @ vue.runtime.esm.js?e832:1854

invoker @ vue.runtime.esm.js?e832:2179

original._wrapper @ vue.runtime.esm.js?e832:6917

sentryWrapped @ helpers.js?aabc:71

**Comment by mariopino** [comment]
I can not reproduce using https://staging--lunieio.netlify.app/ and extension, sooo slow but working:

![image](https://user-images.githubusercontent.com/9256178/92006131-a0d39000-ed44-11ea-8b94-eb49d64c1708.png)

**Comment by mariopino** [comment]
Confirmed that it works:

![image](https://user-images.githubusercontent.com/9256178/92008251-38d27900-ed47-11ea-9295-f59e01303c2f.png)

**Comment by jrmoreau** [comment]
OK @mariopino so this is in the yet-to-be-released version. It works. So I'll wait until we release and have the user try again. Sound good?

**Comment by mariopino** [comment]
> OK @mariopino so this is in the yet-to-be-released version. It works. So I'll wait until we release and have the user try again. Sound good?

Yep! closing this by now.
