### ISSUE TITLE
Polkadot/Substrate undelegations seem to be wrong in Westend

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4806]
According to our our database, Westend undelegations should take up to 7 days. Nevertheless, these are the undelegations I see for the address 5DxrBoa7S2DyJiwvvZKZPzz1xf6Mdbfhs97XWx1Sv8bSFTPa. And it hasn't changed since yesterday, which indicates something must be wrong in our implementation

![image](https://user-images.githubusercontent.com/40721795/91886009-f9ddee00-ec88-11ea-8484-8dd7b5129076.png)

**Comment by mariopino** [comment]
mmm I'm not getting validators or unstakings at all for this address right now (tested on prod and staging), checking!

**Comment by mariopino** [comment]
Obviously not true:

![image](https://user-images.githubusercontent.com/9256178/92226311-d1cad680-eea4-11ea-91da-4c649f6565b0.png)

**Comment by Bitcoinera** [comment]
Ah, we need to check this, but not super important, since it is just a testnet
