### ISSUE TITLE
Use Lunie as Wallet Provider in a Dapp

### ISSUE THREAD

**Issue by JakeHartnell** [luniehq/lunie#4815]
**Is your feature request related to a problem? Please describe.**

I am building a frontend for a Dapp that interacts with the CosmosHub, I would like for users to be able to use the Lunie browser extension to login to and sign transactions.

**Describe the solution you'd like**

I would like to be able to use Lunie as a wallet provider (similar to MetaMask). If this is already possible, some documentation would be nice.

**Describe alternatives you've considered**

I've looked at other projects and solutions, but would really like to support Lunie as I think you all are doing a great job with Wallet UX.

**Additional context**

Any pointers would be appreciated. :pray:

**Comment by faboweb** [comment]
What part of Lunie would you like to use as a wallet provider?

**Comment by JakeHartnell** [comment]
Basically, it would be ideal I there was a way to:
* Get account info (addresses and balances mainly)
* Sign transactions

The browser extension seems most relevant for integration with a frontend application (eventually followed by mobile apps supporting something like [Wallet Connect](https://docs.walletconnect.org/mobile-linking)). I would love to use Lunie similar to MetaMask. MetaMask exposes a `web3` api that can be used for interacting with the chain. Querying data from the chain is easy enough with [CosmJS](https://github.com/CosmWasm/cosmjs), but securely storing keys and signing transactions is where I see Lunie becoming very useful.

Not completely familiar with Lunie's architecture, but if a user has the browser extension installed it would be nice if there was something like `window.cosmos` exposed where I could get accounts to use for sign in or hand a transaction off for signing.

Another project that's starting to do this is Keplr: https://github.com/chainapsis/keplr-extension

They have an example that's mostly what I want (not using the CosmJS library though, no ledger support, and worse UX IMHO):
```
        // See above.
        const cosmosJS = new GaiaApi({
            chainId: "cosmoshub-3",
            walletProvider: window.cosmosJSWalletProvider,
            rpc: "https://node-cosmoshub-3.keplr.app/rpc",
            rest: "https://node-cosmoshub-3.keplr.app/rest"
        });

        // See above.
        await cosmosJS.enable();

        // Get the user's key.
        // And, parse bech32 address and validate it.
        const sender = AccAddress.fromBech32((await cosmosJS.getKeys())[0].bech32Address, "cosmos");

        // Make send message for bank module.
        const msg = new MsgSend(sender, recipient, [new Coin("uatom", amount)]);

        // Request sending messages.
        // Fee will be set by the Keplr extension.
        // The gas adjustment has not been implemented yet, so please set the gas manually.
        const result = await cosmosJS.sendMsgs([msg], {
            gas: 100000,
            memo: "",
            fee: new Coin("uatom", 1)
        }, "sync");

        if (result.code !== undefined && result.code !== 0) {
            alert("Failed to send tx: " + result.log);
        }

        alert("Succeed to send tx");
```

Would be happy to integrate both projects, but am especially interested in Lunie. It's great how you've integrated a large number of coins and test nets, and I am sure other frontend developers building dapps would love to take advantage of that ecosystem.

Does that answer your question?

**Comment by jbibla** [comment]
Hey @JakeHartnell. Yep that answers the question. This isn't possible right now and I'm not sure if / when we'll be able to spend the time to make this possible.
