### ISSUE TITLE
Add claimed rewards event

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4821]
To make it transparent in Polkadot that you received your rewards we want to show the user the events when this happened.

How?
- Listen to claiming extrinsics
- When a claim is detected, get all rewards for all the users and create a notification for each user summing up the rewards they get

- use the db rewards to increase the performance of the query
~- but we need to query the unclaimed rewards per user~ you can't claim an era twice

**Comment by Bitcoinera** [comment]
Rewards notifications, such a killer feature!

**Comment by Bitcoinera** [comment]
> Listen to claiming extrinsics

To listen for these, shouldn't we be listening for every kind of extrinsic to be able to tell?

**Comment by faboweb** [comment]
We are already listening to all extrinsics I think. We just need to react to the claim extrinsics.

**Comment by Bitcoinera** [comment]
> We are already listening to all extrinsics I think. We just need to react to the claim extrinsics.

I don't find this bit in the code :eyes: Unless `eventSubscription` is doing more than it seems at first sight? Is it also reacting like `userTransactionAdded`?

**Comment by faboweb** [comment]
Check `polkadot-node-subscription` > `newBlockHandler` (line 198)

**Comment by Bitcoinera** [comment]
> Check `polkadot-node-subscription` > `newBlockHandler` (line 198)

Oh, I see! Amazing, I can do this !!!

**Comment by faboweb** [comment]
We could standardize events per block on a `key: value` basis and then analyze those respective the protocol
