### ISSUE TITLE
Polkadot dashboard view does not load

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4830]
Per user report and my own re-production the Polkadot dashboard view does not load. Current extension version 1.0.35

**Comment by jrmoreau** [comment]
![Screen Shot 2020-09-05 at 8 50 15 AM](https://user-images.githubusercontent.com/1614127/92305385-d4850480-ef54-11ea-9cbc-c04b8587cf60.png)

**Comment by faboweb** [comment]
Restarted the API
