### ISSUE TITLE
Kusama stake/un-stake not working for multiple users

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4831]
User reported (and reproduced by me) that stake and un-stake tx does not work - fees page never loads (after 5 minutes waiting still nothing)

Current extension version 1.0.35

**Comment by jrmoreau** [comment]
![Screen Shot 2020-09-05 at 8 54 43 AM](https://user-images.githubusercontent.com/1614127/92305443-76a4ec80-ef55-11ea-863e-5e518a3b4f2f.png)

**Comment by faboweb** [comment]
Extension has nothing to do with this.

**Comment by faboweb** [comment]
If the rewards are not loading, there is an issue with the API

**Comment by jrmoreau** [comment]
@faboweb users reporting issue seems to be solved

**Comment by faboweb** [comment]
Fees should not be an issue. there is an issue with the extension though which I will fix tomorrow

**Comment by faboweb** [comment]
We send a validator list like `[undefined]` for unstaking txs to the extension which breaks the extension

**Comment by mariopino** [comment]
Tested staking in staging and production with extension 1.0.37, works flawlessly!
