### ISSUE TITLE
Terra rewards displaying incorrectly (same rewards repeated)

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4832]
KRT and MNT displayed twice. Something's off. I have reproduced. Current extension version 1.0.35

**Comment by jrmoreau** [comment]
![Screen Shot 2020-09-05 at 8 57 21 AM](https://user-images.githubusercontent.com/1614127/92305477-db604700-ef55-11ea-874e-3f7ffaef1d0d.png)

**Comment by faboweb** [comment]
Can you share the address?

**Comment by jrmoreau** [comment]
@faboweb sent in a PM
