### ISSUE TITLE
Un-staking on Kusama shows confusing amount of time for user

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4858]
Kusama un-bonding takes about 7 days maximum, but the un-stake view on Portfolio shows un-staking taking over a month with no real info on the state of whether the funds are un-bonded or just in chill mode but still bonded (purgatory) User's address CacytEud5NbC4ZFJVqkogenHiBddGC5T3pEJ7sQteg2igwM

<img width="1630" alt="Screen Shot 2020-09-08 at 12 15 05 PM" src="https://user-images.githubusercontent.com/1614127/92502158-7747b800-f1cd-11ea-94fc-b428ca965ecc.png">

**Comment by faboweb** [comment]
Address doesn't show this anymore

**Comment by jrmoreau** [comment]
Indeed it's fixed.
