### ISSUE TITLE
Display error in Polkadot showing 0 user balance after nomination

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4860]
User un-nominated an inactive validator, then nominated a new one and now their balance shows 0. 

https://polkascan.io/polkadot/account/13VMMTEozs39R5pv3UGoydNwXW3NXxU7iZ9dFFA4b7tYGEht

**Comment by jrmoreau** [comment]
<img width="1636" alt="Screen Shot 2020-09-08 at 5 03 29 PM" src="https://user-images.githubusercontent.com/1614127/92527618-48453c80-f1f5-11ea-8e8e-314a1eb243bd.png">

**Comment by Bitcoinera** [comment]
Fixed in develop. Probably the funds are now "reserved" balance

**Comment by faboweb** [comment]
came from a bad configuration and is fixed
