### ISSUE TITLE
huge discrepancies in fees paid for re-staking in e-Money

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4864]
Fee calculation was anywhere from .55NGM to over 3NGM to perform a re-stake tx. This seems off. 

Address: emoney1kjhdx3nkh6krdhryvjzkq33xwh6wsyy7ghnylq

**Comment by jrmoreau** [comment]
![Screen Shot 2020-09-09 at 12 58 06 PM](https://user-images.githubusercontent.com/1614127/92629424-4bdfce80-f29c-11ea-9c1f-9acf2528231a.png)

**Comment by faboweb** [comment]
Interesting. Fees should be flat as of our logic. Needs to be investigated. Those restakes where done using Lunie?

**Comment by jrmoreau** [comment]
@faboweb yep those restakes were done on Lunie

**Comment by faboweb** [comment]
emoney gas prices are dynamic so this might just come from their system

**Comment by Bitcoinera** [comment]
Did you take this on @faboweb ?

**Comment by faboweb** [comment]
> emoney gas prices are dynamic so this might just come from their system

I don't think we need to do anything. reopen when you disagree
