### ISSUE TITLE
API breaks when DB is down

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4867]
This is a behavior we recently discovered while `staging-DB` was down... that shortly afterwards `staging-API` would follow right behind.

I think this reveals a weakness and also some bad code in our API. We should make DB and API completely independent and API should still respond to queries that don't require any DB data, in case that DB is down.

Probably this would imply a great refactor for API. Not sure

**Comment by Bitcoinera** [comment]
Do we want to investigate this further?

**Comment by faboweb** [comment]
Without the db, the API can't start as it needs the network configs.

**Comment by faboweb** [comment]
But when the db crashes later, the API shouldn't die. We probably don't handle some db queries gracefully.
