### ISSUE TITLE
Un-stake error on Kusama `cannot read property 'length' of null

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4877]
User trying to unstake on Kusama - on 1.0.37

**Comment by jrmoreau** [comment]
![1](https://user-images.githubusercontent.com/1614127/92800394-a5bac400-f382-11ea-98ab-6ebfe9038e0f.png)
![2](https://user-images.githubusercontent.com/1614127/92800397-a6535a80-f382-11ea-97fb-a3c67bf7da34.png)

**Comment by jrmoreau** [comment]
user address is CacytEud5NbC4ZFJVqkogenHiBddGC5T3pEJ7sQteg2igwM

**Comment by faboweb** [comment]
should be fixed in latest extension

**Comment by Bitcoinera** [comment]
I am going to test this now

**Comment by Bitcoinera** [comment]
Working on develop :shrug:
