### ISSUE TITLE
add withdraw unstaked tokens button in polkadot

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4878]
What is this about? :eyes:

This is already done, right?

**Comment by faboweb** [comment]
> withdraw unstaked tokens 

this is not done. each unstake entry needs to show the "withdraw"/"claim" button once the unbonding period is over. this also needs a new actionmodal and transaction type

**Comment by faboweb** [comment]
Consider doing #4878 first

**Comment by Bitcoinera** [comment]
> Consider doing #4878 first

But this is #4878. Which one do you mean?

**Comment by faboweb** [comment]
Sorry I meant #4879
