### ISSUE TITLE
Remove message creation in API and reuse message creation used in APP

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4879]
api/lib/messageCreators...

**Comment by Bitcoinera** [comment]
Didn't we duplicate in API to improve APP performance (fee calculation)? Why this change again? What has changed?

**Comment by faboweb** [comment]
We create the txs also in the API to calculate fees. But the code to create the txs is duplicated. It exists once in api/lib/messageCreators and once in app/src/signing/networkMessages. When you change one tx generation method you also need to change the other one. This will produce mistakes down the line.

**Comment by Bitcoinera** [comment]
Ah, I get you. So we should simply import from app and use it in API to calculate fees. OK, I see. Nice. I can do this too! Easy-peasy
