### ISSUE TITLE
Introduce global copyable component

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4896]
Since #4566 is already huge, the following enhancements will be treated in separate PRs:

Refactor `Address` component copy logic to have a global copyable component that we can also use in the share section of the new PageProposal (ProposalHeader). Comment: https://github.com/luniehq/lunie/pull/4566#discussion_r487293506

**Comment by faboweb** [comment]
This should be individual issues

**Comment by Bitcoinera** [comment]
XD

**Comment by Bitcoinera** [comment]
OK, will change it :+1:

**Comment by jbibla** [comment]
so low priority let's close for now
