### ISSUE TITLE
Create a new ModalVote for Polkadot democracy proposals (seconding)

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4899]
Since #4566 is already huge, the following enhancements will be treated in separate PRs:

We could also leave it as it is. But maybe not that maintainable, I agree. Although the `v-ifs` are what I find most confusing, the rest is OK.

Comment: https://github.com/luniehq/lunie/pull/4566#discussion_r487289116

**Comment by Bitcoinera** [comment]
The modal could look so that we have the fixed amount, 100 DOTs, as only text, and the big Yes button underneath. Simple and effective.

We could add some explanation in a small span: "This funds will get locked until the proposal goes live"

**Comment by Bitcoinera** [comment]
![image](https://user-images.githubusercontent.com/40721795/93342634-d9d52f80-f82f-11ea-8ee7-7739ddd03eec.png)

**Comment by faboweb** [comment]
kill the "yes" button. it has no purpose. add just a disabled input with the amount. like in modal withdraw

**Comment by jbibla** [comment]
this is really just a deposit and we could use the deposit modal

**Comment by Bitcoinera** [comment]
okidoki
