### ISSUE TITLE
Second transaction not working

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4901]
Somehow the transaction always fails, returning either "Balance too low" [source](https://polkascan.io/polkadot/transaction/0xa327fe696da375b388043f61da77f02f95f6e96ac6d06f7fe6cde243f80242be) or "Proposal does not exist" [source](https://polkascan.io/polkadot/transaction/0xa4d20a146004cd08a747a484ef756ec8597bac55524eec15b8044d353a48bda4).

Need to investigate why

**Comment by Bitcoinera** [comment]
OK, I just asked on Riot about this. Let's see what they reply

**Comment by faboweb** [comment]
are you actually using the extrinsic `api.tx.democracy.second`?

**Comment by Bitcoinera** [comment]
Seems this isn't actually a bug: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$16001906667542FsGxd:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=web3.foundation

**Comment by Bitcoinera** [comment]
> are you actually using the extrinsic `api.tx.democracy.second`?

yeah, sure. It seems you need to have some good funds in order to second a proposal on Polkadot (100 DOTs)

**Comment by Bitcoinera** [comment]
I think we can close this

**Comment by faboweb** [comment]
This actually changes everything. We should display the amount instead of "Yes". And we should display an explanation. Let's create a "BackProposalModal" (I don't like "second" @jbibla what do you think?). Also decouples the tx type from classic voting.

**Comment by jbibla** [comment]
yep, let's display the amount with an explanation. nice idea.

i'm not clear on why we shouldn't consider this a deposit..?

**Comment by faboweb** [comment]
could be considered a deposit. but is there a minimum deposit in that case? @Bitcoinera

**Comment by Bitcoinera** [comment]
yes, the minimum for seconds seems to be always the one given by `api.consts.democracy.minimumDeposit`. So I guess it is intended to be dynamic. Perhaps we need a new query to get it from API although we could also use @polkadot/api in FE to get it. Don't think it is very costly to get it being a constant.

And yes, good point with displaying a message explaining this. So it makes to do #4899 and have this `BackProposalModal` in

**Comment by Bitcoinera** [comment]
PolkadotJS doesn't display this with the deposit anywhere, for some reason :eyes: 

![image](https://user-images.githubusercontent.com/40721795/93326569-4a248680-f819-11ea-9ec2-c95f58c7b70f.png)

**Comment by faboweb** [comment]
> PolkadotJS doesn't display this with the deposit anywhere, for some reason 👀

yeah, super weird o.O

**Comment by jbibla** [comment]
seems like we should just call it a deposit

**Comment by Bitcoinera** [comment]
Just changed it on the PR
