### ISSUE TITLE
polkadot needs some governance notifications

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4915]
last item for web3 governance deliverable: https://github.com/w3f/Open-Grants-Program/pull/20/files#diff-8bfb4d08d065958133dd5b4c5639768fR82

- notifications for new proposals and proposal state changes

**Comment by Bitcoinera** [comment]
Oh wow, didn't know that was actually in. OK, will look into it

**Comment by faboweb** [comment]
this is already in
