### ISSUE TITLE
parameter change proposals in polkadot are missing the most important content

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4917]
our proposals don't show the arguments - which is really the important detail of a parameter change proposal

http://localhost:9080/kusama/proposals/democracy-34
https://kusama.polkassembly.io/proposal/34
https://polkascan.io/kusama/democracy/proposal/34

**Comment by jbibla** [comment]
also, the bars are broken:

![Screen Shot 2020-09-16 at 5 50 03 PM](https://user-images.githubusercontent.com/6021933/93396066-0e9fb180-f845-11ea-9b63-ddc9d166488e.png)

**Comment by Bitcoinera** [comment]
Good point. The arguments. Will look into that right now.

But yeah, the bars for Democracy is something I wanted to talk to you about. Nobody is showing them and I think this is for a reason. The minimumDeposit is actually the minimum each individual/ address who wants to support the proposal needs to put in. So probably we should actually just hide the bar :shrug:

**Comment by Bitcoinera** [comment]
OK, I saw the thing. So where should we display this? In the description I guess
