### ISSUE TITLE
Add unit tests for all new governance components

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4968]
Now we should definitely finally release governance, but all the new governance components that have been introduced lack of any tests.

We should create tests for each one of them after release and test things as important as proposer, timelines, which button appears, etc.

The new governance untested components are:

- ProposalDescription
- ProposalHeader
- ProposalStatusBar
- ParticipantList
- Timeline
- More test with snapshots for PageProposal is probably a good idea

**Comment by jbibla** [comment]
not important right now
