### ISSUE TITLE
Getting eternal loader while opening a Kusama governance proposal

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4969]
**Describe the bug**

Proposal:

https://staging--lunieio.netlify.app/kusama/proposals/referendum-85

**To Reproduce**

Open `/kusama/proposals/referendum-85` in latest develop.
Got console error: "TypeError: _vm.proposal.detailedVotes.timeline is null"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by faboweb** [comment]
fixed
