### ISSUE TITLE
cosmos proposal participant list is missing amount field for votes

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4971]
![Screen Shot 2020-09-22 at 8 08 37 AM](https://user-images.githubusercontent.com/6021933/93880059-d536ce00-fcaa-11ea-9cc5-7fac4d448f9d.png)

**Comment by Bitcoinera** [comment]
Because they don't have amounts, the concept of vote/deposit belongs to Polkadot only

**Comment by jbibla** [comment]
> Because they don't have amounts

votes don't directly have amounts - but when you vote you are voting with the weight of your holdings. validators vote with all staked assets unless token holders vote otherwise. 

it is not a simple 1 vote per address tally system...

**Comment by Bitcoinera** [comment]
So then we are missing an important implementation here related to Cosmos voting display

**Comment by Bitcoinera** [comment]
Are we going to do this in the end or should I close this instead?

**Comment by jbibla** [comment]
closing for now
