### ISSUE TITLE
Data resilience

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4979]
**Is your feature request related to a problem? Please describe.**

As our API reacts live to blocks we might miss some blocks when the API is restarting or there is any form of outage.

**Describe the solution you'd like**

Store the last analyzed block height in the db. Then load that block from the db and start analyzing from that block.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
Cool!!

**Comment by jbibla** [comment]
> Then load that block from the db and start analyzing from that block.

if we can do this - can't we start from block 1 for historical notifications?

**Comment by faboweb** [comment]
yes, but might take a lot of time

**Comment by jbibla** [comment]
so we could index the whole chain (historical data) but the problem is it would have to be faster than the block time and could take many many hours?

**Comment by faboweb** [comment]
or days

**Comment by jbibla** [comment]
this is important for notifications. especially with known node instability.

**Comment by Bitcoinera** [comment]
> if we can do this - can't we start from block 0 for historical notifications?

Are we going to do this in the end, historical notifications? Then we really need to have a much larger DB

**Comment by Bitcoinera** [comment]
True, I see. It is about making sure we don't miss any block/notification due to faulty nodes/connections
