### ISSUE TITLE
Show thresholds for proposals

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#4988]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently proposals only show votes or deposits. We don't show required thresholds to succeed or pass.

I.e. in PolkadotJs
![image](https://user-images.githubusercontent.com/5869273/94064754-c128c480-fdaf-11ea-9f7d-7de640fa4c04.png)

**Describe alternatives you've considered**

Display a bar that shows current votings/deposits and the thresholds. Negative votes could come from the right so we can show the threshold for those on the right. @jbibla ideas?

**Additional context**

**Comment by Bitcoinera** [comment]
Or we could have two bars, one for the Yes (Ayes) and another one for the Nos (Nays)

**Comment by jbibla** [comment]
we probably want to only show 1 bar. 

i think the way to do it is to have yes votes / deposits on the left and the threshold relative to the yes votes / deposits.

**Comment by Bitcoinera** [comment]
can you make some sketch for this like you did for the seed confirmation? Thanks

**Comment by jbibla** [comment]
<img width="437" alt="Screen Shot 2020-09-29 at 6 57 03 AM" src="https://user-images.githubusercontent.com/6021933/94549980-066e4b80-0221-11eb-8546-698fd8c3e7bd.png">
<img width="467" alt="Screen Shot 2020-09-29 at 6 56 37 AM" src="https://user-images.githubusercontent.com/6021933/94549982-0706e200-0221-11eb-89bc-a34e4752ce39.png">
