### ISSUE TITLE
Loader keeps appearing on Transactions Page

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4991]
When scrolling down, the loader keeps appearing, although there are no more transactions to load. The Eventlist component `loadMore` logic must be somehow broken 

![Peek 2020-09-24 20-19](https://user-images.githubusercontent.com/40721795/94183898-6ff9fd00-fea3-11ea-98f0-5b771ee41ea8.gif)

**Comment by faboweb** [comment]
I saw this as well
