### ISSUE TITLE
Network icon not displaying for user logged into notifications

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4996]
No matter where a user logs in from (different browsers and machines) they are unable to see their avatar.

**Comment by jrmoreau** [comment]
![blank avatar](https://user-images.githubusercontent.com/1614127/94272853-a8382480-ff11-11ea-98d6-4f0fba58eec3.png)

If needed I can provide the user's email they registered with in a PM. Let me know

**Comment by jbibla** [comment]
the reason the avatar is not appearing is because they're not signed in...

so the issue is with the sign in flow - can you ask them if they're receiving the emails and what happens when they follow the link from the email?

**Comment by jrmoreau** [comment]
It's showing their username though - so maybe a caching issue? Going to try to have him clear his cache or try to sign in from a fresh browser

**Comment by jbibla** [comment]
> It's showing their username though

do you mean email? we don't have usernames. also, in the screenshot you shared that is not true.

**Comment by Bitcoinera** [comment]
That means something fails in their connection to the `luniefra` instance to grab the icon

**Comment by mariopino** [comment]
I can't reproduce this one.
