### ISSUE TITLE
Stargate Readiness

### ISSUE THREAD

**Issue by zmanian** [luniehq/lunie#5005]
The Stargate upgrade is nearly feature complete and the Stargate team is working with wallet teams to ensure they are ready for stargate.

We are currently running the stargate-3 testnet to enable wallets to test their integrations against stargate.

We expect the stargate software to be in feature freeze shortly.

We would also strongly encourage wallets to test their integrations against the legacy rest amino interface and to experiment with the new GRPC interfaces.

**Comment by jbibla** [comment]
Thanks @zmanian!
