### ISSUE TITLE
Too many emails notifications at once

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5053]
Got 19 emails in a row saying I received 5,000 AKT.

**Comment by jbibla** [comment]
you're actually registered to receive notifications for other addresses - so this is not correct and the bug that we need to address is open here: https://github.com/luniehq/lunie/issues/5054

**Comment by jbibla** [comment]
i think it has something to do with this multi-message transaction: https://akash.aneka.io/txs/E0D29BADA5CC678036279EE0771FD8A0A34840EF0ABA5884E417CD822D2E7F62

perhaps our notification trigger got a little bit over excited?

**Comment by Bitcoinera** [comment]
> i think it has something to do with this multi-message transaction: 

Well, if we are creating the notification per transaction message, then this behavior makes all the sense

**Comment by Bitcoinera** [comment]
One question, @jrmoreau , are you this address: akash1m4zq72erd8pwexwvkkxfrakxfc0fw6gv3hq9cu?

I guess you are not, that you are one of the addresses who received from the above address. And therefore it is a real bug. Still looking at the code figuring this one out

**Comment by Bitcoinera** [comment]
Mmm, seems to work fine. In theory t would send 65 emails to the sender of the multisend transaction, in this case `akash1m4zq72erd8pwexwvkkxfrakxfc0fw6gv3hq9cu`, and one Receive email to each of the recepients.

We could change the behavior of sending 65 emails to the sender though

**Comment by jbibla** [comment]
> In theory it would send 65 emails to the sender
> We could change the behavior of sending 65 emails to the sender though

lol this is not "working fine" - it's one transaction with 65 messages. should be 1 email.

---

the issues is that 2 users have reported receiving 19 and 31 emails respectively - so please take a close look at the logic and how we're handling multi message transactions. agreed that the user should only receive 1 email.

**Comment by Bitcoinera** [comment]
I need to use the command line to create a multi message transaction myself, right? Otherwise I think I can hack it, so never mind

**Comment by jbibla** [comment]
interestingly reward claiming txs are multi message - so you could implement the notification for that 😉

**Comment by jbibla** [comment]
i confirmed that the db has 64 notification entries for this tx: https://akash.aneka.io/txs/E0D29BADA5CC678036279EE0771FD8A0A34840EF0ABA5884E417CD822D2E7F62

which is the reason users are getting spammed

**Comment by Bitcoinera** [comment]
> i confirmed that the db has 64 notification entries for this tx: 

I know, I also checked it yesterday, but what I don't get looking at the code is why they are receiving so many emails if their address is just repeated in data. They are in `involvedAddresses`, but I don't see how this affects the sendEmails function. Will keep checking

**Comment by Bitcoinera** [comment]
What is the purpose of involvedAddresses actually? It is only used for notifications right?
