### ISSUE TITLE
Notifications page won't load

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5054]
<img width="1527" alt="Screen Shot 2020-10-06 at 11 11 18 AM" src="https://user-images.githubusercontent.com/1614127/95220806-d563bd00-07c4-11eb-87ec-6597a46e0379.png">

**Comment by Bitcoinera** [comment]
I cannot reproduce. Can you give it another try? Also the coinLookup error seems an old one... It might be a cached old version of the application?

**Comment by jbibla** [comment]
it seems that #5069 resolved this issue.
