### ISSUE TITLE
bcrypto (verify package valid "main" entry)

### ISSUE THREAD

**Issue by Amrosx** [luniehq/lunie#5064]
**Describe the bug**
I cloned the repo
and I run **Yarn** this error appear
I tried to add the  package bcrypto  but it doesn't work
 Error: Cannot find module 'D:\LunieWallet\lunie\node_modules\are-we-there-yet\index.js'. Please verify that the package.json has a valid "main" entry at tryPackage

**To Reproduce**
I am trying to run Lunie locally 

**Expected behavior**
it suppose to run normally 

**Screenshots**
screenshot for the error
**using default version**
![image](https://user-images.githubusercontent.com/37171239/95326012-9dcf4080-08aa-11eb-874e-7b0f563e519b.png)

**usnig v1.0.53**
![image](https://user-images.githubusercontent.com/37171239/95314012-7328bc00-0899-11eb-9aaa-02ff761f9db5.png)

**Desktop (please complete the following information):**
 - OS: windows OS
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
not used

**Additional context**
not applicable

**Comment by Bitcoinera** [comment]
Thank you for your concern and opening this issue @Amrosx . We will investigate this error quite soon and will keep you updated

**Comment by faboweb** [comment]
what node and yarn version are you using?

**Comment by Amrosx** [comment]
yarn 1.22.5
node v12.16.3
after I delete node_modules and run npm inistall
new issue come up 
**Vue packages version mismatch: localhost:9080**

- vue@2.6.11 (D:\LunieWallet\lunie2\app\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\LunieWallet\lunie2\app\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**my package.json**
"vue": "2.6.11",
"vue-loader": "^15.4.2",
"vue-template-compiler": "^2.6.10"

**Comment by Bitcoinera** [comment]
Maybe kind of obvious but have you tried doing `git pull`? I cannot see that package combination on the `package.json` file in the `app` subrepo

**Comment by faboweb** [comment]
you should use `yarn` to install. maybe that helps? the latest issues also seem like warnings and not errors. can you still start the FE?

**Comment by Amrosx** [comment]
I have tried using yarn add dependencies but  many packages linking problems. Then I did the following steps and it works 

Api folder
- deleted node_modules & package-lock.json 
- npm install
 - yarn start >> localhost:4000

App folder
 - deleted node_modules & package-lock.json 
 - npm install
 - yarn serve to run web on localhost:9080

extension folder
 - npm install

If any comments, please

**Comment by faboweb** [comment]
sweet
