### ISSUE TITLE
user menu addresses are missing

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5065]
I cannot reproduce this.

Please, me issues descriptions if possible with screenshots and steps to reproduce. Otherwise it is very difficult to work on just a sencente :shrug:

![image](https://user-images.githubusercontent.com/40721795/95324280-c4d44500-089f-11eb-90c2-4c5cd0bcfbe7.png)

The only buggy thing I see is a missing Kava icon

**Comment by jbibla** [comment]
yep this is resolved
