### ISSUE TITLE
notifications: issue with validator profile image updates 

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#5074]
**Describe the bug**

- this notification should only be triggered when there is an on-chain update (not a script runner update)
- for some reason these are duplicated

<img width="885" alt="Screen Shot 2020-10-07 at 3 47 58 PM" src="https://user-images.githubusercontent.com/6021933/95380257-7d0be880-08b4-11eb-8f6c-dd310f7b10cb.png">

**Comment by Bitcoinera** [comment]
Ah true, I hadn't noticed:

![image](https://user-images.githubusercontent.com/40721795/95483299-55d61980-098f-11eb-8037-d512e83b0756.png)

Good pick

**Comment by faboweb** [comment]
> this notification should only be triggered when there is an on-chain update (not a script runner update)

we are comparing the image that we see in the validator object. there is no other way. as the identity on chain might not change, but the image does (on Twitter/Keybase).

**Comment by jbibla** [comment]
ok i understand. but this is not working properly - they notifications are duplicated and these validators are not actually updating their images all the time.

**Comment by faboweb** [comment]
>  they notifications are duplicated and these validators are not actually updating their images all the time.

why is this happening?

**Comment by Bitcoinera** [comment]
where are we storing validators to DB? :thinking:
