### ISSUE TITLE
Which version of Nodejs is compatible with Lunie

### ISSUE THREAD

**Issue by Amrosx** [luniehq/lunie#5075]
Hi everybody, all I have tried to install node 10.x , 12.x, 14.x 
but still couldn't run Yarn it seams that there is problem in linking dependencies 
any one can help>> tq

**Comment by jbibla** [comment]
hey @Amrosx! lunie is a mono-repo with a few projects inside. what specifically are you trying to do?

**Comment by Amrosx** [comment]
hi @jbibla I am trying to run the project locally but it's showing Linking dependencies... errors
![image](https://user-images.githubusercontent.com/37171239/95479498-85872080-0993-11eb-9581-6be222451b07.png)

**Comment by Amrosx** [comment]
I used npm install for api and app and solved this issue thank you
