### ISSUE TITLE
E2E Validatorlist

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5077]
We need to fix E2E! Make them reliable again. It is mainly this bug

**Comment by Bitcoinera** [comment]
Should we remove Polkadot E2E?

**Comment by faboweb** [comment]
We need to fix Polkadot E2E tests

**Comment by Bitcoinera** [comment]
Any idea on how to fix the connection issues? With sidecar you think? Seems we had connection issues with sidecar directly on the app, we need to figure out why there and not locally (bandwidth issue?)
