### ISSUE TITLE
Polkadot and Kusama rewards are not updated

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#5080]
**Describe the bug**

Polkadot and Kusama rewards are not updated in both staging and production databases. We need to check the script and improve reliability, A check of the difference between stored and currrent era (should be exactly 1) in a monitoring system would be soo nice.

### Actual eras:

- Polkadot: **130**
- Kusama: **1385**

### Stored eras (production-db):

- Polkadot: **2687** <- no such era exists! we need to check, then clean db and execute rewards script again
- Kusama: **1374**

### Stored eras (staging-db):

- Polkadot: **114**
- Kusama: **1340**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by jbibla** [comment]
thanks mario. this has happened at least a few times now. do we know the root of the problem?

**Comment by mariopino** [comment]
API/Node problems like disconnections, etc

**Comment by faboweb** [comment]
please check later or tomorrow if this is fixed. Script runners are running again

**Comment by mariopino** [comment]
Kusama, polkadot and westend rewards are up to date in staging after latest fixes.
