### ISSUE TITLE
Validators in DB

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#5081]
In Polkadot we have a lot of validators (>500) loading infos for all validators takes a lot of time at the start of the API.
To speedup API boot time we can store all validators for a network in the db. The script runner updates the validators in the background. The API polls the validators from the DB in intervals. The table can be one for all networks, reducing the need for schemas.

Proposed table schema based on the GQL schema:
    id: String!
    networkId: String!
    chainId: String!
    operatorAddress: String
    consensusPubkey: String
    details: String
    website: String
    votingPower: String
    startHeight: Int # used?
    uptimePercentage: String
    tokens: String
    commissionUpdateTime: String
    commission: String
    maxCommission: String
    maxChangeCommission: String
    commissionLastUpdate: String
    lastUpdate: Int # to see if we update correctly
    lastSeen: Int # for validator that disappear
    status: ValidatorStatusEnum
    statusDetailed: String
    selfStake: String
    expectedReturns: String
    name: String
    picture: String # reduces the need for the validator profile info table

**Comment by jbibla** [comment]
still relevant if sidecar changes are implemented?

**Comment by faboweb** [comment]
Let's stall until we know
