### ISSUE TITLE
Rewards amount glitch on Cosmos

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5083]
User reports that rewards displayed does not match actual amount claimable (like a glitch). I reproduced as well using the address cosmos1kjhdx3nkh6krdhryvjzkq33xwh6wsyy785fsga

<img width="1528" alt="Screen Shot 2020-10-12 at 12 56 40 PM" src="https://user-images.githubusercontent.com/1614127/95772659-1ce9bd80-0c8b-11eb-891c-2953f56489af.png">

**Comment by jrmoreau** [comment]
<img width="437" alt="Screen Shot 2020-10-12 at 1 02 34 PM" src="https://user-images.githubusercontent.com/1614127/95772720-34c14180-0c8b-11eb-89ba-d1e5e9425740.png">

**Comment by jrmoreau** [comment]
Screenshot from user 
<img width="552" alt="Screen Shot 2020-10-12 at 5 44 49 PM" src="https://user-images.githubusercontent.com/1614127/95870000-fb93da80-0d39-11eb-931c-342c567fee83.png">

**Comment by faboweb** [comment]
How do you know the rewards are wrong?

**Comment by jrmoreau** [comment]
@faboweb why would claimable rewards in the portfolio view and the max claimable amount in the claim action modal be different?

**Comment by faboweb** [comment]
But they are the same in the screenshot. They just have a different precision

**Comment by Bitcoinera** [comment]
I cannot reproduce. Everything is fine on my side. At least with Gaia (Cosmos Hub is down again due to faulty Figment node)

**Comment by jbibla** [comment]
can confirm this is being reported by some other users too

**Comment by faboweb** [comment]
likely a faulty node then (2 node cluster where one node is behind and therefor gives a different response)

**Comment by jbibla** [comment]
yep, although it appears higher, not lower - which is not what i'd expect from nodes in the past

**Comment by faboweb** [comment]
@jrmoreau is this still an issue?

**Comment by jrmoreau** [comment]
💯  still happening @faboweb . See screenshot of me claiming rewards just now in succession: 

<img width="1449" alt="Screen Shot 2020-10-14 at 11 06 13 AM" src="https://user-images.githubusercontent.com/1614127/96008347-7843b900-0e0d-11eb-82f2-785e19cda04b.png">
<img width="1516" alt="Screen Shot 2020-10-14 at 11 06 31 AM" src="https://user-images.githubusercontent.com/1614127/96008350-78dc4f80-0e0d-11eb-8546-ea9d32250eed.png">
<img width="1521" alt="Screen Shot 2020-10-14 at 11 06 48 AM" src="https://user-images.githubusercontent.com/1614127/96008353-7974e600-0e0d-11eb-82b8-a259f35982e0.png">

**Comment by Bitcoinera** [comment]
I cannot reproduce...

What are we missing?

![image](https://user-images.githubusercontent.com/40721795/96010451-15b8e000-0e42-11eb-922c-d296f6166d32.png)

**Comment by Bitcoinera** [comment]
Do you still have the same issue @jrmoreau ?

I still don't know how to reproduce this

**Comment by jrmoreau** [comment]
@Bitcoinera actually I cannot test as the claims action modal won't load anymore 
<img width="556" alt="Screen Shot 2020-10-15 at 2 11 05 PM" src="https://user-images.githubusercontent.com/1614127/96169588-5a9b5000-0ef0-11eb-8d37-25023b83573c.png">

**Comment by faboweb** [comment]
Still slow but working now
