### ISSUE TITLE
polkadot txs don't work in extension

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#5091]
getting these errors when you approve a tx:
<img width="718" alt="Screen Shot 2020-10-13 at 10 15 43 AM" src="https://user-images.githubusercontent.com/6021933/95872822-3e0ae680-0d3d-11eb-9f00-9a1e9409d9b6.png">

**Comment by faboweb** [comment]
probably need to update the extension with the new polkadot version

**Comment by Bitcoinera** [comment]
That's probably it. I cannot reproduce it on my side either. Looks definitely like an old version

**Comment by jbibla** [comment]
so we need to release the extension i suppose

**Comment by Bitcoinera** [comment]
ah, so you are trying the chrome webstore one. Then yes, we should release it

**Comment by jbibla** [comment]
yep, the release resolved the issue. 

how do we avoid needing to release the extension on every new API version?

**Comment by Bitcoinera** [comment]
> how do we avoid needing to release the extension on every new API version?

Using Simsala these both releases are separated. Manually the key is the CHANGELOG.md file

**Comment by faboweb** [comment]
That is not what Jordan is saying. He is asking about the polkadot API version. Sidecar might help, as it pushes the API version management to a server

**Comment by Bitcoinera** [comment]
ah ok, he meant polkadot/api. Right, now it makes sense. Thanks :pray:
