### ISSUE TITLE
All accounts apparently deleted when deleting single account on Extension

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5097]
This is a small but shocking glitch on the current extension version, as you could appreciate to day in the demo.

Fortunately, it is just a glitch and only the desired account gets deleted

**Comment by faboweb** [comment]
I guess when deleting an account in the response you are not sending the remaining accounts. Though the UI updates with an empty array of accounts even though in the backend the accounts still exist.

**Comment by jbibla** [comment]
this should not have been a separate issue and should have been resolved before merging the PR - and definitely before releasing.

**Comment by Bitcoinera** [comment]
> this should have been resolved before merging the PR - and definitely before releasing.

Ideally yes. We failed to fully review

**Comment by Bitcoinera** [comment]
> I guess when deleting an account in the response you are not sending the remaining accounts. Though the UI updates with an empty array of accounts even though in the backend the accounts still exist.

Good idea. Will fix this one asap

**Comment by Bitcoinera** [comment]
Would be awesome to have #4762 fixed :shrug: It makes it much more time-consuming to debug
