### ISSUE TITLE
Make MaintenanceBar network specific

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5098]
A small feature very easy to do

**Comment by faboweb** [comment]
Use a flag in the table `network` that is optional and can take a network ID. In the FE we also query for this property and show the bar only if that network is active.

**Comment by Bitcoinera** [comment]
shouldn't it be in the table `maintenance`?

**Comment by faboweb** [comment]
in the table `maintenance` use a column `network`
