### ISSUE TITLE
Add export seed to mobile app

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5099]
The same feature than on extension. Need to check how it actually looks now on mobile with UserMenu. There should be a list of accounts like the `TmSessionExtension` component does have:

![image](https://user-images.githubusercontent.com/40721795/95905902-b56e6380-0d99-11eb-8ab6-550307eb6373.png)

**Comment by faboweb** [comment]
It would be nice, if the list in the extension and in the app are the same components.

**Comment by Bitcoinera** [comment]
Maybe we can combine with #4790 ? Or better first do that one, and then do this. And then we already have that component in place. Makes sense to me.

What do you think?

**Comment by faboweb** [comment]
Hmmm actually we don't have an accounts list. The buttons need to be in the User Menu where all accounts live. @jbibla want to sketch sth? want me to sketch sth?

**Comment by faboweb** [comment]
Let's add the 3 dots to the user menu records in the user menu like in the extension revealing the delete button and the "show seed" button.

**Comment by jbibla** [comment]
yep good solution. in the user menu!

**Comment by Bitcoinera** [comment]
This has been also closed by #5147
