### ISSUE TITLE
upgrade Kava

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5100]
When is this actually happening this week?

**Comment by jbibla** [comment]
https://ipfs.io/ipfs/QmRctEN4dsg8HGeTHUpJgY8SB2ZMhfzTuuMpMcMvFv1mDu/kava-4-upgrade-proposal.pdf

**Comment by Bitcoinera** [comment]
Just tested and everything seems fine. Just needed to change the LCD URL. Don't see any error at all.

All good

**Comment by faboweb** [comment]
Sweet!
