### ISSUE TITLE
Add health endpoints and monitoring to script runner instances

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#5109]
**Is your feature request related to a problem? Please describe.**

Script runners were unresponsive causing the rewards for polkadot to be outdated. We were unaware of that.

**Describe the solution you'd like**

Add a /health unpoint that would return 200 always and add a service, that emails us, when the endpoint is not reachable.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bitcoinera** [comment]
We can do this with some Grafana plugin no? Or are they not connected to #infrastructure-alerts on our Slack?

**Comment by faboweb** [comment]
What grafana plugin are you referring to?

**Comment by Bitcoinera** [comment]
Maybe this one is good: https://grafana.com/grafana/plugins/vonage-status-panel?

**Comment by Bitcoinera** [comment]
Can you explain me how our infrastructure-alerts currently works? Is it an integration with DO? We can do the same for scriptRunners too

**Comment by faboweb** [comment]
you could use this one https://uptimerobot.com/

**Comment by Bitcoinera** [comment]
I'm in

![image](https://user-images.githubusercontent.com/40721795/96459858-e2e86080-1222-11eb-83e5-da1f730eaa5d.png)

**Comment by Bitcoinera** [comment]
Ah no, I need the authentication data for it to work:

![image](https://user-images.githubusercontent.com/40721795/96460114-2a6eec80-1223-11eb-8ba6-d920319f7d03.png)
