### ISSUE TITLE
ValidatorProfile UI

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5122]
Since the API part is practically finished (#4468) we need to start working on validators profiles in the FE.

Let's do this! :muscle: 

[Designs](https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/Pjy4q8)!

What I think is [the final version](https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/RLgPQx), right @jbibla ?

**Comment by jbibla** [comment]
yep! i'll get started today. 

but based on this: https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/R7LjLy
