### ISSUE TITLE
un-stake problem with Terra - saying insufficient fees but definitely enough

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5132]
User getting error:

`"Unstaking failed: Broadcast was not successful: insufficient fee: insufficient fees; got: "", required: "623175ukrw,1771uluna,1510691umnt,357usdr,525uusd" = "623175ukrw,1771uluna,1510691umnt,357usdr,525uusd"(gas) +""(stability)."
`

**Comment by jrmoreau** [comment]
reference to address terra1fk7lyw3gf82ymvp4m043mlk7d6ggf9l3av5tmg which has plenty of available funds to pay any amount of fees

**Comment by Bitcoinera** [comment]
I couldn't reproduce. Can you let me know the currency and amount they wanted to send? Thanks

**Comment by jrmoreau** [comment]
@Bitcoinera not sending. un-staking.

**Comment by Bitcoinera** [comment]
ah true :facepalm:

**Comment by Bitcoinera** [comment]
I also couldn't reproduce:

![image](https://user-images.githubusercontent.com/40721795/96640092-f7138700-1322-11eb-8532-04ca98d84cb1.png)

**Comment by jbibla** [comment]
@jrmoreau was it extension, mobile, or ledger?

**Comment by jrmoreau** [comment]
@jbibla it was on the extension

**Comment by jrmoreau** [comment]
Asking for console screenshots

**Comment by jrmoreau** [comment]
![terra error](https://user-images.githubusercontent.com/1614127/96746672-6cb83b00-1395-11eb-89ad-681c7a142f9d.png)

**Comment by Bitcoinera** [comment]
Weird. How did they get 0??

**Comment by faboweb** [comment]
vested account? what is the address?

**Comment by jrmoreau** [comment]
@faboweb address in the second comment `terra1fk7lyw3gf82ymvp4m043mlk7d6ggf9l3av5tmg`

I've never seen a vesting noted on a Terra account. I don't see one here:

https://terra.stake.id/?#/address/terra1fk7lyw3gf82ymvp4m043mlk7d6ggf9l3av5tmg

**Comment by faboweb** [comment]
not a vested account

**Comment by faboweb** [comment]
the problem seems to be that he has 0 fees in the tx but the tx needs fees. temporary issue as @Bitcoinera could unstake without problems?

**Comment by Bitcoinera** [comment]
I think so too. A punctual problem due to a connection failure, nothing more.

Is the user still experiencing this issue @jrmoreau ?

**Comment by jrmoreau** [comment]
I don't know - asked them to try again @Bitcoinera

**Comment by jrmoreau** [comment]
@faboweb @Bitcoinera still no go - they tried again today

![terra still failing](https://user-images.githubusercontent.com/1614127/96930209-58ee0100-1489-11eb-94b9-110ee4bf801b.png)
