### ISSUE TITLE
Akash sending disabled

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5156]
User getting message that sending in Akash is a disabled feature although it's not

**Comment by jrmoreau** [comment]
![photo_2020-10-22 16 21 45](https://user-images.githubusercontent.com/1614127/96925815-b7fc4780-1482-11eb-9660-f05f3a1a2136.jpeg)

**Comment by jrmoreau** [comment]
User is on iOS

1.0.225(218)

**Comment by jbibla** [comment]
hoping a new iOS build will fix this - but not sure if it will / why.

**Comment by faboweb** [comment]
I guess it would fix it. the files for tx generation are missing in that release. the user should just use the web interface for now
