### ISSUE TITLE
Cannot claim rewards on Polkadot (prob Kusama too)

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5164]
Users complaining of not being able to claim rewards. Found issues throughout the process. Reward amount vs. claimable is different. TX didn't get sent to the browser extension too.

**Comment by jrmoreau** [comment]
<img width="1680" alt="Screen Shot 2020-10-26 at 9 32 35 AM" src="https://user-images.githubusercontent.com/1614127/97178879-8202e000-176e-11eb-89d3-cbfb0cfda700.png">
<img width="1679" alt="Screen Shot 2020-10-26 at 9 32 44 AM" src="https://user-images.githubusercontent.com/1614127/97178885-84653a00-176e-11eb-83a3-401153cbda9b.png">
<img width="1680" alt="Screen Shot 2020-10-26 at 9 33 04 AM" src="https://user-images.githubusercontent.com/1614127/97178886-84fdd080-176e-11eb-8d03-109f05c5a801.png">

**Comment by faboweb** [comment]
Bug in the accountRole query

**Comment by mariopino** [comment]
> Bug in the accountRole query

I tested in develop and accountRole query is working fine (tested in polkadot and kusama with all possible roles).

**Comment by mariopino** [comment]
Using app.lunie.io I got this error while claiming rewards:

Withdrawal failed: Rewards for this era have already been claimed for this validator.
