### ISSUE TITLE
User cannot send BNB with Ledger

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5165]
I cannot reproduce but the user has provided some info to look at.

**Comment by jrmoreau** [comment]
Windows 10 up-to-date and Google Chrome.
Cosmos v 2.16.3
Ledger Nano x up to date

![bnbfail](https://user-images.githubusercontent.com/1614127/97188200-a44e2b00-1779-11eb-9128-82678c38411a.png)

**Comment by jrmoreau** [comment]
![bnb fail 2](https://user-images.githubusercontent.com/1614127/97188523-f98a3c80-1779-11eb-9603-7f70d85647a5.png)

**Comment by jrmoreau** [comment]
address: kava1npxusy6j5ctsy55qu4qr0dr05gxmdavajyh9tq

**Comment by faboweb** [comment]
This is Ledger independent. Did this work for the user before? I am resistant to add more fixes to Kava.
