### ISSUE TITLE
Kava dashboard not loading data for user

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#5166]
Doesn't appear to be a node issue - user says they are behind firewall. Could this be related?

**Comment by jrmoreau** [comment]
![kava dashboard fail](https://user-images.githubusercontent.com/1614127/97191831-a7e3b100-177d-11eb-9491-732c64e9a12f.jpg)

**Comment by jrmoreau** [comment]
address: kava1zmkncxu7sx2az048htysyh5efc6j6zdp3m72f2

**Comment by faboweb** [comment]
Probably holds a coin we don't support and that fucks up displaying for him. Should we fix that?
