### ISSUE TITLE
Pulling lunieapi (lunieapi:latest)... 

### ISSUE THREAD

**Issue by Amrosx** [luniehq/lunie#5175]
**Describe the bug**

when I run the docker-compose up it refuse to pull lunieapi image. any body help me with this or how can i create an image from the api project ?

I am using docker on windows OS , but lunix contaiers
 
Tq

**Comment by faboweb** [comment]
I think you need to build the lunieapi image first (api/docker-compose.yaml). But I would suggest you to wait a little with setting up Lunie. We will release a new Lunie these days that is a lot easier to host.

**Comment by Amrosx** [comment]
Thats greate,, 
I have another problem in **HASURA_ADMIN_KEY** I didn't find the secrets and the **staging-db.lunie.io** is not accessible

**Comment by faboweb** [comment]
Hey!
You need to host an own instance of Hasura.

**Comment by Amrosx** [comment]
got it thanks

**Comment by jbibla** [comment]
@Amrosx we are specifically working on a version of Lunie that will have no backend requirements aside from a node. We'll be releasing it in the next week or two.
