### ISSUE TITLE
connect new database

### ISSUE THREAD

**Issue by Amrosx** [luniehq/lunie#5200]
I would like to connect a Fluree blockchain database with lunie. Is there a guide  for that and is this project flexible to accept another database without a lot of chaneges in the code. The Fluree dabase has graphql endpoint api. can any one give me advice on how to connect?

fluree lib
https://www.npmjs.com/package/fluree-cryptography

**Comment by jbibla** [comment]
Hey there! We're releasing a new version of Lunie very soon that will not require any database at all. I would recommend waiting for that release because it will make running an instance of Lunie 10x easier.

**Comment by Amrosx** [comment]
What do you mean of no database? where the data will be stored?

**Comment by jbibla** [comment]
the blockchain is the database - there will not be a requirement for an _extra_ db. most of the data from lunie is already coming directly from the blockchain. 

we have not explored any other database options with Lunie so we can't say what it will take to use with Fluree.

yes, lunie-light is the new version.
