### ISSUE TITLE
lunie will be closed ?!!

### ISSUE THREAD

**Issue by Amrosx** [luniehq/lunie#5205]
I have read this artical 
https://medium.com/luniehq/sunsetting-lunie-io-66d566c14ba1

and I am confused how do you announceing for new version of lunie and the artical above is telling that lunie is not sufficient anymore and you will stop supporting it ?! 

could you explaine please. 
tq

**Comment by faboweb** [comment]
Hey! Could you clarify your questions please? Yes. The hosted version of Lunie at app.lunie.io as well as this repository will be discontinued. There is a much simpler version at https://github.com/luniehq/lunie-light that you can host yourself.
