### ISSUE TITLE
i cannot unstake my atoms or claim the rewards it keep saying i dont have enough to take out

### ISSUE THREAD

**Issue by gllara01** [luniehq/lunie#5271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by faboweb** [comment]
Which Lunie are you using? Which URL? This project is deprecated.
