### ISSUE TITLE
Lunie extension on firefox

### ISSUE THREAD

**Issue by 0xadri** [luniehq/lunie#5277]
It is a feature request. Would be great to use Lunie Extension on Firefox.

**Describe the solution you'd like**
Can we please have Lunie extension on Firefox ?

**Additional context**
Firefox has been spearheading the open-source movement in the web browser industry. Without Firefox the internet would be a totally different beast today.
Tons of crypto early adopters are using/supporting Firefox.
Note that I created this Issue because of the suggestion you guys left on https://lunie.io/guides/getting-started-ext/

**Comment by faboweb** [comment]
The Lunie suite is discontinued. For now, there is no active development. There are no releases to the extension planned. Please check Keplr as an alternative.
