### ISSUE TITLE
nicknames/hosts file for more user-friendly transactions

### ISSUE THREAD

**Issue by nylira** [luniehq/lunie#914]
*We've discussed this in the Voyager UI/UX meeting. I'm making an issue so we don't forget about it.*

* Let users send to people, not bech32 addresses
* Like an /etc/hosts file
* May have security implications: creates an attack vector
* Maybe use bech32 with custom prefixes per address
* Maybe use autocomplete to select addresses

**Comment by faboweb** [comment]
"hosts file" sounds weird. Isn't is just a contact-list the user can create? So more of an address book?
The user could create contacts in a custom bech32 format and store them.

Or users MUST create a contact first before sending. This is how some exchanges do it.

**Comment by fedekunze** [comment]
Can we close this as validators have `monikers` already ?

**Comment by faboweb** [comment]
Users don't have monikers though.

**Comment by jbibla** [comment]
and more broadly, peng is talking about a contact list feature which is not in our roadmap (wallet 2 anyone?)
