### ISSUE TITLE
Update the validators when they change

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#946]
UI Version: 0.7.1

Description:

Currently the validators are loaded once via the LCD. It would be nice to update them every time they change so the user sees the live validator set.

**Comment by jolesbi** [comment]
absolutely. this will need to be dynamic!

**Comment by faboweb** [comment]
There is no event for that yet:
https://github.com/tendermint/tendermint/issues/1916

**Comment by fedekunze** [comment]
- [ ] Listen to `NewBlock` Event
- [ ] Compare validator sets
- [ ] Update if ≠

**Comment by fedekunze** [comment]
New event for Validator Updates [#tendermint/2161](https://github.com/tendermint/tendermint/pull/2161)

**Comment by fedekunze** [comment]
The original proposal is already implemented with the `maybeUpdateValidators` and `setLastHeader` functions that are called when you subscribe to RPC. I will leave this issue open until [#tendermint/2161](https://github.com/tendermint/tendermint/pull/2161) gets merged and included into the SDK

**Comment by faboweb** [comment]
Our current approach works
