### ISSUE TITLE
Add transaction details

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#965]
UI Version: 0.7.1

Description:

We want to show more details of a transaction. We could show those inline / in another page... There are several ideas. @jbibla already has some mockups.

Details can be:
- block,
- addresses,
- type
- fees

**Comment by jbibla** [comment]
please review: 
- https://zpl.io/bLDW6gQ - Tx History - Loading
- https://zpl.io/VDndZ8W - Tx History - Failed
- https://zpl.io/bWLnE7e - Tx History - Claim

**Comment by faboweb** [comment]
I want to some up our discussion:
We don't need a "Tx page" or another form of showing more information on txs. If this is correct, feel free to close this issue.
If there is a need to show fees, we can add another issue for adding fees to transactions.

**Comment by siman** [comment]
> We don't need a "Tx page" or another form of showing more information on txs

Why? I would love to have a tx page. Every blockchain project has an explorer and the most required pages are:

- List of txs
- Tx details
- List of blocks
- Block details
- List of account
- Account details

These pages is a **must have**!

**Comment by faboweb** [comment]
We have the block explorer for showing block related data here https://explorecosmos.network/ .
What would you like to see on a potential "Tx details" page in Voyager you are not seeing on the current tx design?

Designs:
![image](https://user-images.githubusercontent.com/5869273/45091577-35359880-b113-11e8-8e87-419d41e5b437.png)

**Comment by siman** [comment]
Right now tx list page in Voyager on Demo Network looks not attractive:

![image](https://user-images.githubusercontent.com/153928/45093251-85ffbe00-b120-11e8-83c2-dcee60849bab.png)

A new design looks good. Here are my notes on it:
- A number "5" is white so unreadable on yellow. Not enough contract. Better use dark color when light (yellow) background.
- Add UTC to a date and time. Right now it's confusing. Is it in my local time or UTC?

**Comment by faboweb** [comment]
The new transaction design will be available shortly.

> A number "5" is white so unreadable on yellow. Not enough contract. Better use dark color when light (yellow) background.

This is copied out of our design colaboration tool and a note and not part of the design. ;)

> Add UTC to a date and time. Right now it's confusing. Is it in my local time or UTC?

I think showing this in your local time is more accessible then having long UTC strings. But arguable. Pulling in @jbibla .

**Comment by siman** [comment]
Blockchain explorers that look good (IMHO):

[Ark explorer](https://explorer.ark.io/):

![image](https://user-images.githubusercontent.com/153928/45093381-e858be80-b120-11e8-9a6c-62c03cf1994d.png)

Tx details page has good info, though a values could be better aligned close to field labels:

![image](https://user-images.githubusercontent.com/153928/45093485-2c4bc380-b121-11e8-940e-d95d82cb53a1.png)

[Tx details in EOS explorer](https://eostracker.io/transactions/14854126/ac9c0073d37908be6701a107a332d2286eeda4dc55f3feb29ab7454182b83594):

![image](https://user-images.githubusercontent.com/153928/45093559-6c12ab00-b121-11e8-8417-c4d209af7459.png)

I like a tab "Blockchain Raw Data". Too handy for developers :)

![image](https://user-images.githubusercontent.com/153928/45093579-7b91f400-b121-11e8-850b-b87911a1211b.png)

You can take some inspiration from this another explorer for EOS:
https://eosflare.io/

![image](https://user-images.githubusercontent.com/153928/45093699-dd525e00-b121-11e8-8c38-c0a73accf0f0.png)

[Account](https://eosflare.io/account/eosio.stake):

![image](https://user-images.githubusercontent.com/153928/45093743-05da5800-b122-11e8-86a9-c251e16d1862.png)

And of course Etherscan: they have very informative "Tx details" page, I love it:

![image](https://user-images.githubusercontent.com/153928/45093964-b183a800-b122-11e8-9280-a4fceaf03b5f.png)

**Comment by siman** [comment]
I would love to see a "Transactions" page on [Cosmos Explorer](https://explorecosmos.network/) as well. This page should aggregate all transactions found across all blocks. So a user can go to the "Transactions" page and check what is going on on Cosmos. Because right now mostly empty blocks are mined and they get produced to fast, so it's very hard to go through all of the blocks in order to find any non-empty block with txs.

**Comment by jbibla** [comment]
hello @siman ! 

thank you for the ideas and feedback!

to clarify, Voyager will have a Transaction History page so you can see all transactions and associated transaction data that is relevant for your accounts.

the new designs will be available in the next release or the release after that.

please feel free to leave feedback and ideas on [this repo](https://github.com/cosmos/explorer) for the [Cosmos Explorer](https://explorecosmos.network/). i think a transactions page on the explorer is a great idea - and i believe we used to have something like this. @nylira is this within the realm of possibility?

**Comment by siman** [comment]
> please feel free to leave feedback and ideas on this repo for the Cosmos Explorer.

Thank you for an invitation 😃 
As for Cosmos Explorer: I am dreaming of the next feature:

**Custom (dapp specific) tx details** page – it's when developers of dapps (that are based on TM/Cosmos-SDK) would describe different data structure of txs their app has and then based on this specs Cosmos Explorer would dynamically render different versions of "Tx details" page based on the structure/fields of tx. I would love to use this feature for my dapp in order to customize the blockchain/tx explorer for my types of transactions.

**Comment by siman** [comment]
@jbibla so I have posted my prev comment in Cosmos Explorer repo as an idea for custom tx details:
https://github.com/cosmos/explorer/issues/39

**Comment by sabau** [comment]
Me and @fedekunze had a discussion about this, we shuold really do this 👍

**Comment by fedekunze** [comment]
I think we should display the following:

- tx hash
- block
- amount
- sender and receiver addresses
- tx type
- fees
- gas used
- tx tags

**Comment by fedekunze** [comment]
Also provide a link to share the details of the transaction once it's been processed and broadcasted

**Comment by fedekunze** [comment]
User story:

As a user I want to see the details of a transaction I've sent/received in order to confirm that the transaction was successful

**Comment by siman** [comment]
I have implemented "Transaction Details" page in a fork of Cosmos Explorer. Check it out, maybe you will find it helpful: https://github.com/dappforce/tendermint-explorer

**Comment by faboweb** [comment]
> As a user I want to see the details of a transaction I've sent/received in order to confirm that the transaction was successful

You already see that the transaction was successful you don't need the details for that.

> Also provide a link to share the details of the transaction once it's been processed and broadcasted

Should this go in another issue?

**Comment by fedekunze** [comment]
> You already see that the transaction was successful you don't need the details for that.

That doesn't provide all the information about the transaction, we only show the notification and the transaction on the Transactions Page, which only displays the tx type, amount and address of the recipient  

> Should this go in another issue?

yes, I'll create it shortly
