### ISSUE TITLE
Move config.js to root level

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#978]
UI Version: 0.7.1

Description:

The file `app/config.js` is often overlooked by devs. But this file holds port configuration and other constants. We could move the file to the root level to make it more accessable. But there where problems with having the file on root level in production.

**Comment by faboweb** [comment]
Put a symlink to root

**Comment by jbibla** [comment]
still relevant?

**Comment by jbibla** [comment]
do you still want to do this @faboweb?
